PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/SQLXMLImpl.c File Reference
SQLXMLImpl.c File Reference
#include <postgres.h>
#include "org_postgresql_pljava_jdbc_SQLXMLImpl.h"
#include "pljava/type/Type_priv.h"
#include "pljava/VarlenaWrapper.h"
Functions
static bool _SQLXML_canReplaceType (Type self, Type other)
static jvalue _SQLXML_coerceDatum (Type self, Datum arg)
static Datum _SQLXML_coerceObject (Type self, jobject sqlxml)
static Type _SQLXML_obtain (Oid typeId)
static jvalue _SQLXML_coerceDatum_synthetic (Type self, Datum arg)
void pljava_SQLXMLImpl_initialize (void)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_jdbc_SQLXMLImpl__1newWritable (JNIEnv *env, jclass sqlxml_class)
Variables
static TypeClass s_SQLXMLClass
static jclass s_SQLXML_class
static jmethodID s_SQLXML_adopt
static jclass s_SQLXML_Readable_PgXML_class
static jmethodID s_SQLXML_Readable_PgXML_init
static jclass s_SQLXML_Writable_class
static jmethodID s_SQLXML_Writable_init
static TypeClass s_SQLXMLClass_Synthetic
static jclass s_SQLXML_Readable_Synthetic_class
static jmethodID s_SQLXML_Readable_Synthetic_init
Function Documentation
_SQLXML_canReplaceType()
static bool _SQLXML_canReplaceType (Type self, Type other) static
Definition at line 45 of file SQLXMLImpl.c.
{
    TypeClass cls = Type_getClass(other);
    return
        Type_getClass(self) == cls  ||
#if defined(XMLOID)
        Type_getOid(other) == XMLOID  ||
#endif
        Type_getOid(other) == PG_NODE_TREEOID  ||  /* a synthetic rendering */
        Type_getOid(other) == TEXTOID;
}
References Type_getClass(), and Type_getOid().
Referenced by pljava_SQLXMLImpl_initialize().
_SQLXML_coerceDatum()
static jvalue _SQLXML_coerceDatum (Type self, Datum arg) static
Definition at line 57 of file SQLXMLImpl.c.
{
    jvalue result;
    jobject vwi = pljava_VarlenaWrapper_Input(
        arg, TopTransactionContext, TopTransactionResourceOwner);
    result.l = JNI_newObject(
        s_SQLXML_Readable_PgXML_class, s_SQLXML_Readable_PgXML_init,
        vwi, Type_getOid(self));
    JNI_deleteLocalRef(vwi);
    return result;
}
References JNI_deleteLocalRef(), JNI_newObject(), pljava_VarlenaWrapper_Input(), s_SQLXML_Readable_PgXML_class, s_SQLXML_Readable_PgXML_init, and Type_getOid().
Referenced by pljava_SQLXMLImpl_initialize().
_SQLXML_coerceDatum_synthetic()
static jvalue _SQLXML_coerceDatum_synthetic (Type self, Datum arg) static
Definition at line 69 of file SQLXMLImpl.c.
{
    jvalue result;
    jobject vwi = pljava_VarlenaWrapper_Input(
        arg, TopTransactionContext, TopTransactionResourceOwner);
    result.l = JNI_newObject(
        s_SQLXML_Readable_Synthetic_class, s_SQLXML_Readable_Synthetic_init,
        vwi, Type_getOid(self));
    JNI_deleteLocalRef(vwi);
    return result;
}
References JNI_deleteLocalRef(), JNI_newObject(), pljava_VarlenaWrapper_Input(), s_SQLXML_Readable_Synthetic_class, s_SQLXML_Readable_Synthetic_init, and Type_getOid().
Referenced by pljava_SQLXMLImpl_initialize().
_SQLXML_coerceObject()
static Datum _SQLXML_coerceObject (Type self, jobject sqlxml) static
Definition at line 81 of file SQLXMLImpl.c.
{
    jobject vw = JNI_callStaticObjectMethodLocked(
        s_SQLXML_class, s_SQLXML_adopt, sqlxml, Type_getOid(self));
    Datum d = pljava_VarlenaWrapper_adopt(vw);
    JNI_deleteLocalRef(vw);
    if ( VARATT_IS_EXTERNAL_EXPANDED_RW(DatumGetPointer(d)) )
        return TransferExpandedObject(d, CurrentMemoryContext);
    MemoryContextSetParent(
        GetMemoryChunkContext(DatumGetPointer(d)), CurrentMemoryContext);
    return d;
}
References JNI_callStaticObjectMethodLocked(), JNI_deleteLocalRef(), pljava_VarlenaWrapper_adopt(), s_SQLXML_adopt, s_SQLXML_class, and Type_getOid().
Referenced by pljava_SQLXMLImpl_initialize().
_SQLXML_obtain()
static Type _SQLXML_obtain (Oid typeId) static
Definition at line 121 of file SQLXMLImpl.c.
{
    static Type textInstance;
    Oid allowedId = InvalidOid;
    bool synthetic = false;
    Type *cache;
#if defined(XMLOID)
    static Type xmlInstance;
#endif
    static Type pgNodeTreeInstance;
    switch ( typeId )
    {
    case PG_NODE_TREEOID:
        allowedId = PG_NODE_TREEOID;
        synthetic = true;
        cache = &pgNodeTreeInstance;
        break;
    default:
        if ( TEXTOID == typeId )
        {
            cache = &textInstance;
            allowedId = TEXTOID;
        }
#if defined(XMLOID)
        else
        {
            allowedId = XMLOID;
            cache = &xmlInstance;
        }
#endif
    }
    if ( NULL == *cache )
        *cache = TypeClass_allocInstance(
            synthetic ? s_SQLXMLClass_Synthetic : s_SQLXMLClass, allowedId);
    return *cache;
}
References s_SQLXMLClass, s_SQLXMLClass_Synthetic, Type, and TypeClass_allocInstance().
Referenced by pljava_SQLXMLImpl_initialize().
Java_org_postgresql_pljava_jdbc_SQLXMLImpl__1newWritable()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_jdbc_SQLXMLImpl__1newWritable (JNIEnv * env, jclass sqlxml_class)
Definition at line 226 of file SQLXMLImpl.c.
{
    jobject sqlxml = NULL;
    jobject vwo;
    BEGIN_NATIVE
    vwo = pljava_VarlenaWrapper_Output(
            TopTransactionContext, TopTransactionResourceOwner);
    sqlxml = JNI_newObjectLocked(
            s_SQLXML_Writable_class, s_SQLXML_Writable_init, vwo);
    END_NATIVE
    return sqlxml;
}
References JNI_newObjectLocked(), pljava_VarlenaWrapper_Output(), s_SQLXML_Writable_class, and s_SQLXML_Writable_init.
Referenced by pljava_SQLXMLImpl_initialize().
pljava_SQLXMLImpl_initialize()
void pljava_SQLXMLImpl_initialize (void) extern
Definition at line 162 of file SQLXMLImpl.c.
{
    jclass clazz;
    JNINativeMethod methods[] =
    {
        {
        "_newWritable",
        "()Ljava/sql/SQLXML;",
        Java_org_postgresql_pljava_jdbc_SQLXMLImpl__1newWritable
        },
        { 0, 0, 0 }
    };
    TypeClass cls = TypeClass_alloc("type.SQLXML");
    cls->JNISignature = "Ljava/sql/SQLXML;";
    cls->javaTypeName = "java.sql.SQLXML";
    cls->canReplaceType = _SQLXML_canReplaceType;
    cls->coerceDatum  = _SQLXML_coerceDatum;
    cls->coerceObject = _SQLXML_coerceObject;
    s_SQLXMLClass = cls;
    Type_registerType2(InvalidOid, "java.sql.SQLXML", _SQLXML_obtain);
    cls = TypeClass_alloc("type.SQLXML");
    cls->JNISignature = "Ljava/sql/SQLXML;";
    cls->javaTypeName = "java.sql.SQLXML";
    cls->canReplaceType = _SQLXML_canReplaceType;
    cls->coerceDatum  = _SQLXML_coerceDatum_synthetic;
    /* cls->coerceObject = _SQLXML_coerceObject; */
    s_SQLXMLClass_Synthetic = cls; /* what happens if I don't register it? */
    s_SQLXML_class = JNI_newGlobalRef(PgObject_getJavaClass(
        "org/postgresql/pljava/jdbc/SQLXMLImpl"));
    s_SQLXML_adopt = PgObject_getStaticJavaMethod(s_SQLXML_class, "adopt",
        "(Ljava/sql/SQLXML;I)Lorg/postgresql/pljava/internal/VarlenaWrapper;");
    s_SQLXML_Readable_PgXML_class = JNI_newGlobalRef(PgObject_getJavaClass(
        "org/postgresql/pljava/jdbc/SQLXMLImpl$Readable$PgXML"));
    s_SQLXML_Readable_PgXML_init = PgObject_getJavaMethod(
        s_SQLXML_Readable_PgXML_class,
        "<init>", "(Lorg/postgresql/pljava/internal/VarlenaWrapper$Input;I)V");
    s_SQLXML_Readable_Synthetic_class = JNI_newGlobalRef(PgObject_getJavaClass(
        "org/postgresql/pljava/jdbc/SQLXMLImpl$Readable$Synthetic"));
    s_SQLXML_Readable_Synthetic_init = PgObject_getJavaMethod(
        s_SQLXML_Readable_Synthetic_class,
        "<init>", "(Lorg/postgresql/pljava/internal/VarlenaWrapper$Input;I)V");
    s_SQLXML_Writable_class = JNI_newGlobalRef(PgObject_getJavaClass(
        "org/postgresql/pljava/jdbc/SQLXMLImpl$Writable"));
    s_SQLXML_Writable_init = PgObject_getJavaMethod(s_SQLXML_Writable_class,
        "<init>", "(Lorg/postgresql/pljava/internal/VarlenaWrapper$Output;)V");
    clazz = PgObject_getJavaClass("org/postgresql/pljava/jdbc/SQLXMLImpl");
    PgObject_registerNatives2(clazz, methods);
    JNI_deleteLocalRef(clazz);
}
References _SQLXML_canReplaceType(), _SQLXML_coerceDatum(), _SQLXML_coerceDatum_synthetic(), _SQLXML_coerceObject(), _SQLXML_obtain(), Java_org_postgresql_pljava_jdbc_SQLXMLImpl__1newWritable(), JNI_deleteLocalRef(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_getStaticJavaMethod(), PgObject_registerNatives2(), s_SQLXML_adopt, s_SQLXML_class, s_SQLXML_Readable_PgXML_class, s_SQLXML_Readable_PgXML_init, s_SQLXML_Readable_Synthetic_class, s_SQLXML_Readable_Synthetic_init, s_SQLXML_Writable_class, s_SQLXML_Writable_init, s_SQLXMLClass, s_SQLXMLClass_Synthetic, Type_registerType2(), and TypeClass_alloc().
Referenced by Type_initialize().
Variable Documentation
s_SQLXML_adopt
jmethodID s_SQLXML_adopt static
Definition at line 21 of file SQLXMLImpl.c.
Referenced by _SQLXML_coerceObject(), and pljava_SQLXMLImpl_initialize().
s_SQLXML_class
jclass s_SQLXML_class static
Definition at line 20 of file SQLXMLImpl.c.
Referenced by _SQLXML_coerceObject(), and pljava_SQLXMLImpl_initialize().
s_SQLXML_Readable_PgXML_class
jclass s_SQLXML_Readable_PgXML_class static
Definition at line 22 of file SQLXMLImpl.c.
Referenced by _SQLXML_coerceDatum(), and pljava_SQLXMLImpl_initialize().
s_SQLXML_Readable_PgXML_init
jmethodID s_SQLXML_Readable_PgXML_init static
Definition at line 23 of file SQLXMLImpl.c.
Referenced by _SQLXML_coerceDatum(), and pljava_SQLXMLImpl_initialize().
s_SQLXML_Readable_Synthetic_class
jclass s_SQLXML_Readable_Synthetic_class static
Definition at line 28 of file SQLXMLImpl.c.
Referenced by _SQLXML_coerceDatum_synthetic(), and pljava_SQLXMLImpl_initialize().
s_SQLXML_Readable_Synthetic_init
jmethodID s_SQLXML_Readable_Synthetic_init static
Definition at line 29 of file SQLXMLImpl.c.
Referenced by _SQLXML_coerceDatum_synthetic(), and pljava_SQLXMLImpl_initialize().
s_SQLXML_Writable_class
jclass s_SQLXML_Writable_class static
Definition at line 24 of file SQLXMLImpl.c.
Referenced by Java_org_postgresql_pljava_jdbc_SQLXMLImpl__1newWritable(), and pljava_SQLXMLImpl_initialize().
s_SQLXML_Writable_init
jmethodID s_SQLXML_Writable_init static
Definition at line 25 of file SQLXMLImpl.c.
Referenced by Java_org_postgresql_pljava_jdbc_SQLXMLImpl__1newWritable(), and pljava_SQLXMLImpl_initialize().
s_SQLXMLClass
TypeClass s_SQLXMLClass static
Definition at line 19 of file SQLXMLImpl.c.
Referenced by _SQLXML_obtain(), and pljava_SQLXMLImpl_initialize().
s_SQLXMLClass_Synthetic
TypeClass s_SQLXMLClass_Synthetic static
Definition at line 27 of file SQLXMLImpl.c.
Referenced by _SQLXML_obtain(), and pljava_SQLXMLImpl_initialize().