PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Boolean.c File Reference
Boolean.c File Reference
#include "pljava/type/Type_priv.h"
#include "pljava/type/Array.h"
#include "pljava/Invocation.h"
Functions
static Datum _boolean_invoke (Type self, Function fn, PG_FUNCTION_ARGS)
static jvalue _boolean_coerceDatum (Type self, Datum arg)
static jvalue _booleanArray_coerceDatum (Type self, Datum arg)
static Datum _booleanArray_coerceObject (Type self, jobject booleanArray)
static bool _Boolean_canReplace (Type self, Type other)
static jvalue _Boolean_coerceDatum (Type self, Datum arg)
static Datum _Boolean_coerceObject (Type self, jobject booleanObj)
static Type _boolean_createArrayType (Type self, Oid arrayTypeId)
void Boolean_initialize (void)
Variables
static TypeClass s_booleanClass
static jclass s_Boolean_class
static jmethodID s_Boolean_init
static jmethodID s_Boolean_booleanValue
Function Documentation
_Boolean_canReplace()
static bool _Boolean_canReplace (Type self, Type other) static
Definition at line 89 of file Boolean.c.
{
    TypeClass cls = Type_getClass(other);
    return Type_getClass(self) == cls || cls == s_booleanClass;
}
References s_booleanClass, and Type_getClass().
Referenced by Boolean_initialize().
_boolean_coerceDatum()
static jvalue _boolean_coerceDatum (Type self, Datum arg) static
Definition at line 32 of file Boolean.c.
{
    jvalue result;
    result.z = DatumGetBool(arg);
    return result;
}
Referenced by Boolean_initialize().
_Boolean_coerceDatum()
static jvalue _Boolean_coerceDatum (Type self, Datum arg) static
Definition at line 95 of file Boolean.c.
{
    jvalue result;
    result.l = JNI_newObject(s_Boolean_class, s_Boolean_init, DatumGetBool(arg));
    return result;
}
References JNI_newObject(), s_Boolean_class, and s_Boolean_init.
Referenced by Boolean_initialize().
_Boolean_coerceObject()
static Datum _Boolean_coerceObject (Type self, jobject booleanObj) static
Definition at line 102 of file Boolean.c.
{
    return BoolGetDatum(booleanObj == 0 ? false : JNI_callBooleanMethod(booleanObj, s_Boolean_booleanValue) == JNI_TRUE);
}
References JNI_callBooleanMethod(), and s_Boolean_booleanValue.
Referenced by Boolean_initialize().
_boolean_createArrayType()
static Type _boolean_createArrayType (Type self, Oid arrayTypeId) static
Definition at line 107 of file Boolean.c.
{
    return Array_fromOid2(arrayTypeId, self, _booleanArray_coerceDatum, _booleanArray_coerceObject);
}
References _booleanArray_coerceDatum(), _booleanArray_coerceObject(), and Array_fromOid2().
Referenced by Boolean_initialize().
_boolean_invoke()
static Datum _boolean_invoke (Type self, Function fn, PG_FUNCTION_ARGS) static
Definition at line 26 of file Boolean.c.
{
    jboolean v = pljava_Function_booleanInvoke(fn);
    return BoolGetDatum(v);
}
References pljava_Function_booleanInvoke().
Referenced by Boolean_initialize().
_booleanArray_coerceDatum()
static jvalue _booleanArray_coerceDatum (Type self, Datum arg) static
Definition at line 39 of file Boolean.c.
{
    jvalue     result;
    ArrayType* v      = DatumGetArrayTypeP(arg);
    jsize      nElems = (jsize)ArrayGetNItems(ARR_NDIM(v), ARR_DIMS(v));
    jbooleanArray booleanArray = JNI_newBooleanArray(nElems);
    if(ARR_HASNULL(v))
    {
        jsize idx;
        jboolean isCopy = JNI_FALSE;
        bits8* nullBitMap = ARR_NULLBITMAP(v);
        jboolean* values = (jboolean*)ARR_DATA_PTR(v);
        jboolean* elems  = JNI_getBooleanArrayElements(booleanArray, &isCopy);
        for(idx = 0; idx < nElems; ++idx)
        {
            if(arrayIsNull(nullBitMap, idx))
                elems[idx] = 0;
            else
                elems[idx] = *values++;
        }
        JNI_releaseBooleanArrayElements(booleanArray, elems, JNI_COMMIT);
    }
    else
        JNI_setBooleanArrayRegion(booleanArray, 0, nElems, (jboolean*)ARR_DATA_PTR(v));
    result.l = (jobject)booleanArray;
    return result;
}
References arrayIsNull(), JNI_getBooleanArrayElements(), JNI_newBooleanArray(), JNI_releaseBooleanArrayElements(), and JNI_setBooleanArrayRegion().
Referenced by _boolean_createArrayType().
_booleanArray_coerceObject()
static Datum _booleanArray_coerceObject (Type self, jobject booleanArray) static
Definition at line 68 of file Boolean.c.
{
    ArrayType* v;
    jsize nElems;
    if(booleanArray == 0)
        return 0;
    nElems = JNI_getArrayLength((jarray)booleanArray);
    v = createArrayType(nElems, sizeof(jboolean), BOOLOID, false);
    JNI_getBooleanArrayRegion((jbooleanArray)booleanArray, 0,
                      nElems, (jboolean*)ARR_DATA_PTR(v));
    PG_RETURN_ARRAYTYPE_P(v);
}
References createArrayType(), JNI_getArrayLength(), and JNI_getBooleanArrayRegion().
Referenced by _boolean_createArrayType().
Boolean_initialize()
void Boolean_initialize (void) extern
Definition at line 115 of file Boolean.c.
{
    Type t_boolean;
    Type t_Boolean;
    TypeClass cls;
    s_Boolean_class = JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Boolean"));
    s_Boolean_init = PgObject_getJavaMethod(s_Boolean_class, "<init>", "(Z)V");
    s_Boolean_booleanValue = PgObject_getJavaMethod(s_Boolean_class, "booleanValue", "()Z");
    cls = TypeClass_alloc("type.Boolean");
    cls->canReplaceType = _Boolean_canReplace;
    cls->JNISignature = "Ljava/lang/Boolean;";
    cls->javaTypeName = "java.lang.Boolean";
    cls->coerceDatum  = _Boolean_coerceDatum;
    cls->coerceObject = _Boolean_coerceObject;
    t_Boolean = TypeClass_allocInstance(cls, BOOLOID);
    cls = TypeClass_alloc("type.boolean");
    cls->JNISignature = "Z";
    cls->javaTypeName = "boolean";
    cls->invoke       = _boolean_invoke;
    cls->coerceDatum  = _boolean_coerceDatum;
    cls->coerceObject = _Boolean_coerceObject;
    cls->createArrayType = _boolean_createArrayType;
    s_booleanClass = cls;
    t_boolean = TypeClass_allocInstance(cls, BOOLOID);
    t_boolean->objectType = t_Boolean;
    Type_registerType("boolean", t_boolean);
    Type_registerType("java.lang.Boolean", t_Boolean);
}
References _Boolean_canReplace(), _boolean_coerceDatum(), _Boolean_coerceDatum(), _Boolean_coerceObject(), _boolean_createArrayType(), _boolean_invoke(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Boolean_booleanValue, s_Boolean_class, s_Boolean_init, s_booleanClass, Type, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Variable Documentation
s_Boolean_booleanValue
jmethodID s_Boolean_booleanValue static
Definition at line 21 of file Boolean.c.
Referenced by _Boolean_coerceObject(), and Boolean_initialize().
s_Boolean_class
jclass s_Boolean_class static
Definition at line 19 of file Boolean.c.
Referenced by _Boolean_coerceDatum(), and Boolean_initialize().
s_Boolean_init
jmethodID s_Boolean_init static
Definition at line 20 of file Boolean.c.
Referenced by _Boolean_coerceDatum(), and Boolean_initialize().
s_booleanClass
TypeClass s_booleanClass static
Definition at line 18 of file Boolean.c.
Referenced by _Boolean_canReplace(), and Boolean_initialize().