PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/Exception.c File Reference
Exception.c File Reference
#include <postgres.h>
#include <executor/spi.h>
#include "pljava/Backend.h"
#include "pljava/Invocation.h"
#include "pljava/Exception.h"
#include "pljava/type/String.h"
#include "pljava/type/ErrorData.h"
Functions
void Exception_featureNotSupported (const char *requestedFeature, const char *introVersion)
void Exception_throw (int errCode, const char *errMessage,...)
void Exception_throwIllegalArgument (const char *errMessage,...)
void Exception_throwSPI (const char *function, int errCode)
void Exception_throw_ERROR (const char *funcName)
void Exception_initialize (void)
void Exception_initialize2 (void)
Variables
jclass Class_class
jmethodID Class_getName
jmethodID Class_getCanonicalName
jclass ServerException_class
jmethodID ServerException_getErrorData
jmethodID ServerException_init
jclass Throwable_class
jmethodID Throwable_getMessage
jmethodID Throwable_printStackTrace
jclass IllegalArgumentException_class
jmethodID IllegalArgumentException_init
jclass SQLException_class
jmethodID SQLException_init
jmethodID SQLException_getSQLState
jclass UnsupportedOperationException_class
jmethodID UnsupportedOperationException_init
jclass NoSuchFieldError_class
jclass NoSuchMethodError_class
Function Documentation
Exception_featureNotSupported()
void Exception_featureNotSupported (const char * requestedFeature, const char * introVersion)
Definition at line 50 of file Exception.c.
{
    jstring jmsg;
    jobject ex;
    StringInfoData buf;
    initStringInfo(&buf);
    PG_TRY();
    {
        appendStringInfoString(&buf, "Feature: ");
        appendStringInfoString(&buf, requestedFeature);
        appendStringInfoString(&buf, " lacks support in PostgreSQL version ");
        appendStringInfo(&buf, "%d.%d",
                        PG_VERSION_NUM / 10000,
#if PG_VERSION_NUM >= 100000
                        (PG_VERSION_NUM) % 10000
#else
                        (PG_VERSION_NUM / 100) % 100
#endif
        );
        appendStringInfoString(&buf, ". It was introduced in version ");
        appendStringInfoString(&buf, introVersion);
        ereport(DEBUG3, (errmsg("%s", buf.data)));
        jmsg = String_createJavaStringFromNTS(buf.data);
        ex = JNI_newObject(UnsupportedOperationException_class, UnsupportedOperationException_init, jmsg);
        JNI_deleteLocalRef(jmsg);
        JNI_throw(ex);
    }
    PG_CATCH();
    {
        ereport(WARNING, (errcode(ERRCODE_INTERNAL_ERROR), errmsg("Exception while generating exception: %s", buf.data)));
    }
    PG_END_TRY();
    pfree(buf.data);
}
References JNI_deleteLocalRef(), JNI_newObject(), JNI_throw(), String_createJavaStringFromNTS(), UnsupportedOperationException_class, and UnsupportedOperationException_init.
Exception_initialize()
void Exception_initialize (void) extern
Definition at line 189 of file Exception.c.
{
    Class_class = (jclass)JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Class"));
    Throwable_class = (jclass)JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Throwable"));
    Throwable_getMessage = PgObject_getJavaMethod(Throwable_class, "getMessage", "()Ljava/lang/String;");
    Throwable_printStackTrace = PgObject_getJavaMethod(Throwable_class, "printStackTrace", "()V");
    IllegalArgumentException_class = (jclass)JNI_newGlobalRef(PgObject_getJavaClass("java/lang/IllegalArgumentException"));
    IllegalArgumentException_init = PgObject_getJavaMethod(IllegalArgumentException_class, "<init>", "(Ljava/lang/String;)V");
    SQLException_class = (jclass)JNI_newGlobalRef(PgObject_getJavaClass("java/sql/SQLException"));
    SQLException_init = PgObject_getJavaMethod(SQLException_class, "<init>", "(Ljava/lang/String;Ljava/lang/String;)V");
    SQLException_getSQLState = PgObject_getJavaMethod(SQLException_class, "getSQLState", "()Ljava/lang/String;");
    UnsupportedOperationException_class = (jclass)JNI_newGlobalRef(PgObject_getJavaClass("java/lang/UnsupportedOperationException"));
    UnsupportedOperationException_init = PgObject_getJavaMethod(UnsupportedOperationException_class, "<init>", "(Ljava/lang/String;)V");
    NoSuchFieldError_class = (jclass)JNI_newGlobalRef(PgObject_getJavaClass("java/lang/NoSuchFieldError"));
    NoSuchMethodError_class = (jclass)JNI_newGlobalRef(PgObject_getJavaClass("java/lang/NoSuchMethodError"));
    Class_getName = PgObject_getJavaMethod(Class_class, "getName", "()Ljava/lang/String;");
    Class_getCanonicalName = PgObject_getJavaMethod(Class_class,
        "getCanonicalName", "()Ljava/lang/String;");
}
References Class_class, Class_getCanonicalName, Class_getName, IllegalArgumentException_class, IllegalArgumentException_init, JNI_newGlobalRef(), NoSuchFieldError_class, NoSuchMethodError_class, PgObject_getJavaClass(), PgObject_getJavaMethod(), SQLException_class, SQLException_getSQLState, SQLException_init, Throwable_class, Throwable_getMessage, Throwable_printStackTrace, UnsupportedOperationException_class, and UnsupportedOperationException_init.
Referenced by initPLJavaClasses().
Exception_initialize2()
void Exception_initialize2 (void) extern
Definition at line 216 of file Exception.c.
{
    ServerException_class = (jclass)JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/internal/ServerException"));
    ServerException_init = PgObject_getJavaMethod(ServerException_class, "<init>", "(Lorg/postgresql/pljava/internal/ErrorData;)V");
    ServerException_getErrorData = PgObject_getJavaMethod(ServerException_class, "getErrorData", "()Lorg/postgresql/pljava/internal/ErrorData;");
}
References JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), ServerException_class, ServerException_getErrorData, and ServerException_init.
Referenced by initPLJavaClasses().
Exception_throw()
void Exception_throw (int errCode, const char * errMessage, ...)
Definition at line 87 of file Exception.c.
{
    char buf[1024];
    va_list args;
    jstring message;
    jstring sqlState;
    jobject ex;
    int idx;
    va_start(args, errMessage);
    vsnprintf(buf, sizeof(buf), errMessage, args);
    ereport(DEBUG3, (errcode(errCode), errmsg("%s", buf)));
    PG_TRY();
    {
        message = String_createJavaStringFromNTS(buf);
        /* unpack MAKE_SQLSTATE code
         */
        for (idx = 0; idx < 5; ++idx)
        {
            buf[idx] = (char)PGUNSIXBIT(errCode);
            errCode >>= 6;
        }
        buf[idx] = 0;
        sqlState = String_createJavaStringFromNTS(buf);
        ex = JNI_newObject(SQLException_class, SQLException_init, message, sqlState);
        JNI_deleteLocalRef(message);
        JNI_deleteLocalRef(sqlState);
        JNI_throw(ex);
    }
    PG_CATCH();
    {
        ereport(WARNING, (errcode(errCode), errmsg("Exception while generating exception: %s", buf)));
    }
    PG_END_TRY();
    va_end(args);
}
References JNI_deleteLocalRef(), JNI_newObject(), JNI_throw(), SQLException_class, SQLException_init, and String_createJavaStringFromNTS().
Referenced by beginNative(), beginNativeNoErrCheck(), coerceObjects(), Exception_throwSPI(), Java_org_postgresql_pljava_internal_Oid__1forSqlType(), Java_org_postgresql_pljava_internal_Oid__1getJavaClassName(), Java_org_postgresql_pljava_internal_Relation__1modifyTuple(), Java_org_postgresql_pljava_internal_TupleDesc__1getColumnIndex(), Java_org_postgresql_pljava_internal_TupleDesc__1getColumnName(), Java_org_postgresql_pljava_internal_TupleDesc__1getOid(), Java_org_postgresql_pljava_jdbc_Invocation__1register(), and pljava_TupleDesc_getColumnType().
Exception_throw_ERROR()
void Exception_throw_ERROR (const char * funcName)
Definition at line 164 of file Exception.c.
{
    jobject ex;
    PG_TRY();
    {
        jobject ed = pljava_ErrorData_getCurrentError();
        FlushErrorState();
        ex = JNI_newObject(ServerException_class, ServerException_init, ed);
        currentInvocation->errorOccurred = true;
        elog(DEBUG2, "Exception in function %s", funcName);
        JNI_deleteLocalRef(ed);
        JNI_throw(ex);
    }
    PG_CATCH();
    {
        elog(WARNING, "Exception while generating exception");
    }
    PG_END_TRY();
}
References currentInvocation, JNI_deleteLocalRef(), JNI_newObject(), JNI_throw(), pljava_ErrorData_getCurrentError(), ServerException_class, and ServerException_init.
Referenced by Java_org_postgresql_pljava_internal_AclId__1fromName(), Java_org_postgresql_pljava_internal_AclId__1getName(), Java_org_postgresql_pljava_internal_AclId__1getOuterUser(), Java_org_postgresql_pljava_internal_AclId__1getUser(), Java_org_postgresql_pljava_internal_Backend__1getConfigOption(), Java_org_postgresql_pljava_internal_Backend__1log(), Java_org_postgresql_pljava_internal_DualState_00024SingleSPIcursorClose__1spiCursorClose(), Java_org_postgresql_pljava_internal_DualState_00024SingleSPIfreeplan__1spiFreePlan(), Java_org_postgresql_pljava_internal_ExecutionPlan__1cursorOpen(), Java_org_postgresql_pljava_internal_ExecutionPlan__1execute(), Java_org_postgresql_pljava_internal_ExecutionPlan__1isCursorPlan(), Java_org_postgresql_pljava_internal_ExecutionPlan__1prepare(), Java_org_postgresql_pljava_internal_Function__1reconcileTypes(), Java_org_postgresql_pljava_internal_Function__1storeToNonUDT(), Java_org_postgresql_pljava_internal_Function__1storeToUDT(), Java_org_postgresql_pljava_internal_Oid__1forTypeName(), Java_org_postgresql_pljava_internal_PgSavepoint__1release(), Java_org_postgresql_pljava_internal_PgSavepoint__1rollback(), Java_org_postgresql_pljava_internal_PgSavepoint__1set(), Java_org_postgresql_pljava_internal_Portal__1fetch(), Java_org_postgresql_pljava_internal_Portal__1move(), Java_org_postgresql_pljava_internal_Relation__1getName(), Java_org_postgresql_pljava_internal_Relation__1getSchema(), Java_org_postgresql_pljava_internal_Relation__1modifyTuple(), Java_org_postgresql_pljava_internal_SPI__1exec(), Java_org_postgresql_pljava_internal_SubXactListener__1register(), Java_org_postgresql_pljava_internal_SubXactListener__1unregister(), Java_org_postgresql_pljava_internal_TupleDesc__1formTuple(), Java_org_postgresql_pljava_internal_TupleDesc__1getColumnIndex(), Java_org_postgresql_pljava_internal_TupleDesc__1getColumnName(), Java_org_postgresql_pljava_internal_TupleDesc__1getOid(), Java_org_postgresql_pljava_internal_XactListener__1register(), Java_org_postgresql_pljava_internal_XactListener__1unregister(), Java_org_postgresql_pljava_jdbc_SingleRowReader__1getObject(), and pljava_Tuple_getObject().
Exception_throwIllegalArgument()
void Exception_throwIllegalArgument (const char * errMessage, ...)
Definition at line 129 of file Exception.c.
{
    char buf[1024];
    va_list args;
    jstring message;
    jobject ex;
    va_start(args, errMessage);
    vsnprintf(buf, sizeof(buf), errMessage, args);
    ereport(DEBUG3, (errmsg("%s", buf)));
    PG_TRY();
    {
        message = String_createJavaStringFromNTS(buf);
        ex = JNI_newObject(IllegalArgumentException_class, IllegalArgumentException_init, message);
        JNI_deleteLocalRef(message);
        JNI_throw(ex);
    }
    PG_CATCH();
    {
        ereport(WARNING, (errcode(ERRCODE_INTERNAL_ERROR), errmsg("Exception while generating exception: %s", buf)));
    }
    PG_END_TRY();
    va_end(args);
}
References IllegalArgumentException_class, IllegalArgumentException_init, JNI_deleteLocalRef(), JNI_newObject(), JNI_throw(), and String_createJavaStringFromNTS().
Referenced by _byte_array_coerceObject().
Exception_throwSPI()
void Exception_throwSPI (const char * function, int errCode)
Definition at line 157 of file Exception.c.
{
    Exception_throw(ERRCODE_INTERNAL_ERROR,
        "SPI function SPI_%s failed with error %s", function,
            SPI_result_code_string(errCode));
}
References Exception_throw().
Referenced by Java_org_postgresql_pljava_internal_ExecutionPlan__1execute(), Java_org_postgresql_pljava_internal_ExecutionPlan__1prepare(), Java_org_postgresql_pljava_internal_Relation__1modifyTuple(), and Java_org_postgresql_pljava_internal_SPI__1exec().
Variable Documentation
Class_class
jclass Class_class
Definition at line 24 of file Exception.c.
Referenced by Exception_initialize().
Class_getCanonicalName
jmethodID Class_getCanonicalName
Definition at line 26 of file Exception.c.
Referenced by Exception_initialize(), and Type_coerceDatumAs().
Class_getName
jmethodID Class_getName
Definition at line 25 of file Exception.c.
Referenced by elogExceptionMessage(), Exception_initialize(), and UDT_registerUDT().
IllegalArgumentException_class
jclass IllegalArgumentException_class
Definition at line 36 of file Exception.c.
Referenced by Exception_initialize(), and Exception_throwIllegalArgument().
IllegalArgumentException_init
jmethodID IllegalArgumentException_init
Definition at line 37 of file Exception.c.
Referenced by Exception_initialize(), and Exception_throwIllegalArgument().
NoSuchFieldError_class
jclass NoSuchFieldError_class
Definition at line 46 of file Exception.c.
Referenced by Exception_initialize(), and JNI_getFieldIDOrNull().
NoSuchMethodError_class
jclass NoSuchMethodError_class
Definition at line 47 of file Exception.c.
Referenced by Exception_initialize(), and JNI_getStaticMethodIDOrNull().
ServerException_class
jclass ServerException_class
Definition at line 28 of file Exception.c.
Referenced by endCall(), endCallMonitorHeld(), Exception_initialize2(), and Exception_throw_ERROR().
ServerException_getErrorData
jmethodID ServerException_getErrorData
Definition at line 29 of file Exception.c.
Referenced by endCall(), endCallMonitorHeld(), and Exception_initialize2().
ServerException_init
jmethodID ServerException_init
Definition at line 30 of file Exception.c.
Referenced by Exception_initialize2(), and Exception_throw_ERROR().
SQLException_class
jclass SQLException_class
Definition at line 39 of file Exception.c.
Referenced by elogExceptionMessage(), Exception_initialize(), and Exception_throw().
SQLException_getSQLState
jmethodID SQLException_getSQLState
Definition at line 41 of file Exception.c.
Referenced by elogExceptionMessage(), and Exception_initialize().
SQLException_init
jmethodID SQLException_init
Definition at line 40 of file Exception.c.
Referenced by Exception_initialize(), and Exception_throw().
Throwable_class
jclass Throwable_class
Definition at line 32 of file Exception.c.
Referenced by Exception_initialize().
Throwable_getMessage
jmethodID Throwable_getMessage
Definition at line 33 of file Exception.c.
Referenced by elogExceptionMessage(), and Exception_initialize().
Throwable_printStackTrace
jmethodID Throwable_printStackTrace
Definition at line 34 of file Exception.c.
Referenced by Exception_initialize(), and printStacktrace().
UnsupportedOperationException_class
jclass UnsupportedOperationException_class
Definition at line 43 of file Exception.c.
Referenced by Exception_featureNotSupported(), and Exception_initialize().
UnsupportedOperationException_init
jmethodID UnsupportedOperationException_init
Definition at line 44 of file Exception.c.
Referenced by Exception_featureNotSupported(), and Exception_initialize().