PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/SQLChunkIOOrder.c File Reference
SQLChunkIOOrder.c File Reference
#include <postgres.h>
#include "pljava/PgObject.h"
Functions
void SQLChunkIOOrder_initialize (void)
Function Documentation
SQLChunkIOOrder_initialize()
void SQLChunkIOOrder_initialize (void) extern
Definition at line 17 of file SQLChunkIOOrder.c.
{
    /*
     * Nothing more is needed here than to cause the class's static initializer
     * to run (at the chosen time, from native code, before user Java code could
     * have altered the needed system properties).
     *
     * The JNI_FindClass mentions that it initializes the named class, but only
     * says so in one place, does not clearly say it returns an initialized
     * class, and does not mention ExceptionInInitializerError as a possible
     * exception.
     *
     * GetStaticFieldID clearly says it causes an uninitialized class to be
     * initialized, and lists ExceptionInInitializerError as a possible
     * exception. So, just to be sure, a field ID is fetched here.
     */
    jclass cls = PgObject_getJavaClass(
        "org/postgresql/pljava/jdbc/SQLChunkIOOrder");
    PgObject_getStaticJavaField(cls, "MIRROR_J2P", "Ljava/nio/ByteOrder;");
}
References PgObject_getJavaClass(), and PgObject_getStaticJavaField().
Referenced by initPLJavaClasses().