PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Float.c File Reference
Float.c File Reference
#include "pljava/type/Type_priv.h"
#include "pljava/type/Array.h"
#include "pljava/Invocation.h"
Functions
static Datum _asDatum (jfloat v)
static Datum _float_invoke (Type self, Function fn, PG_FUNCTION_ARGS)
static jvalue _float_coerceDatum (Type self, Datum arg)
static jvalue _floatArray_coerceDatum (Type self, Datum arg)
static Datum _floatArray_coerceObject (Type self, jobject floatArray)
static bool _Float_canReplace (Type self, Type other)
static jvalue _Float_coerceDatum (Type self, Datum arg)
static Datum _Float_coerceObject (Type self, jobject floatObj)
static Type _float_createArrayType (Type self, Oid arrayTypeId)
void Float_initialize (void)
Variables
static TypeClass s_floatClass
static jclass s_Float_class
static jmethodID s_Float_init
static jmethodID s_Float_floatValue
Function Documentation
_asDatum()
static Datum _asDatum (jfloat v) static
Definition at line 26 of file Float.c.
{
    MemoryContext currCtx = Invocation_switchToUpperContext();
    Datum ret = Float4GetDatum(v);
    MemoryContextSwitchTo(currCtx);
    return ret;
}
References Invocation_switchToUpperContext().
Referenced by _Float_coerceObject(), and _float_invoke().
_Float_canReplace()
static bool _Float_canReplace (Type self, Type other) static
Definition at line 96 of file Float.c.
{
    TypeClass cls = Type_getClass(other);
    return Type_getClass(self) == cls || cls == s_floatClass;
}
References s_floatClass, and Type_getClass().
Referenced by Float_initialize().
_float_coerceDatum()
static jvalue _float_coerceDatum (Type self, Datum arg) static
Definition at line 39 of file Float.c.
{
    jvalue result;
    result.f = DatumGetFloat4(arg);
    return result;
}
Referenced by Float_initialize().
_Float_coerceDatum()
static jvalue _Float_coerceDatum (Type self, Datum arg) static
Definition at line 102 of file Float.c.
{
    jvalue result;
    result.l = JNI_newObject(s_Float_class, s_Float_init, DatumGetFloat4(arg));
    return result;
}
References JNI_newObject(), s_Float_class, and s_Float_init.
Referenced by Float_initialize().
_Float_coerceObject()
static Datum _Float_coerceObject (Type self, jobject floatObj) static
Definition at line 109 of file Float.c.
{
    return _asDatum(floatObj == 0 ? 0.0f : JNI_callFloatMethod(floatObj, s_Float_floatValue));
}
References _asDatum(), JNI_callFloatMethod(), and s_Float_floatValue.
Referenced by Float_initialize().
_float_createArrayType()
static Type _float_createArrayType (Type self, Oid arrayTypeId) static
Definition at line 114 of file Float.c.
{
    return Array_fromOid2(arrayTypeId, self, _floatArray_coerceDatum, _floatArray_coerceObject);
}
References _floatArray_coerceDatum(), _floatArray_coerceObject(), and Array_fromOid2().
Referenced by Float_initialize().
_float_invoke()
static Datum _float_invoke (Type self, Function fn, PG_FUNCTION_ARGS) static
Definition at line 34 of file Float.c.
{
    return _asDatum(pljava_Function_floatInvoke(fn));
}
References _asDatum(), and pljava_Function_floatInvoke().
Referenced by Float_initialize().
_floatArray_coerceDatum()
static jvalue _floatArray_coerceDatum (Type self, Datum arg) static
Definition at line 46 of file Float.c.
{
    jvalue     result;
    ArrayType* v      = DatumGetArrayTypeP(arg);
    jsize      nElems = (jsize)ArrayGetNItems(ARR_NDIM(v), ARR_DIMS(v));
    jfloatArray floatArray = JNI_newFloatArray(nElems);
    if(ARR_HASNULL(v))
    {
        jsize idx;
        jboolean isCopy = JNI_FALSE;
        bits8* nullBitMap = ARR_NULLBITMAP(v);
        jfloat* values = (jfloat*)ARR_DATA_PTR(v);
        jfloat* elems  = JNI_getFloatArrayElements(floatArray, &isCopy);
        for(idx = 0; idx < nElems; ++idx)
        {
            if(arrayIsNull(nullBitMap, idx))
                elems[idx] = 0;
            else
                elems[idx] = *values++;
        }
        JNI_releaseFloatArrayElements(floatArray, elems, JNI_COMMIT);
    }
    else
        JNI_setFloatArrayRegion(floatArray, 0, nElems, (jfloat*)ARR_DATA_PTR(v));
    result.l = (jobject)floatArray;
    return result;
}
References arrayIsNull(), JNI_getFloatArrayElements(), JNI_newFloatArray(), JNI_releaseFloatArrayElements(), and JNI_setFloatArrayRegion().
Referenced by _float_createArrayType().
_floatArray_coerceObject()
static Datum _floatArray_coerceObject (Type self, jobject floatArray) static
Definition at line 75 of file Float.c.
{
    ArrayType* v;
    jsize nElems;
    if(floatArray == 0)
        return 0;
    nElems = JNI_getArrayLength((jarray)floatArray);
    v = createArrayType(nElems, sizeof(jfloat), FLOAT4OID, false);
    JNI_getFloatArrayRegion((jfloatArray)floatArray, 0,
                      nElems, (jfloat*)ARR_DATA_PTR(v));
    PG_RETURN_ARRAYTYPE_P(v);
}
References createArrayType(), JNI_getArrayLength(), and JNI_getFloatArrayRegion().
Referenced by _float_createArrayType().
Float_initialize()
void Float_initialize (void) extern
Definition at line 122 of file Float.c.
{
    Type t_float;
    Type t_Float;
    TypeClass cls;
    s_Float_class = JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Float"));
    s_Float_init = PgObject_getJavaMethod(s_Float_class, "<init>", "(F)V");
    s_Float_floatValue = PgObject_getJavaMethod(s_Float_class, "floatValue", "()F");
    cls = TypeClass_alloc("type.Float");
    cls->canReplaceType = _Float_canReplace;
    cls->JNISignature = "Ljava/lang/Float;";
    cls->javaTypeName = "java.lang.Float";
    cls->coerceDatum  = _Float_coerceDatum;
    cls->coerceObject = _Float_coerceObject;
    t_Float = TypeClass_allocInstance(cls, FLOAT4OID);
    cls = TypeClass_alloc("type.float");
    cls->JNISignature = "F";
    cls->javaTypeName = "float";
    cls->invoke       = _float_invoke;
    cls->coerceDatum  = _float_coerceDatum;
    cls->coerceObject = _Float_coerceObject;
    cls->createArrayType = _float_createArrayType;
    s_floatClass = cls;
    t_float = TypeClass_allocInstance(cls, FLOAT4OID);
    t_float->objectType = t_Float;
    Type_registerType("float", t_float);
    Type_registerType("java.lang.Float", t_Float);
}
References _Float_canReplace(), _float_coerceDatum(), _Float_coerceDatum(), _Float_coerceObject(), _float_createArrayType(), _float_invoke(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Float_class, s_Float_floatValue, s_Float_init, s_floatClass, Type, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Variable Documentation
s_Float_class
jclass s_Float_class static
Definition at line 19 of file Float.c.
Referenced by _Float_coerceDatum(), and Float_initialize().
s_Float_floatValue
jmethodID s_Float_floatValue static
Definition at line 21 of file Float.c.
Referenced by _Float_coerceObject(), and Float_initialize().
s_Float_init
jmethodID s_Float_init static
Definition at line 20 of file Float.c.
Referenced by _Float_coerceDatum(), and Float_initialize().
s_floatClass
TypeClass s_floatClass static
Definition at line 18 of file Float.c.
Referenced by _Float_canReplace(), and Float_initialize().