PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Portal.c File Reference
Portal.c File Reference
#include <postgres.h>
#include <commands/portalcmds.h>
#include <executor/spi.h>
#include <executor/tuptable.h>
#include "org_postgresql_pljava_internal_Portal.h"
#include "pljava/Backend.h"
#include "pljava/DualState.h"
#include "pljava/Exception.h"
#include "pljava/Invocation.h"
#include "pljava/HashMap.h"
#include "pljava/type/Type_priv.h"
#include "pljava/type/TupleDesc.h"
#include "pljava/type/Portal.h"
#include "pljava/type/String.h"
Functions
jobject pljava_Portal_create (Portal portal, jobject jplan)
void pljava_Portal_initialize (void)
JNIEXPORT jlong JNICALL Java_org_postgresql_pljava_internal_Portal__1getPortalPos (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jlong JNICALL Java_org_postgresql_pljava_internal_Portal__1fetch (JNIEnv *env, jclass clazz, jlong _this, jboolean forward, jlong count)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_Portal__1getName (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Portal__1getTupleDesc (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_Portal__1isAtStart (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_Portal__1isAtEnd (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jlong JNICALL Java_org_postgresql_pljava_internal_Portal__1move (JNIEnv *env, jclass clazz, jlong _this, jboolean forward, jlong count)
Variables
static jclass s_Portal_class
static jmethodID s_Portal_init
Function Documentation
Java_org_postgresql_pljava_internal_Portal__1fetch()
JNIEXPORT jlong JNICALL Java_org_postgresql_pljava_internal_Portal__1fetch (JNIEnv * env, jclass clazz, jlong _this, jboolean forward, jlong count)
Definition at line 138 of file Portal.c.
{
    jlong result = 0;
    if(_this != 0)
    {
        BEGIN_NATIVE
        Ptr2Long p2l;
        STACK_BASE_VARS
        STACK_BASE_PUSH(env)
        /*
         * One call to cleanEnqueued... is made in Invocation_popInvocation,
         * when any PL/Java function returns to PostgreSQL. But what of a
         * PL/Java function that loops through a lot of data before returning?
         * It could be important to call cleanEnqueued... from some other
         * strategically-chosen places, and this seems a good one. We get here
         * every fetchSize (default 1000? See SPIStatement) rows retrieved.
         */
        pljava_DualState_cleanEnqueuedInstances();
        p2l.longVal = _this;
        PG_TRY();
        {
            Invocation_assertConnect();
            SPI_cursor_fetch((Portal)p2l.ptrVal, forward == JNI_TRUE,
                (long)count);
            result = (jlong)SPI_processed;
        }
        PG_CATCH();
        {
            Exception_throw_ERROR("SPI_cursor_fetch");
        }
        PG_END_TRY();
        STACK_BASE_POP()
        END_NATIVE
    }
    return result;
}
References Exception_throw_ERROR(), Invocation_assertConnect(), and pljava_DualState_cleanEnqueuedInstances().
Referenced by pljava_Portal_initialize().
Java_org_postgresql_pljava_internal_Portal__1getName()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_Portal__1getName (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 183 of file Portal.c.
{
    jstring result = 0;
    if(_this != 0)
    {
        BEGIN_NATIVE
        Ptr2Long p2l;
        p2l.longVal = _this;
        result = String_createJavaStringFromNTS(((Portal)p2l.ptrVal)->name);
        END_NATIVE
    }
    return result;
}
References String_createJavaStringFromNTS().
Referenced by pljava_Portal_initialize().
Java_org_postgresql_pljava_internal_Portal__1getPortalPos()
JNIEXPORT jlong JNICALL Java_org_postgresql_pljava_internal_Portal__1getPortalPos (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 120 of file Portal.c.
{
    jlong result = 0;
    if(_this != 0)
    {
        Ptr2Long p2l;
        p2l.longVal = _this;
        result = (jlong)((Portal)p2l.ptrVal)->portalPos;
    }
    return result;
}
Referenced by pljava_Portal_initialize().
Java_org_postgresql_pljava_internal_Portal__1getTupleDesc()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Portal__1getTupleDesc (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 203 of file Portal.c.
{
    jobject result = 0;
    if(_this != 0)
    {
        BEGIN_NATIVE
        Ptr2Long p2l;
        p2l.longVal = _this;
        result = pljava_TupleDesc_create(((Portal)p2l.ptrVal)->tupDesc);
        END_NATIVE
    }
    return result;
}
References pljava_TupleDesc_create().
Referenced by pljava_Portal_initialize().
Java_org_postgresql_pljava_internal_Portal__1isAtEnd()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_Portal__1isAtEnd (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 241 of file Portal.c.
{
    jboolean result = JNI_FALSE;
    if(_this != 0)
    {
        Ptr2Long p2l;
        p2l.longVal = _this;
        result = (jboolean)((Portal)p2l.ptrVal)->atEnd;
    }
    return result;
}
Referenced by pljava_Portal_initialize().
Java_org_postgresql_pljava_internal_Portal__1isAtStart()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_Portal__1isAtStart (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 223 of file Portal.c.
{
    jboolean result = JNI_FALSE;
    if(_this != 0)
    {
        Ptr2Long p2l;
        p2l.longVal = _this;
        result = (jboolean)((Portal)p2l.ptrVal)->atStart;
    }
    return result;
}
Referenced by pljava_Portal_initialize().
Java_org_postgresql_pljava_internal_Portal__1move()
JNIEXPORT jlong JNICALL Java_org_postgresql_pljava_internal_Portal__1move (JNIEnv * env, jclass clazz, jlong _this, jboolean forward, jlong count)
Definition at line 259 of file Portal.c.
{
    jlong result = 0;
    if(_this != 0)
    {
        BEGIN_NATIVE
        Ptr2Long p2l;
        STACK_BASE_VARS
        STACK_BASE_PUSH(env)
        p2l.longVal = _this;
        PG_TRY();
        {
            Invocation_assertConnect();
            SPI_cursor_move((Portal)p2l.ptrVal, forward == JNI_TRUE, (long)count);
            result = (jlong)SPI_processed;
        }
        PG_CATCH();
        {
            Exception_throw_ERROR("SPI_cursor_move");
        }
        PG_END_TRY();
        STACK_BASE_POP()
        END_NATIVE
    }
    return result;
}
References Exception_throw_ERROR(), and Invocation_assertConnect().
Referenced by pljava_Portal_initialize().
pljava_Portal_create()
jobject pljava_Portal_create (Portal portal, jobject jplan)
Definition at line 40 of file Portal.c.
{
    jobject jportal;
    Ptr2Long p2l;
    Ptr2Long p2lro;
    if(portal == 0)
        return NULL;
    p2l.longVal = 0L; /* ensure that the rest is zeroed out */
    p2l.ptrVal = portal;
    p2lro.longVal = 0L;
    p2lro.ptrVal = portal->resowner;
    jportal = JNI_newObjectLocked(s_Portal_class, s_Portal_init,
        pljava_DualState_key(), p2lro.longVal, p2l.longVal, jplan);
    return jportal;
}
References JNI_newObjectLocked(), pljava_DualState_key(), s_Portal_class, and s_Portal_init.
Referenced by Java_org_postgresql_pljava_internal_ExecutionPlan__1cursorOpen().
pljava_Portal_initialize()
void pljava_Portal_initialize (void)
Definition at line 62 of file Portal.c.
{
    JNINativeMethod methods[] =
    {
        {
        "_getName",
        "(J)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_Portal__1getName
        },
        {
        "_getPortalPos",
        "(J)J",
        Java_org_postgresql_pljava_internal_Portal__1getPortalPos
        },
        {
        "_getTupleDesc",
        "(J)Lorg/postgresql/pljava/internal/TupleDesc;",
        Java_org_postgresql_pljava_internal_Portal__1getTupleDesc
        },
        {
        "_fetch",
        "(JZJ)J",
        Java_org_postgresql_pljava_internal_Portal__1fetch
        },
        {
        "_isAtEnd",
        "(J)Z",
        Java_org_postgresql_pljava_internal_Portal__1isAtEnd
        },
        {
        "_isAtStart",
        "(J)Z",
        Java_org_postgresql_pljava_internal_Portal__1isAtStart
        },
        {
        "_move",
        "(JZJ)J",
        Java_org_postgresql_pljava_internal_Portal__1move
        },
        { 0, 0, 0 }
    };
    s_Portal_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/internal/Portal"));
    PgObject_registerNatives2(s_Portal_class, methods);
    s_Portal_init = PgObject_getJavaMethod(s_Portal_class, "<init>",
        "(Lorg/postgresql/pljava/internal/DualState$Key;JJLorg/postgresql/pljava/internal/ExecutionPlan;)V");
}
References Java_org_postgresql_pljava_internal_Portal__1fetch(), Java_org_postgresql_pljava_internal_Portal__1getName(), Java_org_postgresql_pljava_internal_Portal__1getPortalPos(), Java_org_postgresql_pljava_internal_Portal__1getTupleDesc(), Java_org_postgresql_pljava_internal_Portal__1isAtEnd(), Java_org_postgresql_pljava_internal_Portal__1isAtStart(), Java_org_postgresql_pljava_internal_Portal__1move(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_registerNatives2(), s_Portal_class, and s_Portal_init.
Referenced by pljava_DualState_initialize().
Variable Documentation
s_Portal_class
jclass s_Portal_class static
Definition at line 34 of file Portal.c.
Referenced by pljava_Portal_create(), and pljava_Portal_initialize().
s_Portal_init
jmethodID s_Portal_init static
Definition at line 35 of file Portal.c.
Referenced by pljava_Portal_create(), and pljava_Portal_initialize().