PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/BigDecimal.c File Reference
BigDecimal.c File Reference
#include <postgres.h>
#include <utils/memutils.h>
#include <utils/numeric.h>
#include "pljava/type/String_priv.h"
Functions
static jvalue _BigDecimal_coerceDatum (Type self, Datum arg)
static Datum _BigDecimal_coerceObject (Type self, jobject value)
static Type BigDecimal_obtain (Oid typeId)
void BigDecimal_initialize (void)
Variables
static jclass s_BigDecimal_class
static jmethodID s_BigDecimal_init
static jmethodID s_BigDecimal_toString
static TypeClass s_BigDecimalClass
Function Documentation
_BigDecimal_coerceDatum()
static jvalue _BigDecimal_coerceDatum (Type self, Datum arg) static
Definition at line 25 of file BigDecimal.c.
{
    jvalue result = _String_coerceDatum(self, arg);
    if(result.l != 0)
        result.l = JNI_newObject(s_BigDecimal_class, s_BigDecimal_init, result.l);
    return result;
}
References _String_coerceDatum(), JNI_newObject(), s_BigDecimal_class, and s_BigDecimal_init.
Referenced by BigDecimal_initialize().
_BigDecimal_coerceObject()
static Datum _BigDecimal_coerceObject (Type self, jobject value) static
Definition at line 33 of file BigDecimal.c.
{
    jstring jstr = (jstring)JNI_callObjectMethod(value, s_BigDecimal_toString);
    Datum ret = _String_coerceObject(self, jstr);
    JNI_deleteLocalRef(jstr);
    return ret;
}
References _String_coerceObject(), JNI_callObjectMethod(), JNI_deleteLocalRef(), and s_BigDecimal_toString.
Referenced by BigDecimal_initialize().
BigDecimal_initialize()
void BigDecimal_initialize (void) extern
Definition at line 49 of file BigDecimal.c.
{
    s_BigDecimal_class = JNI_newGlobalRef(PgObject_getJavaClass("java/math/BigDecimal"));
    s_BigDecimal_init = PgObject_getJavaMethod(s_BigDecimal_class, "<init>", "(Ljava/lang/String;)V");
    s_BigDecimal_toString = PgObject_getJavaMethod(s_BigDecimal_class, "toString", "()Ljava/lang/String;");
    s_BigDecimalClass = TypeClass_alloc2("type.BigDecimal", sizeof(struct TypeClass_), sizeof(struct String_));
    s_BigDecimalClass->JNISignature   = "Ljava/math/BigDecimal;";
    s_BigDecimalClass->javaTypeName   = "java.math.BigDecimal";
    s_BigDecimalClass->canReplaceType = _Type_canReplaceType;
    s_BigDecimalClass->coerceDatum    = _BigDecimal_coerceDatum;
    s_BigDecimalClass->coerceObject   = _BigDecimal_coerceObject;
    Type_registerType2(NUMERICOID, "java.math.BigDecimal", BigDecimal_obtain);
}
References _BigDecimal_coerceDatum(), _BigDecimal_coerceObject(), _Type_canReplaceType(), BigDecimal_obtain(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_BigDecimal_class, s_BigDecimal_init, s_BigDecimal_toString, s_BigDecimalClass, Type_registerType2(), and TypeClass_alloc2().
Referenced by Type_initialize().
BigDecimal_obtain()
static Type BigDecimal_obtain (Oid typeId) static
Definition at line 41 of file BigDecimal.c.
{
    return (Type)StringClass_obtain(s_BigDecimalClass, typeId);
}
References s_BigDecimalClass, StringClass_obtain(), and Type.
Referenced by BigDecimal_initialize().
Variable Documentation
s_BigDecimal_class
jclass s_BigDecimal_class static
Definition at line 20 of file BigDecimal.c.
Referenced by _BigDecimal_coerceDatum(), and BigDecimal_initialize().
s_BigDecimal_init
jmethodID s_BigDecimal_init static
Definition at line 21 of file BigDecimal.c.
Referenced by _BigDecimal_coerceDatum(), and BigDecimal_initialize().
s_BigDecimal_toString
jmethodID s_BigDecimal_toString static
Definition at line 22 of file BigDecimal.c.
Referenced by _BigDecimal_coerceObject(), and BigDecimal_initialize().
s_BigDecimalClass
TypeClass s_BigDecimalClass static
Definition at line 23 of file BigDecimal.c.
Referenced by BigDecimal_initialize(), and BigDecimal_obtain().