PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Oid.c File Reference
Oid.c File Reference
#include <postgres.h>
#include <parser/parse_type.h>
#include "org_postgresql_pljava_internal_Oid.h"
#include "java_sql_Types.h"
#include "pljava/type/Type_priv.h"
#include "pljava/type/Oid.h"
#include "pljava/type/String.h"
#include "pljava/Exception.h"
#include "pljava/Function.h"
#include "pljava/Invocation.h"
Macros
#define Type PGType
Functions
jobject Oid_create (Oid oid)
Oid Oid_getOid (jobject joid)
Oid Oid_forSqlType (int sqlType)
static jvalue _Oid_coerceDatum (Type self, Datum arg)
static Datum _Oid_coerceObject (Type self, jobject oidObj)
void Oid_initialize (void)
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_Oid__1forSqlType (JNIEnv *env, jclass cls, jint sqlType)
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_Oid__1forTypeName (JNIEnv *env, jclass cls, jstring typeString)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Oid__1getTypeId (JNIEnv *env, jclass cls)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_Oid__1getJavaClassName (JNIEnv *env, jclass cls, jint oid)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Oid__1getCurrentLoader (JNIEnv *env, jclass cls)
Variables
static jclass s_Oid_class
static jmethodID s_Oid_init
static jmethodID s_Oid_registerType
static jfieldID s_Oid_m_native
static jobject s_OidOid
Macro Definition Documentation
Type
#define Type PGType
Definition at line 15 of file Oid.c.
Function Documentation
_Oid_coerceDatum()
static jvalue _Oid_coerceDatum (Type self, Datum arg) static
Definition at line 159 of file Oid.c.
{
    jvalue result;
    result.l = Oid_create(DatumGetObjectId(arg));
    return result;
}
References Oid_create().
Referenced by Oid_initialize().
_Oid_coerceObject()
static Datum _Oid_coerceObject (Type self, jobject oidObj) static
Definition at line 166 of file Oid.c.
{
    return Oid_getOid(oidObj);
}
References Oid_getOid().
Referenced by Oid_initialize().
Java_org_postgresql_pljava_internal_Oid__1forSqlType()
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_Oid__1forSqlType (JNIEnv * env, jclass cls, jint sqlType)
Definition at line 236 of file Oid.c.
{
    Oid typeId = InvalidOid;
    BEGIN_NATIVE
    typeId = Oid_forSqlType(sqlType);
    if(typeId == InvalidOid)
        Exception_throw(ERRCODE_INTERNAL_ERROR, "No such SQL type: %d", (int)sqlType);
    END_NATIVE
    return typeId;
}
References Exception_throw(), and Oid_forSqlType().
Referenced by Oid_initialize().
Java_org_postgresql_pljava_internal_Oid__1forTypeName()
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_Oid__1forTypeName (JNIEnv * env, jclass cls, jstring typeString)
Definition at line 253 of file Oid.c.
{
    Oid typeId = InvalidOid;
    BEGIN_NATIVE
    char* typeNameOrOid = String_createNTS(typeString);
    if(typeNameOrOid != 0)
    {
        PG_TRY();
        {
            int32 typmod = 0;
            parseTypeString(typeNameOrOid, &typeId, &typmod, 0);
        }
        PG_CATCH();
        {
            Exception_throw_ERROR("parseTypeString");
        }
        PG_END_TRY();
        pfree(typeNameOrOid);
    }
    END_NATIVE
    return typeId;
}
References Exception_throw_ERROR(), and String_createNTS().
Referenced by Oid_initialize().
Java_org_postgresql_pljava_internal_Oid__1getCurrentLoader()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Oid__1getCurrentLoader (JNIEnv * env, jclass cls)
Definition at line 317 of file Oid.c.
{
    jobject result = NULL;
    BEGIN_NATIVE
    result = Function_currentLoader();
    END_NATIVE
    return result;
}
References Function_currentLoader().
Referenced by Oid_initialize().
Java_org_postgresql_pljava_internal_Oid__1getJavaClassName()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_Oid__1getJavaClassName (JNIEnv * env, jclass cls, jint oid)
Definition at line 294 of file Oid.c.
{
    jstring result = 0;
    BEGIN_NATIVE
    if(!OidIsValid((Oid)oid))
    {
        Exception_throw(ERRCODE_DATA_EXCEPTION, "Invalid OID \"%d\"", (int)oid);
    }
    else
    {
        Type type = Type_objectTypeFromOid((Oid)oid, Invocation_getTypeMap());
        result = String_createJavaStringFromNTS(Type_getJavaTypeName(type));
    }
    END_NATIVE
    return result;
}
References Exception_throw(), Invocation_getTypeMap(), String_createJavaStringFromNTS(), Type, Type_getJavaTypeName(), and Type_objectTypeFromOid().
Referenced by Oid_initialize().
Java_org_postgresql_pljava_internal_Oid__1getTypeId()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Oid__1getTypeId (JNIEnv * env, jclass cls)
Definition at line 283 of file Oid.c.
{
    return s_OidOid;
}
References s_OidOid.
Referenced by Oid_initialize().
Oid_create()
jobject Oid_create (Oid oid)
Definition at line 37 of file Oid.c.
{
    jobject joid;
    /*
     * This is a natural place to have a StaticAssertStmt making sure the
     * ubiquitous PG type 'Oid' fits in a jint. If it is ever removed from here
     * or this code goes away, it should go someplace else. If it ever produces
     * an error, don't assume the only things that need fixing will be in this
     * file or nearby....
     */
    StaticAssertStmt(sizeof(Oid) <= sizeof(jint), "Oid wider than jint?!");
    if(OidIsValid(oid))
        joid = JNI_newObject(s_Oid_class, s_Oid_init, oid);
    else
        joid = 0;
    return joid;
}
References jint(), JNI_newObject(), s_Oid_class, and s_Oid_init.
Referenced by _Oid_coerceDatum(), checkTypeMappedUDT(), Java_org_postgresql_pljava_internal_TupleDesc__1getOid(), and Oid_initialize().
Oid_forSqlType()
Oid Oid_forSqlType (int sqlType)
Definition at line 62 of file Oid.c.
{
    Oid typeId;
    switch(sqlType)
    {
        case java_sql_Types_BIT:
            typeId = BITOID;
            break;
        case java_sql_Types_TINYINT:
            typeId = CHAROID;
            break;
        case java_sql_Types_SMALLINT:
            typeId = INT2OID;
            break;
        case java_sql_Types_INTEGER:
            typeId = INT4OID;
            break;
        case java_sql_Types_BIGINT:
            typeId = INT8OID;
            break;
        case java_sql_Types_FLOAT:
        case java_sql_Types_REAL:
            typeId = FLOAT4OID;
            break;
        case java_sql_Types_DOUBLE:
            typeId = FLOAT8OID;
            break;
        case java_sql_Types_NUMERIC:
        case java_sql_Types_DECIMAL:
            typeId = NUMERICOID;
            break;
        case java_sql_Types_DATE:
            typeId = DATEOID;
            break;
        case java_sql_Types_TIME:
            typeId = TIMEOID;
            break;
        case java_sql_Types_TIMESTAMP:
            typeId = TIMESTAMPOID;
            break;
        case java_sql_Types_BOOLEAN:
            typeId = BOOLOID;
            break;
        case java_sql_Types_BINARY:
        case java_sql_Types_VARBINARY:
        case java_sql_Types_LONGVARBINARY:
        case java_sql_Types_BLOB:
            typeId = BYTEAOID;
            break;
        case java_sql_Types_CHAR:
        case java_sql_Types_VARCHAR:
        case java_sql_Types_LONGVARCHAR:
        case java_sql_Types_CLOB:
        case java_sql_Types_DATALINK:
            typeId = TEXTOID;
            break;
        case java_sql_Types_NULL:
        case java_sql_Types_OTHER:
        case java_sql_Types_JAVA_OBJECT:
        case java_sql_Types_DISTINCT:
        case java_sql_Types_STRUCT:
        case java_sql_Types_ARRAY:
        case java_sql_Types_REF:
            typeId = InvalidOid;    /* Not yet mapped */
            break;
        /* JDBC 4.0 - present in Java 6 and later, no need to conditionalize */
        case java_sql_Types_SQLXML:
#ifdef  XMLOID                  /* but PG can have been built without libxml */
            typeId = XMLOID;
#else
            typeId = InvalidOid;
#endif
            break;
        case java_sql_Types_ROWID:
        case java_sql_Types_NCHAR:
        case java_sql_Types_NVARCHAR:
        case java_sql_Types_LONGNVARCHAR:
        case java_sql_Types_NCLOB:
            typeId = InvalidOid;    /* Not yet mapped */
            break;
        case java_sql_Types_TIME_WITH_TIMEZONE:
            typeId = TIMETZOID;
            break;
        case java_sql_Types_TIMESTAMP_WITH_TIMEZONE:
            typeId = TIMESTAMPTZOID;
            break;
        case java_sql_Types_REF_CURSOR:
        default:
            typeId = InvalidOid;    /* Not yet mapped */
            break;
    }
    return typeId;
}
Referenced by Java_org_postgresql_pljava_internal_Oid__1forSqlType().
Oid_getOid()
Oid Oid_getOid (jobject joid)
Definition at line 55 of file Oid.c.
{
    if(joid == 0)
        return InvalidOid;
    return ObjectIdGetDatum(JNI_getIntField(joid, s_Oid_m_native));
}
References JNI_getIntField(), and s_Oid_m_native.
Referenced by _Oid_coerceObject(), Java_org_postgresql_pljava_internal_AclId__1hasSchemaCreatePermission(), and Java_org_postgresql_pljava_internal_ExecutionPlan__1prepare().
Oid_initialize()
void Oid_initialize (void) extern
Definition at line 174 of file Oid.c.
{
    TypeClass cls;
    JNINativeMethod methods[] = {
        {
        "_forTypeName",
        "(Ljava/lang/String;)I",
        Java_org_postgresql_pljava_internal_Oid__1forTypeName
        },
        {
        "_forSqlType",
        "(I)I",
        Java_org_postgresql_pljava_internal_Oid__1forSqlType
        },
        {
        "_getTypeId",
        "()Lorg/postgresql/pljava/internal/Oid;",
        Java_org_postgresql_pljava_internal_Oid__1getTypeId
        },
        {
        "_getJavaClassName",
        "(I)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_Oid__1getJavaClassName
        },
        {
        "_getCurrentLoader",
        "()Ljava/lang/ClassLoader;",
        Java_org_postgresql_pljava_internal_Oid__1getCurrentLoader
        },
        { 0, 0, 0 }};
    jobject tmp;
    s_Oid_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/internal/Oid"));
    PgObject_registerNatives2(s_Oid_class, methods);
    s_Oid_init = PgObject_getJavaMethod(s_Oid_class, "<init>", "(I)V");
    s_Oid_m_native = PgObject_getJavaField(s_Oid_class, "m_native", "I");
    cls = TypeClass_alloc("type.Oid");
    cls->JNISignature   = "Lorg/postgresql/pljava/internal/Oid;";
    cls->javaTypeName   = "org.postgresql.pljava.internal.Oid";
    cls->coerceDatum    = _Oid_coerceDatum;
    cls->coerceObject   = _Oid_coerceObject;
    Type_registerType("org.postgresql.pljava.internal.Oid", TypeClass_allocInstance(cls, OIDOID));
    tmp = Oid_create(OIDOID);
    s_OidOid = JNI_newGlobalRef(tmp);
    JNI_deleteLocalRef(tmp);
    s_Oid_registerType = PgObject_getStaticJavaMethod(
                s_Oid_class, "registerType",
                "(Ljava/lang/Class;Lorg/postgresql/pljava/internal/Oid;)V");
    JNI_callStaticVoidMethod(s_Oid_class, s_Oid_registerType, s_Oid_class, s_OidOid);
}
References _Oid_coerceDatum(), _Oid_coerceObject(), Java_org_postgresql_pljava_internal_Oid__1forSqlType(), Java_org_postgresql_pljava_internal_Oid__1forTypeName(), Java_org_postgresql_pljava_internal_Oid__1getCurrentLoader(), Java_org_postgresql_pljava_internal_Oid__1getJavaClassName(), Java_org_postgresql_pljava_internal_Oid__1getTypeId(), JNI_callStaticVoidMethod(), JNI_deleteLocalRef(), JNI_newGlobalRef(), Oid_create(), PgObject_getJavaClass(), PgObject_getJavaField(), PgObject_getJavaMethod(), PgObject_getStaticJavaMethod(), PgObject_registerNatives2(), s_Oid_class, s_Oid_init, s_Oid_m_native, s_Oid_registerType, s_OidOid, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Variable Documentation
s_Oid_class
jclass s_Oid_class static
Definition at line 28 of file Oid.c.
Referenced by Oid_create(), and Oid_initialize().
s_Oid_init
jmethodID s_Oid_init static
Definition at line 29 of file Oid.c.
Referenced by Oid_create(), and Oid_initialize().
s_Oid_m_native
jfieldID s_Oid_m_native static
Definition at line 31 of file Oid.c.
Referenced by Oid_getOid(), and Oid_initialize().
s_Oid_registerType
jmethodID s_Oid_registerType static
Definition at line 30 of file Oid.c.
Referenced by Oid_initialize().
s_OidOid
jobject s_OidOid static
Definition at line 32 of file Oid.c.
Referenced by Java_org_postgresql_pljava_internal_Oid__1getTypeId(), and Oid_initialize().