PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Byte.c File Reference
Byte.c File Reference
#include "pljava/type/Type_priv.h"
#include "pljava/type/Array.h"
#include "pljava/Invocation.h"
Functions
static Datum _byte_invoke (Type self, Function fn, PG_FUNCTION_ARGS)
static jvalue _byte_coerceDatum (Type self, Datum arg)
static jvalue _byteArray_coerceDatum (Type self, Datum arg)
static Datum _byteArray_coerceObject (Type self, jobject byteArray)
static bool _Byte_canReplace (Type self, Type other)
static jvalue _Byte_coerceDatum (Type self, Datum arg)
static Datum _Byte_coerceObject (Type self, jobject byteObj)
static Type _byte_createArrayType (Type self, Oid arrayTypeId)
void Byte_initialize (void)
Variables
static TypeClass s_byteClass
static jclass s_Byte_class
static jmethodID s_Byte_init
static jmethodID s_Byte_byteValue
Function Documentation
_Byte_canReplace()
static bool _Byte_canReplace (Type self, Type other) static
Definition at line 90 of file Byte.c.
{
    TypeClass cls = Type_getClass(other);
    return Type_getClass(self) == cls || cls == s_byteClass;
}
References s_byteClass, and Type_getClass().
Referenced by Byte_initialize().
_byte_coerceDatum()
static jvalue _byte_coerceDatum (Type self, Datum arg) static
Definition at line 36 of file Byte.c.
{
    jvalue result;
    result.b = DatumGetChar(arg);
    return result;
}
Referenced by Byte_initialize().
_Byte_coerceDatum()
static jvalue _Byte_coerceDatum (Type self, Datum arg) static
Definition at line 96 of file Byte.c.
{
    jvalue result;
    result.l = JNI_newObject(s_Byte_class, s_Byte_init, DatumGetChar(arg));
    return result;
}
References JNI_newObject(), s_Byte_class, and s_Byte_init.
Referenced by Byte_initialize().
_Byte_coerceObject()
static Datum _Byte_coerceObject (Type self, jobject byteObj) static
Definition at line 103 of file Byte.c.
{
    return CharGetDatum(byteObj == 0 ? 0 : JNI_callByteMethod(byteObj, s_Byte_byteValue));
}
References JNI_callByteMethod(), and s_Byte_byteValue.
Referenced by Byte_initialize().
_byte_createArrayType()
static Type _byte_createArrayType (Type self, Oid arrayTypeId) static
Definition at line 108 of file Byte.c.
{
    return Array_fromOid2(arrayTypeId, self, _byteArray_coerceDatum, _byteArray_coerceObject);
}
References _byteArray_coerceDatum(), _byteArray_coerceObject(), and Array_fromOid2().
Referenced by Byte_initialize().
_byte_invoke()
static Datum _byte_invoke (Type self, Function fn, PG_FUNCTION_ARGS) static
Definition at line 30 of file Byte.c.
{
    jbyte v = pljava_Function_byteInvoke(fn);
    return CharGetDatum(v);
}
References pljava_Function_byteInvoke().
Referenced by Byte_initialize().
_byteArray_coerceDatum()
static jvalue _byteArray_coerceDatum (Type self, Datum arg) static
Definition at line 43 of file Byte.c.
{
    jvalue     result;
    ArrayType* v      = DatumGetArrayTypeP(arg);
    jsize      nElems = (jsize)ArrayGetNItems(ARR_NDIM(v), ARR_DIMS(v));
    jbyteArray byteArray = JNI_newByteArray(nElems);
    if(ARR_HASNULL(v))
    {
        jsize idx;
        jboolean isCopy = JNI_FALSE;
        bits8* nullBitMap = ARR_NULLBITMAP(v);
        jbyte* values = (jbyte*)ARR_DATA_PTR(v);
        jbyte* elems  = JNI_getByteArrayElements(byteArray, &isCopy);
        for(idx = 0; idx < nElems; ++idx)
        {
            if(arrayIsNull(nullBitMap, idx))
                elems[idx] = 0;
            else
                elems[idx] = *values++;
        }
        JNI_releaseByteArrayElements(byteArray, elems, JNI_COMMIT);
    }
    else
        JNI_setByteArrayRegion(byteArray, 0, nElems, (jbyte*)ARR_DATA_PTR(v));
    result.l = (jobject)byteArray;
    return result;
}
References arrayIsNull(), JNI_getByteArrayElements(), JNI_newByteArray(), JNI_releaseByteArrayElements(), and JNI_setByteArrayRegion().
Referenced by _byte_createArrayType().
_byteArray_coerceObject()
static Datum _byteArray_coerceObject (Type self, jobject byteArray) static
Definition at line 72 of file Byte.c.
{
    ArrayType* v;
    jsize nElems;
    if(byteArray == 0)
        return 0;
    nElems = JNI_getArrayLength((jarray)byteArray);
    v = createArrayType(nElems, sizeof(jbyte), CHAROID, false);
    JNI_getByteArrayRegion((jbyteArray)byteArray, 0, nElems, (jbyte*)ARR_DATA_PTR(v));
    PG_RETURN_ARRAYTYPE_P(v);
}
References createArrayType(), JNI_getArrayLength(), and JNI_getByteArrayRegion().
Referenced by _byte_createArrayType().
Byte_initialize()
void Byte_initialize (void) extern
Definition at line 116 of file Byte.c.
{
    Type t_byte;
    Type t_Byte;
    TypeClass cls;
    s_Byte_class = JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Byte"));
    s_Byte_init = PgObject_getJavaMethod(s_Byte_class, "<init>", "(B)V");
    s_Byte_byteValue = PgObject_getJavaMethod(s_Byte_class, "byteValue", "()B");
    cls = TypeClass_alloc("type.Byte");
    cls->canReplaceType = _Byte_canReplace;
    cls->JNISignature = "Ljava/lang/Byte;";
    cls->javaTypeName = "java.lang.Byte";
    cls->coerceDatum  = _Byte_coerceDatum;
    cls->coerceObject = _Byte_coerceObject;
    t_Byte = TypeClass_allocInstance(cls, CHAROID);
    cls = TypeClass_alloc("type.byte");
    cls->JNISignature = "B";
    cls->javaTypeName = "byte";
    cls->invoke       = _byte_invoke;
    cls->coerceDatum  = _byte_coerceDatum;
    cls->coerceObject = _Byte_coerceObject;
    cls->createArrayType = _byte_createArrayType;
    s_byteClass = cls;
    t_byte = TypeClass_allocInstance(cls, CHAROID);
    t_byte->objectType = t_Byte;
    Type_registerType("byte", t_byte);
    Type_registerType("java.lang.Byte", t_Byte);
}
References _Byte_canReplace(), _byte_coerceDatum(), _Byte_coerceDatum(), _Byte_coerceObject(), _byte_createArrayType(), _byte_invoke(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Byte_byteValue, s_Byte_class, s_Byte_init, s_byteClass, Type, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Variable Documentation
s_Byte_byteValue
jmethodID s_Byte_byteValue static
Definition at line 25 of file Byte.c.
Referenced by _Byte_coerceObject(), and Byte_initialize().
s_Byte_class
jclass s_Byte_class static
Definition at line 23 of file Byte.c.
Referenced by _Byte_coerceDatum(), and Byte_initialize().
s_Byte_init
jmethodID s_Byte_init static
Definition at line 24 of file Byte.c.
Referenced by _Byte_coerceDatum(), and Byte_initialize().
s_byteClass
TypeClass s_byteClass static
Definition at line 22 of file Byte.c.
Referenced by _Byte_canReplace(), and Byte_initialize().