PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/JNICalls.c File Reference
JNICalls.c File Reference
#include <string.h>
#include "pljava/JNICalls.h"
#include "pljava/Backend.h"
#include "pljava/Invocation.h"
#include "pljava/Exception.h"
#include "pljava/type/ErrorData.h"
#include "pljava/type/String.h"
Macros
#define BEGIN_JAVA { JNIEnv* env = jniEnv; jniEnv = 0;
#define END_JAVA jniEnv = env; }
#define BEGIN_CALL
#define END_CALL endCall(env); }
#define BEGIN_CALL_MONITOR_HELD BEGIN_JAVA
#define END_CALL_MONITOR_HELD endCallMonitorHeld(env); }
Functions
jint (JNICALL *pljava_createvm)(JavaVM **
void pljava_JNI_setThreadPolicy (bool refuseOtherThreads, bool doMonitorOps)
void pljava_JNI_threadInitialize (bool manageLoader)
static void elogExceptionMessage (JNIEnv *env, jthrowable exh, int logLevel)
static void printStacktrace (JNIEnv *env, jobject exh)
static void endCall (JNIEnv *env)
static void endCallMonitorHeld (JNIEnv *env)
bool beginNativeNoErrCheck (JNIEnv *env)
bool beginNative (JNIEnv *env)
jboolean JNI_callBooleanMethod (jobject object, jmethodID methodID,...)
jboolean JNI_callBooleanMethodV (jobject object, jmethodID methodID, va_list args)
jbyte JNI_callByteMethod (jobject object, jmethodID methodID,...)
jbyte JNI_callByteMethodV (jobject object, jmethodID methodID, va_list args)
jdouble JNI_callDoubleMethod (jobject object, jmethodID methodID,...)
jdouble JNI_callDoubleMethodV (jobject object, jmethodID methodID, va_list args)
jfloat JNI_callFloatMethod (jobject object, jmethodID methodID,...)
jfloat JNI_callFloatMethodV (jobject object, jmethodID methodID, va_list args)
jint JNI_callIntMethod (jobject object, jmethodID methodID,...)
jint JNI_callIntMethodV (jobject object, jmethodID methodID, va_list args)
jint JNI_callIntMethodLocked (jobject object, jmethodID methodID,...)
jint JNI_callIntMethodLockedV (jobject object, jmethodID methodID, va_list args)
jlong JNI_callLongMethod (jobject object, jmethodID methodID,...)
jlong JNI_callLongMethodV (jobject object, jmethodID methodID, va_list args)
jlong JNI_callLongMethodLocked (jobject object, jmethodID methodID,...)
jlong JNI_callLongMethodLockedV (jobject object, jmethodID methodID, va_list args)
jshort JNI_callShortMethod (jobject object, jmethodID methodID,...)
jshort JNI_callShortMethodV (jobject object, jmethodID methodID, va_list args)
jobject JNI_callObjectMethod (jobject object, jmethodID methodID,...)
jobject JNI_callObjectMethodV (jobject object, jmethodID methodID, va_list args)
jobject JNI_callObjectMethodLocked (jobject object, jmethodID methodID,...)
jobject JNI_callObjectMethodLockedV (jobject object, jmethodID methodID, va_list args)
jboolean JNI_callStaticBooleanMethod (jclass clazz, jmethodID methodID,...)
jboolean JNI_callStaticBooleanMethodA (jclass clazz, jmethodID methodID, jvalue *args)
jboolean JNI_callStaticBooleanMethodV (jclass clazz, jmethodID methodID, va_list args)
jbyte JNI_callStaticByteMethod (jclass clazz, jmethodID methodID,...)
jbyte JNI_callStaticByteMethodA (jclass clazz, jmethodID methodID, jvalue *args)
jbyte JNI_callStaticByteMethodV (jclass clazz, jmethodID methodID, va_list args)
jshort JNI_callStaticShortMethod (jclass clazz, jmethodID methodID,...)
jshort JNI_callStaticShortMethodV (jclass clazz, jmethodID methodID, va_list args)
jchar JNI_callStaticCharMethod (jclass clazz, jmethodID methodID,...)
jchar JNI_callStaticCharMethodV (jclass clazz, jmethodID methodID, va_list args)
jdouble JNI_callStaticDoubleMethod (jclass clazz, jmethodID methodID,...)
jdouble JNI_callStaticDoubleMethodA (jclass clazz, jmethodID methodID, jvalue *args)
jdouble JNI_callStaticDoubleMethodV (jclass clazz, jmethodID methodID, va_list args)
jfloat JNI_callStaticFloatMethod (jclass clazz, jmethodID methodID,...)
jfloat JNI_callStaticFloatMethodA (jclass clazz, jmethodID methodID, jvalue *args)
jfloat JNI_callStaticFloatMethodV (jclass clazz, jmethodID methodID, va_list args)
jint JNI_callStaticIntMethod (jclass clazz, jmethodID methodID,...)
jint JNI_callStaticIntMethodA (jclass clazz, jmethodID methodID, jvalue *args)
jint JNI_callStaticIntMethodV (jclass clazz, jmethodID methodID, va_list args)
jlong JNI_callStaticLongMethod (jclass clazz, jmethodID methodID,...)
jlong JNI_callStaticLongMethodA (jclass clazz, jmethodID methodID, jvalue *args)
jlong JNI_callStaticLongMethodV (jclass clazz, jmethodID methodID, va_list args)
jobject JNI_callStaticObjectMethod (jclass clazz, jmethodID methodID,...)
jobject JNI_callStaticObjectMethodA (jclass clazz, jmethodID methodID, jvalue *args)
jobject JNI_callStaticObjectMethodV (jclass clazz, jmethodID methodID, va_list args)
jobject JNI_callStaticObjectMethodLocked (jclass clazz, jmethodID methodID,...)
jobject JNI_callStaticObjectMethodLockedV (jclass clazz, jmethodID methodID, va_list args)
jshort JNI_callStaticShortMethodA (jclass clazz, jmethodID methodID, jvalue *args)
void JNI_callStaticVoidMethod (jclass clazz, jmethodID methodID,...)
void JNI_callStaticVoidMethodA (jclass clazz, jmethodID methodID, jvalue *args)
void JNI_callStaticVoidMethodV (jclass clazz, jmethodID methodID, va_list args)
void JNI_callStaticVoidMethodLocked (jclass clazz, jmethodID methodID,...)
void JNI_callStaticVoidMethodLockedV (jclass clazz, jmethodID methodID, va_list args)
void JNI_callVoidMethod (jobject object, jmethodID methodID,...)
void JNI_callVoidMethodV (jobject object, jmethodID methodID, va_list args)
void JNI_callVoidMethodLocked (jobject object, jmethodID methodID,...)
void JNI_callVoidMethodLockedV (jobject object, jmethodID methodID, va_list args)
jint JNI_createVM (JavaVM **javaVM, JavaVMInitArgs *vmArgs)
void JNI_deleteGlobalRef (jobject object)
void JNI_deleteLocalRef (jobject object)
void JNI_deleteWeakGlobalRef (jweak object)
jint JNI_destroyVM (JavaVM *vm)
jboolean JNI_exceptionCheck (void)
void JNI_exceptionClear (void)
void JNI_exceptionDescribe (void)
jthrowable JNI_exceptionOccurred (void)
jclass JNI_findClass (const char *className)
jsize JNI_getArrayLength (jarray array)
jbyte * JNI_getByteArrayElements (jbyteArray array, jboolean *isCopy)
void JNI_getByteArrayRegion (jbyteArray array, jsize start, jsize len, jbyte *buf)
jboolean * JNI_getBooleanArrayElements (jbooleanArray array, jboolean *isCopy)
void JNI_getBooleanArrayRegion (jbooleanArray array, jsize start, jsize len, jboolean *buf)
jdouble * JNI_getDoubleArrayElements (jdoubleArray array, jboolean *isCopy)
void JNI_getDoubleArrayRegion (jdoubleArray array, jsize start, jsize len, jdouble *buf)
jfieldID JNI_getFieldID (jclass clazz, const char *name, const char *sig)
jfieldID JNI_getFieldIDOrNull (jclass clazz, const char *name, const char *sig)
jfloat * JNI_getFloatArrayElements (jfloatArray array, jboolean *isCopy)
void JNI_getFloatArrayRegion (jfloatArray array, jsize start, jsize len, jfloat *buf)
jint * JNI_getIntArrayElements (jintArray array, jboolean *isCopy)
void JNI_getIntArrayRegion (jintArray array, jsize start, jsize len, jint *buf)
jint JNI_getIntField (jobject object, jfieldID field)
jlong * JNI_getLongArrayElements (jlongArray array, jboolean *isCopy)
void JNI_getLongArrayRegion (jlongArray array, jsize start, jsize len, jlong *buf)
jlong JNI_getLongField (jobject object, jfieldID field)
jmethodID JNI_getMethodID (jclass clazz, const char *name, const char *sig)
jobject JNI_getObjectArrayElement (jobjectArray array, jsize index)
jclass JNI_getObjectClass (jobject obj)
jshort * JNI_getShortArrayElements (jshortArray array, jboolean *isCopy)
void JNI_getShortArrayRegion (jshortArray array, jsize start, jsize len, jshort *buf)
jfieldID JNI_getStaticFieldID (jclass clazz, const char *name, const char *sig)
jmethodID JNI_getStaticMethodID (jclass clazz, const char *name, const char *sig)
jmethodID JNI_getStaticMethodIDOrNull (jclass clazz, const char *name, const char *sig)
jboolean JNI_getStaticBooleanField (jclass clazz, jfieldID field)
jint JNI_getStaticIntField (jclass clazz, jfieldID field)
jobject JNI_getStaticObjectField (jclass clazz, jfieldID field)
const char * JNI_getStringUTFChars (jstring string, jboolean *isCopy)
jboolean JNI_hasNullArrayElement (jobjectArray array)
jboolean JNI_isCallingJava (void)
jboolean JNI_isInstanceOf (jobject obj, jclass clazz)
jboolean JNI_isSameObject (jobject obj1, jobject obj2)
jbyteArray JNI_newByteArray (jsize length)
jbooleanArray JNI_newBooleanArray (jsize length)
jobjectArray JNI_newObjectArray (jsize length, jclass elementClass, jobject initialElement)
jobject JNI_newDirectByteBuffer (void *address, jlong capacity)
jdoubleArray JNI_newDoubleArray (jsize length)
jfloatArray JNI_newFloatArray (jsize length)
jobject JNI_newGlobalRef (jobject object)
jintArray JNI_newIntArray (jsize length)
jobject JNI_newLocalRef (jobject object)
jlongArray JNI_newLongArray (jsize length)
jshortArray JNI_newShortArray (jsize length)
jstring JNI_newStringUTF (const char *bytes)
jint JNI_pushLocalFrame (jint capacity)
jobject JNI_popLocalFrame (jobject resultObj)
jweak JNI_newWeakGlobalRef (jobject object)
jobject JNI_newObject (jclass clazz, jmethodID ctor,...)
jobject JNI_newObjectV (jclass clazz, jmethodID ctor, va_list args)
jobject JNI_newObjectLocked (jclass clazz, jmethodID ctor,...)
jobject JNI_newObjectLockedV (jclass clazz, jmethodID ctor, va_list args)
void JNI_releaseByteArrayElements (jbyteArray array, jbyte *elems, jint mode)
void JNI_releaseBooleanArrayElements (jbooleanArray array, jboolean *elems, jint mode)
void JNI_releaseDoubleArrayElements (jdoubleArray array, jdouble *elems, jint mode)
void JNI_releaseFloatArrayElements (jfloatArray array, jfloat *elems, jint mode)
void JNI_releaseIntArrayElements (jintArray array, jint *elems, jint mode)
void JNI_releaseLongArrayElements (jlongArray array, jlong *elems, jint mode)
void JNI_releaseShortArrayElements (jshortArray array, jshort *elems, jint mode)
void JNI_releaseStringUTFChars (jstring string, const char *utf)
jint JNI_registerNatives (jclass clazz, const JNINativeMethod *methods, jint nMethods)
void JNI_setByteArrayRegion (jbyteArray array, jsize start, jsize len, jbyte *buf)
void JNI_setBooleanArrayRegion (jbooleanArray array, jsize start, jsize len, jboolean *buf)
void JNI_setDoubleArrayRegion (jdoubleArray array, jsize start, jsize len, jdouble *buf)
void JNI_setFloatArrayRegion (jfloatArray array, jsize start, jsize len, jfloat *buf)
JNIEnv * JNI_setEnv (JNIEnv *env)
void JNI_setIntArrayRegion (jintArray array, jsize start, jsize len, jint *buf)
void JNI_setLongArrayRegion (jlongArray array, jsize start, jsize len, jlong *buf)
void JNI_setIntField (jobject object, jfieldID field, jint value)
void JNI_setLongField (jobject object, jfieldID field, jlong value)
void JNI_setObjectArrayElement (jobjectArray array, jsize index, jobject value)
void JNI_setShortArrayRegion (jshortArray array, jsize start, jsize len, jshort *buf)
void JNI_setThreadLock (jobject lockObject)
jint JNI_throw (jthrowable obj)
static void _updaterCommon (JNIEnv *env, jobject thread, jobject loader)
static void _heavyUpdater (jobject loader)
static void _lightUpdater (jobject loader)
static void _noopUpdater (jobject loader)
Variables
JNIEnv * jniEnv
void void *void * mainThreadId
static JNIEnv * primordialJNIEnv
static jobject s_threadLock
static bool s_refuseOtherThreads = false
static bool s_doMonitorOps = true
static jclass s_Thread_class
static jmethodID s_Thread_currentThread
static jfieldID s_Thread_contextLoader
static jobject s_threadObject
JNI_ContextLoaderUpdater * JNI_loaderUpdater
JNI_ContextLoaderRestorer * JNI_loaderRestorer
static JNI_ContextLoaderUpdater _noopUpdater
static JNI_ContextLoaderRestorer _noopRestorer
static JNI_ContextLoaderUpdater _lightUpdater
static JNI_ContextLoaderRestorer _lightRestorer
static JNI_ContextLoaderUpdater _heavyUpdater
static JNI_ContextLoaderRestorer _heavyRestorer
Macro Definition Documentation
BEGIN_CALL
#define BEGIN_CALL
Value:
    BEGIN_JAVA \
    if(s_doMonitorOps && ((*env)->MonitorExit(env, s_threadLock) < 0)) \
        elog(ERROR, "Java exit monitor failure");
Definition at line 132 of file JNICalls.c.
{
    StringInfoData buf;
    int sqlState = ERRCODE_INTERNAL_ERROR;
    JNIEnv* saveEnv = jniEnv;
    jclass exhClass = (*env)->GetObjectClass(env, exh);
    jstring jtmp =
        (jstring)(*env)->CallObjectMethod(env, exhClass, Class_getName);
    /* ExceptionOccurred check is found below ... */
    initStringInfo(&buf);
    jniEnv = env; /* Used by the String operations */
    if ( 0 == (*env)->ExceptionOccurred(env) ) /* ... here */
        String_appendJavaString(&buf, jtmp);
    else
    {
        (*env)->ExceptionClear(env);
        appendStringInfoString(&buf, "<unknown Java class>");
    }
    (*env)->DeleteLocalRef(env, exhClass);
    (*env)->DeleteLocalRef(env, jtmp);
    jtmp = (jstring)(*env)->CallObjectMethod(env, exh, Throwable_getMessage);
    if ( 0 != (*env)->ExceptionOccurred(env) )
    {
        (*env)->ExceptionClear(env);
        jtmp = 0;
    }
    if(jtmp != 0)
    {
        appendStringInfoString(&buf, ": ");
        String_appendJavaString(&buf, jtmp);
        (*env)->DeleteLocalRef(env, jtmp);
    }
    if((*env)->IsInstanceOf(env, exh, SQLException_class))
    {
        jtmp = (*env)->CallObjectMethod(env, exh, SQLException_getSQLState);
        if ( 0 != (*env)->ExceptionOccurred(env) )
        {
            (*env)->ExceptionClear(env);
            jtmp = 0;
        }
        if(jtmp != 0)
        {
            char* s = String_createNTS(jtmp);
            (*env)->DeleteLocalRef(env, jtmp);
            if(strlen(s) >= 5)
                sqlState = MAKE_SQLSTATE(s[0], s[1], s[2], s[3], s[4]);
            pfree(s);
        }
    }
    jniEnv = saveEnv;
    ereport(logLevel, (errcode(sqlState), errmsg("%s", buf.data)));
}
static void printStacktrace(JNIEnv* env, jobject exh)
{
#ifndef _MSC_VER
    if(DEBUG1 >= log_min_messages || DEBUG1 >= client_min_messages)
#else
    /* This is gross, but only happens as often as an exception escapes Java
     * code to be rethrown. There is some renewed interest on pgsql-hackers to
     * find a good answer for the MSVC PGDLLIMPORT nonsense, and all of this
     * handling of exceptions and logging could stand some rework anyway.
     */
    if ( 0 == strncmp("debug", PG_GETCONFIGOPTION("log_min_messages"), 5)
        || 0 == strncmp("debug", PG_GETCONFIGOPTION("client_min_messages"), 5) )
#endif
    {
        int currLevel = Backend_setJavaLogLevel(DEBUG1);
        (*env)->CallVoidMethod(env, exh, Throwable_printStackTrace);
        (*env)->ExceptionOccurred(env); /* sop for JNI exception-check check */
        Backend_setJavaLogLevel(currLevel);
    }
}
static void endCall(JNIEnv* env)
{
    jobject exh = (*env)->ExceptionOccurred(env);
    if(exh != 0)
        (*env)->ExceptionClear(env);
    if(s_doMonitorOps && ((*env)->MonitorEnter(env, s_threadLock) < 0))
        elog(ERROR, "Java enter monitor failure");
    jniEnv = env;
    if(exh != 0)
    {
        printStacktrace(env, exh);
        if((*env)->IsInstanceOf(env, exh, ServerException_class))
        {
            /* Rethrow the server error.
             */
            jobject jed = (*env)->CallObjectMethod(env, exh, ServerException_getErrorData);
            if ( 0 != (*env)->ExceptionOccurred(env) )
            {
                (*env)->ExceptionClear(env);
                jed = 0;
            }
            if(jed != 0)
                ReThrowError(pljava_ErrorData_getErrorData(jed));
        }
        /* There's no return from this call.
         */
        elogExceptionMessage(env, exh, ERROR);
    }
}
static void endCallMonitorHeld(JNIEnv* env)
{
    jobject exh = (*env)->ExceptionOccurred(env);
    if(exh != 0)
        (*env)->ExceptionClear(env);
    jniEnv = env;
    if(exh != 0)
    {
        printStacktrace(env, exh);
        if((*env)->IsInstanceOf(env, exh, ServerException_class))
        {
            /* Rethrow the server error.
             */
            jobject jed = (*env)->CallObjectMethod(env, exh, ServerException_getErrorData);
            if ( 0 != (*env)->ExceptionOccurred(env) )
            {
                (*env)->ExceptionClear(env);
                jed = 0;
            }
            if(jed != 0)
                ReThrowError(pljava_ErrorData_getErrorData(jed));
        }
        /* There's no return from this call.
         */
        elogExceptionMessage(env, exh, ERROR);
    }
}
bool beginNativeNoErrCheck(JNIEnv* env)
{
    if ( s_refuseOtherThreads  &&  env != primordialJNIEnv )
    {
        env = JNI_setEnv(env);
        Exception_throw(ERRCODE_INTERNAL_ERROR,
            "Attempt by non-initial thread to enter PostgreSQL from Java");
        JNI_setEnv(env);
        return false;
    }
    if((env = JNI_setEnv(env)) != 0)
    {
        /* The backend is *not* awaiting the return of a call to the JVM
         * so there's no way the JVM can be allowed to call out at this
         * point.
         */
        Exception_throw(ERRCODE_INTERNAL_ERROR,
            "An attempt was made to call a PostgreSQL backend function while main thread was not in the JVM");
        JNI_setEnv(env);
        return false;
    }
    return true;
}
bool beginNative(JNIEnv* env)
{
    if (!currentInvocation)
    {
        env = JNI_setEnv(env);
        Exception_throw(ERRCODE_INTERNAL_ERROR, "An attempt was made to call a PostgreSQL backend function in a transaction callback.  At the end of a transaction you may not access the database any longer.");
        JNI_setEnv(env);
        return false;
    }
    if(currentInvocation->errorOccurred)
    {
        /* An elog with level higher than ERROR was issued. The transaction
         * state is unknown. There's no way the JVM is allowed to enter the
         * backend at this point.
         */
        env = JNI_setEnv(env);
        Exception_throw(ERRCODE_INTERNAL_ERROR,
            "An attempt was made to call a PostgreSQL backend function after an elog(ERROR) had been issued");
        JNI_setEnv(env);
        return false;
    }
    return beginNativeNoErrCheck(env);
}
jboolean JNI_callBooleanMethod(jobject object, jmethodID methodID, ...)
{
    jboolean result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callBooleanMethodV(object, methodID, args);
    va_end(args);
    return result;
}
jboolean JNI_callBooleanMethodV(jobject object, jmethodID methodID, va_list args)
{
    jboolean result;
    BEGIN_CALL
    result = (*env)->CallBooleanMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
jbyte JNI_callByteMethod(jobject object, jmethodID methodID, ...)
{
    jbyte result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callByteMethodV(object, methodID, args);
    va_end(args);
    return result;
}
jbyte JNI_callByteMethodV(jobject object, jmethodID methodID, va_list args)
{
    jbyte result;
    BEGIN_CALL
    result = (*env)->CallByteMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
jdouble JNI_callDoubleMethod(jobject object, jmethodID methodID, ...)
{
    jdouble result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callDoubleMethodV(object, methodID, args);
    va_end(args);
    return result;
}
jdouble JNI_callDoubleMethodV(jobject object, jmethodID methodID, va_list args)
{
    jdouble result;
    BEGIN_CALL
    result = (*env)->CallDoubleMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
jfloat JNI_callFloatMethod(jobject object, jmethodID methodID, ...)
{
    jfloat result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callFloatMethodV(object, methodID, args);
    va_end(args);
    return result;
}
jfloat JNI_callFloatMethodV(jobject object, jmethodID methodID, va_list args)
{
    jfloat result;
    BEGIN_CALL
    result = (*env)->CallFloatMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
jint JNI_callIntMethod(jobject object, jmethodID methodID, ...)
{
    jint result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callIntMethodV(object, methodID, args);
    va_end(args);
    return result;
}
jint JNI_callIntMethodV(jobject object, jmethodID methodID, va_list args)
{
    jint result;
    BEGIN_CALL
    result = (*env)->CallIntMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
jint JNI_callIntMethodLocked(jobject object, jmethodID methodID, ...)
{
    jint result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callIntMethodLockedV(object, methodID, args);
    va_end(args);
    return result;
}
jint JNI_callIntMethodLockedV(jobject object, jmethodID methodID, va_list args)
{
    jint result;
    BEGIN_CALL_MONITOR_HELD
    result = (*env)->CallIntMethodV(env, object, methodID, args);
    END_CALL_MONITOR_HELD
    return result;
}
jlong JNI_callLongMethod(jobject object, jmethodID methodID, ...)
{
    jlong result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callLongMethodV(object, methodID, args);
    va_end(args);
    return result;
}
jlong JNI_callLongMethodV(jobject object, jmethodID methodID, va_list args)
{
    jlong result;
    BEGIN_CALL
    result = (*env)->CallLongMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
jlong JNI_callLongMethodLocked(jobject object, jmethodID methodID, ...)
{
    jlong result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callLongMethodLockedV(object, methodID, args);
    va_end(args);
    return result;
}
jlong JNI_callLongMethodLockedV(jobject object, jmethodID methodID, va_list args)
{
    jlong result;
    BEGIN_CALL_MONITOR_HELD
    result = (*env)->CallLongMethodV(env, object, methodID, args);
    END_CALL_MONITOR_HELD
    return result;
}
jshort JNI_callShortMethod(jobject object, jmethodID methodID, ...)
{
    jshort result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callShortMethodV(object, methodID, args);
    va_end(args);
    return result;
}
jshort JNI_callShortMethodV(jobject object, jmethodID methodID, va_list args)
{
    jshort result;
    BEGIN_CALL
    result = (*env)->CallShortMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
jobject JNI_callObjectMethod(jobject object, jmethodID methodID, ...)
{
    jobject result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callObjectMethodV(object, methodID, args);
    va_end(args);
    return result;
}
jobject JNI_callObjectMethodV(jobject object, jmethodID methodID, va_list args)
{
    jobject result;
    BEGIN_CALL
    result = (*env)->CallObjectMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
jobject JNI_callObjectMethodLocked(jobject object, jmethodID methodID, ...)
{
    jobject result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callObjectMethodLockedV(object, methodID, args);
    va_end(args);
    return result;
}
jobject JNI_callObjectMethodLockedV(jobject object, jmethodID methodID, va_list args)
{
    jobject result;
    BEGIN_CALL_MONITOR_HELD
    result = (*env)->CallObjectMethodV(env, object, methodID, args);
    END_CALL_MONITOR_HELD
    return result;
}
jboolean JNI_callStaticBooleanMethod(jclass clazz, jmethodID methodID, ...)
{
    jboolean result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticBooleanMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
jboolean JNI_callStaticBooleanMethodA(jclass clazz, jmethodID methodID, jvalue* args)
{
    jboolean result;
    BEGIN_CALL
    result = (*env)->CallStaticBooleanMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
jboolean JNI_callStaticBooleanMethodV(jclass clazz, jmethodID methodID, va_list args)
{
    jboolean result;
    BEGIN_CALL
    result = (*env)->CallStaticBooleanMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
jbyte JNI_callStaticByteMethod(jclass clazz, jmethodID methodID, ...)
{
    jbyte result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticByteMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
jbyte JNI_callStaticByteMethodA(jclass clazz, jmethodID methodID, jvalue* args)
{
    jbyte result;
    BEGIN_CALL
    result = (*env)->CallStaticByteMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
jbyte JNI_callStaticByteMethodV(jclass clazz, jmethodID methodID, va_list args)
{
    jbyte result;
    BEGIN_CALL
    result = (*env)->CallStaticByteMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
jshort JNI_callStaticShortMethod(jclass clazz, jmethodID methodID, ...)
{
    jshort result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticShortMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
jshort JNI_callStaticShortMethodV(jclass clazz, jmethodID methodID, va_list args)
{
    jshort result;
    BEGIN_CALL
    result = (*env)->CallStaticShortMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
jchar JNI_callStaticCharMethod(jclass clazz, jmethodID methodID, ...)
{
    jchar result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticCharMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
jchar JNI_callStaticCharMethodV(jclass clazz, jmethodID methodID, va_list args)
{
    jchar result;
    BEGIN_CALL
    result = (*env)->CallStaticCharMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
jdouble JNI_callStaticDoubleMethod(jclass clazz, jmethodID methodID, ...)
{
    jdouble result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticDoubleMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
jdouble JNI_callStaticDoubleMethodA(jclass clazz, jmethodID methodID, jvalue* args)
{
    jdouble result;
    BEGIN_CALL
    result = (*env)->CallStaticDoubleMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
jdouble JNI_callStaticDoubleMethodV(jclass clazz, jmethodID methodID, va_list args)
{
    jdouble result;
    BEGIN_CALL
    result = (*env)->CallStaticDoubleMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
jfloat JNI_callStaticFloatMethod(jclass clazz, jmethodID methodID, ...)
{
    jfloat result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticFloatMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
jfloat JNI_callStaticFloatMethodA(jclass clazz, jmethodID methodID, jvalue* args)
{
    jfloat result;
    BEGIN_CALL
    result = (*env)->CallStaticFloatMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
jfloat JNI_callStaticFloatMethodV(jclass clazz, jmethodID methodID, va_list args)
{
    jfloat result;
    BEGIN_CALL
    result = (*env)->CallStaticFloatMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
jint JNI_callStaticIntMethod(jclass clazz, jmethodID methodID, ...)
{
    jint result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticIntMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
jint JNI_callStaticIntMethodA(jclass clazz, jmethodID methodID, jvalue* args)
{
    jint result;
    BEGIN_CALL
    result = (*env)->CallStaticIntMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
jint JNI_callStaticIntMethodV(jclass clazz, jmethodID methodID, va_list args)
{
    jint result;
    BEGIN_CALL
    result = (*env)->CallStaticIntMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
jlong JNI_callStaticLongMethod(jclass clazz, jmethodID methodID, ...)
{
    jlong result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticLongMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
jlong JNI_callStaticLongMethodA(jclass clazz, jmethodID methodID, jvalue* args)
{
    jlong result;
    BEGIN_CALL
    result = (*env)->CallStaticLongMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
jlong JNI_callStaticLongMethodV(jclass clazz, jmethodID methodID, va_list args)
{
    jlong result;
    BEGIN_CALL
    result = (*env)->CallStaticLongMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
jobject JNI_callStaticObjectMethod(jclass clazz, jmethodID methodID, ...)
{
    jobject result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticObjectMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
jobject JNI_callStaticObjectMethodA(jclass clazz, jmethodID methodID, jvalue* args)
{
    jobject result;
    BEGIN_CALL
    result = (*env)->CallStaticObjectMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
jobject JNI_callStaticObjectMethodV(jclass clazz, jmethodID methodID, va_list args)
{
    jobject result;
    BEGIN_CALL
    result = (*env)->CallStaticObjectMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
jobject JNI_callStaticObjectMethodLocked(jclass clazz, jmethodID methodID, ...)
{
    jobject result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticObjectMethodLockedV(clazz, methodID, args);
    va_end(args);
    return result;
}
jobject JNI_callStaticObjectMethodLockedV(jclass clazz, jmethodID methodID, va_list args)
{
    jobject result;
    BEGIN_CALL_MONITOR_HELD
    result = (*env)->CallStaticObjectMethodV(env, clazz, methodID, args);
    END_CALL_MONITOR_HELD
    return result;
}
jshort JNI_callStaticShortMethodA(jclass clazz, jmethodID methodID, jvalue* args)
{
    jshort result;
    BEGIN_CALL
    result = (*env)->CallStaticShortMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
void JNI_callStaticVoidMethod(jclass clazz, jmethodID methodID, ...)
{
    va_list args;
    va_start(args, methodID);
    JNI_callStaticVoidMethodV(clazz, methodID, args);
    va_end(args);
}
void JNI_callStaticVoidMethodA(jclass clazz, jmethodID methodID, jvalue* args)
{
    BEGIN_CALL
    (*env)->CallStaticVoidMethodA(env, clazz, methodID, args);
    END_CALL
}
void JNI_callStaticVoidMethodV(jclass clazz, jmethodID methodID, va_list args)
{
    BEGIN_CALL
    (*env)->CallStaticVoidMethodV(env, clazz, methodID, args);
    END_CALL
}
void JNI_callStaticVoidMethodLocked(jclass clazz, jmethodID methodID, ...)
{
    va_list args;
    va_start(args, methodID);
    JNI_callStaticVoidMethodLockedV(clazz, methodID, args);
    va_end(args);
}
void JNI_callStaticVoidMethodLockedV(jclass clazz, jmethodID methodID, va_list args)
{
    BEGIN_CALL_MONITOR_HELD
    (*env)->CallStaticVoidMethodV(env, clazz, methodID, args);
    END_CALL_MONITOR_HELD
}
void JNI_callVoidMethod(jobject object, jmethodID methodID, ...)
{
    va_list args;
    va_start(args, methodID);
    JNI_callVoidMethodV(object, methodID, args);
    va_end(args);
}
void JNI_callVoidMethodV(jobject object, jmethodID methodID, va_list args)
{
    BEGIN_CALL
    (*env)->CallVoidMethodV(env, object, methodID, args);
    END_CALL
}
void JNI_callVoidMethodLocked(jobject object, jmethodID methodID, ...)
{
    va_list args;
    va_start(args, methodID);
    JNI_callVoidMethodLockedV(object, methodID, args);
    va_end(args);
}
void JNI_callVoidMethodLockedV(jobject object, jmethodID methodID, va_list args)
{
    BEGIN_CALL_MONITOR_HELD
    (*env)->CallVoidMethodV(env, object, methodID, args);
    END_CALL_MONITOR_HELD
}
jint JNI_createVM(JavaVM** javaVM, JavaVMInitArgs* vmArgs)
{
    JNIEnv* env = 0;
    jint jstat = pljava_createvm(javaVM, (void **)&env, vmArgs);
    if(jstat == JNI_OK)
    {
        jniEnv = env;
        primordialJNIEnv = env;
        mainThreadId = env;
    }
    return jstat;
}
void JNI_deleteGlobalRef(jobject object)
{
    BEGIN_JAVA
    (*env)->DeleteGlobalRef(env, object);
    END_JAVA
}
void JNI_deleteLocalRef(jobject object)
{
    BEGIN_JAVA
    (*env)->DeleteLocalRef(env, object);
    END_JAVA
}
void JNI_deleteWeakGlobalRef(jweak object)
{
    BEGIN_JAVA
    (*env)->DeleteWeakGlobalRef(env, object);
    END_JAVA
}
jint JNI_destroyVM(JavaVM *vm)
{
    jint result;
    BEGIN_JAVA
    result = (*vm)->DestroyJavaVM(vm);
    END_JAVA
    jniEnv = 0;
    s_threadLock = 0;
    return result;
}
jboolean JNI_exceptionCheck(void)
{
    jboolean result;
    BEGIN_JAVA
    result = (*env)->ExceptionCheck(env);
    END_JAVA
    return result;
}
void JNI_exceptionClear(void)
{
    BEGIN_JAVA
    (*env)->ExceptionClear(env);
    END_JAVA
}
void JNI_exceptionDescribe(void)
{
    /* The ExceptionDescribe will print on stderr. Not a good idea
     * since the exception itself might have been caused by an unwriteable
     * stdout/stderr (happens when running as a windows service
     *
     * (*env)->ExceptionDescribe(env);
     */
    jthrowable exh;
    BEGIN_JAVA
    exh = (*env)->ExceptionOccurred(env);
    if(exh != 0)
    {
        (*env)->ExceptionClear(env);
        printStacktrace(env, exh);
        elogExceptionMessage(env, exh, WARNING);
    }
    END_JAVA
}
jthrowable JNI_exceptionOccurred(void)
{
    jthrowable result;
    BEGIN_JAVA
    result = (*env)->ExceptionOccurred(env);
    END_JAVA
    return result;
}
jclass JNI_findClass(const char* className)
{
    jclass result;
    BEGIN_JAVA
    result = (*env)->FindClass(env, className);
    END_JAVA
    return result;
}
jsize JNI_getArrayLength(jarray array)
{
    jsize result;
    BEGIN_JAVA
    result = (*env)->GetArrayLength(env, array);
    END_JAVA
    return result;
}
jbyte* JNI_getByteArrayElements(jbyteArray array, jboolean* isCopy)
{
    jbyte* result;
    BEGIN_JAVA
    result = (*env)->GetByteArrayElements(env, array, isCopy);
    END_JAVA
    return result;
}
void JNI_getByteArrayRegion(jbyteArray array, jsize start, jsize len, jbyte* buf)
{
    BEGIN_JAVA
    (*env)->GetByteArrayRegion(env, array, start, len, buf);
    END_JAVA
}
jboolean* JNI_getBooleanArrayElements(jbooleanArray array, jboolean* isCopy)
{
    jboolean* result;
    BEGIN_JAVA
    result = (*env)->GetBooleanArrayElements(env, array, isCopy);
    END_JAVA
    return result;
}
void JNI_getBooleanArrayRegion(jbooleanArray array, jsize start, jsize len, jboolean* buf)
{
    BEGIN_JAVA
    (*env)->GetBooleanArrayRegion(env, array, start, len, buf);
    END_JAVA
}
jdouble* JNI_getDoubleArrayElements(jdoubleArray array, jboolean* isCopy)
{
    jdouble* result;
    BEGIN_JAVA
    result = (*env)->GetDoubleArrayElements(env, array, isCopy);
    END_JAVA
    return result;
}
void JNI_getDoubleArrayRegion(jdoubleArray array, jsize start, jsize len, jdouble* buf)
{
    BEGIN_JAVA
    (*env)->GetDoubleArrayRegion(env, array, start, len, buf);
    END_JAVA
}
jfieldID JNI_getFieldID(jclass clazz, const char* name, const char* sig)
{
    jfieldID result;
    BEGIN_JAVA
    result = (*env)->GetFieldID(env, clazz, name, sig);
    END_JAVA
    return result;
}
jfieldID JNI_getFieldIDOrNull(jclass clazz, const char* name, const char* sig)
{
    jfieldID result;
    jobject exh;
    BEGIN_CALL
    result = (*env)->GetFieldID(env, clazz, name, sig);
    if(result == 0) {
        exh = (*env)->ExceptionOccurred(env);
        if ( 0 != exh )
        {
            /*
             * Ignore a NoSuchFieldError, but not any other exception.
             * This operation order (first clear the pending exception, then
             * do the IsInstanceOf check, then Throw again if not the expected
             * class) avoids a benign -Xcheck:JNI warning about calling
             * IsInstanceOf while an exception is pending.
             */
            (*env)->ExceptionClear(env);
            if ( ! (*env)->IsInstanceOf(env, exh, NoSuchFieldError_class) )
                (*env)->Throw(env, exh);
            (*env)->DeleteLocalRef(env, exh);
        }
    }
    END_CALL
    return result;
}
jfloat* JNI_getFloatArrayElements(jfloatArray array, jboolean* isCopy)
{
    jfloat* result;
    BEGIN_JAVA
    result = (*env)->GetFloatArrayElements(env, array, isCopy);
    END_JAVA
    return result;
}
void JNI_getFloatArrayRegion(jfloatArray array, jsize start, jsize len, jfloat* buf)
{
    BEGIN_JAVA
    (*env)->GetFloatArrayRegion(env, array, start, len, buf);
    END_JAVA
}
jint* JNI_getIntArrayElements(jintArray array, jboolean* isCopy)
{
    jint* result;
    BEGIN_JAVA
    result = (*env)->GetIntArrayElements(env, array, isCopy);
    END_JAVA
    return result;
}
void JNI_getIntArrayRegion(jintArray array, jsize start, jsize len, jint* buf)
{
    BEGIN_JAVA
    (*env)->GetIntArrayRegion(env, array, start, len, buf);
    END_JAVA
}
jint JNI_getIntField(jobject object, jfieldID field)
{
    jint result;
    BEGIN_JAVA
    result = (*env)->GetIntField(env, object, field);
    END_JAVA
    return result;
}
jlong* JNI_getLongArrayElements(jlongArray array, jboolean* isCopy)
{
    jlong* result;
    BEGIN_JAVA
    result = (*env)->GetLongArrayElements(env, array, isCopy);
    END_JAVA
    return result;
}
void JNI_getLongArrayRegion(jlongArray array, jsize start, jsize len, jlong* buf)
{
    BEGIN_JAVA
    (*env)->GetLongArrayRegion(env, array, start, len, buf);
    END_JAVA
}
jlong JNI_getLongField(jobject object, jfieldID field)
{
    jlong result;
    BEGIN_JAVA
    result = (*env)->GetLongField(env, object, field);
    END_JAVA
    return result;
}
jmethodID JNI_getMethodID(jclass clazz, const char* name, const char* sig)
{
    jmethodID result;
    BEGIN_JAVA
    result = (*env)->GetMethodID(env, clazz, name, sig);
    END_JAVA
    return result;
}
jobject JNI_getObjectArrayElement(jobjectArray array, jsize index)
{
    jobject result;
    BEGIN_JAVA
    result = (*env)->GetObjectArrayElement(env, array, index);
    END_JAVA
    return result;
}
jclass JNI_getObjectClass(jobject obj)
{
    jclass result;
    BEGIN_JAVA
    result = (*env)->GetObjectClass(env, obj);
    END_JAVA
    return result;
}
jshort* JNI_getShortArrayElements(jshortArray array, jboolean* isCopy)
{
    jshort* result;
    BEGIN_JAVA
    result = (*env)->GetShortArrayElements(env, array, isCopy);
    END_JAVA
    return result;
}
void JNI_getShortArrayRegion(jshortArray array, jsize start, jsize len, jshort* buf)
{
    BEGIN_JAVA
    (*env)->GetShortArrayRegion(env, array, start, len, buf);
    END_JAVA
}
jfieldID JNI_getStaticFieldID(jclass clazz, const char* name, const char* sig)
{
    jfieldID result;
    BEGIN_JAVA
    result = (*env)->GetStaticFieldID(env, clazz, name, sig);
    END_JAVA
    return result;
}
jmethodID JNI_getStaticMethodID(jclass clazz, const char* name, const char* sig)
{
    jmethodID result;
    BEGIN_CALL
    result = (*env)->GetStaticMethodID(env, clazz, name, sig);
    END_CALL
    return result;
}
jmethodID JNI_getStaticMethodIDOrNull(jclass clazz, const char* name, const char* sig)
{
    jmethodID result;
    jobject exh;
    BEGIN_CALL
    result = (*env)->GetStaticMethodID(env, clazz, name, sig);
    if(result == 0) {
        exh = (*env)->ExceptionOccurred(env);
        if ( 0 != exh )
        {
            /*
             * Ignore a NoSuchMethodError, but not any other exception.
             * This operation order (first clear the pending exception, then
             * do the IsInstanceOf check, then Throw again if not the expected
             * class) avoids a benign -Xcheck:JNI warning about calling
             * IsInstanceOf while an exception is pending.
             */
            (*env)->ExceptionClear(env);
            if ( ! (*env)->IsInstanceOf(env, exh, NoSuchMethodError_class) )
                (*env)->Throw(env, exh);
            (*env)->DeleteLocalRef(env, exh);
        }
    }
    END_CALL
    return result;
}
jboolean JNI_getStaticBooleanField(jclass clazz, jfieldID field)
{
    jboolean result;
    BEGIN_JAVA
    result = (*env)->GetStaticBooleanField(env, clazz, field);
    END_JAVA
    return result;
}
jint JNI_getStaticIntField(jclass clazz, jfieldID field)
{
    jint result;
    BEGIN_JAVA
    result = (*env)->GetStaticIntField(env, clazz, field);
    END_JAVA
    return result;
}
jobject JNI_getStaticObjectField(jclass clazz, jfieldID field)
{
    jobject result;
    BEGIN_JAVA
    result = (*env)->GetStaticObjectField(env, clazz, field);
    END_JAVA
    return result;
}
const char* JNI_getStringUTFChars(jstring string, jboolean* isCopy)
{
    const char* result;
    BEGIN_JAVA
    result = (*env)->GetStringUTFChars(env, string, isCopy);
    END_JAVA
    return result;
}
jboolean JNI_hasNullArrayElement(jobjectArray array)
{
    jsize idx;
    jboolean foundNull = JNI_FALSE;
    BEGIN_JAVA
    idx = (*env)->GetArrayLength(env, array);
    while(--idx >= 0)
    {
        if((*env)->GetObjectArrayElement(env, array, idx) != 0)
            continue;
        foundNull = JNI_TRUE;
        break;
    }
    END_JAVA
    return foundNull;
}
jboolean JNI_isCallingJava(void)
{
    return jniEnv == 0;
}
jboolean JNI_isInstanceOf(jobject obj, jclass clazz)
{
    jboolean result;
    BEGIN_JAVA
    result = (*env)->IsInstanceOf(env, obj, clazz);
    END_JAVA
    return result;
}
jboolean JNI_isSameObject(jobject obj1, jobject obj2)
{
    jboolean result;
    BEGIN_JAVA
    result = (*env)->IsSameObject(env, obj1, obj2);
    END_JAVA
    return result;
}
jbyteArray JNI_newByteArray(jsize length)
{
    jbyteArray result;
    BEGIN_JAVA
    result = (*env)->NewByteArray(env, length);
    END_JAVA
    return result;
}
jbooleanArray JNI_newBooleanArray(jsize length)
{
    jbooleanArray result;
    BEGIN_JAVA
    result = (*env)->NewBooleanArray(env, length);
    END_JAVA
    return result;
}
jobjectArray JNI_newObjectArray(jsize length, jclass elementClass, jobject initialElement)
{
    jobjectArray result;
    BEGIN_JAVA
    result = (*env)->NewObjectArray(env, length, elementClass, initialElement);
    END_JAVA
    return result;
}
jobject JNI_newDirectByteBuffer(void* address, jlong capacity)
{
    jobject result;
    BEGIN_JAVA
    result = (*env)->NewDirectByteBuffer(env, address, capacity);
    END_JAVA
    return result;
}
jdoubleArray JNI_newDoubleArray(jsize length)
{
    jdoubleArray result;
    BEGIN_JAVA
    result = (*env)->NewDoubleArray(env, length);
    END_JAVA
    return result;
}
jfloatArray JNI_newFloatArray(jsize length)
{
    jfloatArray result;
    BEGIN_JAVA
    result = (*env)->NewFloatArray(env, length);
    END_JAVA
    return result;
}
jobject JNI_newGlobalRef(jobject object)
{
    jobject result;
    BEGIN_JAVA
    result = (*env)->NewGlobalRef(env, object);
    END_JAVA
    return result;
}
jintArray JNI_newIntArray(jsize length)
{
    jintArray result;
    BEGIN_JAVA
    result = (*env)->NewIntArray(env, length);
    END_JAVA
    return result;
}
jobject JNI_newLocalRef(jobject object)
{
    jobject result;
    BEGIN_JAVA
    result = (*env)->NewLocalRef(env, object);
    END_JAVA
    return result;
}
jlongArray JNI_newLongArray(jsize length)
{
    jlongArray result;
    BEGIN_JAVA
    result = (*env)->NewLongArray(env, length);
    END_JAVA
    return result;
}
jshortArray JNI_newShortArray(jsize length)
{
    jshortArray result;
    BEGIN_JAVA
    result = (*env)->NewShortArray(env, length);
    END_JAVA
    return result;
}
jstring JNI_newStringUTF(const char* bytes)
{
    jstring result;
    BEGIN_JAVA
    result = (*env)->NewStringUTF(env, bytes);
    END_JAVA
    return result;
}
jint JNI_pushLocalFrame(jint capacity)
{
    jint result;
    BEGIN_JAVA
    result = (*env)->PushLocalFrame(env, capacity);
    END_JAVA
    return result;
}
jobject JNI_popLocalFrame(jobject resultObj)
{
    jobject result;
    BEGIN_JAVA
    result = (*env)->PopLocalFrame(env, resultObj);
    END_JAVA
    return result;
}
jweak JNI_newWeakGlobalRef(jobject object)
{
    jweak result;
    BEGIN_JAVA
    result = (*env)->NewWeakGlobalRef(env, object);
    END_JAVA
    return result;
}
jobject JNI_newObject(jclass clazz, jmethodID ctor, ...)
{
    jobject result;
    va_list args;
    va_start(args, ctor);
    result = JNI_newObjectV(clazz, ctor, args);
    va_end(args);
    return result;
}
jobject JNI_newObjectV(jclass clazz, jmethodID ctor, va_list args)
{
    jobject result;
    BEGIN_CALL
    result = (*env)->NewObjectV(env, clazz, ctor, args);
    END_CALL
    return result;
}
jobject JNI_newObjectLocked(jclass clazz, jmethodID ctor, ...)
{
    jobject result;
    va_list args;
    va_start(args, ctor);
    result = JNI_newObjectLockedV(clazz, ctor, args);
    va_end(args);
    return result;
}
jobject JNI_newObjectLockedV(jclass clazz, jmethodID ctor, va_list args)
{
    jobject result;
    BEGIN_CALL_MONITOR_HELD
    result = (*env)->NewObjectV(env, clazz, ctor, args);
    END_CALL_MONITOR_HELD
    return result;
}
void JNI_releaseByteArrayElements(jbyteArray array, jbyte* elems, jint mode)
{
    BEGIN_JAVA
    (*env)->ReleaseByteArrayElements(env, array, elems, mode);
    END_JAVA
}
void JNI_releaseBooleanArrayElements(jbooleanArray array, jboolean* elems, jint mode)
{
    BEGIN_JAVA
    (*env)->ReleaseBooleanArrayElements(env, array, elems, mode);
    END_JAVA
}
void JNI_releaseDoubleArrayElements(jdoubleArray array, jdouble* elems, jint mode)
{
    BEGIN_JAVA
    (*env)->ReleaseDoubleArrayElements(env, array, elems, mode);
    END_JAVA
}
void JNI_releaseFloatArrayElements(jfloatArray array, jfloat* elems, jint mode)
{
    BEGIN_JAVA
    (*env)->ReleaseFloatArrayElements(env, array, elems, mode);
    END_JAVA
}
void JNI_releaseIntArrayElements(jintArray array, jint* elems, jint mode)
{
    BEGIN_JAVA
    (*env)->ReleaseIntArrayElements(env, array, elems, mode);
    END_JAVA
}
void JNI_releaseLongArrayElements(jlongArray array, jlong* elems, jint mode)
{
    BEGIN_JAVA
    (*env)->ReleaseLongArrayElements(env, array, elems, mode);
    END_JAVA
}
void JNI_releaseShortArrayElements(jshortArray array, jshort* elems, jint mode)
{
    BEGIN_JAVA
    (*env)->ReleaseShortArrayElements(env, array, elems, mode);
    END_JAVA
}
void JNI_releaseStringUTFChars(jstring string, const char *utf)
{
    BEGIN_JAVA
    (*env)->ReleaseStringUTFChars(env, string, utf);
    END_JAVA
}
jint JNI_registerNatives(jclass clazz, const JNINativeMethod* methods, jint nMethods)
{
    jint result;
    BEGIN_JAVA
    result = (*env)->RegisterNatives(env, clazz, methods, nMethods);
    END_JAVA
    return result;
}
void JNI_setByteArrayRegion(jbyteArray array, jsize start, jsize len, jbyte* buf)
{
    BEGIN_JAVA
    (*env)->SetByteArrayRegion(env, array, start, len, buf);
    END_JAVA
}
void JNI_setBooleanArrayRegion(jbooleanArray array, jsize start, jsize len, jboolean* buf)
{
    BEGIN_JAVA
    (*env)->SetBooleanArrayRegion(env, array, start, len, buf);
    END_JAVA
}
void JNI_setDoubleArrayRegion(jdoubleArray array, jsize start, jsize len, jdouble* buf)
{
    BEGIN_JAVA
    (*env)->SetDoubleArrayRegion(env, array, start, len, buf);
    END_JAVA
}
void JNI_setFloatArrayRegion(jfloatArray array, jsize start, jsize len, jfloat* buf)
{
    BEGIN_JAVA
    (*env)->SetFloatArrayRegion(env, array, start, len, buf);
    END_JAVA
}
JNIEnv* JNI_setEnv(JNIEnv* env)
{
    JNIEnv* oldEnv = jniEnv;
    jniEnv = env;
    return oldEnv;
}
void JNI_setIntArrayRegion(jintArray array, jsize start, jsize len, jint* buf)
{
    BEGIN_JAVA
    (*env)->SetIntArrayRegion(env, array, start, len, buf);
    END_JAVA
}
void JNI_setLongArrayRegion(jlongArray array, jsize start, jsize len, jlong* buf)
{
    BEGIN_JAVA
    (*env)->SetLongArrayRegion(env, array, start, len, buf);
    END_JAVA
}
void JNI_setIntField(jobject object, jfieldID field, jint value)
{
    BEGIN_JAVA
    (*env)->SetIntField(env, object, field, value);
    END_JAVA
}
void JNI_setLongField(jobject object, jfieldID field, jlong value)
{
    BEGIN_JAVA
    (*env)->SetLongField(env, object, field, value);
    END_JAVA
}
void JNI_setObjectArrayElement(jobjectArray array, jsize index, jobject value)
{
    BEGIN_JAVA
    (*env)->SetObjectArrayElement(env, array, index, value);
    END_JAVA
}
void JNI_setShortArrayRegion(jshortArray array, jsize start, jsize len, jshort* buf)
{
    BEGIN_JAVA
    (*env)->SetShortArrayRegion(env, array, start, len, buf);
    END_JAVA
}
void JNI_setThreadLock(jobject lockObject)
{
    BEGIN_JAVA
    s_threadLock = (*env)->NewGlobalRef(env, lockObject);
    if(NULL != s_threadLock  &&  (*env)->MonitorEnter(env, s_threadLock) < 0)
        elog(ERROR, "Java enter monitor failure (initial)");
    END_JAVA
}
jint JNI_throw(jthrowable obj)
{
    jint result;
    BEGIN_JAVA
    result = (*env)->Throw(env, obj);
    END_JAVA
    return result;
}
/*
 * Implementations of the context class loader updater and restorer.
 * The loader reference passed in is not to be deleted. If saved anywhere,
 * a new global ref is to be taken, and later deleted when restored.
 */
static inline void _updaterCommon(JNIEnv *env, jobject thread, jobject loader)
{
    jobject old = (*env)->GetObjectField(env, thread, s_Thread_contextLoader);
    /*
     * If it is not already the loader we want, change it, and set
     * currentInvocation->savedLoader to restore it later. If this is
     * a top-level invocation, we don't care what it gets restored to, so lie,
     * and save loader there instead of old. If there are many consecutive
     * top-level calls with the same context loader, that will save work later.
     *
     * If it is already the loader we want, again we check for a top-level call,
     * and can leave currentInvocation->savedLoader completely unset in that
     * case, so the restore call will be skipped completely. If not a top-level
     * call, though, see that it gets restored to what the caller might expect,
     * even if it somehow got changed.
     */
    if ( ! (*env)->IsSameObject(env, old, loader) )
    {
        (*env)->SetObjectField(env, thread, s_Thread_contextLoader, loader);
        currentInvocation->savedLoader = (*env)->NewGlobalRef(env,
            ( NULL == currentInvocation->previous ) ? loader : old);
    }
    else if ( NULL != currentInvocation->previous )
        currentInvocation->savedLoader = (*env)->NewGlobalRef(env, old);
    (*env)->DeleteLocalRef(env, old);
}
static void _heavyUpdater(jobject loader)
{
    jobject thread;
    jobject exh;
    BEGIN_JAVA
    thread =
        (*env)->CallStaticObjectMethod(env,
            s_Thread_class, s_Thread_currentThread); /* should never fail */
    exh = (*env)->ExceptionOccurred(env); /* but mollify -Xcheck:jni anyway */
    if(exh != 0)
    {
        (*env)->ExceptionClear(env);
        elogExceptionMessage(env, exh, ERROR);
    }
    _updaterCommon(env, thread, loader);
    (*env)->DeleteLocalRef(env, thread);
    END_JAVA
}
void _heavyRestorer()
{
    jobject thread;
    jobject value;
    jobject exh;
    BEGIN_JAVA
    thread =
        (*env)->CallStaticObjectMethod(env,
            s_Thread_class, s_Thread_currentThread); /* should never fail */
    exh = (*env)->ExceptionOccurred(env); /* but mollify -Xcheck:jni anyway */
    if(exh != 0)
    {
        (*env)->ExceptionClear(env);
        elogExceptionMessage(env, exh, ERROR);
    }
    value = currentInvocation->savedLoader;
    (*env)->SetObjectField(env, thread, s_Thread_contextLoader, value);
    (*env)->DeleteGlobalRef(env, value);
    (*env)->DeleteLocalRef(env, thread);
    END_JAVA
}
static void _lightUpdater(jobject loader)
{
    BEGIN_JAVA
    _updaterCommon(env, s_threadObject, loader);
    END_JAVA
}
void _lightRestorer()
{
    jobject value;
    BEGIN_JAVA
    value = currentInvocation->savedLoader;
    (*env)->SetObjectField(env, s_threadObject, s_Thread_contextLoader, value);
    (*env)->DeleteGlobalRef(env, value);
    END_JAVA
}
static void _noopUpdater(jobject loader)
{
}
void _noopRestorer()
{
}
BEGIN_CALL_MONITOR_HELD
#define BEGIN_CALL_MONITOR_HELD BEGIN_JAVA
Definition at line 139 of file JNICalls.c.
BEGIN_JAVA
#define BEGIN_JAVA { JNIEnv* env = jniEnv; jniEnv = 0;
Definition at line 129 of file JNICalls.c.
END_CALL
#define END_CALL endCall(env); }
Definition at line 137 of file JNICalls.c.
END_CALL_MONITOR_HELD
#define END_CALL_MONITOR_HELD endCallMonitorHeld(env); }
Definition at line 142 of file JNICalls.c.
END_JAVA
#define END_JAVA jniEnv = env; }
Definition at line 130 of file JNICalls.c.
Function Documentation
_heavyUpdater()
static void _heavyUpdater (jobject loader) static
Definition at line 1670 of file JNICalls.c.
{
    jobject thread;
    jobject exh;
    BEGIN_JAVA
    thread =
        (*env)->CallStaticObjectMethod(env,
            s_Thread_class, s_Thread_currentThread); /* should never fail */
    exh = (*env)->ExceptionOccurred(env); /* but mollify -Xcheck:jni anyway */
    if(exh != 0)
    {
        (*env)->ExceptionClear(env);
        elogExceptionMessage(env, exh, ERROR);
    }
    _updaterCommon(env, thread, loader);
    (*env)->DeleteLocalRef(env, thread);
    END_JAVA
}
References _updaterCommon(), BEGIN_JAVA, elogExceptionMessage(), END_JAVA, s_Thread_class, and s_Thread_currentThread.
_lightUpdater()
static void _lightUpdater (jobject loader) static
Definition at line 1723 of file JNICalls.c.
{
    BEGIN_JAVA
    _updaterCommon(env, s_threadObject, loader);
    END_JAVA
}
References _updaterCommon(), BEGIN_JAVA, END_JAVA, and s_threadObject.
_noopUpdater()
static void _noopUpdater (jobject loader) static
Definition at line 1746 of file JNICalls.c.
{
}
_updaterCommon()
static void _updaterCommon (JNIEnv * env, jobject thread, jobject loader) inline static
Definition at line 1639 of file JNICalls.c.
{
    jobject old = (*env)->GetObjectField(env, thread, s_Thread_contextLoader);
    /*
     * If it is not already the loader we want, change it, and set
     * currentInvocation->savedLoader to restore it later. If this is
     * a top-level invocation, we don't care what it gets restored to, so lie,
     * and save loader there instead of old. If there are many consecutive
     * top-level calls with the same context loader, that will save work later.
     *
     * If it is already the loader we want, again we check for a top-level call,
     * and can leave currentInvocation->savedLoader completely unset in that
     * case, so the restore call will be skipped completely. If not a top-level
     * call, though, see that it gets restored to what the caller might expect,
     * even if it somehow got changed.
     */
    if ( ! (*env)->IsSameObject(env, old, loader) )
    {
        (*env)->SetObjectField(env, thread, s_Thread_contextLoader, loader);
        currentInvocation->savedLoader = (*env)->NewGlobalRef(env,
            ( NULL == currentInvocation->previous ) ? loader : old);
    }
    else if ( NULL != currentInvocation->previous )
        currentInvocation->savedLoader = (*env)->NewGlobalRef(env, old);
    (*env)->DeleteLocalRef(env, old);
}
References currentInvocation, and s_Thread_contextLoader.
Referenced by _heavyUpdater(), and _lightUpdater().
beginNative()
bool beginNative (JNIEnv * env)
Definition at line 315 of file JNICalls.c.
{
    if (!currentInvocation)
    {
        env = JNI_setEnv(env);
        Exception_throw(ERRCODE_INTERNAL_ERROR, "An attempt was made to call a PostgreSQL backend function in a transaction callback.  At the end of a transaction you may not access the database any longer.");
        JNI_setEnv(env);
        return false;
    }
    if(currentInvocation->errorOccurred)
    {
        /* An elog with level higher than ERROR was issued. The transaction
         * state is unknown. There's no way the JVM is allowed to enter the
         * backend at this point.
         */
        env = JNI_setEnv(env);
        Exception_throw(ERRCODE_INTERNAL_ERROR,
            "An attempt was made to call a PostgreSQL backend function after an elog(ERROR) had been issued");
        JNI_setEnv(env);
        return false;
    }
    return beginNativeNoErrCheck(env);
}
References beginNativeNoErrCheck(), currentInvocation, Exception_throw(), and JNI_setEnv().
beginNativeNoErrCheck()
bool beginNativeNoErrCheck (JNIEnv * env)
Definition at line 290 of file JNICalls.c.
{
    if ( s_refuseOtherThreads  &&  env != primordialJNIEnv )
    {
        env = JNI_setEnv(env);
        Exception_throw(ERRCODE_INTERNAL_ERROR,
            "Attempt by non-initial thread to enter PostgreSQL from Java");
        JNI_setEnv(env);
        return false;
    }
    if((env = JNI_setEnv(env)) != 0)
    {
        /* The backend is *not* awaiting the return of a call to the JVM
         * so there's no way the JVM can be allowed to call out at this
         * point.
         */
        Exception_throw(ERRCODE_INTERNAL_ERROR,
            "An attempt was made to call a PostgreSQL backend function while main thread was not in the JVM");
        JNI_setEnv(env);
        return false;
    }
    return true;
}
References Exception_throw(), JNI_setEnv(), primordialJNIEnv, and s_refuseOtherThreads.
Referenced by beginNative().
elogExceptionMessage()
static void elogExceptionMessage (JNIEnv * env, jthrowable exh, int logLevel) static
Definition at line 144 of file JNICalls.c.
{
    StringInfoData buf;
    int sqlState = ERRCODE_INTERNAL_ERROR;
    JNIEnv* saveEnv = jniEnv;
    jclass exhClass = (*env)->GetObjectClass(env, exh);
    jstring jtmp =
        (jstring)(*env)->CallObjectMethod(env, exhClass, Class_getName);
    /* ExceptionOccurred check is found below ... */
    initStringInfo(&buf);
    jniEnv = env; /* Used by the String operations */
    if ( 0 == (*env)->ExceptionOccurred(env) ) /* ... here */
        String_appendJavaString(&buf, jtmp);
    else
    {
        (*env)->ExceptionClear(env);
        appendStringInfoString(&buf, "<unknown Java class>");
    }
    (*env)->DeleteLocalRef(env, exhClass);
    (*env)->DeleteLocalRef(env, jtmp);
    jtmp = (jstring)(*env)->CallObjectMethod(env, exh, Throwable_getMessage);
    if ( 0 != (*env)->ExceptionOccurred(env) )
    {
        (*env)->ExceptionClear(env);
        jtmp = 0;
    }
    if(jtmp != 0)
    {
        appendStringInfoString(&buf, ": ");
        String_appendJavaString(&buf, jtmp);
        (*env)->DeleteLocalRef(env, jtmp);
    }
    if((*env)->IsInstanceOf(env, exh, SQLException_class))
    {
        jtmp = (*env)->CallObjectMethod(env, exh, SQLException_getSQLState);
        if ( 0 != (*env)->ExceptionOccurred(env) )
        {
            (*env)->ExceptionClear(env);
            jtmp = 0;
        }
        if(jtmp != 0)
        {
            char* s = String_createNTS(jtmp);
            (*env)->DeleteLocalRef(env, jtmp);
            if(strlen(s) >= 5)
                sqlState = MAKE_SQLSTATE(s[0], s[1], s[2], s[3], s[4]);
            pfree(s);
        }
    }
    jniEnv = saveEnv;
    ereport(logLevel, (errcode(sqlState), errmsg("%s", buf.data)));
}
References Class_getName, jniEnv, SQLException_class, SQLException_getSQLState, String_appendJavaString(), String_createNTS(), and Throwable_getMessage.
Referenced by _heavyUpdater(), endCall(), endCallMonitorHeld(), and JNI_exceptionDescribe().
endCall()
static void endCall (JNIEnv * env) static
Definition at line 227 of file JNICalls.c.
{
    jobject exh = (*env)->ExceptionOccurred(env);
    if(exh != 0)
        (*env)->ExceptionClear(env);
    if(s_doMonitorOps && ((*env)->MonitorEnter(env, s_threadLock) < 0))
        elog(ERROR, "Java enter monitor failure");
    jniEnv = env;
    if(exh != 0)
    {
        printStacktrace(env, exh);
        if((*env)->IsInstanceOf(env, exh, ServerException_class))
        {
            /* Rethrow the server error.
             */
            jobject jed = (*env)->CallObjectMethod(env, exh, ServerException_getErrorData);
            if ( 0 != (*env)->ExceptionOccurred(env) )
            {
                (*env)->ExceptionClear(env);
                jed = 0;
            }
            if(jed != 0)
                ReThrowError(pljava_ErrorData_getErrorData(jed));
        }
        /* There's no return from this call.
         */
        elogExceptionMessage(env, exh, ERROR);
    }
}
References elogExceptionMessage(), jniEnv, pljava_ErrorData_getErrorData(), printStacktrace(), s_doMonitorOps, s_threadLock, ServerException_class, and ServerException_getErrorData.
endCallMonitorHeld()
static void endCallMonitorHeld (JNIEnv * env) static
Definition at line 260 of file JNICalls.c.
{
    jobject exh = (*env)->ExceptionOccurred(env);
    if(exh != 0)
        (*env)->ExceptionClear(env);
    jniEnv = env;
    if(exh != 0)
    {
        printStacktrace(env, exh);
        if((*env)->IsInstanceOf(env, exh, ServerException_class))
        {
            /* Rethrow the server error.
             */
            jobject jed = (*env)->CallObjectMethod(env, exh, ServerException_getErrorData);
            if ( 0 != (*env)->ExceptionOccurred(env) )
            {
                (*env)->ExceptionClear(env);
                jed = 0;
            }
            if(jed != 0)
                ReThrowError(pljava_ErrorData_getErrorData(jed));
        }
        /* There's no return from this call.
         */
        elogExceptionMessage(env, exh, ERROR);
    }
}
References elogExceptionMessage(), jniEnv, pljava_ErrorData_getErrorData(), printStacktrace(), ServerException_class, and ServerException_getErrorData.
jint()
jint (JNICALL * pljava_createvm)
Referenced by _int_invoke(), _intArray_coerceDatum(), _intArray_coerceObject(), _LocalDateTime_coerceDatum(), _OffsetDateTime_coerceObject(), _OffsetTime_coerceObject(), AclId_create(), initializeJavaVM(), initsequencer(), Java_org_postgresql_pljava_internal_ErrorData__1getCursorPos(), Java_org_postgresql_pljava_internal_ErrorData__1getInternalPos(), Java_org_postgresql_pljava_internal_ErrorData__1getLineno(), Java_org_postgresql_pljava_internal_ErrorData__1getSavedErrno(), Java_org_postgresql_pljava_internal_ExecutionPlan__1execute(), Java_org_postgresql_pljava_internal_Function__1storeToNonUDT(), Java_org_postgresql_pljava_internal_PgSavepoint__1set(), Java_org_postgresql_pljava_internal_Relation__1modifyTuple(), Java_org_postgresql_pljava_internal_SPI__1exec(), Java_org_postgresql_pljava_internal_SPI__1getResult(), Java_org_postgresql_pljava_internal_TriggerData__1getArguments(), Java_org_postgresql_pljava_internal_TupleDesc__1formTuple(), Java_org_postgresql_pljava_internal_TupleDesc__1getColumnIndex(), JNI_callIntMethod(), JNI_callIntMethodLocked(), JNI_callIntMethodLockedV(), JNI_callIntMethodV(), JNI_callStaticIntMethod(), JNI_callStaticIntMethodA(), JNI_callStaticIntMethodV(), JNI_createVM(), JNI_destroyVM(), JNI_getIntArrayElements(), JNI_getIntField(), JNI_getStaticIntField(), JNI_pushLocalFrame(), JNI_registerNatives(), JNI_throw(), Oid_create(), PgObject_registerNatives2(), PgSavepoint_initialize(), pljava_PgSavepoint_forId(), pljava_TupleDesc_internalCreate(), subXactCB(), Timestamp_coerceDatumTZ_dd(), Timestamp_coerceDatumTZ_id(), Timestamp_coerceObjectTZ_dd(), Timestamp_coerceObjectTZ_id(), TupleTable_create(), and xactCB().
JNI_callBooleanMethod()
jboolean JNI_callBooleanMethod (jobject object, jmethodID methodID, ...)
Definition at line 340 of file JNICalls.c.
{
    jboolean result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callBooleanMethodV(object, methodID, args);
    va_end(args);
    return result;
}
References JNI_callBooleanMethodV().
Referenced by _Boolean_coerceObject().
JNI_callBooleanMethodV()
jboolean JNI_callBooleanMethodV (jobject object, jmethodID methodID, va_list args)
Definition at line 350 of file JNICalls.c.
{
    jboolean result;
    BEGIN_CALL
    result = (*env)->CallBooleanMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callBooleanMethod().
JNI_callByteMethod()
jbyte JNI_callByteMethod (jobject object, jmethodID methodID, ...)
Definition at line 359 of file JNICalls.c.
{
    jbyte result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callByteMethodV(object, methodID, args);
    va_end(args);
    return result;
}
References JNI_callByteMethodV().
Referenced by _Byte_coerceObject().
JNI_callByteMethodV()
jbyte JNI_callByteMethodV (jobject object, jmethodID methodID, va_list args)
Definition at line 369 of file JNICalls.c.
{
    jbyte result;
    BEGIN_CALL
    result = (*env)->CallByteMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callByteMethod().
JNI_callDoubleMethod()
jdouble JNI_callDoubleMethod (jobject object, jmethodID methodID, ...)
Definition at line 378 of file JNICalls.c.
{
    jdouble result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callDoubleMethodV(object, methodID, args);
    va_end(args);
    return result;
}
References JNI_callDoubleMethodV().
Referenced by _Double_coerceObject().
JNI_callDoubleMethodV()
jdouble JNI_callDoubleMethodV (jobject object, jmethodID methodID, va_list args)
Definition at line 388 of file JNICalls.c.
{
    jdouble result;
    BEGIN_CALL
    result = (*env)->CallDoubleMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callDoubleMethod().
JNI_callFloatMethod()
jfloat JNI_callFloatMethod (jobject object, jmethodID methodID, ...)
Definition at line 397 of file JNICalls.c.
{
    jfloat result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callFloatMethodV(object, methodID, args);
    va_end(args);
    return result;
}
References JNI_callFloatMethodV().
Referenced by _Float_coerceObject(), and String_initialize_codec().
JNI_callFloatMethodV()
jfloat JNI_callFloatMethodV (jobject object, jmethodID methodID, va_list args)
Definition at line 407 of file JNICalls.c.
{
    jfloat result;
    BEGIN_CALL
    result = (*env)->CallFloatMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callFloatMethod().
JNI_callIntMethod()
jint JNI_callIntMethod (jobject object, jmethodID methodID, ...)
Definition at line 416 of file JNICalls.c.
{
    jint result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callIntMethodV(object, methodID, args);
    va_end(args);
    return result;
}
References jint(), and JNI_callIntMethodV().
Referenced by _Integer_coerceObject(), _OffsetDateTime_coerceObject(), _OffsetTime_coerceObject(), Timestamp_coerceObjectTZ_dd(), and Timestamp_coerceObjectTZ_id().
JNI_callIntMethodLocked()
jint JNI_callIntMethodLocked (jobject object, jmethodID methodID, ...)
Definition at line 435 of file JNICalls.c.
{
    jint result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callIntMethodLockedV(object, methodID, args);
    va_end(args);
    return result;
}
References jint(), and JNI_callIntMethodLockedV().
Referenced by appendCharBuffer().
JNI_callIntMethodLockedV()
jint JNI_callIntMethodLockedV (jobject object, jmethodID methodID, va_list args)
Definition at line 445 of file JNICalls.c.
{
    jint result;
    BEGIN_CALL_MONITOR_HELD
    result = (*env)->CallIntMethodV(env, object, methodID, args);
    END_CALL_MONITOR_HELD
    return result;
}
References BEGIN_CALL_MONITOR_HELD, END_CALL_MONITOR_HELD, and jint().
Referenced by JNI_callIntMethodLocked().
JNI_callIntMethodV()
jint JNI_callIntMethodV (jobject object, jmethodID methodID, va_list args)
Definition at line 426 of file JNICalls.c.
{
    jint result;
    BEGIN_CALL
    result = (*env)->CallIntMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, END_CALL, and jint().
Referenced by JNI_callIntMethod().
JNI_callLongMethod()
jlong JNI_callLongMethod (jobject object, jmethodID methodID, ...)
Definition at line 454 of file JNICalls.c.
{
    jlong result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callLongMethodV(object, methodID, args);
    va_end(args);
    return result;
}
References JNI_callLongMethodV().
Referenced by _byte_array_coerceObject(), _Date_coerceObject(), _getTupleAndClear(), _LocalDate_coerceObject(), _LocalTime_coerceObject(), _Long_coerceObject(), _OffsetDateTime_coerceObject(), pljava_ErrorData_getErrorData(), pljava_TriggerData_getTriggerReturnTuple(), SQLOutputToTuple_getTuple(), Time_getMillisecsToday(), Timestamp_coerceObjectTZ_dd(), and Timestamp_coerceObjectTZ_id().
JNI_callLongMethodLocked()
jlong JNI_callLongMethodLocked (jobject object, jmethodID methodID, ...)
Definition at line 473 of file JNICalls.c.
{
    jlong result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callLongMethodLockedV(object, methodID, args);
    va_end(args);
    return result;
}
References JNI_callLongMethodLockedV().
Referenced by pljava_VarlenaWrapper_adopt().
JNI_callLongMethodLockedV()
jlong JNI_callLongMethodLockedV (jobject object, jmethodID methodID, va_list args)
Definition at line 483 of file JNICalls.c.
{
    jlong result;
    BEGIN_CALL_MONITOR_HELD
    result = (*env)->CallLongMethodV(env, object, methodID, args);
    END_CALL_MONITOR_HELD
    return result;
}
References BEGIN_CALL_MONITOR_HELD, and END_CALL_MONITOR_HELD.
Referenced by JNI_callLongMethodLocked().
JNI_callLongMethodV()
jlong JNI_callLongMethodV (jobject object, jmethodID methodID, va_list args)
Definition at line 464 of file JNICalls.c.
{
    jlong result;
    BEGIN_CALL
    result = (*env)->CallLongMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callLongMethod().
JNI_callObjectMethod()
jobject JNI_callObjectMethod (jobject object, jmethodID methodID, ...)
Definition at line 511 of file JNICalls.c.
{
    jobject result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callObjectMethodV(object, methodID, args);
    va_end(args);
    return result;
}
References JNI_callObjectMethodV().
Referenced by _BigDecimal_coerceObject(), _LocalDateTime_coerceObject(), _OffsetTime_coerceObject(), _String_coerceObject(), checkTypeMappedUDT(), PgObject_getClassName(), String_initialize_codec(), Type_coerceDatumAs(), Type_coerceObjectBridged(), and UDT_registerUDT().
JNI_callObjectMethodLocked()
jobject JNI_callObjectMethodLocked (jobject object, jmethodID methodID, ...)
Definition at line 530 of file JNICalls.c.
{
    jobject result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callObjectMethodLockedV(object, methodID, args);
    va_end(args);
    return result;
}
References JNI_callObjectMethodLockedV().
Referenced by appendCharBuffer(), Java_org_postgresql_pljava_internal_Backend__1pokeJEP411(), Java_org_postgresql_pljava_jdbc_SQLOutputToChunk__1ensureCapacity(), SQLOutputToChunk_create(), String_createJavaString(), and String_createJavaStringFromNTS().
JNI_callObjectMethodLockedV()
jobject JNI_callObjectMethodLockedV (jobject object, jmethodID methodID, va_list args)
Definition at line 540 of file JNICalls.c.
{
    jobject result;
    BEGIN_CALL_MONITOR_HELD
    result = (*env)->CallObjectMethodV(env, object, methodID, args);
    END_CALL_MONITOR_HELD
    return result;
}
References BEGIN_CALL_MONITOR_HELD, and END_CALL_MONITOR_HELD.
Referenced by JNI_callObjectMethodLocked().
JNI_callObjectMethodV()
jobject JNI_callObjectMethodV (jobject object, jmethodID methodID, va_list args)
Definition at line 521 of file JNICalls.c.
{
    jobject result;
    BEGIN_CALL
    result = (*env)->CallObjectMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callObjectMethod().
JNI_callShortMethod()
jshort JNI_callShortMethod (jobject object, jmethodID methodID, ...)
Definition at line 492 of file JNICalls.c.
{
    jshort result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callShortMethodV(object, methodID, args);
    va_end(args);
    return result;
}
References JNI_callShortMethodV().
Referenced by _Short_coerceObject().
JNI_callShortMethodV()
jshort JNI_callShortMethodV (jobject object, jmethodID methodID, va_list args)
Definition at line 502 of file JNICalls.c.
{
    jshort result;
    BEGIN_CALL
    result = (*env)->CallShortMethodV(env, object, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callShortMethod().
JNI_callStaticBooleanMethod()
jboolean JNI_callStaticBooleanMethod (jclass clazz, jmethodID methodID, ...)
Definition at line 549 of file JNICalls.c.
{
    jboolean result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticBooleanMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
References JNI_callStaticBooleanMethodV().
JNI_callStaticBooleanMethodA()
jboolean JNI_callStaticBooleanMethodA (jclass clazz, jmethodID methodID, jvalue * args)
Definition at line 559 of file JNICalls.c.
{
    jboolean result;
    BEGIN_CALL
    result = (*env)->CallStaticBooleanMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
JNI_callStaticBooleanMethodV()
jboolean JNI_callStaticBooleanMethodV (jclass clazz, jmethodID methodID, va_list args)
Definition at line 568 of file JNICalls.c.
{
    jboolean result;
    BEGIN_CALL
    result = (*env)->CallStaticBooleanMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callStaticBooleanMethod().
JNI_callStaticByteMethod()
jbyte JNI_callStaticByteMethod (jclass clazz, jmethodID methodID, ...)
Definition at line 577 of file JNICalls.c.
{
    jbyte result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticByteMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
References JNI_callStaticByteMethodV().
JNI_callStaticByteMethodA()
jbyte JNI_callStaticByteMethodA (jclass clazz, jmethodID methodID, jvalue * args)
Definition at line 587 of file JNICalls.c.
{
    jbyte result;
    BEGIN_CALL
    result = (*env)->CallStaticByteMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
JNI_callStaticByteMethodV()
jbyte JNI_callStaticByteMethodV (jclass clazz, jmethodID methodID, va_list args)
Definition at line 596 of file JNICalls.c.
{
    jbyte result;
    BEGIN_CALL
    result = (*env)->CallStaticByteMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callStaticByteMethod().
JNI_callStaticCharMethod()
jchar JNI_callStaticCharMethod (jclass clazz, jmethodID methodID, ...)
Definition at line 624 of file JNICalls.c.
{
    jchar result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticCharMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
References JNI_callStaticCharMethodV().
JNI_callStaticCharMethodV()
jchar JNI_callStaticCharMethodV (jclass clazz, jmethodID methodID, va_list args)
Definition at line 634 of file JNICalls.c.
{
    jchar result;
    BEGIN_CALL
    result = (*env)->CallStaticCharMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callStaticCharMethod().
JNI_callStaticDoubleMethod()
jdouble JNI_callStaticDoubleMethod (jclass clazz, jmethodID methodID, ...)
Definition at line 643 of file JNICalls.c.
{
    jdouble result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticDoubleMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
References JNI_callStaticDoubleMethodV().
JNI_callStaticDoubleMethodA()
jdouble JNI_callStaticDoubleMethodA (jclass clazz, jmethodID methodID, jvalue * args)
Definition at line 653 of file JNICalls.c.
{
    jdouble result;
    BEGIN_CALL
    result = (*env)->CallStaticDoubleMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
JNI_callStaticDoubleMethodV()
jdouble JNI_callStaticDoubleMethodV (jclass clazz, jmethodID methodID, va_list args)
Definition at line 662 of file JNICalls.c.
{
    jdouble result;
    BEGIN_CALL
    result = (*env)->CallStaticDoubleMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callStaticDoubleMethod().
JNI_callStaticFloatMethod()
jfloat JNI_callStaticFloatMethod (jclass clazz, jmethodID methodID, ...)
Definition at line 671 of file JNICalls.c.
{
    jfloat result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticFloatMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
References JNI_callStaticFloatMethodV().
JNI_callStaticFloatMethodA()
jfloat JNI_callStaticFloatMethodA (jclass clazz, jmethodID methodID, jvalue * args)
Definition at line 681 of file JNICalls.c.
{
    jfloat result;
    BEGIN_CALL
    result = (*env)->CallStaticFloatMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
JNI_callStaticFloatMethodV()
jfloat JNI_callStaticFloatMethodV (jclass clazz, jmethodID methodID, va_list args)
Definition at line 690 of file JNICalls.c.
{
    jfloat result;
    BEGIN_CALL
    result = (*env)->CallStaticFloatMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callStaticFloatMethod().
JNI_callStaticIntMethod()
jint JNI_callStaticIntMethod (jclass clazz, jmethodID methodID, ...)
Definition at line 699 of file JNICalls.c.
{
    jint result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticIntMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
References jint(), and JNI_callStaticIntMethodV().
JNI_callStaticIntMethodA()
jint JNI_callStaticIntMethodA (jclass clazz, jmethodID methodID, jvalue * args)
Definition at line 709 of file JNICalls.c.
{
    jint result;
    BEGIN_CALL
    result = (*env)->CallStaticIntMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, END_CALL, and jint().
JNI_callStaticIntMethodV()
jint JNI_callStaticIntMethodV (jclass clazz, jmethodID methodID, va_list args)
Definition at line 718 of file JNICalls.c.
{
    jint result;
    BEGIN_CALL
    result = (*env)->CallStaticIntMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, END_CALL, and jint().
Referenced by JNI_callStaticIntMethod().
JNI_callStaticLongMethod()
jlong JNI_callStaticLongMethod (jclass clazz, jmethodID methodID, ...)
Definition at line 727 of file JNICalls.c.
{
    jlong result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticLongMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
References JNI_callStaticLongMethodV().
JNI_callStaticLongMethodA()
jlong JNI_callStaticLongMethodA (jclass clazz, jmethodID methodID, jvalue * args)
Definition at line 737 of file JNICalls.c.
{
    jlong result;
    BEGIN_CALL
    result = (*env)->CallStaticLongMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
JNI_callStaticLongMethodV()
jlong JNI_callStaticLongMethodV (jclass clazz, jmethodID methodID, va_list args)
Definition at line 746 of file JNICalls.c.
{
    jlong result;
    BEGIN_CALL
    result = (*env)->CallStaticLongMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callStaticLongMethod().
JNI_callStaticObjectMethod()
jobject JNI_callStaticObjectMethod (jclass clazz, jmethodID methodID, ...)
Definition at line 755 of file JNICalls.c.
{
    jobject result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticObjectMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
References JNI_callStaticObjectMethodV().
Referenced by _LocalDate_coerceDatum(), _LocalDateTime_coerceDatum(), _LocalTime_coerceDatum(), _OffsetDateTime_coerceDatum(), _OffsetTime_coerceDatum(), Function_checkTypeBaseUDT(), Function_create(), InstallHelper_hello(), obtainUDTHandle(), pljava_Function_booleanInvoke(), pljava_Function_byteInvoke(), pljava_Function_charInvoke(), pljava_Function_doubleInvoke(), pljava_Function_floatInvoke(), pljava_Function_intInvoke(), pljava_Function_longInvoke(), pljava_Function_refInvoke(), pljava_Function_shortInvoke(), pljava_Function_udtParseInvoke(), pljava_Function_udtReadInvoke(), pljava_Function_udtToStringInvoke(), pljava_Function_voidInvoke(), pljava_Function_vpcInvoke(), and pljava_JNI_threadInitialize().
JNI_callStaticObjectMethodA()
jobject JNI_callStaticObjectMethodA (jclass clazz, jmethodID methodID, jvalue * args)
Definition at line 765 of file JNICalls.c.
{
    jobject result;
    BEGIN_CALL
    result = (*env)->CallStaticObjectMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
JNI_callStaticObjectMethodLocked()
jobject JNI_callStaticObjectMethodLocked (jclass clazz, jmethodID methodID, ...)
Definition at line 783 of file JNICalls.c.
{
    jobject result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticObjectMethodLockedV(clazz, methodID, args);
    va_end(args);
    return result;
}
References JNI_callStaticObjectMethodLockedV().
Referenced by _SQLXML_coerceObject(), addTypeBridge(), pljava_PgSavepoint_forId(), String_appendJavaString(), String_createNTS(), String_createText(), and String_initialize_codec().
JNI_callStaticObjectMethodLockedV()
jobject JNI_callStaticObjectMethodLockedV (jclass clazz, jmethodID methodID, va_list args)
Definition at line 793 of file JNICalls.c.
{
    jobject result;
    BEGIN_CALL_MONITOR_HELD
    result = (*env)->CallStaticObjectMethodV(env, clazz, methodID, args);
    END_CALL_MONITOR_HELD
    return result;
}
References BEGIN_CALL_MONITOR_HELD, and END_CALL_MONITOR_HELD.
Referenced by JNI_callStaticObjectMethodLocked().
JNI_callStaticObjectMethodV()
jobject JNI_callStaticObjectMethodV (jclass clazz, jmethodID methodID, va_list args)
Definition at line 774 of file JNICalls.c.
{
    jobject result;
    BEGIN_CALL
    result = (*env)->CallStaticObjectMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callStaticObjectMethod().
JNI_callStaticShortMethod()
jshort JNI_callStaticShortMethod (jclass clazz, jmethodID methodID, ...)
Definition at line 605 of file JNICalls.c.
{
    jshort result;
    va_list args;
    va_start(args, methodID);
    result = JNI_callStaticShortMethodV(clazz, methodID, args);
    va_end(args);
    return result;
}
References JNI_callStaticShortMethodV().
JNI_callStaticShortMethodA()
jshort JNI_callStaticShortMethodA (jclass clazz, jmethodID methodID, jvalue * args)
Definition at line 802 of file JNICalls.c.
{
    jshort result;
    BEGIN_CALL
    result = (*env)->CallStaticShortMethodA(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
JNI_callStaticShortMethodV()
jshort JNI_callStaticShortMethodV (jclass clazz, jmethodID methodID, va_list args)
Definition at line 615 of file JNICalls.c.
{
    jshort result;
    BEGIN_CALL
    result = (*env)->CallStaticShortMethodV(env, clazz, methodID, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callStaticShortMethod().
JNI_callStaticVoidMethod()
void JNI_callStaticVoidMethod (jclass clazz, jmethodID methodID, ...)
Definition at line 811 of file JNICalls.c.
{
    va_list args;
    va_start(args, methodID);
    JNI_callStaticVoidMethodV(clazz, methodID, args);
    va_end(args);
}
References JNI_callStaticVoidMethodV().
Referenced by initJavaSession(), InstallHelper_groundwork(), Oid_initialize(), pljava_Function_popFrame(), pljava_Function_udtWriteInvoke(), subXactCB(), and xactCB().
JNI_callStaticVoidMethodA()
void JNI_callStaticVoidMethodA (jclass clazz, jmethodID methodID, jvalue * args)
Definition at line 819 of file JNICalls.c.
{
    BEGIN_CALL
    (*env)->CallStaticVoidMethodA(env, clazz, methodID, args);
    END_CALL
}
References BEGIN_CALL, and END_CALL.
JNI_callStaticVoidMethodLocked()
void JNI_callStaticVoidMethodLocked (jclass clazz, jmethodID methodID, ...)
Definition at line 833 of file JNICalls.c.
{
    va_list args;
    va_start(args, methodID);
    JNI_callStaticVoidMethodLockedV(clazz, methodID, args);
    va_end(args);
}
References JNI_callStaticVoidMethodLockedV().
Referenced by pljava_DualState_cleanEnqueuedInstances(), pljava_DualState_nativeRelease(), and reserveParameterFrame().
JNI_callStaticVoidMethodLockedV()
void JNI_callStaticVoidMethodLockedV (jclass clazz, jmethodID methodID, va_list args)
Definition at line 841 of file JNICalls.c.
{
    BEGIN_CALL_MONITOR_HELD
    (*env)->CallStaticVoidMethodV(env, clazz, methodID, args);
    END_CALL_MONITOR_HELD
}
References BEGIN_CALL_MONITOR_HELD, and END_CALL_MONITOR_HELD.
Referenced by JNI_callStaticVoidMethodLocked().
JNI_callStaticVoidMethodV()
void JNI_callStaticVoidMethodV (jclass clazz, jmethodID methodID, va_list args)
Definition at line 826 of file JNICalls.c.
{
    BEGIN_CALL
    (*env)->CallStaticVoidMethodV(env, clazz, methodID, args);
    END_CALL
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callStaticVoidMethod().
JNI_callVoidMethod()
void JNI_callVoidMethod (jobject object, jmethodID methodID, ...)
Definition at line 848 of file JNICalls.c.
{
    va_list args;
    va_start(args, methodID);
    JNI_callVoidMethodV(object, methodID, args);
    va_end(args);
}
References JNI_callVoidMethodV().
Referenced by _byte_array_coerceObject(), SQLInputFromChunk_close(), SQLOutputToChunk_close(), Timestamp_coerceDatumTZ_dd(), and Timestamp_coerceDatumTZ_id().
JNI_callVoidMethodLocked()
void JNI_callVoidMethodLocked (jobject object, jmethodID methodID, ...)
Definition at line 863 of file JNICalls.c.
{
    va_list args;
    va_start(args, methodID);
    JNI_callVoidMethodLockedV(object, methodID, args);
    va_end(args);
}
References JNI_callVoidMethodLockedV().
Referenced by appendCharBuffer(), and Invocation_popInvocation().
JNI_callVoidMethodLockedV()
void JNI_callVoidMethodLockedV (jobject object, jmethodID methodID, va_list args)
Definition at line 871 of file JNICalls.c.
{
    BEGIN_CALL_MONITOR_HELD
    (*env)->CallVoidMethodV(env, object, methodID, args);
    END_CALL_MONITOR_HELD
}
References BEGIN_CALL_MONITOR_HELD, and END_CALL_MONITOR_HELD.
Referenced by JNI_callVoidMethodLocked().
JNI_callVoidMethodV()
void JNI_callVoidMethodV (jobject object, jmethodID methodID, va_list args)
Definition at line 856 of file JNICalls.c.
{
    BEGIN_CALL
    (*env)->CallVoidMethodV(env, object, methodID, args);
    END_CALL
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_callVoidMethod().
JNI_createVM()
jint JNI_createVM (JavaVM ** javaVM, JavaVMInitArgs * vmArgs)
Definition at line 878 of file JNICalls.c.
{
    JNIEnv* env = 0;
    jint jstat = pljava_createvm(javaVM, (void **)&env, vmArgs);
    if(jstat == JNI_OK)
    {
        jniEnv = env;
        primordialJNIEnv = env;
        mainThreadId = env;
    }
    return jstat;
}
References jint(), jniEnv, mainThreadId, and primordialJNIEnv.
Referenced by initializeJavaVM().
JNI_deleteGlobalRef()
void JNI_deleteGlobalRef (jobject object)
Definition at line 891 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->DeleteGlobalRef(env, object);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _closeIteration(), _Function_finalize(), and Invocation_popInvocation().
JNI_deleteLocalRef()
void JNI_deleteLocalRef (jobject object)
Definition at line 898 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->DeleteLocalRef(env, object);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _Array_coerceDatum(), _Array_coerceObject(), _BigDecimal_coerceObject(), _byte_array_coerceObject(), _Composite_getSRFCollector(), _Composite_invoke(), _LocalDateTime_coerceObject(), _LocalDateTime_obtain(), _OffsetDateTime_coerceDatum(), _OffsetTime_coerceDatum(), _OffsetTime_coerceObject(), _SQLXML_coerceDatum(), _SQLXML_coerceDatum_synthetic(), _SQLXML_coerceObject(), _String_coerceObject(), _Type_invoke(), addTypeBridge(), appendCharBuffer(), checkTypeMappedUDT(), coerceObjects(), coerceScalarDatum(), coerceScalarObject(), coerceTupleDatum(), Exception_featureNotSupported(), Exception_throw(), Exception_throw_ERROR(), Exception_throwIllegalArgument(), Function_checkTypeBaseUDT(), Function_create(), Function_initialize(), initializeTypeBridges(), initJavaSession(), InstallHelper_groundwork(), InstallHelper_hello(), Invocation_initialize(), invokeTrigger(), Java_org_postgresql_pljava_internal_ExecutionPlan__1prepare(), Java_org_postgresql_pljava_internal_Function__1storeToNonUDT(), Java_org_postgresql_pljava_internal_TriggerData__1getArguments(), Java_org_postgresql_pljava_internal_TupleDesc__1formTuple(), obtainUDTHandle(), Oid_initialize(), PgObject_getClassName(), PgObject_registerNatives(), pljava_DualState_initialize(), pljava_SingleRowReader_create(), pljava_SingleRowReader_initialize(), pljava_SQLInputFromTuple_create(), pljava_SQLInputFromTuple_initialize(), pljava_SQLXMLImpl_initialize(), pljava_TriggerData_initialize(), pljava_Tuple_createArray(), pljava_VarlenaWrapper_initialize(), pljava_VarlenaWrapper_Input(), pljava_VarlenaWrapper_Output(), SQLOutputToTuple_create(), String_appendJavaString(), String_createJavaString(), String_createJavaStringFromNTS(), String_createNTS(), String_createText(), Type_coerceDatumAs(), Type_coerceObjectBridged(), Type_getJavaClass(), Type_invokeSRF(), UDT_input(), UDT_output(), and UDT_registerUDT().
JNI_deleteWeakGlobalRef()
void JNI_deleteWeakGlobalRef (jweak object)
Definition at line 905 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->DeleteWeakGlobalRef(env, object);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
JNI_destroyVM()
jint JNI_destroyVM (JavaVM * vm)
Definition at line 912 of file JNICalls.c.
{
    jint result;
    BEGIN_JAVA
    result = (*vm)->DestroyJavaVM(vm);
    END_JAVA
    jniEnv = 0;
    s_threadLock = 0;
    return result;
}
References BEGIN_JAVA, END_JAVA, jint(), jniEnv, and s_threadLock.
Referenced by _destroyJavaVM().
JNI_exceptionCheck()
jboolean JNI_exceptionCheck (void)
Definition at line 923 of file JNICalls.c.
{
    jboolean result;
    BEGIN_JAVA
    result = (*env)->ExceptionCheck(env);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _String_coerceObject(), initializeJavaVM(), initJavaSession(), invokeTrigger(), and PgObject_getJavaClass().
JNI_exceptionClear()
void JNI_exceptionClear (void)
Definition at line 932 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->ExceptionClear(env);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by initializeJavaVM(), initJavaSession(), Java_org_postgresql_pljava_internal_Backend__1pokeJEP411(), PgObject_getJavaClass(), PgObject_registerNatives2(), and PgObject_throwMemberError().
JNI_exceptionDescribe()
void JNI_exceptionDescribe (void)
Definition at line 939 of file JNICalls.c.
{
    /* The ExceptionDescribe will print on stderr. Not a good idea
     * since the exception itself might have been caused by an unwriteable
     * stdout/stderr (happens when running as a windows service
     *
     * (*env)->ExceptionDescribe(env);
     */
    jthrowable exh;
    BEGIN_JAVA
    exh = (*env)->ExceptionOccurred(env);
    if(exh != 0)
    {
        (*env)->ExceptionClear(env);
        printStacktrace(env, exh);
        elogExceptionMessage(env, exh, WARNING);
    }
    END_JAVA
}
References BEGIN_JAVA, elogExceptionMessage(), END_JAVA, and printStacktrace().
Referenced by initializeJavaVM(), initJavaSession(), PgObject_getJavaClass(), PgObject_registerNatives2(), and PgObject_throwMemberError().
JNI_exceptionOccurred()
jthrowable JNI_exceptionOccurred (void)
Definition at line 959 of file JNICalls.c.
{
    jthrowable result;
    BEGIN_JAVA
    result = (*env)->ExceptionOccurred(env);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
JNI_findClass()
jclass JNI_findClass (const char * className)
Definition at line 968 of file JNICalls.c.
{
    jclass result;
    BEGIN_JAVA
    result = (*env)->FindClass(env, className);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by Java_org_postgresql_pljava_internal_Backend__1pokeJEP411(), and PgObject_getJavaClass().
JNI_getArrayLength()
jsize JNI_getArrayLength (jarray array)
Definition at line 977 of file JNICalls.c.
{
    jsize result;
    BEGIN_JAVA
    result = (*env)->GetArrayLength(env, array);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _Array_coerceObject(), _booleanArray_coerceObject(), _byte_array_coerceObject(), _byteArray_coerceObject(), _doubleArray_coerceObject(), _floatArray_coerceObject(), _intArray_coerceObject(), _longArray_coerceObject(), _shortArray_coerceObject(), coerceObjects(), Java_org_postgresql_pljava_internal_ExecutionPlan__1prepare(), Java_org_postgresql_pljava_internal_Function__1reconcileTypes(), and Java_org_postgresql_pljava_internal_Relation__1modifyTuple().
JNI_getBooleanArrayElements()
jboolean * JNI_getBooleanArrayElements (jbooleanArray array, jboolean * isCopy)
Definition at line 1002 of file JNICalls.c.
{
    jboolean* result;
    BEGIN_JAVA
    result = (*env)->GetBooleanArrayElements(env, array, isCopy);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _booleanArray_coerceDatum().
JNI_getBooleanArrayRegion()
void JNI_getBooleanArrayRegion (jbooleanArray array, jsize start, jsize len, jboolean * buf)
Definition at line 1011 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->GetBooleanArrayRegion(env, array, start, len, buf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _booleanArray_coerceObject().
JNI_getByteArrayElements()
jbyte * JNI_getByteArrayElements (jbyteArray array, jboolean * isCopy)
Definition at line 986 of file JNICalls.c.
{
    jbyte* result;
    BEGIN_JAVA
    result = (*env)->GetByteArrayElements(env, array, isCopy);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _byteArray_coerceDatum().
JNI_getByteArrayRegion()
void JNI_getByteArrayRegion (jbyteArray array, jsize start, jsize len, jbyte * buf)
Definition at line 995 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->GetByteArrayRegion(env, array, start, len, buf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _byte_array_coerceObject(), and _byteArray_coerceObject().
JNI_getDoubleArrayElements()
jdouble * JNI_getDoubleArrayElements (jdoubleArray array, jboolean * isCopy)
Definition at line 1018 of file JNICalls.c.
{
    jdouble* result;
    BEGIN_JAVA
    result = (*env)->GetDoubleArrayElements(env, array, isCopy);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _doubleArray_coerceDatum().
JNI_getDoubleArrayRegion()
void JNI_getDoubleArrayRegion (jdoubleArray array, jsize start, jsize len, jdouble * buf)
Definition at line 1027 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->GetDoubleArrayRegion(env, array, start, len, buf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _doubleArray_coerceObject().
JNI_getFieldID()
jfieldID JNI_getFieldID (jclass clazz, const char * name, const char * sig)
Definition at line 1034 of file JNICalls.c.
{
    jfieldID result;
    BEGIN_JAVA
    result = (*env)->GetFieldID(env, clazz, name, sig);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by PgObject_getJavaField().
JNI_getFieldIDOrNull()
jfieldID JNI_getFieldIDOrNull (jclass clazz, const char * name, const char * sig)
Definition at line 1043 of file JNICalls.c.
{
    jfieldID result;
    jobject exh;
    BEGIN_CALL
    result = (*env)->GetFieldID(env, clazz, name, sig);
    if(result == 0) {
        exh = (*env)->ExceptionOccurred(env);
        if ( 0 != exh )
        {
            /*
             * Ignore a NoSuchFieldError, but not any other exception.
             * This operation order (first clear the pending exception, then
             * do the IsInstanceOf check, then Throw again if not the expected
             * class) avoids a benign -Xcheck:JNI warning about calling
             * IsInstanceOf while an exception is pending.
             */
            (*env)->ExceptionClear(env);
            if ( ! (*env)->IsInstanceOf(env, exh, NoSuchFieldError_class) )
                (*env)->Throw(env, exh);
            (*env)->DeleteLocalRef(env, exh);
        }
    }
    END_CALL
    return result;
}
References BEGIN_CALL, END_CALL, and NoSuchFieldError_class.
Referenced by pljava_JNI_threadInitialize().
JNI_getFloatArrayElements()
jfloat * JNI_getFloatArrayElements (jfloatArray array, jboolean * isCopy)
Definition at line 1070 of file JNICalls.c.
{
    jfloat* result;
    BEGIN_JAVA
    result = (*env)->GetFloatArrayElements(env, array, isCopy);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _floatArray_coerceDatum().
JNI_getFloatArrayRegion()
void JNI_getFloatArrayRegion (jfloatArray array, jsize start, jsize len, jfloat * buf)
Definition at line 1079 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->GetFloatArrayRegion(env, array, start, len, buf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _floatArray_coerceObject().
JNI_getIntArrayElements()
jint * JNI_getIntArrayElements (jintArray array, jboolean * isCopy)
Definition at line 1086 of file JNICalls.c.
{
    jint* result;
    BEGIN_JAVA
    result = (*env)->GetIntArrayElements(env, array, isCopy);
    END_JAVA
    return result;
}
References BEGIN_JAVA, END_JAVA, and jint().
Referenced by _intArray_coerceDatum(), Java_org_postgresql_pljava_internal_Function__1storeToNonUDT(), and Java_org_postgresql_pljava_internal_Relation__1modifyTuple().
JNI_getIntArrayRegion()
void JNI_getIntArrayRegion (jintArray array, jsize start, jsize len, jint * buf)
Definition at line 1095 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->GetIntArrayRegion(env, array, start, len, buf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _intArray_coerceObject().
JNI_getIntField()
jint JNI_getIntField (jobject object, jfieldID field)
Definition at line 1102 of file JNICalls.c.
{
    jint result;
    BEGIN_JAVA
    result = (*env)->GetIntField(env, object, field);
    END_JAVA
    return result;
}
References BEGIN_JAVA, END_JAVA, and jint().
Referenced by AclId_getAclId(), and Oid_getOid().
JNI_getLongArrayElements()
jlong * JNI_getLongArrayElements (jlongArray array, jboolean * isCopy)
Definition at line 1111 of file JNICalls.c.
{
    jlong* result;
    BEGIN_JAVA
    result = (*env)->GetLongArrayElements(env, array, isCopy);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _longArray_coerceDatum().
JNI_getLongArrayRegion()
void JNI_getLongArrayRegion (jlongArray array, jsize start, jsize len, jlong * buf)
Definition at line 1120 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->GetLongArrayRegion(env, array, start, len, buf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _longArray_coerceObject().
JNI_getLongField()
jlong JNI_getLongField (jobject object, jfieldID field)
Definition at line 1127 of file JNICalls.c.
{
    jlong result;
    BEGIN_JAVA
    result = (*env)->GetLongField(env, object, field);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
JNI_getMethodID()
jmethodID JNI_getMethodID (jclass clazz, const char * name, const char * sig)
Definition at line 1136 of file JNICalls.c.
{
    jmethodID result;
    BEGIN_JAVA
    result = (*env)->GetMethodID(env, clazz, name, sig);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by Java_org_postgresql_pljava_internal_Backend__1pokeJEP411(), and PgObject_getJavaMethod().
JNI_getObjectArrayElement()
jobject JNI_getObjectArrayElement (jobjectArray array, jsize index)
Definition at line 1145 of file JNICalls.c.
{
    jobject result;
    BEGIN_JAVA
    result = (*env)->GetObjectArrayElement(env, array, index);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _Array_coerceObject(), coerceObjects(), Java_org_postgresql_pljava_internal_ExecutionPlan__1prepare(), Java_org_postgresql_pljava_internal_Function__1reconcileTypes(), Java_org_postgresql_pljava_internal_Function__1storeToNonUDT(), Java_org_postgresql_pljava_internal_Relation__1modifyTuple(), and Java_org_postgresql_pljava_internal_TupleDesc__1formTuple().
JNI_getObjectClass()
jclass JNI_getObjectClass (jobject obj)
Definition at line 1154 of file JNICalls.c.
{
    jclass result;
    BEGIN_JAVA
    result = (*env)->GetObjectClass(env, obj);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by Java_org_postgresql_pljava_internal_Backend__1pokeJEP411().
JNI_getShortArrayElements()
jshort * JNI_getShortArrayElements (jshortArray array, jboolean * isCopy)
Definition at line 1163 of file JNICalls.c.
{
    jshort* result;
    BEGIN_JAVA
    result = (*env)->GetShortArrayElements(env, array, isCopy);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _shortArray_coerceDatum().
JNI_getShortArrayRegion()
void JNI_getShortArrayRegion (jshortArray array, jsize start, jsize len, jshort * buf)
Definition at line 1172 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->GetShortArrayRegion(env, array, start, len, buf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _shortArray_coerceObject().
JNI_getStaticBooleanField()
jboolean JNI_getStaticBooleanField (jclass clazz, jfieldID field)
Definition at line 1224 of file JNICalls.c.
{
    jboolean result;
    BEGIN_JAVA
    result = (*env)->GetStaticBooleanField(env, clazz, field);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by initPLJavaClasses(), and InstallHelper_hello().
JNI_getStaticFieldID()
jfieldID JNI_getStaticFieldID (jclass clazz, const char * name, const char * sig)
Definition at line 1179 of file JNICalls.c.
{
    jfieldID result;
    BEGIN_JAVA
    result = (*env)->GetStaticFieldID(env, clazz, name, sig);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by Java_org_postgresql_pljava_internal_Backend__1pokeJEP411(), and PgObject_getStaticJavaField().
JNI_getStaticIntField()
jint JNI_getStaticIntField (jclass clazz, jfieldID field)
Definition at line 1233 of file JNICalls.c.
{
    jint result;
    BEGIN_JAVA
    result = (*env)->GetStaticIntField(env, clazz, field);
    END_JAVA
    return result;
}
References BEGIN_JAVA, END_JAVA, and jint().
Referenced by initPLJavaClasses().
JNI_getStaticMethodID()
jmethodID JNI_getStaticMethodID (jclass clazz, const char * name, const char * sig)
Definition at line 1188 of file JNICalls.c.
{
    jmethodID result;
    BEGIN_CALL
    result = (*env)->GetStaticMethodID(env, clazz, name, sig);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by PgObject_getStaticJavaMethod().
JNI_getStaticMethodIDOrNull()
jmethodID JNI_getStaticMethodIDOrNull (jclass clazz, const char * name, const char * sig)
Definition at line 1197 of file JNICalls.c.
{
    jmethodID result;
    jobject exh;
    BEGIN_CALL
    result = (*env)->GetStaticMethodID(env, clazz, name, sig);
    if(result == 0) {
        exh = (*env)->ExceptionOccurred(env);
        if ( 0 != exh )
        {
            /*
             * Ignore a NoSuchMethodError, but not any other exception.
             * This operation order (first clear the pending exception, then
             * do the IsInstanceOf check, then Throw again if not the expected
             * class) avoids a benign -Xcheck:JNI warning about calling
             * IsInstanceOf while an exception is pending.
             */
            (*env)->ExceptionClear(env);
            if ( ! (*env)->IsInstanceOf(env, exh, NoSuchMethodError_class) )
                (*env)->Throw(env, exh);
            (*env)->DeleteLocalRef(env, exh);
        }
    }
    END_CALL
    return result;
}
References BEGIN_CALL, END_CALL, and NoSuchMethodError_class.
JNI_getStaticObjectField()
jobject JNI_getStaticObjectField (jclass clazz, jfieldID field)
Definition at line 1242 of file JNICalls.c.
{
    jobject result;
    BEGIN_JAVA
    result = (*env)->GetStaticObjectField(env, clazz, field);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _LocalDateTime_obtain(), Function_initialize(), initPLJavaClasses(), Java_org_postgresql_pljava_internal_Backend__1pokeJEP411(), and String_initialize_codec().
JNI_getStringUTFChars()
const char * JNI_getStringUTFChars (jstring string, jboolean * isCopy)
Definition at line 1251 of file JNICalls.c.
{
    const char* result;
    BEGIN_JAVA
    result = (*env)->GetStringUTFChars(env, string, isCopy);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by String_createNTS().
JNI_hasNullArrayElement()
jboolean JNI_hasNullArrayElement (jobjectArray array)
Definition at line 1260 of file JNICalls.c.
{
    jsize idx;
    jboolean foundNull = JNI_FALSE;
    BEGIN_JAVA
    idx = (*env)->GetArrayLength(env, array);
    while(--idx >= 0)
    {
        if((*env)->GetObjectArrayElement(env, array, idx) != 0)
            continue;
        foundNull = JNI_TRUE;
        break;
    }
    END_JAVA
    return foundNull;
}
References BEGIN_JAVA, and END_JAVA.
JNI_isCallingJava()
jboolean JNI_isCallingJava (void)
Definition at line 1277 of file JNICalls.c.
{
    return jniEnv == 0;
}
References jniEnv.
Referenced by Java_org_postgresql_pljava_internal_Backend_isCallingJava().
JNI_isInstanceOf()
jboolean JNI_isInstanceOf (jobject obj, jclass clazz)
Definition at line 1282 of file JNICalls.c.
{
    jboolean result;
    BEGIN_JAVA
    result = (*env)->IsInstanceOf(env, obj, clazz);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _byte_array_coerceObject(), and Type_coerceObjectBridged().
JNI_isSameObject()
jboolean JNI_isSameObject (jobject obj1, jobject obj2)
Definition at line 1291 of file JNICalls.c.
{
    jboolean result;
    BEGIN_JAVA
    result = (*env)->IsSameObject(env, obj1, obj2);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by appendCharBuffer(), and Function_checkTypeBaseUDT().
JNI_newBooleanArray()
jbooleanArray JNI_newBooleanArray (jsize length)
Definition at line 1309 of file JNICalls.c.
{
    jbooleanArray result;
    BEGIN_JAVA
    result = (*env)->NewBooleanArray(env, length);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _booleanArray_coerceDatum().
JNI_newByteArray()
jbyteArray JNI_newByteArray (jsize length)
Definition at line 1300 of file JNICalls.c.
{
    jbyteArray result;
    BEGIN_JAVA
    result = (*env)->NewByteArray(env, length);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _byte_array_coerceDatum(), and _byteArray_coerceDatum().
JNI_newDirectByteBuffer()
jobject JNI_newDirectByteBuffer (void * address, jlong capacity)
Definition at line 1327 of file JNICalls.c.
{
    jobject result;
    BEGIN_JAVA
    result = (*env)->NewDirectByteBuffer(env, address, capacity);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _byte_array_coerceObject(), appendCharBuffer(), Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1detoast(), Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Output_00024State__1nextBuffer(), Java_org_postgresql_pljava_jdbc_SQLOutputToChunk__1ensureCapacity(), pljava_VarlenaWrapper_Input(), pljava_VarlenaWrapper_Output(), SQLInputFromChunk_create(), SQLOutputToChunk_create(), String_createJavaString(), and String_createJavaStringFromNTS().
JNI_newDoubleArray()
jdoubleArray JNI_newDoubleArray (jsize length)
Definition at line 1336 of file JNICalls.c.
{
    jdoubleArray result;
    BEGIN_JAVA
    result = (*env)->NewDoubleArray(env, length);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _doubleArray_coerceDatum().
JNI_newFloatArray()
jfloatArray JNI_newFloatArray (jsize length)
Definition at line 1345 of file JNICalls.c.
{
    jfloatArray result;
    BEGIN_JAVA
    result = (*env)->NewFloatArray(env, length);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _floatArray_coerceDatum().
JNI_newGlobalRef()
jobject JNI_newGlobalRef (jobject object)
Definition at line 1354 of file JNICalls.c.
{
    jobject result;
    BEGIN_JAVA
    result = (*env)->NewGlobalRef(env, object);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _LocalDate_obtain(), _LocalDateTime_obtain(), _LocalTime_obtain(), _OffsetTime_obtain(), AclId_initialize(), BigDecimal_initialize(), Boolean_initialize(), byte_array_initialize(), Byte_initialize(), Composite_initialize(), Date_initialize(), Double_initialize(), Exception_initialize(), Exception_initialize2(), Float_initialize(), Function_create(), Function_initialize(), initializeTypeBridges(), initPLJavaClasses(), InstallHelper_initialize(), Integer_initialize(), Java_org_postgresql_pljava_internal_Function__1storeToNonUDT(), Java_org_postgresql_pljava_internal_Function__1storeToUDT(), Long_initialize(), Oid_initialize(), PgObject_getClassName(), PgSavepoint_initialize(), pljava_DualState_initialize(), pljava_ErrorData_initialize(), pljava_ExecutionPlan_initialize(), pljava_JNI_threadInitialize(), pljava_Portal_initialize(), pljava_Relation_initialize(), pljava_SingleRowReader_initialize(), pljava_SQLInputFromTuple_initialize(), pljava_SQLXMLImpl_initialize(), pljava_TriggerData_initialize(), pljava_Tuple_initialize(), pljava_TupleDesc_initialize(), pljava_VarlenaWrapper_initialize(), Short_initialize(), SQLInputFromChunk_initialize(), SQLOutputToChunk_initialize(), SQLOutputToTuple_initialize(), String_initialize(), String_initialize_codec(), SubXactListener_initialize(), Time_initialize(), Timestamp_initialize(), TupleTable_initialize(), Type_getJavaClass(), Type_initialize(), Type_invokeSRF(), UDT_registerUDT(), and XactListener_initialize().
JNI_newIntArray()
jintArray JNI_newIntArray (jsize length)
Definition at line 1363 of file JNICalls.c.
{
    jintArray result;
    BEGIN_JAVA
    result = (*env)->NewIntArray(env, length);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _intArray_coerceDatum().
JNI_newLocalRef()
jobject JNI_newLocalRef (jobject object)
Definition at line 1372 of file JNICalls.c.
{
    jobject result;
    BEGIN_JAVA
    result = (*env)->NewLocalRef(env, object);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
JNI_newLongArray()
jlongArray JNI_newLongArray (jsize length)
Definition at line 1381 of file JNICalls.c.
{
    jlongArray result;
    BEGIN_JAVA
    result = (*env)->NewLongArray(env, length);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _longArray_coerceDatum().
JNI_newObject()
jobject JNI_newObject (jclass clazz, jmethodID ctor, ...)
Definition at line 1435 of file JNICalls.c.
{
    jobject result;
    va_list args;
    va_start(args, ctor);
    result = JNI_newObjectV(clazz, ctor, args);
    va_end(args);
    return result;
}
References JNI_newObjectV().
Referenced by _BigDecimal_coerceDatum(), _Boolean_coerceDatum(), _Byte_coerceDatum(), _createWriter(), _Date_coerceDatum(), _Double_coerceDatum(), _Float_coerceDatum(), _Integer_coerceDatum(), _Long_coerceDatum(), _Short_coerceDatum(), _SQLXML_coerceDatum(), _SQLXML_coerceDatum_synthetic(), AclId_create(), Exception_featureNotSupported(), Exception_throw(), Exception_throw_ERROR(), Exception_throwIllegalArgument(), Oid_create(), pljava_DualState_initialize(), SQLInputFromChunk_create(), SQLOutputToChunk_create(), SQLOutputToTuple_create(), Time_coerceDatumTZ_dd(), Time_coerceDatumTZ_id(), Timestamp_coerceDatumTZ_dd(), Timestamp_coerceDatumTZ_id(), TupleTable_create(), and TupleTable_createFromSlot().
JNI_newObjectArray()
jobjectArray JNI_newObjectArray (jsize length, jclass elementClass, jobject initialElement)
Definition at line 1318 of file JNICalls.c.
{
    jobjectArray result;
    BEGIN_JAVA
    result = (*env)->NewObjectArray(env, length, elementClass, initialElement);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _Array_coerceDatum(), Java_org_postgresql_pljava_internal_TriggerData__1getArguments(), and pljava_Tuple_createArray().
JNI_newObjectLocked()
jobject JNI_newObjectLocked (jclass clazz, jmethodID ctor, ...)
Definition at line 1454 of file JNICalls.c.
{
    jobject result;
    va_list args;
    va_start(args, ctor);
    result = JNI_newObjectLockedV(clazz, ctor, args);
    va_end(args);
    return result;
}
References JNI_newObjectLockedV().
Referenced by Java_org_postgresql_pljava_internal_ExecutionPlan__1prepare(), Java_org_postgresql_pljava_jdbc_SQLXMLImpl__1newWritable(), pljava_ErrorData_getCurrentError(), pljava_Portal_create(), pljava_Relation_create(), pljava_SingleRowReader_create(), pljava_SQLInputFromTuple_create(), pljava_TriggerData_create(), pljava_Tuple_internalCreate(), pljava_TupleDesc_internalCreate(), pljava_VarlenaWrapper_Input(), and pljava_VarlenaWrapper_Output().
JNI_newObjectLockedV()
jobject JNI_newObjectLockedV (jclass clazz, jmethodID ctor, va_list args)
Definition at line 1464 of file JNICalls.c.
{
    jobject result;
    BEGIN_CALL_MONITOR_HELD
    result = (*env)->NewObjectV(env, clazz, ctor, args);
    END_CALL_MONITOR_HELD
    return result;
}
References BEGIN_CALL_MONITOR_HELD, and END_CALL_MONITOR_HELD.
Referenced by JNI_newObjectLocked().
JNI_newObjectV()
jobject JNI_newObjectV (jclass clazz, jmethodID ctor, va_list args)
Definition at line 1445 of file JNICalls.c.
{
    jobject result;
    BEGIN_CALL
    result = (*env)->NewObjectV(env, clazz, ctor, args);
    END_CALL
    return result;
}
References BEGIN_CALL, and END_CALL.
Referenced by JNI_newObject().
JNI_newShortArray()
jshortArray JNI_newShortArray (jsize length)
Definition at line 1390 of file JNICalls.c.
{
    jshortArray result;
    BEGIN_JAVA
    result = (*env)->NewShortArray(env, length);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _shortArray_coerceDatum().
JNI_newStringUTF()
jstring JNI_newStringUTF (const char * bytes)
Definition at line 1399 of file JNICalls.c.
{
    jstring result;
    BEGIN_JAVA
    result = (*env)->NewStringUTF(env, bytes);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by String_initialize_codec().
JNI_newWeakGlobalRef()
jweak JNI_newWeakGlobalRef (jobject object)
Definition at line 1426 of file JNICalls.c.
{
    jweak result;
    BEGIN_JAVA
    result = (*env)->NewWeakGlobalRef(env, object);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
JNI_popLocalFrame()
jobject JNI_popLocalFrame (jobject resultObj)
Definition at line 1417 of file JNICalls.c.
{
    jobject result;
    BEGIN_JAVA
    result = (*env)->PopLocalFrame(env, resultObj);
    END_JAVA
    return result;
}
References BEGIN_JAVA, and END_JAVA.
Referenced by Invocation_popBootContext(), Invocation_popInvocation(), and String_initialize().
JNI_pushLocalFrame()
jint JNI_pushLocalFrame (jint capacity)
Definition at line 1408 of file JNICalls.c.
{
    jint result;
    BEGIN_JAVA
    result = (*env)->PushLocalFrame(env, capacity);
    END_JAVA
    return result;
}
References BEGIN_JAVA, END_JAVA, and jint().
Referenced by Invocation_pushBootContext(), Invocation_pushInvocation(), and String_initialize().
JNI_registerNatives()
jint JNI_registerNatives (jclass clazz, const JNINativeMethod * methods, jint nMethods)
Definition at line 1529 of file JNICalls.c.
{
    jint result;
    BEGIN_JAVA
    result = (*env)->RegisterNatives(env, clazz, methods, nMethods);
    END_JAVA
    return result;
}
References BEGIN_JAVA, END_JAVA, and jint().
Referenced by PgObject_registerNatives2().
JNI_releaseBooleanArrayElements()
void JNI_releaseBooleanArrayElements (jbooleanArray array, jboolean * elems, jint mode)
Definition at line 1480 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->ReleaseBooleanArrayElements(env, array, elems, mode);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _booleanArray_coerceDatum().
JNI_releaseByteArrayElements()
void JNI_releaseByteArrayElements (jbyteArray array, jbyte * elems, jint mode)
Definition at line 1473 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->ReleaseByteArrayElements(env, array, elems, mode);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _byteArray_coerceDatum().
JNI_releaseDoubleArrayElements()
void JNI_releaseDoubleArrayElements (jdoubleArray array, jdouble * elems, jint mode)
Definition at line 1487 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->ReleaseDoubleArrayElements(env, array, elems, mode);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _doubleArray_coerceDatum().
JNI_releaseFloatArrayElements()
void JNI_releaseFloatArrayElements (jfloatArray array, jfloat * elems, jint mode)
Definition at line 1494 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->ReleaseFloatArrayElements(env, array, elems, mode);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _floatArray_coerceDatum().
JNI_releaseIntArrayElements()
void JNI_releaseIntArrayElements (jintArray array, jint * elems, jint mode)
Definition at line 1501 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->ReleaseIntArrayElements(env, array, elems, mode);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _intArray_coerceDatum(), Java_org_postgresql_pljava_internal_Function__1storeToNonUDT(), and Java_org_postgresql_pljava_internal_Relation__1modifyTuple().
JNI_releaseLongArrayElements()
void JNI_releaseLongArrayElements (jlongArray array, jlong * elems, jint mode)
Definition at line 1508 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->ReleaseLongArrayElements(env, array, elems, mode);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _longArray_coerceDatum().
JNI_releaseShortArrayElements()
void JNI_releaseShortArrayElements (jshortArray array, jshort * elems, jint mode)
Definition at line 1515 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->ReleaseShortArrayElements(env, array, elems, mode);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _shortArray_coerceDatum().
JNI_releaseStringUTFChars()
void JNI_releaseStringUTFChars (jstring string, const char * utf)
Definition at line 1522 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->ReleaseStringUTFChars(env, string, utf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by String_createNTS().
JNI_setBooleanArrayRegion()
void JNI_setBooleanArrayRegion (jbooleanArray array, jsize start, jsize len, jboolean * buf)
Definition at line 1545 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->SetBooleanArrayRegion(env, array, start, len, buf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _booleanArray_coerceDatum().
JNI_setByteArrayRegion()
void JNI_setByteArrayRegion (jbyteArray array, jsize start, jsize len, jbyte * buf)
Definition at line 1538 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->SetByteArrayRegion(env, array, start, len, buf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _byte_array_coerceDatum(), and _byteArray_coerceDatum().
JNI_setDoubleArrayRegion()
void JNI_setDoubleArrayRegion (jdoubleArray array, jsize start, jsize len, jdouble * buf)
Definition at line 1552 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->SetDoubleArrayRegion(env, array, start, len, buf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _doubleArray_coerceDatum().
JNI_setEnv()
JNIEnv * JNI_setEnv (JNIEnv * env)
Definition at line 1566 of file JNICalls.c.
{
    JNIEnv* oldEnv = jniEnv;
    jniEnv = env;
    return oldEnv;
}
References jniEnv.
Referenced by beginNative(), and beginNativeNoErrCheck().
JNI_setFloatArrayRegion()
void JNI_setFloatArrayRegion (jfloatArray array, jsize start, jsize len, jfloat * buf)
Definition at line 1559 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->SetFloatArrayRegion(env, array, start, len, buf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _floatArray_coerceDatum().
JNI_setIntArrayRegion()
void JNI_setIntArrayRegion (jintArray array, jsize start, jsize len, jint * buf)
Definition at line 1573 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->SetIntArrayRegion(env, array, start, len, buf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _intArray_coerceDatum().
JNI_setIntField()
void JNI_setIntField (jobject object, jfieldID field, jint value)
Definition at line 1587 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->SetIntField(env, object, field, value);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by Java_org_postgresql_pljava_internal_PgSavepoint__1set().
JNI_setLongArrayRegion()
void JNI_setLongArrayRegion (jlongArray array, jsize start, jsize len, jlong * buf)
Definition at line 1580 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->SetLongArrayRegion(env, array, start, len, buf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _longArray_coerceDatum().
JNI_setLongField()
void JNI_setLongField (jobject object, jfieldID field, jlong value)
Definition at line 1594 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->SetLongField(env, object, field, value);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1detoast().
JNI_setObjectArrayElement()
void JNI_setObjectArrayElement (jobjectArray array, jsize index, jobject value)
Definition at line 1601 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->SetObjectArrayElement(env, array, index, value);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _Array_coerceDatum(), Function_invoke(), invokeTrigger(), Java_org_postgresql_pljava_internal_Function__1reconcileTypes(), Java_org_postgresql_pljava_internal_Function__1storeToNonUDT(), Java_org_postgresql_pljava_internal_TriggerData__1getArguments(), pljava_Function_setParameter(), pljava_Function_vpcInvoke(), and pljava_Tuple_createArray().
JNI_setShortArrayRegion()
void JNI_setShortArrayRegion (jshortArray array, jsize start, jsize len, jshort * buf)
Definition at line 1608 of file JNICalls.c.
{
    BEGIN_JAVA
    (*env)->SetShortArrayRegion(env, array, start, len, buf);
    END_JAVA
}
References BEGIN_JAVA, and END_JAVA.
Referenced by _shortArray_coerceDatum().
JNI_setThreadLock()
void JNI_setThreadLock (jobject lockObject)
Definition at line 1615 of file JNICalls.c.
{
    BEGIN_JAVA
    s_threadLock = (*env)->NewGlobalRef(env, lockObject);
    if(NULL != s_threadLock  &&  (*env)->MonitorEnter(env, s_threadLock) < 0)
        elog(ERROR, "Java enter monitor failure (initial)");
    END_JAVA
}
References BEGIN_JAVA, END_JAVA, and s_threadLock.
Referenced by initPLJavaClasses().
JNI_throw()
jint JNI_throw (jthrowable obj)
Definition at line 1624 of file JNICalls.c.
{
    jint result;
    BEGIN_JAVA
    result = (*env)->Throw(env, obj);
    END_JAVA
    return result;
}
References BEGIN_JAVA, END_JAVA, and jint().
Referenced by Exception_featureNotSupported(), Exception_throw(), Exception_throw_ERROR(), and Exception_throwIllegalArgument().
pljava_JNI_setThreadPolicy()
void pljava_JNI_setThreadPolicy (bool refuseOtherThreads, bool doMonitorOps)
Definition at line 43 of file JNICalls.c.
{
    s_refuseOtherThreads = refuseOtherThreads;
    s_doMonitorOps = doMonitorOps;
}
References s_doMonitorOps, and s_refuseOtherThreads.
Referenced by ASSIGNENUMHOOK().
pljava_JNI_threadInitialize()
void pljava_JNI_threadInitialize (bool manageLoader)
Definition at line 69 of file JNICalls.c.
{
    if ( ! manageLoader )
    {
        JNI_loaderUpdater  = _noopUpdater;
        JNI_loaderRestorer = _noopRestorer;
        return;
    }
    s_Thread_class = JNI_newGlobalRef(PgObject_getJavaClass(
        "java/lang/Thread"));
    s_Thread_currentThread = PgObject_getStaticJavaMethod(
        s_Thread_class,
        "currentThread",
        "()"
        "Ljava/lang/Thread;");
    s_Thread_contextLoader = JNI_getFieldIDOrNull(s_Thread_class,
        "contextClassLoader", "Ljava/lang/ClassLoader;");
    if ( NULL == s_Thread_contextLoader )
    {
        ereport(WARNING, (
            errmsg("unable to manage thread context classloaders in this JVM")
        ));
        JNI_loaderUpdater  = _noopUpdater;
        JNI_loaderRestorer = _noopRestorer;
    }
    else if ( s_refuseOtherThreads  ||  ! s_doMonitorOps )
    {
        s_threadObject =
            JNI_newGlobalRef(
                JNI_callStaticObjectMethod(
                    s_Thread_class, s_Thread_currentThread));
        JNI_loaderUpdater  = _lightUpdater;
        JNI_loaderRestorer = _lightRestorer;
    }
    else
    {
        JNI_loaderUpdater  = _heavyUpdater;
        JNI_loaderRestorer = _heavyRestorer;
    }
}
References _heavyRestorer, _heavyUpdater, _lightRestorer, _lightUpdater, _noopRestorer, _noopUpdater, JNI_callStaticObjectMethod(), JNI_getFieldIDOrNull(), JNI_loaderRestorer, JNI_loaderUpdater, JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getStaticJavaMethod(), s_doMonitorOps, s_refuseOtherThreads, s_Thread_class, s_Thread_contextLoader, s_Thread_currentThread, and s_threadObject.
Referenced by InstallHelper_hello().
printStacktrace()
static void printStacktrace (JNIEnv * env, jobject exh) static
Definition at line 206 of file JNICalls.c.
{
#ifndef _MSC_VER
    if(DEBUG1 >= log_min_messages || DEBUG1 >= client_min_messages)
#else
    /* This is gross, but only happens as often as an exception escapes Java
     * code to be rethrown. There is some renewed interest on pgsql-hackers to
     * find a good answer for the MSVC PGDLLIMPORT nonsense, and all of this
     * handling of exceptions and logging could stand some rework anyway.
     */
    if ( 0 == strncmp("debug", PG_GETCONFIGOPTION("log_min_messages"), 5)
        || 0 == strncmp("debug", PG_GETCONFIGOPTION("client_min_messages"), 5) )
#endif
    {
        int currLevel = Backend_setJavaLogLevel(DEBUG1);
        (*env)->CallVoidMethod(env, exh, Throwable_printStackTrace);
        (*env)->ExceptionOccurred(env); /* sop for JNI exception-check check */
        Backend_setJavaLogLevel(currLevel);
    }
}
References Backend_setJavaLogLevel(), and Throwable_printStackTrace.
Referenced by endCall(), endCallMonitorHeld(), and JNI_exceptionDescribe().
Variable Documentation
_heavyRestorer
void _heavyRestorer static
Definition at line 67 of file JNICalls.c.
Referenced by pljava_JNI_threadInitialize().
_heavyUpdater
JNI_ContextLoaderUpdater _heavyUpdater static
Definition at line 66 of file JNICalls.c.
Referenced by pljava_JNI_threadInitialize().
_lightRestorer
void _lightRestorer static
Definition at line 64 of file JNICalls.c.
Referenced by pljava_JNI_threadInitialize().
_lightUpdater
JNI_ContextLoaderUpdater _lightUpdater static
Definition at line 63 of file JNICalls.c.
Referenced by pljava_JNI_threadInitialize().
_noopRestorer
void _noopRestorer static
Definition at line 61 of file JNICalls.c.
Referenced by pljava_JNI_threadInitialize().
_noopUpdater
JNI_ContextLoaderUpdater _noopUpdater static
Definition at line 60 of file JNICalls.c.
Referenced by pljava_JNI_threadInitialize().
JNI_loaderRestorer
JNI_ContextLoaderRestorer* JNI_loaderRestorer
Definition at line 58 of file JNICalls.c.
Referenced by pljava_JNI_threadInitialize().
JNI_loaderUpdater
JNI_ContextLoaderUpdater* JNI_loaderUpdater
Definition at line 57 of file JNICalls.c.
Referenced by pljava_JNI_threadInitialize().
jniEnv
JNIEnv* jniEnv
Definition at line 25 of file JNICalls.c.
Referenced by elogExceptionMessage(), endCall(), endCallMonitorHeld(), JNI_createVM(), JNI_destroyVM(), JNI_isCallingJava(), and JNI_setEnv().
mainThreadId
void void* void* mainThreadId
Definition at line 28 of file JNICalls.c.
Referenced by JNI_createVM().
primordialJNIEnv
JNIEnv* primordialJNIEnv static
Definition at line 30 of file JNICalls.c.
Referenced by beginNativeNoErrCheck(), and JNI_createVM().
s_doMonitorOps
bool s_doMonitorOps = true static
Definition at line 35 of file JNICalls.c.
Referenced by endCall(), pljava_JNI_setThreadPolicy(), and pljava_JNI_threadInitialize().
s_refuseOtherThreads
bool s_refuseOtherThreads = false static
Definition at line 34 of file JNICalls.c.
Referenced by beginNativeNoErrCheck(), pljava_JNI_setThreadPolicy(), and pljava_JNI_threadInitialize().
s_Thread_class
jclass s_Thread_class static
Definition at line 37 of file JNICalls.c.
Referenced by _heavyUpdater(), and pljava_JNI_threadInitialize().
s_Thread_contextLoader
jfieldID s_Thread_contextLoader static
Definition at line 39 of file JNICalls.c.
Referenced by _updaterCommon(), and pljava_JNI_threadInitialize().
s_Thread_currentThread
jmethodID s_Thread_currentThread static
Definition at line 38 of file JNICalls.c.
Referenced by _heavyUpdater(), and pljava_JNI_threadInitialize().
s_threadLock
jobject s_threadLock static
Definition at line 32 of file JNICalls.c.
Referenced by endCall(), JNI_destroyVM(), and JNI_setThreadLock().
s_threadObject
jobject s_threadObject static
Definition at line 41 of file JNICalls.c.
Referenced by _lightUpdater(), and pljava_JNI_threadInitialize().