PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/SQLOutputToTuple.c File Reference
SQLOutputToTuple.c File Reference
#include <postgres.h>
#include "pljava/type/Type.h"
#include "pljava/type/TupleDesc.h"
#include "pljava/SQLOutputToTuple.h"
Functions
jobject SQLOutputToTuple_create (TupleDesc td)
HeapTuple SQLOutputToTuple_getTuple (jobject sqlOutput)
void SQLOutputToTuple_initialize (void)
Variables
static jclass s_SQLOutputToTuple_class
static jmethodID s_SQLOutputToTuple_init
static jmethodID s_SQLOutputToTuple_getTuple
Function Documentation
SQLOutputToTuple_create()
jobject SQLOutputToTuple_create (TupleDesc td)
Definition at line 24 of file SQLOutputToTuple.c.
{
    jobject tupleDesc = pljava_TupleDesc_create(td);
    jobject result = JNI_newObject(s_SQLOutputToTuple_class, s_SQLOutputToTuple_init, tupleDesc);
    JNI_deleteLocalRef(tupleDesc);
    return result;
}
References JNI_deleteLocalRef(), JNI_newObject(), pljava_TupleDesc_create(), s_SQLOutputToTuple_class, and s_SQLOutputToTuple_init.
Referenced by coerceTupleObject().
SQLOutputToTuple_getTuple()
HeapTuple SQLOutputToTuple_getTuple (jobject sqlOutput)
Definition at line 32 of file SQLOutputToTuple.c.
{
    Ptr2Long p2l;
    if(sqlOutput == 0)
        return 0;
    p2l.longVal = JNI_callLongMethod(sqlOutput, s_SQLOutputToTuple_getTuple);
    if(p2l.longVal == 0)
        return 0;
    return (HeapTuple)p2l.ptrVal;
}
References JNI_callLongMethod(), and s_SQLOutputToTuple_getTuple.
Referenced by coerceTupleObject().
SQLOutputToTuple_initialize()
void SQLOutputToTuple_initialize (void) extern
Definition at line 48 of file SQLOutputToTuple.c.
{
    s_SQLOutputToTuple_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/jdbc/SQLOutputToTuple"));
    s_SQLOutputToTuple_init = PgObject_getJavaMethod(s_SQLOutputToTuple_class, "<init>", "(Lorg/postgresql/pljava/internal/TupleDesc;)V");
    s_SQLOutputToTuple_getTuple = PgObject_getJavaMethod(s_SQLOutputToTuple_class, "getTuple", "()J");
}
References JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_SQLOutputToTuple_class, s_SQLOutputToTuple_getTuple, and s_SQLOutputToTuple_init.
Referenced by initPLJavaClasses().
Variable Documentation
s_SQLOutputToTuple_class
jclass s_SQLOutputToTuple_class static
Definition at line 20 of file SQLOutputToTuple.c.
Referenced by SQLOutputToTuple_create(), and SQLOutputToTuple_initialize().
s_SQLOutputToTuple_getTuple
jmethodID s_SQLOutputToTuple_getTuple static
Definition at line 22 of file SQLOutputToTuple.c.
Referenced by SQLOutputToTuple_getTuple(), and SQLOutputToTuple_initialize().
s_SQLOutputToTuple_init
jmethodID s_SQLOutputToTuple_init static
Definition at line 21 of file SQLOutputToTuple.c.
Referenced by SQLOutputToTuple_create(), and SQLOutputToTuple_initialize().