PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/Invocation.c File Reference
Invocation.c File Reference
#include <postgres.h>
#include <executor/spi.h>
#include "org_postgresql_pljava_jdbc_Invocation.h"
#include "pljava/Invocation.h"
#include "pljava/Function.h"
#include "pljava/PgObject.h"
#include "pljava/JNICalls.h"
#include "pljava/Backend.h"
#include "pljava/DualState.h"
#include "pljava/Exception.h"
Macros
#define LOCAL_FRAME_SIZE 128
Functions
void pljava_Invocation_shareFrame (jvalue *slot0, jshort *limits)
void Invocation_initialize (void)
void Invocation_assertConnect (void)
void Invocation_assertDisconnect (void)
jobject Invocation_getTypeMap (void)
void Invocation_pushBootContext (Invocation *ctx)
void Invocation_popBootContext (void)
void Invocation_pushInvocation (Invocation *ctx)
void Invocation_popInvocation (bool wasException)
MemoryContext Invocation_switchToUpperContext (void)
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_jdbc_Invocation__1getNestingLevel (JNIEnv *env, jclass cls)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_jdbc_Invocation__1getCurrent (JNIEnv *env, jclass cls)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_jdbc_Invocation__1clearErrorCondition (JNIEnv *env, jclass cls)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_jdbc_Invocation__1register (JNIEnv *env, jobject _this)
Variables
static jmethodID s_Invocation_onExit
static unsigned int s_callLevel = 0
Invocation * currentInvocation
static jvalue * s_primSlot0
static jshort * s_frameLimits
Macro Definition Documentation
LOCAL_FRAME_SIZE
#define LOCAL_FRAME_SIZE 128
Definition at line 25 of file Invocation.c.
Function Documentation
Invocation_assertConnect()
void Invocation_assertConnect (void)
Definition at line 93 of file Invocation.c.
{
    int rslt;
    if(!currentInvocation->hasConnected)
    {
        rslt = SPI_connect();
        if ( SPI_OK_CONNECT != rslt )
            elog(ERROR, "SPI_connect returned %s",
                        SPI_result_code_string(rslt));
#if PG_VERSION_NUM >= 100000
        if ( NULL != currentInvocation->triggerData )
        {
            rslt = SPI_register_trigger_data(currentInvocation->triggerData);
            if ( SPI_OK_TD_REGISTER != rslt )
                elog(WARNING, "SPI_register_trigger_data returned %s",
                              SPI_result_code_string(rslt));
        }
#endif
        currentInvocation->hasConnected = true;
    }
}
References currentInvocation.
Referenced by invokeTrigger(), Java_org_postgresql_pljava_internal_ExecutionPlan__1cursorOpen(), Java_org_postgresql_pljava_internal_ExecutionPlan__1execute(), Java_org_postgresql_pljava_internal_ExecutionPlan__1isCursorPlan(), Java_org_postgresql_pljava_internal_ExecutionPlan__1prepare(), Java_org_postgresql_pljava_internal_PgSavepoint__1set(), Java_org_postgresql_pljava_internal_Portal__1fetch(), Java_org_postgresql_pljava_internal_Portal__1move(), and Java_org_postgresql_pljava_internal_SPI__1exec().
Invocation_assertDisconnect()
void Invocation_assertDisconnect (void)
Definition at line 115 of file Invocation.c.
{
    if(currentInvocation->hasConnected)
    {
        SPI_finish();
        currentInvocation->hasConnected = false;
    }
}
References currentInvocation.
Referenced by _closeIteration(), Function_invoke(), and Type_invokeSRF().
Invocation_getTypeMap()
jobject Invocation_getTypeMap (void)
Definition at line 131 of file Invocation.c.
{
    Function f = currentInvocation->function;
    return f == 0 ? 0 : Function_getTypeMap(f);
}
References currentInvocation, and Function_getTypeMap().
Referenced by coerceObjects(), Java_org_postgresql_pljava_internal_Oid__1getJavaClassName(), Java_org_postgresql_pljava_internal_Relation__1modifyTuple(), Java_org_postgresql_pljava_internal_TupleDesc__1formTuple(), and pljava_TupleDesc_getColumnType().
Invocation_initialize()
void Invocation_initialize (void) extern
Definition at line 59 of file Invocation.c.
{
    jclass cls;
    JNINativeMethod invocationMethods[] =
    {
        {
        "_getCurrent",
        "()Lorg/postgresql/pljava/jdbc/Invocation;",
        Java_org_postgresql_pljava_jdbc_Invocation__1getCurrent
        },
        {
        "_getNestingLevel",
        "()I",
        Java_org_postgresql_pljava_jdbc_Invocation__1getNestingLevel
        },
        {
        "_clearErrorCondition",
        "()V",
        Java_org_postgresql_pljava_jdbc_Invocation__1clearErrorCondition
        },
        {
        "_register",
        "()V",
        Java_org_postgresql_pljava_jdbc_Invocation__1register
        },
        { 0, 0, 0 }
    };
    cls = PgObject_getJavaClass("org/postgresql/pljava/jdbc/Invocation");
    PgObject_registerNatives2(cls, invocationMethods);
    s_Invocation_onExit = PgObject_getJavaMethod(cls, "onExit", "(Z)V");
    JNI_deleteLocalRef(cls);
}
References Java_org_postgresql_pljava_jdbc_Invocation__1clearErrorCondition(), Java_org_postgresql_pljava_jdbc_Invocation__1getCurrent(), Java_org_postgresql_pljava_jdbc_Invocation__1getNestingLevel(), Java_org_postgresql_pljava_jdbc_Invocation__1register(), JNI_deleteLocalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_registerNatives2(), and s_Invocation_onExit.
Referenced by initPLJavaClasses().
Invocation_popBootContext()
void Invocation_popBootContext (void)
Definition at line 157 of file Invocation.c.
{
    JNI_popLocalFrame(0);
    currentInvocation = 0;
    --s_callLevel;
    /*
     * Nothing is done here with savedLoader. It is just set to 0 in
     * pushBootContext (uses can precede allocation of the sentinel value),
     * and PL/Java functions (which could save a value) aren't called in a
     * boot context.
     */
}
References currentInvocation, JNI_popLocalFrame(), and s_callLevel.
Referenced by initsequencer(), and InstallHelper_hello().
Invocation_popInvocation()
void Invocation_popInvocation (bool wasException)
Definition at line 190 of file Invocation.c.
{
    Invocation* ctx = currentInvocation->previous;
    bool heavy = FRAME_LIMITS_PUSHED == currentInvocation->frameLimits;
    /*
     * If the more heavyweight parameter-frame push wasn't done, do
     * the lighter cleanup here.
     */
    if ( ! heavy )
    {
        /*
         * The lighter-weight cleanup.
         */
        *s_frameLimits = currentInvocation->frameLimits;
        *s_primSlot0   = currentInvocation->primSlot0;
    }
    pljava_Function_popFrame(heavy);
    /*
     * If a Java Invocation instance was created and associated with this
     * invocation, delete the reference (after calling its onExit method,
     * indicating whether the return is exceptional or not).
     */
    if(currentInvocation->invocation != 0)
    {
        JNI_callVoidMethodLocked(
            currentInvocation->invocation, s_Invocation_onExit,
            (wasException || currentInvocation->errorOccurred)
            ? JNI_TRUE : JNI_FALSE);
        JNI_deleteGlobalRef(currentInvocation->invocation);
    }
    /*
     * Do nativeRelease for any DualState instances scoped to this invocation.
     */
    pljava_DualState_nativeRelease(currentInvocation);
    /*
     * Check for any DualState objects that became unreachable and can be freed.
     */
    pljava_DualState_cleanEnqueuedInstances();
    if(currentInvocation->hasConnected)
        SPI_finish();
    JNI_popLocalFrame(0);
    if(ctx != 0)
    {
        MemoryContextSwitchTo(ctx->upperContext);
    }
    currentInvocation = ctx;
    --s_callLevel;
}
References currentInvocation, JNI_callVoidMethodLocked(), JNI_deleteGlobalRef(), JNI_popLocalFrame(), pljava_DualState_cleanEnqueuedInstances(), pljava_DualState_nativeRelease(), pljava_Function_popFrame(), s_callLevel, s_frameLimits, s_Invocation_onExit, and s_primSlot0.
Referenced by _endOfSetCB(), InstallHelper_groundwork(), internalCallHandler(), and internalValidator().
Invocation_pushBootContext()
void Invocation_pushBootContext (Invocation * ctx)
Definition at line 137 of file Invocation.c.
{
    JNI_pushLocalFrame(LOCAL_FRAME_SIZE);
    ctx->invocation      = 0;
    ctx->function        = 0;
    ctx->frameLimits     = 0;
    ctx->primSlot0.j     = 0L;
    ctx->savedLoader     = 0;
    ctx->hasConnected    = false;
    ctx->upperContext    = CurrentMemoryContext;
    ctx->errorOccurred   = false;
    ctx->inExprContextCB = false;
    ctx->previous        = 0;
#if PG_VERSION_NUM >= 100000
    ctx->triggerData     = 0;
#endif
    currentInvocation    = ctx;
    ++s_callLevel;
}
References currentInvocation, JNI_pushLocalFrame(), LOCAL_FRAME_SIZE, and s_callLevel.
Referenced by _destroyJavaVM(), initsequencer(), and InstallHelper_hello().
Invocation_pushInvocation()
void Invocation_pushInvocation (Invocation * ctx)
Definition at line 170 of file Invocation.c.
{
    JNI_pushLocalFrame(LOCAL_FRAME_SIZE);
    ctx->invocation      = 0;
    ctx->function        = 0;
    ctx->frameLimits     = *s_frameLimits;
    ctx->primSlot0       = *s_primSlot0;
    ctx->savedLoader     = pljava_Function_NO_LOADER;
    ctx->hasConnected    = false;
    ctx->upperContext    = CurrentMemoryContext;
    ctx->errorOccurred   = false;
    ctx->inExprContextCB = false;
    ctx->previous        = currentInvocation;
#if PG_VERSION_NUM >= 100000
    ctx->triggerData     = 0;
#endif
    currentInvocation   = ctx;
    ++s_callLevel;
}
References currentInvocation, JNI_pushLocalFrame(), LOCAL_FRAME_SIZE, pljava_Function_NO_LOADER, s_callLevel, s_frameLimits, and s_primSlot0.
Referenced by _endOfSetCB(), InstallHelper_groundwork(), internalCallHandler(), and internalValidator().
Invocation_switchToUpperContext()
MemoryContext Invocation_switchToUpperContext (void)
Definition at line 248 of file Invocation.c.
{
    return MemoryContextSwitchTo(currentInvocation->upperContext);
}
References currentInvocation.
Referenced by _asDatum(), _asDatum(), _asDatum(), _Coerce_coerceObject(), _Coerce_invoke(), _Composite_invoke(), _Type_invoke(), coerceScalarObject(), createArrayType(), invokeTrigger(), and UDT_output().
Java_org_postgresql_pljava_jdbc_Invocation__1clearErrorCondition()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_jdbc_Invocation__1clearErrorCondition (JNIEnv * env, jclass cls)
Definition at line 281 of file Invocation.c.
{
    currentInvocation->errorOccurred = false;
}
References currentInvocation.
Referenced by Invocation_initialize().
Java_org_postgresql_pljava_jdbc_Invocation__1getCurrent()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_jdbc_Invocation__1getCurrent (JNIEnv * env, jclass cls)
Definition at line 270 of file Invocation.c.
{
    return currentInvocation->invocation;
}
References currentInvocation.
Referenced by Invocation_initialize().
Java_org_postgresql_pljava_jdbc_Invocation__1getNestingLevel()
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_jdbc_Invocation__1getNestingLevel (JNIEnv * env, jclass cls)
Definition at line 259 of file Invocation.c.
{
    return s_callLevel;
}
References s_callLevel.
Referenced by Invocation_initialize().
Java_org_postgresql_pljava_jdbc_Invocation__1register()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_jdbc_Invocation__1register (JNIEnv * env, jobject _this)
Definition at line 292 of file Invocation.c.
{
    if ( NULL == currentInvocation->invocation )
    {
        currentInvocation->invocation = (*env)->NewGlobalRef(env, _this);
        return;
    }
    if ( (*env)->IsSameObject(env, currentInvocation->invocation, _this) )
        return;
    BEGIN_NATIVE
    Exception_throw(ERRCODE_INTERNAL_ERROR,
        "mismanaged PL/Java invocation stack");
    END_NATIVE
}
References currentInvocation, and Exception_throw().
Referenced by Invocation_initialize().
pljava_Invocation_shareFrame()
void pljava_Invocation_shareFrame (jvalue * slot0, jshort * limits)
Definition at line 50 of file Invocation.c.
{
    if ( 0 != s_primSlot0  ||  0 != s_frameLimits )
        return;
    s_primSlot0 = slot0;
    s_frameLimits = limits;
}
References s_frameLimits, and s_primSlot0.
Referenced by Java_org_postgresql_pljava_internal_Function_00024EarlyNatives__1parameterArea().
Variable Documentation
currentInvocation
Invocation* currentInvocation
Definition at line 30 of file Invocation.c.
Referenced by _closeIteration(), _destroyJavaVM(), _endOfSetCB(), _updaterCommon(), beginNative(), Exception_throw_ERROR(), Function_currentLoader(), Function_inUse(), Function_isCurrentReadOnly(), getFunction(), Invocation_assertConnect(), Invocation_assertDisconnect(), Invocation_getTypeMap(), Invocation_popBootContext(), Invocation_popInvocation(), Invocation_pushBootContext(), Invocation_pushInvocation(), Invocation_switchToUpperContext(), invokeTrigger(), Java_org_postgresql_pljava_internal_DualState_00024SingleSPIcursorClose__1spiCursorClose(), Java_org_postgresql_pljava_jdbc_Invocation__1clearErrorCondition(), Java_org_postgresql_pljava_jdbc_Invocation__1getCurrent(), Java_org_postgresql_pljava_jdbc_Invocation__1register(), pljava_Function_popFrame(), pljava_Relation_create(), pljava_SingleRowReader_create(), pljava_SQLInputFromTuple_create(), pljava_TriggerData_create(), reserveParameterFrame(), stashCallContext(), and Type_invokeSRF().
s_callLevel
unsigned int s_callLevel = 0 static
Definition at line 28 of file Invocation.c.
Referenced by Invocation_popBootContext(), Invocation_popInvocation(), Invocation_pushBootContext(), Invocation_pushInvocation(), and Java_org_postgresql_pljava_jdbc_Invocation__1getNestingLevel().
s_frameLimits
jshort* s_frameLimits static
Definition at line 43 of file Invocation.c.
Referenced by Invocation_popInvocation(), Invocation_pushInvocation(), and pljava_Invocation_shareFrame().
s_Invocation_onExit
jmethodID s_Invocation_onExit static
Definition at line 27 of file Invocation.c.
Referenced by Invocation_initialize(), and Invocation_popInvocation().
s_primSlot0
jvalue* s_primSlot0 static
Definition at line 42 of file Invocation.c.
Referenced by Invocation_popInvocation(), Invocation_pushInvocation(), and pljava_Invocation_shareFrame().