PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Timestamp.c File Reference
Timestamp.c File Reference
#include <time.h>
#include <postgres.h>
#include <utils/datetime.h>
#include "pljava/Backend.h"
#include "pljava/type/Type_priv.h"
#include "pljava/type/Timestamp.h"
Macros
#define EPOCH_DIFF (((uint32)86400) * (POSTGRES_EPOCH_JDATE - UNIX_EPOCH_JDATE))
Functions
static Type _LocalDateTime_obtain (Oid)
static Type _OffsetDateTime_obtain (Oid)
static int32 Timestamp_getTimeZone_dd (double dt)
static bool _LocalDateTime_canReplaceType (Type self, Type other)
static jvalue _LocalDateTime_coerceDatum (Type self, Datum arg)
static Datum _LocalDateTime_coerceObject (Type self, jobject timestamp)
static bool _OffsetDateTime_canReplaceType (Type self, Type other)
static jvalue _OffsetDateTime_coerceDatum (Type self, Datum arg)
static Datum _OffsetDateTime_coerceObject (Type self, jobject timestamp)
static bool _Timestamp_canReplaceType (Type self, Type other)
static jvalue Timestamp_coerceDatumTZ_id (Type self, Datum arg, bool tzAdjust)
static jvalue Timestamp_coerceDatumTZ_dd (Type self, Datum arg, bool tzAdjust)
static jvalue Timestamp_coerceDatumTZ (Type self, Datum arg, bool tzAdjust)
static Datum Timestamp_coerceObjectTZ_id (Type self, jobject jts, bool tzAdjust)
static Datum Timestamp_coerceObjectTZ_dd (Type self, jobject jts, bool tzAdjust)
static Datum Timestamp_coerceObjectTZ (Type self, jobject jts, bool tzAdjust)
static jvalue _Timestamp_coerceDatum (Type self, Datum arg)
static Datum _Timestamp_coerceObject (Type self, jobject ts)
static bool _Timestamptz_canReplaceType (Type self, Type other)
static jvalue _Timestamptz_coerceDatum (Type self, Datum arg)
static Datum _Timestamptz_coerceObject (Type self, jobject ts)
static int32 Timestamp_getTimeZone (pg_time_t time)
int32 Timestamp_getTimeZone_id (int64 dt)
int32 Timestamp_getCurrentTimeZone (void)
void Timestamp_initialize (void)
Variables
static jclass s_Timestamp_class
static jmethodID s_Timestamp_init
static jmethodID s_Timestamp_getNanos
static jmethodID s_Timestamp_getTime
static jmethodID s_Timestamp_setNanos
static TypeClass s_TimestampClass
static TypeClass s_TimestamptzClass
static TypeClass s_LocalDateTimeClass
static TypeClass s_OffsetDateTimeClass
static Type s_LocalDateTimeInstance
static jclass s_LocalDateTime_class
static jmethodID s_LocalDateTime_ofEpochSecond
static jmethodID s_LocalDateTime_atOffset
static Type s_OffsetDateTimeInstance
static jclass s_OffsetDateTime_class
static jmethodID s_OffsetDateTime_of
static jmethodID s_OffsetDateTime_toEpochSecond
static jmethodID s_OffsetDateTime_getNano
static jobject s_ZoneOffset_UTC
Macro Definition Documentation
EPOCH_DIFF
#define EPOCH_DIFF (((uint32)86400) * (POSTGRES_EPOCH_JDATE - UNIX_EPOCH_JDATE))
Definition at line 24 of file Timestamp.c.
Function Documentation
_LocalDateTime_canReplaceType()
static bool _LocalDateTime_canReplaceType (Type self, Type other) static
Definition at line 101 of file Timestamp.c.
{
    TypeClass cls = Type_getClass(other);
    return Type_getClass(self) == cls  ||  Type_getOid(other) == TIMESTAMPOID;
}
References Type_getClass(), and Type_getOid().
Referenced by Timestamp_initialize().
_LocalDateTime_coerceDatum()
static jvalue _LocalDateTime_coerceDatum (Type self, Datum arg) static
Definition at line 107 of file Timestamp.c.
{
    jint  onlyMicros;
    jlong secs;
    jvalue result;
#if PG_VERSION_NUM < 100000
    if ( !integerDateTimes )
    {
        double fracSecs = DatumGetFloat8(arg);
        secs = (jlong)floor(fracSecs);
        fracSecs -= (double)secs;
        onlyMicros = ((jint)floor(2e6 * fracSecs) + 1) / 2;
    }
    else
#endif
    {
        int64 micros = DatumGetInt64(arg);
        /* Expect number of microseconds since 01 Jan 2000. Tease out a
         * non-negative sub-second microseconds value (whether this C compiler's
         * signed % has trunc or floor behavior). Factor a 2 out right away to
         * avoid wraparound when flooring near the most negative values.
         */
        int lowBit = (int)(micros & 1);
        micros = (micros ^ lowBit) / 2;
        onlyMicros = (jint)(((micros % 500000) + 500000) % 500000);
        secs = (micros - onlyMicros) / 500000;
        onlyMicros = (onlyMicros << 1) | lowBit;
    }
    result.l = JNI_callStaticObjectMethod(s_LocalDateTime_class,
        s_LocalDateTime_ofEpochSecond,
        EPOCH_DIFF + secs, 1000 * onlyMicros, s_ZoneOffset_UTC);
    return result;
}
References EPOCH_DIFF, integerDateTimes, jint(), JNI_callStaticObjectMethod(), s_LocalDateTime_class, s_LocalDateTime_ofEpochSecond, and s_ZoneOffset_UTC.
Referenced by Timestamp_initialize().
_LocalDateTime_coerceObject()
static Datum _LocalDateTime_coerceObject (Type self, jobject timestamp) static
Definition at line 141 of file Timestamp.c.
{
    jobject offsetDateTime = JNI_callObjectMethod(timestamp,
        s_LocalDateTime_atOffset, s_ZoneOffset_UTC);
    Datum result = Type_coerceObject(s_OffsetDateTimeInstance, offsetDateTime);
    JNI_deleteLocalRef(offsetDateTime);
    return result;
}
References JNI_callObjectMethod(), JNI_deleteLocalRef(), s_LocalDateTime_atOffset, s_OffsetDateTimeInstance, s_ZoneOffset_UTC, and Type_coerceObject().
Referenced by Timestamp_initialize().
_LocalDateTime_obtain()
static Type _LocalDateTime_obtain (Oid typeId) static
Definition at line 150 of file Timestamp.c.
{
    if ( NULL == s_LocalDateTimeInstance )
    {
        jclass zoneOffsetCls = PgObject_getJavaClass("java/time/ZoneOffset");
        jfieldID fldUTC = PgObject_getStaticJavaField(
            zoneOffsetCls, "UTC", "Ljava/time/ZoneOffset;");
        s_ZoneOffset_UTC = JNI_newGlobalRef(JNI_getStaticObjectField(
            zoneOffsetCls, fldUTC));
        JNI_deleteLocalRef(zoneOffsetCls);
        s_LocalDateTime_class = JNI_newGlobalRef(PgObject_getJavaClass(
            "java/time/LocalDateTime"));
        s_LocalDateTime_ofEpochSecond = PgObject_getStaticJavaMethod(
            s_LocalDateTime_class, "ofEpochSecond",
            "(JILjava/time/ZoneOffset;)Ljava/time/LocalDateTime;");
        s_LocalDateTime_atOffset = PgObject_getJavaMethod(s_LocalDateTime_class,
            "atOffset", "(Ljava/time/ZoneOffset;)Ljava/time/OffsetDateTime;");
        s_OffsetDateTime_class = JNI_newGlobalRef(PgObject_getJavaClass(
            "java/time/OffsetDateTime"));
        s_OffsetDateTime_toEpochSecond = PgObject_getJavaMethod(
            s_OffsetDateTime_class, "toEpochSecond", "()J");
        s_OffsetDateTime_getNano = PgObject_getJavaMethod(
            s_OffsetDateTime_class, "getNano", "()I");
        s_LocalDateTimeInstance =
            TypeClass_allocInstance(s_LocalDateTimeClass, TIMESTAMPOID);
        if ( NULL == s_OffsetDateTimeInstance )
            _OffsetDateTime_obtain(TIMESTAMPTZOID);
    }
    return s_LocalDateTimeInstance;
}
References _OffsetDateTime_obtain(), JNI_deleteLocalRef(), JNI_getStaticObjectField(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_getStaticJavaField(), PgObject_getStaticJavaMethod(), s_LocalDateTime_atOffset, s_LocalDateTime_class, s_LocalDateTime_ofEpochSecond, s_LocalDateTimeClass, s_LocalDateTimeInstance, s_OffsetDateTime_class, s_OffsetDateTime_getNano, s_OffsetDateTime_toEpochSecond, s_OffsetDateTimeInstance, s_ZoneOffset_UTC, and TypeClass_allocInstance().
Referenced by _OffsetDateTime_obtain(), and Timestamp_initialize().
_OffsetDateTime_canReplaceType()
static bool _OffsetDateTime_canReplaceType (Type self, Type other) static
Definition at line 189 of file Timestamp.c.
{
    TypeClass cls = Type_getClass(other);
    return Type_getClass(self) == cls  ||  Type_getOid(other) == TIMESTAMPTZOID;
}
References Type_getClass(), and Type_getOid().
Referenced by Timestamp_initialize().
_OffsetDateTime_coerceDatum()
static jvalue _OffsetDateTime_coerceDatum (Type self, Datum arg) static
Definition at line 195 of file Timestamp.c.
{
    jvalue localDateTime = Type_coerceDatum(s_LocalDateTimeInstance, arg);
    jvalue result;
    result.l = JNI_callStaticObjectMethod(s_OffsetDateTime_class,
        s_OffsetDateTime_of, localDateTime.l, s_ZoneOffset_UTC);
    JNI_deleteLocalRef(localDateTime.l);
    return result;
}
References JNI_callStaticObjectMethod(), JNI_deleteLocalRef(), s_LocalDateTimeInstance, s_OffsetDateTime_class, s_OffsetDateTime_of, s_ZoneOffset_UTC, and Type_coerceDatum().
Referenced by Timestamp_initialize().
_OffsetDateTime_coerceObject()
static Datum _OffsetDateTime_coerceObject (Type self, jobject timestamp) static
Definition at line 205 of file Timestamp.c.
{
    jlong epochSec = JNI_callLongMethod(
        timestamp, s_OffsetDateTime_toEpochSecond) - EPOCH_DIFF;
    jint nanos = JNI_callIntMethod(timestamp, s_OffsetDateTime_getNano);
    Datum result;
#if PG_VERSION_NUM < 100000
    if ( !integerDateTimes )
    {
        double secs = (double)epochSec + ((double)nanos)/1e9;
        result = Float8GetDatum(secs);
    }
    else
#endif
    {
        result = Int64GetDatum(1000000L * epochSec + nanos / 1000);
    }
    return result;
}
References EPOCH_DIFF, integerDateTimes, jint(), JNI_callIntMethod(), JNI_callLongMethod(), s_OffsetDateTime_getNano, and s_OffsetDateTime_toEpochSecond.
Referenced by Timestamp_initialize().
_OffsetDateTime_obtain()
static Type _OffsetDateTime_obtain (Oid typeId) static
Definition at line 227 of file Timestamp.c.
{
    if ( NULL == s_OffsetDateTimeInstance )
    {
        s_OffsetDateTimeInstance =
            TypeClass_allocInstance(s_OffsetDateTimeClass, TIMESTAMPTZOID);
        if ( NULL == s_LocalDateTimeInstance )
            _LocalDateTime_obtain(TIMESTAMPOID);
        s_OffsetDateTime_of = PgObject_getStaticJavaMethod(
            s_OffsetDateTime_class, "of",
            "(Ljava/time/LocalDateTime;Ljava/time/ZoneOffset;)"
            "Ljava/time/OffsetDateTime;");
    }
    return s_OffsetDateTimeInstance;
}
References _LocalDateTime_obtain(), PgObject_getStaticJavaMethod(), s_LocalDateTimeInstance, s_OffsetDateTime_class, s_OffsetDateTime_of, s_OffsetDateTimeClass, s_OffsetDateTimeInstance, and TypeClass_allocInstance().
Referenced by _LocalDateTime_obtain(), and Timestamp_initialize().
_Timestamp_canReplaceType()
static bool _Timestamp_canReplaceType (Type self, Type other) static
Definition at line 245 of file Timestamp.c.
{
    TypeClass cls = Type_getClass(other);
    return Type_getClass(self) == cls || cls == s_TimestamptzClass;
}
References s_TimestamptzClass, and Type_getClass().
Referenced by Timestamp_initialize().
_Timestamp_coerceDatum()
static jvalue _Timestamp_coerceDatum (Type self, Datum arg) static
Definition at line 372 of file Timestamp.c.
{
    return Timestamp_coerceDatumTZ(self, arg, true);
}
References Timestamp_coerceDatumTZ().
Referenced by Timestamp_initialize().
_Timestamp_coerceObject()
static Datum _Timestamp_coerceObject (Type self, jobject ts) static
Definition at line 377 of file Timestamp.c.
{
    return Timestamp_coerceObjectTZ(self, ts, true);
}
References Timestamp_coerceObjectTZ().
Referenced by Timestamp_initialize().
_Timestamptz_canReplaceType()
static bool _Timestamptz_canReplaceType (Type self, Type other) static
Definition at line 386 of file Timestamp.c.
{
    TypeClass cls = Type_getClass(other);
    return Type_getClass(self) == cls || cls == s_TimestampClass;
}
References s_TimestampClass, and Type_getClass().
Referenced by Timestamp_initialize().
_Timestamptz_coerceDatum()
static jvalue _Timestamptz_coerceDatum (Type self, Datum arg) static
Definition at line 392 of file Timestamp.c.
{
    return Timestamp_coerceDatumTZ(self, arg, false);
}
References Timestamp_coerceDatumTZ().
Referenced by Timestamp_initialize().
_Timestamptz_coerceObject()
static Datum _Timestamptz_coerceObject (Type self, jobject ts) static
Definition at line 397 of file Timestamp.c.
{
    return Timestamp_coerceObjectTZ(self, ts, false);
}
References Timestamp_coerceObjectTZ().
Referenced by Timestamp_initialize().
Timestamp_coerceDatumTZ()
static jvalue Timestamp_coerceDatumTZ (Type self, Datum arg, bool tzAdjust) static
Definition at line 307 of file Timestamp.c.
{
    return
#if PG_VERSION_NUM < 100000
        (!integerDateTimes) ? Timestamp_coerceDatumTZ_dd(self, arg, tzAdjust) :
#endif
        Timestamp_coerceDatumTZ_id(self, arg, tzAdjust);
}
References integerDateTimes, Timestamp_coerceDatumTZ_dd(), and Timestamp_coerceDatumTZ_id().
Referenced by _Timestamp_coerceDatum(), and _Timestamptz_coerceDatum().
Timestamp_coerceDatumTZ_dd()
static jvalue Timestamp_coerceDatumTZ_dd (Type self, Datum arg, bool tzAdjust) static
Definition at line 285 of file Timestamp.c.
{
    jlong secs;
    jint  uSecs;
    jvalue result;
    double ts = DatumGetFloat8(arg);
    int    tz = Timestamp_getTimeZone_dd(ts);
    /* Expect <seconds since Jan 01 2000>.<fractions of seconds>
     */
    if(tzAdjust)
        ts += tz; /* Adjust from local time to UTC */
    ts += EPOCH_DIFF; /* Adjust for diff between Postgres and Java (Unix) */
    secs = (jlong) floor(ts); /* Take just the secs */
    uSecs = (((jint) ((ts - (double)secs) * 2e6)) + 1) / 2; /* Preserve usecs */
    result.l = JNI_newObject(s_Timestamp_class, s_Timestamp_init, secs * 1000);
    if(uSecs != 0)
        JNI_callVoidMethod(result.l, s_Timestamp_setNanos, uSecs * 1000);
    return result;
}
References EPOCH_DIFF, jint(), JNI_callVoidMethod(), JNI_newObject(), s_Timestamp_class, s_Timestamp_init, s_Timestamp_setNanos, and Timestamp_getTimeZone_dd().
Referenced by Timestamp_coerceDatumTZ().
Timestamp_coerceDatumTZ_id()
static jvalue Timestamp_coerceDatumTZ_id (Type self, Datum arg, bool tzAdjust) static
Definition at line 251 of file Timestamp.c.
{
    jvalue result;
    jint  uSecs;
    jlong mSecs;
    int64 ts = DatumGetInt64(arg);
    /* Expect number of microseconds since 01 Jan 2000. Tease out a non-negative
     * sub-second microseconds value (whether this C compiler's signed %
     * has trunc or floor behavior). Factor a 2 out right away to
     * avoid wraparound when flooring near the most negative values.
     */
    int lowBit = (int)(ts & 1);
    ts = (ts ^ lowBit) / 2;
    uSecs = (jint)(((ts % 500000) + 500000) % 500000);
    mSecs = (ts - uSecs) / 500; /* Convert to millisecs */
    uSecs = (uSecs << 1) | lowBit;
    if(tzAdjust)
    {
        int tz = Timestamp_getTimeZone_id(ts); /* function expects halved ts */
        mSecs += tz * 1000; /* Adjust from local time to UTC */
    }
    /* Adjust for diff between Postgres and Java (Unix) */
    mSecs += ((jlong)EPOCH_DIFF) * 1000L;
    result.l = JNI_newObject(s_Timestamp_class, s_Timestamp_init, mSecs);
    if(uSecs != 0)
        JNI_callVoidMethod(result.l, s_Timestamp_setNanos, uSecs * 1000);
    return result;
}
References EPOCH_DIFF, jint(), JNI_callVoidMethod(), JNI_newObject(), s_Timestamp_class, s_Timestamp_init, s_Timestamp_setNanos, and Timestamp_getTimeZone_id().
Referenced by Timestamp_coerceDatumTZ().
Timestamp_coerceObjectTZ()
static Datum Timestamp_coerceObjectTZ (Type self, jobject jts, bool tzAdjust) static
Definition at line 363 of file Timestamp.c.
{
    return
#if PG_VERSION_NUM < 100000
        (!integerDateTimes) ? Timestamp_coerceObjectTZ_dd(self, jts, tzAdjust) :
#endif
        Timestamp_coerceObjectTZ_id(self, jts, tzAdjust);
}
References integerDateTimes, Timestamp_coerceObjectTZ_dd(), and Timestamp_coerceObjectTZ_id().
Referenced by _Timestamp_coerceObject(), and _Timestamptz_coerceObject().
Timestamp_coerceObjectTZ_dd()
static Datum Timestamp_coerceObjectTZ_dd (Type self, jobject jts, bool tzAdjust) static
Definition at line 341 of file Timestamp.c.
{
    double ts;
    jlong mSecs = JNI_callLongMethod(jts, s_Timestamp_getTime);
    jint  nSecs = JNI_callIntMethod(jts, s_Timestamp_getNanos);
    /*
     * getNanos() should have supplied non-negative nSecs, whether mSecs is
     * positive or negative. So mSecs needs to be floor()ed to a multiple of
     * 1000 ms, whether this C compiler does signed integer division with floor
     * or trunc.
     */
    mSecs -= ((mSecs % 1000) + 1000) % 1000;
    ts = ((double)mSecs) / 1000.0; /* Convert to seconds */
    ts -= EPOCH_DIFF;
    if(nSecs != 0)
        ts += ((double)nSecs) / 1000000000.0;   /* Convert to seconds */
    if(tzAdjust)
        ts -= Timestamp_getTimeZone_dd(ts); /* Adjust from UTC to local time */
    return Float8GetDatum(ts);
}
References EPOCH_DIFF, jint(), JNI_callIntMethod(), JNI_callLongMethod(), s_Timestamp_getNanos, s_Timestamp_getTime, and Timestamp_getTimeZone_dd().
Referenced by Timestamp_coerceObjectTZ().
Timestamp_coerceObjectTZ_id()
static Datum Timestamp_coerceObjectTZ_id (Type self, jobject jts, bool tzAdjust) static
Definition at line 316 of file Timestamp.c.
{
    int64 ts;
    int lowBit;
    jlong mSecs = JNI_callLongMethod(jts, s_Timestamp_getTime);
    jint  nSecs = JNI_callIntMethod(jts, s_Timestamp_getNanos);
    /*
     * getNanos() should have supplied non-negative nSecs, whether mSecs is
     * positive or negative. So mSecs needs to be floor()ed to a multiple of
     * 1000 ms, whether this C compiler does signed integer division with floor
     * or trunc.
     */
    mSecs -= ((mSecs % 1000) + 1000) % 1000;
    mSecs -= ((jlong)EPOCH_DIFF) * 1000L;
    ts = mSecs * 500L; /* millisecs to microsecs, save a factor of 2 for now */
    if(tzAdjust) /* Adjust from UTC to local time; function expects halved ts */
        ts -= ((jlong)Timestamp_getTimeZone_id(ts)) * 500000L;
    nSecs /= 1000; /* ok, now they are really microsecs */
    lowBit = nSecs & 1;
    nSecs >>= 1; /* nSecs >= 0 so >> has a defined C result */
    ts = 2 * (ts + nSecs) | lowBit;
    return Int64GetDatum(ts);
}
References EPOCH_DIFF, jint(), JNI_callIntMethod(), JNI_callLongMethod(), s_Timestamp_getNanos, s_Timestamp_getTime, and Timestamp_getTimeZone_id().
Referenced by Timestamp_coerceObjectTZ().
Timestamp_getCurrentTimeZone()
int32 Timestamp_getCurrentTimeZone (void)
Definition at line 444 of file Timestamp.c.
{
    return Timestamp_getTimeZone((pg_time_t)time(NULL));
}
References Timestamp_getTimeZone().
Referenced by _Timetz_coerceObject(), Time_coerceDatumTZ_dd(), Time_coerceDatumTZ_id(), and Time_getMillisecsToday().
Timestamp_getTimeZone()
static int32 Timestamp_getTimeZone (pg_time_t time) static
Definition at line 406 of file Timestamp.c.
{
    struct pg_tm* tx = pg_localtime(&time, session_timezone);
    if ( NULL == tx )
        ereport(ERROR, (
            errcode(ERRCODE_DATA_EXCEPTION),
            errmsg("could not resolve timestamp: %m")
        ));
    return -(int32)tx->tm_gmtoff;
}
Referenced by Timestamp_getCurrentTimeZone(), Timestamp_getTimeZone_dd(), and Timestamp_getTimeZone_id().
Timestamp_getTimeZone_dd()
static int32 Timestamp_getTimeZone_dd (double dt) static
Definition at line 429 of file Timestamp.c.
{
    if ( TIMESTAMP_NOT_FINITE(dt) )
    {
        errno = EOVERFLOW;
        ereport(ERROR, (
            errcode(ERRCODE_DATA_EXCEPTION),
            errmsg("could not resolve timestamp: %m")
        ));
    }
    return Timestamp_getTimeZone(
        (pg_time_t)rint(dt + (POSTGRES_EPOCH_JDATE - UNIX_EPOCH_JDATE) * 86400));
}
References Timestamp_getTimeZone().
Referenced by Timestamp_coerceDatumTZ_dd(), and Timestamp_coerceObjectTZ_dd().
Timestamp_getTimeZone_id()
int32 Timestamp_getTimeZone_id (int64 dt)
Definition at line 421 of file Timestamp.c.
{
    return Timestamp_getTimeZone(
        dt / INT64CONST(500000) +
        (POSTGRES_EPOCH_JDATE - UNIX_EPOCH_JDATE) * 86400
    );
}
References Timestamp_getTimeZone().
Referenced by _Date_coerceDatum(), _Date_coerceObject(), Timestamp_coerceDatumTZ_id(), and Timestamp_coerceObjectTZ_id().
Timestamp_initialize()
void Timestamp_initialize (void) extern
Definition at line 450 of file Timestamp.c.
{
    TypeClass cls;
    s_Timestamp_class = JNI_newGlobalRef(PgObject_getJavaClass("java/sql/Timestamp"));
    s_Timestamp_init = PgObject_getJavaMethod(s_Timestamp_class, "<init>", "(J)V");
    s_Timestamp_getNanos = PgObject_getJavaMethod(s_Timestamp_class, "getNanos", "()I");
    s_Timestamp_getTime  = PgObject_getJavaMethod(s_Timestamp_class, "getTime",  "()J");
    s_Timestamp_setNanos = PgObject_getJavaMethod(s_Timestamp_class, "setNanos", "(I)V");
    cls = TypeClass_alloc("type.Timestamp");
    cls->JNISignature   = "Ljava/sql/Timestamp;";
    cls->javaTypeName   = "java.sql.Timestamp";
    cls->canReplaceType = _Timestamp_canReplaceType;
    cls->coerceDatum    = _Timestamp_coerceDatum;
    cls->coerceObject   = _Timestamp_coerceObject;
    Type_registerType(0, TypeClass_allocInstance(cls, TIMESTAMPOID));
    s_TimestampClass = cls;
    cls = TypeClass_alloc("type.Timestamptz");
    cls->JNISignature   = "Ljava/sql/Timestamp;";
    cls->javaTypeName   = "java.sql.Timestamp";
    cls->canReplaceType = _Timestamptz_canReplaceType;
    cls->coerceDatum    = _Timestamptz_coerceDatum;
    cls->coerceObject   = _Timestamptz_coerceObject;
    Type_registerType("java.sql.Timestamp", TypeClass_allocInstance(cls, TIMESTAMPTZOID));
    s_TimestamptzClass = cls;
    cls = TypeClass_alloc("type.LocalDateTime");
    cls->JNISignature = "Ljava/time/LocalDateTime;";
    cls->javaTypeName = "java.time.LocalDateTime";
    cls->coerceDatum  = _LocalDateTime_coerceDatum;
    cls->coerceObject = _LocalDateTime_coerceObject;
    cls->canReplaceType = _LocalDateTime_canReplaceType;
    s_LocalDateTimeClass  = cls;
    Type_registerType2(InvalidOid, "java.time.LocalDateTime",
        _LocalDateTime_obtain);
    cls = TypeClass_alloc("type.OffsetDateTime");
    cls->JNISignature = "Ljava/time/OffsetDateTime;";
    cls->javaTypeName = "java.time.OffsetDateTime";
    cls->coerceDatum  = _OffsetDateTime_coerceDatum;
    cls->coerceObject = _OffsetDateTime_coerceObject;
    cls->canReplaceType = _OffsetDateTime_canReplaceType;
    s_OffsetDateTimeClass  = cls;
    Type_registerType2(InvalidOid, "java.time.OffsetDateTime",
        _OffsetDateTime_obtain);
}
References _LocalDateTime_canReplaceType(), _LocalDateTime_coerceDatum(), _LocalDateTime_coerceObject(), _LocalDateTime_obtain(), _OffsetDateTime_canReplaceType(), _OffsetDateTime_coerceDatum(), _OffsetDateTime_coerceObject(), _OffsetDateTime_obtain(), _Timestamp_canReplaceType(), _Timestamp_coerceDatum(), _Timestamp_coerceObject(), _Timestamptz_canReplaceType(), _Timestamptz_coerceDatum(), _Timestamptz_coerceObject(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_LocalDateTimeClass, s_OffsetDateTimeClass, s_Timestamp_class, s_Timestamp_getNanos, s_Timestamp_getTime, s_Timestamp_init, s_Timestamp_setNanos, s_TimestampClass, s_TimestamptzClass, Type_registerType(), Type_registerType2(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Variable Documentation
s_LocalDateTime_atOffset
jmethodID s_LocalDateTime_atOffset static
Definition at line 82 of file Timestamp.c.
Referenced by _LocalDateTime_coerceObject(), and _LocalDateTime_obtain().
s_LocalDateTime_class
jclass s_LocalDateTime_class static
Definition at line 80 of file Timestamp.c.
Referenced by _LocalDateTime_coerceDatum(), and _LocalDateTime_obtain().
s_LocalDateTime_ofEpochSecond
jmethodID s_LocalDateTime_ofEpochSecond static
Definition at line 81 of file Timestamp.c.
Referenced by _LocalDateTime_coerceDatum(), and _LocalDateTime_obtain().
s_LocalDateTimeClass
TypeClass s_LocalDateTimeClass static
Definition at line 73 of file Timestamp.c.
Referenced by _LocalDateTime_obtain(), and Timestamp_initialize().
s_LocalDateTimeInstance
Type s_LocalDateTimeInstance static
Definition at line 79 of file Timestamp.c.
Referenced by _LocalDateTime_obtain(), _OffsetDateTime_coerceDatum(), and _OffsetDateTime_obtain().
s_OffsetDateTime_class
jclass s_OffsetDateTime_class static
Definition at line 84 of file Timestamp.c.
Referenced by _LocalDateTime_obtain(), _OffsetDateTime_coerceDatum(), and _OffsetDateTime_obtain().
s_OffsetDateTime_getNano
jmethodID s_OffsetDateTime_getNano static
Definition at line 87 of file Timestamp.c.
Referenced by _LocalDateTime_obtain(), and _OffsetDateTime_coerceObject().
s_OffsetDateTime_of
jmethodID s_OffsetDateTime_of static
Definition at line 85 of file Timestamp.c.
Referenced by _OffsetDateTime_coerceDatum(), and _OffsetDateTime_obtain().
s_OffsetDateTime_toEpochSecond
jmethodID s_OffsetDateTime_toEpochSecond static
Definition at line 86 of file Timestamp.c.
Referenced by _LocalDateTime_obtain(), and _OffsetDateTime_coerceObject().
s_OffsetDateTimeClass
TypeClass s_OffsetDateTimeClass static
Definition at line 74 of file Timestamp.c.
Referenced by _OffsetDateTime_obtain(), and Timestamp_initialize().
s_OffsetDateTimeInstance
Type s_OffsetDateTimeInstance static
Definition at line 83 of file Timestamp.c.
Referenced by _LocalDateTime_coerceObject(), _LocalDateTime_obtain(), and _OffsetDateTime_obtain().
s_Timestamp_class
jclass s_Timestamp_class static
Definition at line 64 of file Timestamp.c.
Referenced by Timestamp_coerceDatumTZ_dd(), Timestamp_coerceDatumTZ_id(), and Timestamp_initialize().
s_Timestamp_getNanos
jmethodID s_Timestamp_getNanos static
Definition at line 66 of file Timestamp.c.
Referenced by Timestamp_coerceObjectTZ_dd(), Timestamp_coerceObjectTZ_id(), and Timestamp_initialize().
s_Timestamp_getTime
jmethodID s_Timestamp_getTime static
Definition at line 67 of file Timestamp.c.
Referenced by Timestamp_coerceObjectTZ_dd(), Timestamp_coerceObjectTZ_id(), and Timestamp_initialize().
s_Timestamp_init
jmethodID s_Timestamp_init static
Definition at line 65 of file Timestamp.c.
Referenced by Timestamp_coerceDatumTZ_dd(), Timestamp_coerceDatumTZ_id(), and Timestamp_initialize().
s_Timestamp_setNanos
jmethodID s_Timestamp_setNanos static
Definition at line 68 of file Timestamp.c.
Referenced by Timestamp_coerceDatumTZ_dd(), Timestamp_coerceDatumTZ_id(), and Timestamp_initialize().
s_TimestampClass
TypeClass s_TimestampClass static
Definition at line 70 of file Timestamp.c.
Referenced by _Timestamptz_canReplaceType(), and Timestamp_initialize().
s_TimestamptzClass
TypeClass s_TimestamptzClass static
Definition at line 71 of file Timestamp.c.
Referenced by _Timestamp_canReplaceType(), and Timestamp_initialize().
s_ZoneOffset_UTC
jobject s_ZoneOffset_UTC static
Definition at line 88 of file Timestamp.c.
Referenced by _LocalDateTime_coerceDatum(), _LocalDateTime_coerceObject(), _LocalDateTime_obtain(), and _OffsetDateTime_coerceDatum().