PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/Session.c File Reference
Session.c File Reference
#include <postgres.h>
#include <miscadmin.h>
#include "org_postgresql_pljava_internal_Session.h"
#include "pljava/Session.h"
#include "pljava/type/AclId.h"
Functions
void Session_initialize (void)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_Session__1setUser (JNIEnv *env, jclass cls, jobject aclId, jboolean isLocalChange)
Function Documentation
Java_org_postgresql_pljava_internal_Session__1setUser()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_Session__1setUser (JNIEnv * env, jclass cls, jobject aclId, jboolean isLocalChange)
Definition at line 42 of file Session.c.
{
    bool wasLocalChange = false;
    int secContext;
    Oid dummy;
    /* No error checking since this might be a restore of user in
     * a finally block after an exception.
     */
    BEGIN_NATIVE_NO_ERRCHECK
    if (InSecurityRestrictedOperation())
        ereport(ERROR,  (errcode(ERRCODE_INSUFFICIENT_PRIVILEGE), errmsg(
            "cannot set parameter \"%s\" within security-restricted operation",
            "role")));
    GetUserIdAndSecContext(&dummy, &secContext);
    wasLocalChange = 0 != ( secContext & SECURITY_LOCAL_USERID_CHANGE );
    if ( isLocalChange )
        secContext |= SECURITY_LOCAL_USERID_CHANGE;
    else
        secContext &= ~SECURITY_LOCAL_USERID_CHANGE;
    SetUserIdAndSecContext(AclId_getAclId(aclId), secContext);
    END_NATIVE
    return wasLocalChange ? JNI_TRUE : JNI_FALSE;
}
References AclId_getAclId().
Referenced by Session_initialize().
Session_initialize()
void Session_initialize (void) extern
Definition at line 20 of file Session.c.
{
    JNINativeMethod methods[] = {
        {
        "_setUser",
        "(Lorg/postgresql/pljava/internal/AclId;Z)Z",
        Java_org_postgresql_pljava_internal_Session__1setUser
        },
        { 0, 0, 0 }};
    PgObject_registerNatives("org/postgresql/pljava/internal/Session", methods);
}
References Java_org_postgresql_pljava_internal_Session__1setUser(), and PgObject_registerNatives().
Referenced by initPLJavaClasses().