PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Short.c File Reference
Short.c File Reference
#include "pljava/type/Type_priv.h"
#include "pljava/type/Array.h"
#include "pljava/Invocation.h"
Functions
static Datum _short_invoke (Type self, Function fn, PG_FUNCTION_ARGS)
static jvalue _short_coerceDatum (Type self, Datum arg)
static jvalue _shortArray_coerceDatum (Type self, Datum arg)
static Datum _shortArray_coerceObject (Type self, jobject shortArray)
static bool _Short_canReplace (Type self, Type other)
static jvalue _Short_coerceDatum (Type self, Datum arg)
static Datum _Short_coerceObject (Type self, jobject shortObj)
static Type _short_createArrayType (Type self, Oid arrayTypeId)
void Short_initialize (void)
Variables
static TypeClass s_shortClass
static jclass s_Short_class
static jmethodID s_Short_init
static jmethodID s_Short_shortValue
Function Documentation
_Short_canReplace()
static bool _Short_canReplace (Type self, Type other) static
Definition at line 88 of file Short.c.
{
    TypeClass cls = Type_getClass(other);
    return Type_getClass(self) == cls || cls == s_shortClass;
}
References s_shortClass, and Type_getClass().
Referenced by Short_initialize().
_short_coerceDatum()
static jvalue _short_coerceDatum (Type self, Datum arg) static
Definition at line 32 of file Short.c.
{
    jvalue result;
    result.s = DatumGetInt16(arg);
    return result;
}
Referenced by Short_initialize().
_Short_coerceDatum()
static jvalue _Short_coerceDatum (Type self, Datum arg) static
Definition at line 94 of file Short.c.
{
    jvalue result;
    result.l = JNI_newObject(s_Short_class, s_Short_init, DatumGetInt16(arg));
    return result;
}
References JNI_newObject(), s_Short_class, and s_Short_init.
Referenced by Short_initialize().
_Short_coerceObject()
static Datum _Short_coerceObject (Type self, jobject shortObj) static
Definition at line 101 of file Short.c.
{
    return Int16GetDatum(shortObj == 0 ? 0 : JNI_callShortMethod(shortObj, s_Short_shortValue));
}
References JNI_callShortMethod(), and s_Short_shortValue.
Referenced by Short_initialize().
_short_createArrayType()
static Type _short_createArrayType (Type self, Oid arrayTypeId) static
Definition at line 106 of file Short.c.
{
    return Array_fromOid2(arrayTypeId, self, _shortArray_coerceDatum, _shortArray_coerceObject);
}
References _shortArray_coerceDatum(), _shortArray_coerceObject(), and Array_fromOid2().
Referenced by Short_initialize().
_short_invoke()
static Datum _short_invoke (Type self, Function fn, PG_FUNCTION_ARGS) static
Definition at line 26 of file Short.c.
{
    jshort v = pljava_Function_shortInvoke(fn);
    return Int16GetDatum(v);
}
References pljava_Function_shortInvoke().
Referenced by Short_initialize().
_shortArray_coerceDatum()
static jvalue _shortArray_coerceDatum (Type self, Datum arg) static
Definition at line 39 of file Short.c.
{
    jvalue     result;
    ArrayType* v      = DatumGetArrayTypeP(arg);
    jsize      nElems = (jsize)ArrayGetNItems(ARR_NDIM(v), ARR_DIMS(v));
    jshortArray shortArray = JNI_newShortArray(nElems);
    if(ARR_HASNULL(v))
    {
        jsize idx;
        jboolean isCopy = JNI_FALSE;
        bits8* nullBitMap = ARR_NULLBITMAP(v);
        jshort* values = (jshort*)ARR_DATA_PTR(v);
        jshort* elems  = JNI_getShortArrayElements(shortArray, &isCopy);
        for(idx = 0; idx < nElems; ++idx)
        {
            if(arrayIsNull(nullBitMap, idx))
                elems[idx] = 0;
            else
                elems[idx] = *values++;
        }
        JNI_releaseShortArrayElements(shortArray, elems, JNI_COMMIT);
    }
    else
        JNI_setShortArrayRegion(shortArray, 0, nElems, (jshort*)ARR_DATA_PTR(v));
    result.l = (jobject)shortArray;
    return result;
}
References arrayIsNull(), JNI_getShortArrayElements(), JNI_newShortArray(), JNI_releaseShortArrayElements(), and JNI_setShortArrayRegion().
Referenced by _short_createArrayType().
_shortArray_coerceObject()
static Datum _shortArray_coerceObject (Type self, jobject shortArray) static
Definition at line 68 of file Short.c.
{
    ArrayType* v;
    jsize nElems;
    if(shortArray == 0)
        return 0;
    nElems = JNI_getArrayLength((jarray)shortArray);
    v = createArrayType(nElems, sizeof(jshort), INT2OID, false);
    JNI_getShortArrayRegion(
            (jshortArray)shortArray, 0, nElems, (jshort*)ARR_DATA_PTR(v));
    PG_RETURN_ARRAYTYPE_P(v);
}
References createArrayType(), JNI_getArrayLength(), and JNI_getShortArrayRegion().
Referenced by _short_createArrayType().
Short_initialize()
void Short_initialize (void) extern
Definition at line 114 of file Short.c.
{
    Type t_short;
    Type t_Short;
    TypeClass cls;
    s_Short_class = JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Short"));
    s_Short_init = PgObject_getJavaMethod(s_Short_class, "<init>", "(S)V");
    s_Short_shortValue = PgObject_getJavaMethod(s_Short_class, "shortValue", "()S");
    cls = TypeClass_alloc("type.Short");
    cls->canReplaceType = _Short_canReplace;
    cls->JNISignature = "Ljava/lang/Short;";
    cls->javaTypeName = "java.lang.Short";
    cls->coerceDatum  = _Short_coerceDatum;
    cls->coerceObject = _Short_coerceObject;
    t_Short = TypeClass_allocInstance(cls, INT2OID);
    cls = TypeClass_alloc("type.short");
    cls->JNISignature = "S";
    cls->javaTypeName = "short";
    cls->invoke       = _short_invoke;
    cls->coerceDatum  = _short_coerceDatum;
    cls->coerceObject = _Short_coerceObject;
    cls->createArrayType = _short_createArrayType;
    s_shortClass = cls;
    t_short = TypeClass_allocInstance(cls, INT2OID);
    t_short->objectType = t_Short;
    Type_registerType("short", t_short);
    Type_registerType("java.lang.Short", t_Short);
}
References _Short_canReplace(), _short_coerceDatum(), _Short_coerceDatum(), _Short_coerceObject(), _short_createArrayType(), _short_invoke(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Short_class, s_Short_init, s_Short_shortValue, s_shortClass, Type, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Variable Documentation
s_Short_class
jclass s_Short_class static
Definition at line 19 of file Short.c.
Referenced by _Short_coerceDatum(), and Short_initialize().
s_Short_init
jmethodID s_Short_init static
Definition at line 20 of file Short.c.
Referenced by _Short_coerceDatum(), and Short_initialize().
s_Short_shortValue
jmethodID s_Short_shortValue static
Definition at line 21 of file Short.c.
Referenced by _Short_coerceObject(), and Short_initialize().
s_shortClass
TypeClass s_shortClass static
Definition at line 18 of file Short.c.
Referenced by _Short_canReplace(), and Short_initialize().