PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/DualState.c File Reference
DualState.c File Reference
#include "org_postgresql_pljava_internal_DualState_SinglePfree.h"
#include "org_postgresql_pljava_internal_DualState_SingleMemContextDelete.h"
#include "org_postgresql_pljava_internal_DualState_SingleFreeTupleDesc.h"
#include "org_postgresql_pljava_internal_DualState_SingleHeapFreeTuple.h"
#include "org_postgresql_pljava_internal_DualState_SingleFreeErrorData.h"
#include "org_postgresql_pljava_internal_DualState_SingleSPIfreeplan.h"
#include "org_postgresql_pljava_internal_DualState_SingleSPIcursorClose.h"
#include "pljava/DualState.h"
#include "pljava/Backend.h"
#include "pljava/Exception.h"
#include "pljava/Invocation.h"
#include "pljava/PgObject.h"
#include "pljava/JNICalls.h"
#include "pljava/SPI.h"
#include "pljava/type/ErrorData.h"
#include "pljava/type/Portal.h"
#include "pljava/type/Relation.h"
#include "pljava/type/SingleRowReader.h"
#include "pljava/type/TriggerData.h"
#include "pljava/type/Tuple.h"
#include "pljava/type/TupleDesc.h"
#include "pljava/SQLInputFromTuple.h"
#include "pljava/VarlenaWrapper.h"
Functions
void pljava_ExecutionPlan_initialize (void)
static void resourceReleaseCB (ResourceReleasePhase phase, bool isCommit, bool isTopLevel, void *arg)
jobject pljava_DualState_key (void)
void pljava_DualState_cleanEnqueuedInstances (void)
void pljava_DualState_nativeRelease (void *ro)
void pljava_DualState_initialize (void)
void pljava_DualState_unregister (void)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_DualState_00024SinglePfree__1pfree (JNIEnv *env, jobject _this, jlong pointer)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_DualState_00024SingleMemContextDelete__1memContextDelete (JNIEnv *env, jobject _this, jlong pointer)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_DualState_00024SingleFreeTupleDesc__1freeTupleDesc (JNIEnv *env, jobject _this, jlong pointer)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_DualState_00024SingleHeapFreeTuple__1heapFreeTuple (JNIEnv *env, jobject _this, jlong pointer)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_DualState_00024SingleFreeErrorData__1freeErrorData (JNIEnv *env, jobject _this, jlong pointer)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_DualState_00024SingleSPIfreeplan__1spiFreePlan (JNIEnv *env, jobject _this, jlong pointer)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_DualState_00024SingleSPIcursorClose__1spiCursorClose (JNIEnv *env, jobject _this, jlong pointer)
Variables
static jclass s_DualState_class
static jmethodID s_DualState_resourceOwnerRelease
static jmethodID s_DualState_cleanEnqueuedInstances
static jobject s_DualState_key
Function Documentation
Java_org_postgresql_pljava_internal_DualState_00024SingleFreeErrorData__1freeErrorData()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_DualState_00024SingleFreeErrorData__1freeErrorData (JNIEnv * env, jobject _this, jlong pointer)
Definition at line 355 of file DualState.c.
{
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2l;
    p2l.longVal = pointer;
    FreeErrorData(p2l.ptrVal);
    END_NATIVE
}
Referenced by pljava_DualState_initialize().
Java_org_postgresql_pljava_internal_DualState_00024SingleFreeTupleDesc__1freeTupleDesc()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_DualState_00024SingleFreeTupleDesc__1freeTupleDesc (JNIEnv * env, jobject _this, jlong pointer)
Definition at line 319 of file DualState.c.
{
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2l;
    p2l.longVal = pointer;
    FreeTupleDesc(p2l.ptrVal);
    END_NATIVE
}
Referenced by pljava_DualState_initialize().
Java_org_postgresql_pljava_internal_DualState_00024SingleHeapFreeTuple__1heapFreeTuple()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_DualState_00024SingleHeapFreeTuple__1heapFreeTuple (JNIEnv * env, jobject _this, jlong pointer)
Definition at line 337 of file DualState.c.
{
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2l;
    p2l.longVal = pointer;
    heap_freetuple(p2l.ptrVal);
    END_NATIVE
}
Referenced by pljava_DualState_initialize().
Java_org_postgresql_pljava_internal_DualState_00024SingleMemContextDelete__1memContextDelete()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_DualState_00024SingleMemContextDelete__1memContextDelete (JNIEnv * env, jobject _this, jlong pointer)
Definition at line 301 of file DualState.c.
{
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2l;
    p2l.longVal = pointer;
    MemoryContextDelete(p2l.ptrVal);
    END_NATIVE
}
Referenced by pljava_DualState_initialize().
Java_org_postgresql_pljava_internal_DualState_00024SinglePfree__1pfree()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_DualState_00024SinglePfree__1pfree (JNIEnv * env, jobject _this, jlong pointer)
Definition at line 283 of file DualState.c.
{
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2l;
    p2l.longVal = pointer;
    pfree(p2l.ptrVal);
    END_NATIVE
}
Referenced by pljava_DualState_initialize().
Java_org_postgresql_pljava_internal_DualState_00024SingleSPIcursorClose__1spiCursorClose()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_DualState_00024SingleSPIcursorClose__1spiCursorClose (JNIEnv * env, jobject _this, jlong pointer)
Definition at line 399 of file DualState.c.
{
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2l;
    p2l.longVal = pointer;
    PG_TRY();
    {
        /*
         * This code copied from its former location in Portal.c, for reasons
         * not really explained there, is different from most of the other
         * javaStateReleased actions here, by virtue of being conditional; it
         * does nothing if the current Invocation's errorOccurred flag is set,
         * or during an end-of-expression-context callback from the executor.
         */
        if ( NULL != currentInvocation && ! currentInvocation->errorOccurred
            && ! currentInvocation->inExprContextCB )
            SPI_cursor_close(p2l.ptrVal);
    }
    PG_CATCH();
    {
        Exception_throw_ERROR("SPI_cursor_close");
    }
    PG_END_TRY();
    END_NATIVE
}
References currentInvocation, and Exception_throw_ERROR().
Referenced by pljava_DualState_initialize().
Java_org_postgresql_pljava_internal_DualState_00024SingleSPIfreeplan__1spiFreePlan()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_DualState_00024SingleSPIfreeplan__1spiFreePlan (JNIEnv * env, jobject _this, jlong pointer)
Definition at line 373 of file DualState.c.
{
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2l;
    p2l.longVal = pointer;
    PG_TRY();
    {
        SPI_freeplan(p2l.ptrVal);
    }
    PG_CATCH();
    {
        Exception_throw_ERROR("SPI_freeplan");
    }
    PG_END_TRY();
    END_NATIVE
}
References Exception_throw_ERROR().
Referenced by pljava_DualState_initialize().
pljava_DualState_cleanEnqueuedInstances()
void pljava_DualState_cleanEnqueuedInstances (void)
Definition at line 72 of file DualState.c.
{
    JNI_callStaticVoidMethodLocked(s_DualState_class,
                                   s_DualState_cleanEnqueuedInstances);
}
References JNI_callStaticVoidMethodLocked(), s_DualState_class, and s_DualState_cleanEnqueuedInstances.
Referenced by Invocation_popInvocation(), and Java_org_postgresql_pljava_internal_Portal__1fetch().
pljava_DualState_initialize()
void pljava_DualState_initialize (void)
Definition at line 107 of file DualState.c.
{
    jclass clazz;
    jmethodID ctor;
    JNINativeMethod singlePfreeMethods[] =
    {
        {
        "_pfree",
        "(J)V",
        Java_org_postgresql_pljava_internal_DualState_00024SinglePfree__1pfree
        },
        { 0, 0, 0 }
    };
    JNINativeMethod singleMemContextDeleteMethods[] =
    {
        {
        "_memContextDelete",
        "(J)V",
        Java_org_postgresql_pljava_internal_DualState_00024SingleMemContextDelete__1memContextDelete
        },
        { 0, 0, 0 }
    };
    JNINativeMethod singleFreeTupleDescMethods[] =
    {
        {
        "_freeTupleDesc",
        "(J)V",
        Java_org_postgresql_pljava_internal_DualState_00024SingleFreeTupleDesc__1freeTupleDesc
        },
        { 0, 0, 0 }
    };
    JNINativeMethod singleHeapFreeTupleMethods[] =
    {
        {
        "_heapFreeTuple",
        "(J)V",
        Java_org_postgresql_pljava_internal_DualState_00024SingleHeapFreeTuple__1heapFreeTuple
        },
        { 0, 0, 0 }
    };
    JNINativeMethod singleFreeErrorDataMethods[] =
    {
        {
        "_freeErrorData",
        "(J)V",
        Java_org_postgresql_pljava_internal_DualState_00024SingleFreeErrorData__1freeErrorData
        },
        { 0, 0, 0 }
    };
    JNINativeMethod singleSPIfreeplanMethods[] =
    {
        {
        "_spiFreePlan",
        "(J)V",
        Java_org_postgresql_pljava_internal_DualState_00024SingleSPIfreeplan__1spiFreePlan
        },
        { 0, 0, 0 }
    };
    JNINativeMethod singleSPIcursorCloseMethods[] =
    {
        {
        "_spiCursorClose",
        "(J)V",
        Java_org_postgresql_pljava_internal_DualState_00024SingleSPIcursorClose__1spiCursorClose
        },
        { 0, 0, 0 }
    };
    s_DualState_class = (jclass)JNI_newGlobalRef(PgObject_getJavaClass(
        "org/postgresql/pljava/internal/DualState"));
    s_DualState_resourceOwnerRelease = PgObject_getStaticJavaMethod(
        s_DualState_class, "resourceOwnerRelease", "(J)V");
    s_DualState_cleanEnqueuedInstances = PgObject_getStaticJavaMethod(
        s_DualState_class, "cleanEnqueuedInstances", "()V");
    clazz = (jclass)PgObject_getJavaClass(
        "org/postgresql/pljava/internal/DualState$Key");
    ctor = PgObject_getJavaMethod(clazz, "<init>", "()V");
    s_DualState_key = JNI_newGlobalRef(JNI_newObject(clazz, ctor));
    JNI_deleteLocalRef(clazz);
    clazz = (jclass)PgObject_getJavaClass(
        "org/postgresql/pljava/internal/DualState$SinglePfree");
    PgObject_registerNatives2(clazz, singlePfreeMethods);
    JNI_deleteLocalRef(clazz);
    clazz = (jclass)PgObject_getJavaClass(
        "org/postgresql/pljava/internal/DualState$SingleMemContextDelete");
    PgObject_registerNatives2(clazz, singleMemContextDeleteMethods);
    JNI_deleteLocalRef(clazz);
    clazz = (jclass)PgObject_getJavaClass(
        "org/postgresql/pljava/internal/DualState$SingleFreeTupleDesc");
    PgObject_registerNatives2(clazz, singleFreeTupleDescMethods);
    JNI_deleteLocalRef(clazz);
    clazz = (jclass)PgObject_getJavaClass(
        "org/postgresql/pljava/internal/DualState$SingleHeapFreeTuple");
    PgObject_registerNatives2(clazz, singleHeapFreeTupleMethods);
    JNI_deleteLocalRef(clazz);
    clazz = (jclass)PgObject_getJavaClass(
        "org/postgresql/pljava/internal/DualState$SingleFreeErrorData");
    PgObject_registerNatives2(clazz, singleFreeErrorDataMethods);
    JNI_deleteLocalRef(clazz);
    clazz = (jclass)PgObject_getJavaClass(
        "org/postgresql/pljava/internal/DualState$SingleSPIfreeplan");
    PgObject_registerNatives2(clazz, singleSPIfreeplanMethods);
    JNI_deleteLocalRef(clazz);
    clazz = (jclass)PgObject_getJavaClass(
        "org/postgresql/pljava/internal/DualState$SingleSPIcursorClose");
    PgObject_registerNatives2(clazz, singleSPIcursorCloseMethods);
    JNI_deleteLocalRef(clazz);
    RegisterResourceReleaseCallback(resourceReleaseCB, NULL);
    /*
     * Call initialize() methods of known classes built upon DualState.
     */
    pljava_ErrorData_initialize();
    pljava_ExecutionPlan_initialize();
    pljava_Portal_initialize();
    pljava_Relation_initialize();
    pljava_SingleRowReader_initialize();
    pljava_SQLInputFromTuple_initialize();
    pljava_TriggerData_initialize();
    pljava_TupleDesc_initialize();
    pljava_Tuple_initialize();
    pljava_VarlenaWrapper_initialize();
}
References Java_org_postgresql_pljava_internal_DualState_00024SingleFreeErrorData__1freeErrorData(), Java_org_postgresql_pljava_internal_DualState_00024SingleFreeTupleDesc__1freeTupleDesc(), Java_org_postgresql_pljava_internal_DualState_00024SingleHeapFreeTuple__1heapFreeTuple(), Java_org_postgresql_pljava_internal_DualState_00024SingleMemContextDelete__1memContextDelete(), Java_org_postgresql_pljava_internal_DualState_00024SinglePfree__1pfree(), Java_org_postgresql_pljava_internal_DualState_00024SingleSPIcursorClose__1spiCursorClose(), Java_org_postgresql_pljava_internal_DualState_00024SingleSPIfreeplan__1spiFreePlan(), JNI_deleteLocalRef(), JNI_newGlobalRef(), JNI_newObject(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_getStaticJavaMethod(), PgObject_registerNatives2(), pljava_ErrorData_initialize(), pljava_ExecutionPlan_initialize(), pljava_Portal_initialize(), pljava_Relation_initialize(), pljava_SingleRowReader_initialize(), pljava_SQLInputFromTuple_initialize(), pljava_TriggerData_initialize(), pljava_Tuple_initialize(), pljava_TupleDesc_initialize(), pljava_VarlenaWrapper_initialize(), resourceReleaseCB(), s_DualState_class, s_DualState_cleanEnqueuedInstances, s_DualState_key, and s_DualState_resourceOwnerRelease.
Referenced by initPLJavaClasses().
pljava_DualState_key()
jobject pljava_DualState_key (void)
Definition at line 60 of file DualState.c.
{
    return s_DualState_key;
}
References s_DualState_key.
Referenced by Java_org_postgresql_pljava_internal_ExecutionPlan__1prepare(), pljava_ErrorData_getCurrentError(), pljava_Portal_create(), pljava_Relation_create(), pljava_SingleRowReader_create(), pljava_SQLInputFromTuple_create(), pljava_TriggerData_create(), pljava_Tuple_internalCreate(), pljava_TupleDesc_internalCreate(), pljava_VarlenaWrapper_adopt(), pljava_VarlenaWrapper_Input(), and pljava_VarlenaWrapper_Output().
pljava_DualState_nativeRelease()
void pljava_DualState_nativeRelease (void * ro)
Definition at line 89 of file DualState.c.
{
    Ptr2Long p2l;
    /*
     * This static assertion does not need to be in every file
     * that uses Ptr2Long, but it should be somewhere once, so here it is.
     */
    StaticAssertStmt(sizeof p2l.ptrVal <= sizeof p2l.longVal,
                     "Pointer will not fit in long on this platform");
    p2l.longVal = 0L;
    p2l.ptrVal = ro;
    JNI_callStaticVoidMethodLocked(s_DualState_class,
                                   s_DualState_resourceOwnerRelease,
                                   p2l.longVal);
}
References JNI_callStaticVoidMethodLocked(), s_DualState_class, and s_DualState_resourceOwnerRelease.
Referenced by Invocation_popInvocation(), and resourceReleaseCB().
pljava_DualState_unregister()
void pljava_DualState_unregister (void)
Definition at line 247 of file DualState.c.
{
    UnregisterResourceReleaseCallback(resourceReleaseCB, NULL);
}
References resourceReleaseCB().
Referenced by initsequencer(), and onJVMExitOrAbort().
pljava_ExecutionPlan_initialize()
void pljava_ExecutionPlan_initialize (void) extern
Definition at line 49 of file ExecutionPlan.c.
{
    JNINativeMethod methods[] =
    {
        {
        "_cursorOpen",
        "(JLjava/lang/String;[Ljava/lang/Object;S)Lorg/postgresql/pljava/internal/Portal;",
        Java_org_postgresql_pljava_internal_ExecutionPlan__1cursorOpen
        },
        {
        "_isCursorPlan",
        "(J)Z",
        Java_org_postgresql_pljava_internal_ExecutionPlan__1isCursorPlan
        },
        {
        "_execute",
        "(J[Ljava/lang/Object;SI)I",
        Java_org_postgresql_pljava_internal_ExecutionPlan__1execute
        },
        {
        "_prepare",
        "(Ljava/lang/Object;Ljava/lang/String;[Lorg/postgresql/pljava/internal/Oid;)Lorg/postgresql/pljava/internal/ExecutionPlan;",
        Java_org_postgresql_pljava_internal_ExecutionPlan__1prepare
        },
        { 0, 0, 0 }
    };
    PgObject_registerNatives("org/postgresql/pljava/internal/ExecutionPlan", methods);
    s_ExecutionPlan_class = (jclass)JNI_newGlobalRef(PgObject_getJavaClass(
        "org/postgresql/pljava/internal/ExecutionPlan"));
    s_ExecutionPlan_init = PgObject_getJavaMethod(s_ExecutionPlan_class,
        "<init>",
        "(Lorg/postgresql/pljava/internal/DualState$Key;J"
        "Ljava/lang/Object;J)V");
}
References Java_org_postgresql_pljava_internal_ExecutionPlan__1cursorOpen(), Java_org_postgresql_pljava_internal_ExecutionPlan__1execute(), Java_org_postgresql_pljava_internal_ExecutionPlan__1isCursorPlan(), Java_org_postgresql_pljava_internal_ExecutionPlan__1prepare(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_registerNatives(), s_ExecutionPlan_class, and s_ExecutionPlan_init.
Referenced by pljava_DualState_initialize().
resourceReleaseCB()
static void resourceReleaseCB (ResourceReleasePhase phase, bool isCommit, bool isTopLevel, void * arg) static
Definition at line 252 of file DualState.c.
{
    /*
     * The way ResourceOwnerRelease is implemented, callbacks to loadable
     * modules (like us!) happen /after/ all of the built-in releasey actions
     * for a particular phase. So, by looking for RESOURCE_RELEASE_LOCKS here,
     * we actually end up executing after all the built-in lock-related stuff
     * has been released, but before any of the built-in stuff released in the
     * RESOURCE_RELEASE_AFTER_LOCKS phase. Which, at least for the currently
     * implemented DualState subclasses, is about the right time.
     */
    if ( RESOURCE_RELEASE_LOCKS != phase )
        return;
    pljava_DualState_nativeRelease(CurrentResourceOwner);
    if ( isTopLevel )
        Backend_warnJEP411(isCommit);
}
References Backend_warnJEP411(), and pljava_DualState_nativeRelease().
Referenced by pljava_DualState_initialize(), and pljava_DualState_unregister().
Variable Documentation
s_DualState_class
jclass s_DualState_class static
Definition at line 47 of file DualState.c.
Referenced by pljava_DualState_cleanEnqueuedInstances(), pljava_DualState_initialize(), and pljava_DualState_nativeRelease().
s_DualState_cleanEnqueuedInstances
jmethodID s_DualState_cleanEnqueuedInstances static
Definition at line 50 of file DualState.c.
Referenced by pljava_DualState_cleanEnqueuedInstances(), and pljava_DualState_initialize().
s_DualState_key
jobject s_DualState_key static
Definition at line 52 of file DualState.c.
Referenced by pljava_DualState_initialize(), and pljava_DualState_key().
s_DualState_resourceOwnerRelease
jmethodID s_DualState_resourceOwnerRelease static
Definition at line 49 of file DualState.c.
Referenced by pljava_DualState_initialize(), and pljava_DualState_nativeRelease().