PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Time.c File Reference
Time.c File Reference
#include <time.h>
#include <postgres.h>
#include <utils/date.h>
#include <utils/datetime.h>
#include "pljava/Backend.h"
#include "pljava/type/Type_priv.h"
#include "pljava/type/Time.h"
#include "pljava/type/Timestamp.h"
Functions
static bool _LocalTime_canReplaceType (Type self, Type other)
static jvalue _LocalTime_coerceDatum (Type self, Datum arg)
static Datum _LocalTime_coerceObject (Type self, jobject time)
static Type _LocalTime_obtain (Oid typeId)
static bool _OffsetTime_canReplaceType (Type self, Type other)
static jvalue _OffsetTime_coerceDatum (Type self, Datum arg)
static Datum _OffsetTime_coerceObject (Type self, jobject time)
static Type _OffsetTime_obtain (Oid typeId)
static jlong msecsAtMidnight (void)
static jvalue Time_coerceDatumTZ_dd (Type self, double t, bool tzAdjust)
static jvalue Time_coerceDatumTZ_id (Type self, int64 t, bool tzAdjust)
static jlong Time_getMillisecsToday (Type self, jobject jt, bool tzAdjust)
static double Time_coerceObjectTZ_dd (Type self, jobject jt, bool tzAdjust)
static int64 Time_coerceObjectTZ_id (Type self, jobject jt, bool tzAdjust)
static jvalue _Time_coerceDatum (Type self, Datum arg)
static Datum _Time_coerceObject (Type self, jobject time)
static jvalue _Timetz_coerceDatum (Type self, Datum arg)
static Datum _Timetz_coerceObject (Type self, jobject time)
void Time_initialize (void)
Variables
static jclass s_Time_class
static jmethodID s_Time_init
static jmethodID s_Time_getTime
static TypeClass s_LocalTimeClass
static TypeClass s_OffsetTimeClass
static Type s_LocalTimeInstance
static jclass s_LocalTime_class
static jmethodID s_LocalTime_ofNanoOfDay
static jmethodID s_LocalTime_toNanoOfDay
static Type s_OffsetTimeInstance
static jclass s_OffsetTime_class
static jmethodID s_OffsetTime_of
static jmethodID s_OffsetTime_toLocalTime
static jmethodID s_OffsetTime_getOffset
static jclass s_ZoneOffset_class
static jmethodID s_ZoneOffset_ofTotalSeconds
static jmethodID s_ZoneOffset_getTotalSeconds
Function Documentation
_LocalTime_canReplaceType()
static bool _LocalTime_canReplaceType (Type self, Type other) static
Definition at line 72 of file Time.c.
{
    TypeClass cls = Type_getClass(other);
    return Type_getClass(self) == cls  ||  Type_getOid(other) == TIMEOID;
}
References Type_getClass(), and Type_getOid().
Referenced by Time_initialize().
_LocalTime_coerceDatum()
static jvalue _LocalTime_coerceDatum (Type self, Datum arg) static
Definition at line 78 of file Time.c.
{
    jlong nanos =
#if PG_VERSION_NUM < 100000
        (!integerDateTimes) ? (jlong)floor(1e9 * DatumGetFloat8(arg)) :
#endif
        1000 * DatumGetInt64(arg);
    jvalue result;
    if ( 1000L * USECS_PER_DAY == nanos )
        -- nanos;
    result.l = JNI_callStaticObjectMethod(
        s_LocalTime_class, s_LocalTime_ofNanoOfDay, nanos);
    return result;
}
References integerDateTimes, JNI_callStaticObjectMethod(), s_LocalTime_class, and s_LocalTime_ofNanoOfDay.
Referenced by Time_initialize().
_LocalTime_coerceObject()
static Datum _LocalTime_coerceObject (Type self, jobject time) static
Definition at line 93 of file Time.c.
{
    jlong nanos = JNI_callLongMethod(time, s_LocalTime_toNanoOfDay);
    return
#if PG_VERSION_NUM < 100000
        (!integerDateTimes) ? Float8GetDatum(((double)nanos) / 1e9) :
#endif
        Int64GetDatum((nanos + 1) / 1000);
}
References integerDateTimes, JNI_callLongMethod(), and s_LocalTime_toNanoOfDay.
Referenced by Time_initialize().
_LocalTime_obtain()
static Type _LocalTime_obtain (Oid typeId) static
Definition at line 103 of file Time.c.
{
    if ( NULL == s_LocalTimeInstance )
    {
        s_LocalTime_class = JNI_newGlobalRef(PgObject_getJavaClass(
            "java/time/LocalTime"));
        s_LocalTime_ofNanoOfDay = PgObject_getStaticJavaMethod(s_LocalTime_class,
            "ofNanoOfDay", "(J)Ljava/time/LocalTime;");
        s_LocalTime_toNanoOfDay = PgObject_getJavaMethod(s_LocalTime_class,
            "toNanoOfDay", "()J");
        s_LocalTimeInstance =
            TypeClass_allocInstance(s_LocalTimeClass, TIMEOID);
    }
    return s_LocalTimeInstance;
}
References JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_getStaticJavaMethod(), s_LocalTime_class, s_LocalTime_ofNanoOfDay, s_LocalTime_toNanoOfDay, s_LocalTimeClass, s_LocalTimeInstance, and TypeClass_allocInstance().
Referenced by _OffsetTime_obtain(), and Time_initialize().
_OffsetTime_canReplaceType()
static bool _OffsetTime_canReplaceType (Type self, Type other) static
Definition at line 124 of file Time.c.
{
    TypeClass cls = Type_getClass(other);
    return Type_getClass(self) == cls  ||  Type_getOid(other) == TIMETZOID;
}
References Type_getClass(), and Type_getOid().
Referenced by Time_initialize().
_OffsetTime_coerceDatum()
static jvalue _OffsetTime_coerceDatum (Type self, Datum arg) static
Definition at line 130 of file Time.c.
{
    jvalue localTime;
    jobject zoneOffset;
    int32 offsetSecs;
    jvalue result;
#if PG_VERSION_NUM < 100000
    if ( !integerDateTimes )
    {
        TimeTzADT_dd* tza = (TimeTzADT_dd*)DatumGetPointer(arg);
        localTime =
            Type_coerceDatum(s_LocalTimeInstance, Float8GetDatum(tza->time));
        offsetSecs = tza->zone;
    }
    else
#endif
    {
        TimeTzADT_id* tza = (TimeTzADT_id*)DatumGetPointer(arg);
        localTime =
            Type_coerceDatum(s_LocalTimeInstance, Int64GetDatum(tza->time));
        offsetSecs = tza->zone;
    }
    zoneOffset = JNI_callStaticObjectMethod(s_ZoneOffset_class,
        s_ZoneOffset_ofTotalSeconds, - offsetSecs); /* PG/Java signs differ */
    result.l = JNI_callStaticObjectMethod(
        s_OffsetTime_class, s_OffsetTime_of, localTime.l, zoneOffset);
    JNI_deleteLocalRef(localTime.l);
    JNI_deleteLocalRef(zoneOffset);
    return result;
}
References integerDateTimes, JNI_callStaticObjectMethod(), JNI_deleteLocalRef(), s_LocalTimeInstance, s_OffsetTime_class, s_OffsetTime_of, s_ZoneOffset_class, s_ZoneOffset_ofTotalSeconds, and Type_coerceDatum().
Referenced by Time_initialize().
_OffsetTime_coerceObject()
static Datum _OffsetTime_coerceObject (Type self, jobject time) static
Definition at line 166 of file Time.c.
{
    jobject localTime = JNI_callObjectMethod(time, s_OffsetTime_toLocalTime);
    jobject zoneOffset = JNI_callObjectMethod(time, s_OffsetTime_getOffset);
    jint offsetSecs =
        - /* PG/Java signs differ */
        JNI_callIntMethod(zoneOffset, s_ZoneOffset_getTotalSeconds);
    Datum result;
#if PG_VERSION_NUM < 100000
    if ( !integerDateTimes )
    {
        TimeTzADT_dd* tza = (TimeTzADT_dd*)palloc(sizeof(TimeTzADT_dd));
        tza->zone = offsetSecs;
        tza->time =
            DatumGetFloat8(Type_coerceObject(s_LocalTimeInstance, localTime));
        result = PointerGetDatum(tza);
    }
    else
#endif
    {
        TimeTzADT_id* tza = (TimeTzADT_id*)palloc(sizeof(TimeTzADT_id));
        tza->zone = offsetSecs;
        tza->time =
            DatumGetInt64(Type_coerceObject(s_LocalTimeInstance, localTime));
        result = PointerGetDatum(tza);
    }
    JNI_deleteLocalRef(localTime);
    JNI_deleteLocalRef(zoneOffset);
    return result;
}
References integerDateTimes, jint(), JNI_callIntMethod(), JNI_callObjectMethod(), JNI_deleteLocalRef(), s_LocalTimeInstance, s_OffsetTime_getOffset, s_OffsetTime_toLocalTime, s_ZoneOffset_getTotalSeconds, and Type_coerceObject().
Referenced by Time_initialize().
_OffsetTime_obtain()
static Type _OffsetTime_obtain (Oid typeId) static
Definition at line 199 of file Time.c.
{
    if ( NULL == s_OffsetTimeInstance )
    {
        _LocalTime_obtain(TIMEOID); /* Make sure LocalTime statics are there */
        s_OffsetTime_class = JNI_newGlobalRef(PgObject_getJavaClass(
            "java/time/OffsetTime"));
        s_OffsetTime_of = PgObject_getStaticJavaMethod(s_OffsetTime_class, "of",
            "(Ljava/time/LocalTime;Ljava/time/ZoneOffset;)"
            "Ljava/time/OffsetTime;");
        s_OffsetTime_toLocalTime = PgObject_getJavaMethod(s_OffsetTime_class,
            "toLocalTime", "()Ljava/time/LocalTime;");
        s_OffsetTime_getOffset = PgObject_getJavaMethod(s_OffsetTime_class,
            "getOffset", "()Ljava/time/ZoneOffset;");
        s_ZoneOffset_class = JNI_newGlobalRef(PgObject_getJavaClass(
            "java/time/ZoneOffset"));
        s_ZoneOffset_ofTotalSeconds = PgObject_getStaticJavaMethod(
            s_ZoneOffset_class, "ofTotalSeconds", "(I)Ljava/time/ZoneOffset;");
        s_ZoneOffset_getTotalSeconds = PgObject_getJavaMethod(
            s_ZoneOffset_class, "getTotalSeconds", "()I");
        s_OffsetTimeInstance =
            TypeClass_allocInstance(s_OffsetTimeClass, TIMETZOID);
    }
    return s_OffsetTimeInstance;
}
References _LocalTime_obtain(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_getStaticJavaMethod(), s_OffsetTime_class, s_OffsetTime_getOffset, s_OffsetTime_of, s_OffsetTime_toLocalTime, s_OffsetTimeClass, s_OffsetTimeInstance, s_ZoneOffset_class, s_ZoneOffset_getTotalSeconds, s_ZoneOffset_ofTotalSeconds, and TypeClass_allocInstance().
Referenced by Time_initialize().
_Time_coerceDatum()
static jvalue _Time_coerceDatum (Type self, Datum arg) static
Definition at line 281 of file Time.c.
{
    return
#if PG_VERSION_NUM < 100000
        (!integerDateTimes) ?
        Time_coerceDatumTZ_dd(self, DatumGetFloat8(arg), true) :
#endif
        Time_coerceDatumTZ_id(self, DatumGetInt64(arg), true);
}
References integerDateTimes, Time_coerceDatumTZ_dd(), and Time_coerceDatumTZ_id().
Referenced by Time_initialize().
_Time_coerceObject()
static Datum _Time_coerceObject (Type self, jobject time) static
Definition at line 291 of file Time.c.
{
    return
#if PG_VERSION_NUM < 100000
        (!integerDateTimes) ?
        Float8GetDatum(Time_coerceObjectTZ_dd(self, time, true)) :
#endif
        Int64GetDatum(Time_coerceObjectTZ_id(self, time, true));
}
References integerDateTimes, Time_coerceObjectTZ_dd(), and Time_coerceObjectTZ_id().
Referenced by Time_initialize().
_Timetz_coerceDatum()
static jvalue _Timetz_coerceDatum (Type self, Datum arg) static
Definition at line 306 of file Time.c.
{
    jvalue val;
#if PG_VERSION_NUM < 100000
    if(!integerDateTimes)
    {
        TimeTzADT_dd* tza = (TimeTzADT_dd*)DatumGetPointer(arg);
        double t = tza->time + tza->zone; /* Convert to UTC */
        val = Time_coerceDatumTZ_dd(self, t, false);
    }
    else
#endif
    {
        TimeTzADT_id* tza = (TimeTzADT_id*)DatumGetPointer(arg);
        int64 t = tza->time + (int64)tza->zone * 1000000; /* Convert to UTC */
        val = Time_coerceDatumTZ_id(self, t, false);
    }
    return val;
}
References integerDateTimes, Time_coerceDatumTZ_dd(), and Time_coerceDatumTZ_id().
Referenced by Time_initialize().
_Timetz_coerceObject()
static Datum _Timetz_coerceObject (Type self, jobject time) static
Definition at line 326 of file Time.c.
{
    Datum datum;
#if PG_VERSION_NUM < 100000
    if(!integerDateTimes)
    {
        TimeTzADT_dd* tza = (TimeTzADT_dd*)palloc(sizeof(TimeTzADT_dd));
        tza->time = Time_coerceObjectTZ_dd(self, time, false);
        tza->zone = Timestamp_getCurrentTimeZone();
        tza->time -= tza->zone; /* Convert UTC to local time */
        datum = PointerGetDatum(tza);
    }
    else
#endif
    {
        TimeTzADT_id* tza = (TimeTzADT_id*)palloc(sizeof(TimeTzADT_id));
        tza->time = Time_coerceObjectTZ_id(self, time, false);
        tza->zone = Timestamp_getCurrentTimeZone();
        tza->time -= (int64)tza->zone * 1000000; /* Convert UTC to local time */
        datum = PointerGetDatum(tza);
    }
    return datum;
}
References integerDateTimes, Time_coerceObjectTZ_dd(), Time_coerceObjectTZ_id(), and Timestamp_getCurrentTimeZone().
Referenced by Time_initialize().
msecsAtMidnight()
static jlong msecsAtMidnight (void) static
Definition at line 228 of file Time.c.
{
    pg_time_t now = (pg_time_t)time(NULL) / 86400;
    return INT64CONST(1000) * (jlong)(now * 86400);
}
Referenced by Time_coerceDatumTZ_dd(), and Time_coerceDatumTZ_id().
Time_coerceDatumTZ_dd()
static jvalue Time_coerceDatumTZ_dd (Type self, double t, bool tzAdjust) static
Definition at line 235 of file Time.c.
{
    jlong mSecs;
    jvalue result;
    if(tzAdjust)
        t += Timestamp_getCurrentTimeZone();/* Adjust from local time to UTC */
    t *= 1000.0;                        /* Convert to millisecs */
    mSecs = (jlong)floor(t);
    result.l = JNI_newObject(s_Time_class, s_Time_init, mSecs + msecsAtMidnight());
    return result;
}
References JNI_newObject(), msecsAtMidnight(), s_Time_class, s_Time_init, and Timestamp_getCurrentTimeZone().
Referenced by _Time_coerceDatum(), and _Timetz_coerceDatum().
Time_coerceDatumTZ_id()
static jvalue Time_coerceDatumTZ_id (Type self, int64 t, bool tzAdjust) static
Definition at line 248 of file Time.c.
{
    jvalue result;
    jlong mSecs = t / 1000;         /* Convert to millisecs */
    if(tzAdjust)
        mSecs += Timestamp_getCurrentTimeZone() * 1000;/* Adjust from local time to UTC */
    result.l = JNI_newObject(s_Time_class, s_Time_init, mSecs + msecsAtMidnight());
    return result;
}
References JNI_newObject(), msecsAtMidnight(), s_Time_class, s_Time_init, and Timestamp_getCurrentTimeZone().
Referenced by _Time_coerceDatum(), and _Timetz_coerceDatum().
Time_coerceObjectTZ_dd()
static double Time_coerceObjectTZ_dd (Type self, jobject jt, bool tzAdjust) static
Definition at line 268 of file Time.c.
{
    jlong mSecs = Time_getMillisecsToday(self, jt, tzAdjust);
    return ((double)mSecs) / 1000.0; /* Convert to seconds */
}
References Time_getMillisecsToday().
Referenced by _Time_coerceObject(), and _Timetz_coerceObject().
Time_coerceObjectTZ_id()
static int64 Time_coerceObjectTZ_id (Type self, jobject jt, bool tzAdjust) static
Definition at line 275 of file Time.c.
{
    jlong mSecs = Time_getMillisecsToday(self, jt, tzAdjust);
    return mSecs * 1000L; /* Convert millisecs to microsecs */
}
References Time_getMillisecsToday().
Referenced by _Time_coerceObject(), and _Timetz_coerceObject().
Time_getMillisecsToday()
static jlong Time_getMillisecsToday (Type self, jobject jt, bool tzAdjust) static
Definition at line 258 of file Time.c.
{
    jlong mSecs = JNI_callLongMethod(jt, s_Time_getTime);
    if(tzAdjust)
        mSecs -= ((jlong)Timestamp_getCurrentTimeZone()) * 1000L; /* Adjust from UTC to local time */
    mSecs %= 86400000; /* Strip everything above 24 hours */
    return mSecs;
}
References JNI_callLongMethod(), s_Time_getTime, and Timestamp_getCurrentTimeZone().
Referenced by Time_coerceObjectTZ_dd(), and Time_coerceObjectTZ_id().
Time_initialize()
void Time_initialize (void) extern
Definition at line 351 of file Time.c.
{
    TypeClass cls;
    s_Time_class = JNI_newGlobalRef(PgObject_getJavaClass("java/sql/Time"));
    s_Time_init = PgObject_getJavaMethod(s_Time_class, "<init>", "(J)V");
    s_Time_getTime = PgObject_getJavaMethod(s_Time_class, "getTime", "()J");
    cls = TypeClass_alloc("type.Time");
    cls->JNISignature = "Ljava/sql/Time;";
    cls->javaTypeName = "java.sql.Time";
    cls->coerceDatum  = _Time_coerceDatum;
    cls->coerceObject = _Time_coerceObject;
    Type_registerType(0, TypeClass_allocInstance(cls, TIMEOID));
    cls = TypeClass_alloc("type.Timetz");
    cls->JNISignature = "Ljava/sql/Time;";
    cls->javaTypeName = "java.sql.Time";
    cls->coerceDatum  = _Timetz_coerceDatum;
    cls->coerceObject = _Timetz_coerceObject;
    Type_registerType("java.sql.Time", TypeClass_allocInstance(cls, TIMETZOID));
    cls = TypeClass_alloc("type.LocalTime");
    cls->JNISignature = "Ljava/time/LocalTime;";
    cls->javaTypeName = "java.time.LocalTime";
    cls->coerceDatum  = _LocalTime_coerceDatum;
    cls->coerceObject = _LocalTime_coerceObject;
    cls->canReplaceType = _LocalTime_canReplaceType;
    s_LocalTimeClass  = cls;
    Type_registerType2(InvalidOid, "java.time.LocalTime", _LocalTime_obtain);
    cls = TypeClass_alloc("type.OffsetTime");
    cls->JNISignature = "Ljava/time/OffsetTime;";
    cls->javaTypeName = "java.time.OffsetTime";
    cls->coerceDatum  = _OffsetTime_coerceDatum;
    cls->coerceObject = _OffsetTime_coerceObject;
    cls->canReplaceType = _OffsetTime_canReplaceType;
    s_OffsetTimeClass  = cls;
    Type_registerType2(InvalidOid, "java.time.OffsetTime", _OffsetTime_obtain);
}
References _LocalTime_canReplaceType(), _LocalTime_coerceDatum(), _LocalTime_coerceObject(), _LocalTime_obtain(), _OffsetTime_canReplaceType(), _OffsetTime_coerceDatum(), _OffsetTime_coerceObject(), _OffsetTime_obtain(), _Time_coerceDatum(), _Time_coerceObject(), _Timetz_coerceDatum(), _Timetz_coerceObject(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_LocalTimeClass, s_OffsetTimeClass, s_Time_class, s_Time_getTime, s_Time_init, Type_registerType(), Type_registerType2(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Variable Documentation
s_LocalTime_class
jclass s_LocalTime_class static
Definition at line 56 of file Time.c.
Referenced by _LocalTime_coerceDatum(), and _LocalTime_obtain().
s_LocalTime_ofNanoOfDay
jmethodID s_LocalTime_ofNanoOfDay static
Definition at line 57 of file Time.c.
Referenced by _LocalTime_coerceDatum(), and _LocalTime_obtain().
s_LocalTime_toNanoOfDay
jmethodID s_LocalTime_toNanoOfDay static
Definition at line 58 of file Time.c.
Referenced by _LocalTime_coerceObject(), and _LocalTime_obtain().
s_LocalTimeClass
TypeClass s_LocalTimeClass static
Definition at line 49 of file Time.c.
Referenced by _LocalTime_obtain(), and Time_initialize().
s_LocalTimeInstance
Type s_LocalTimeInstance static
Definition at line 55 of file Time.c.
Referenced by _LocalTime_obtain(), _OffsetTime_coerceDatum(), and _OffsetTime_coerceObject().
s_OffsetTime_class
jclass s_OffsetTime_class static
Definition at line 60 of file Time.c.
Referenced by _OffsetTime_coerceDatum(), and _OffsetTime_obtain().
s_OffsetTime_getOffset
jmethodID s_OffsetTime_getOffset static
Definition at line 63 of file Time.c.
Referenced by _OffsetTime_coerceObject(), and _OffsetTime_obtain().
s_OffsetTime_of
jmethodID s_OffsetTime_of static
Definition at line 61 of file Time.c.
Referenced by _OffsetTime_coerceDatum(), and _OffsetTime_obtain().
s_OffsetTime_toLocalTime
jmethodID s_OffsetTime_toLocalTime static
Definition at line 62 of file Time.c.
Referenced by _OffsetTime_coerceObject(), and _OffsetTime_obtain().
s_OffsetTimeClass
TypeClass s_OffsetTimeClass static
Definition at line 50 of file Time.c.
Referenced by _OffsetTime_obtain(), and Time_initialize().
s_OffsetTimeInstance
Type s_OffsetTimeInstance static
Definition at line 59 of file Time.c.
Referenced by _OffsetTime_obtain().
s_Time_class
jclass s_Time_class static
Definition at line 45 of file Time.c.
Referenced by Time_coerceDatumTZ_dd(), Time_coerceDatumTZ_id(), and Time_initialize().
s_Time_getTime
jmethodID s_Time_getTime static
Definition at line 47 of file Time.c.
Referenced by Time_getMillisecsToday(), and Time_initialize().
s_Time_init
jmethodID s_Time_init static
Definition at line 46 of file Time.c.
Referenced by Time_coerceDatumTZ_dd(), Time_coerceDatumTZ_id(), and Time_initialize().
s_ZoneOffset_class
jclass s_ZoneOffset_class static
Definition at line 64 of file Time.c.
Referenced by _OffsetTime_coerceDatum(), and _OffsetTime_obtain().
s_ZoneOffset_getTotalSeconds
jmethodID s_ZoneOffset_getTotalSeconds static
Definition at line 66 of file Time.c.
Referenced by _OffsetTime_coerceObject(), and _OffsetTime_obtain().
s_ZoneOffset_ofTotalSeconds
jmethodID s_ZoneOffset_ofTotalSeconds static
Definition at line 65 of file Time.c.
Referenced by _OffsetTime_coerceDatum(), and _OffsetTime_obtain().