PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/TupleTable.c File Reference
TupleTable.c File Reference
#include <postgres.h>
#include <executor/spi.h>
#include <executor/tuptable.h>
#include "pljava/type/Type_priv.h"
#include "pljava/type/TupleTable.h"
#include "pljava/type/Tuple.h"
#include "pljava/type/TupleDesc.h"
Macros
#define ExecCopySlotHeapTuple(tts) ExecCopySlotTuple((tts))
Functions
jobject TupleTable_createFromSlot (TupleTableSlot *tts)
jobject TupleTable_create (SPITupleTable *tts, jobject knownTD)
void TupleTable_initialize (void)
Variables
static jclass s_TupleTable_class
static jmethodID s_TupleTable_init
Macro Definition Documentation
ExecCopySlotHeapTuple
#define ExecCopySlotHeapTuple (tts) ExecCopySlotTuple((tts))
Definition at line 23 of file TupleTable.c.
Function Documentation
TupleTable_create()
jobject TupleTable_create (SPITupleTable * tts, jobject knownTD)
Definition at line 50 of file TupleTable.c.
{
    jobjectArray tuples;
    uint64 tupcount;
    MemoryContext curr;
    if(tts == 0)
        return 0;
#if PG_VERSION_NUM < 130000
    tupcount = tts->alloced - tts->free;
#else
    tupcount = tts->numvals;
#endif
    if ( tupcount > PG_INT32_MAX )
        ereport(ERROR,
                (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                 errmsg("a PL/Java TupleTable cannot represent more than "
                    "INT32_MAX rows")));
    curr = MemoryContextSwitchTo(JavaMemoryContext);
    if(knownTD == 0)
        knownTD = pljava_TupleDesc_internalCreate(tts->tupdesc);
    tuples = pljava_Tuple_createArray(tts->vals, (jint)tupcount, true);
    MemoryContextSwitchTo(curr);
    return JNI_newObject(s_TupleTable_class, s_TupleTable_init, knownTD, tuples);
}
References JavaMemoryContext, jint(), JNI_newObject(), pljava_Tuple_createArray(), pljava_TupleDesc_internalCreate(), s_TupleTable_class, and s_TupleTable_init.
Referenced by Java_org_postgresql_pljava_internal_SPI__1getTupTable().
TupleTable_createFromSlot()
jobject TupleTable_createFromSlot (TupleTableSlot * tts)
Definition at line 29 of file TupleTable.c.
{
    HeapTuple tuple;
    jobject tupdesc;
    jobjectArray tuples;
    MemoryContext curr;
    if(tts == 0)
        return 0;
    curr = MemoryContextSwitchTo(JavaMemoryContext);
    tupdesc = pljava_TupleDesc_internalCreate(tts->tts_tupleDescriptor);
    tuple   = ExecCopySlotHeapTuple(tts);
    tuples  = pljava_Tuple_createArray(&tuple, 1, false);
    MemoryContextSwitchTo(curr);
    return JNI_newObject(s_TupleTable_class, s_TupleTable_init, tupdesc, tuples);
}
References ExecCopySlotHeapTuple, JavaMemoryContext, JNI_newObject(), pljava_Tuple_createArray(), pljava_TupleDesc_internalCreate(), s_TupleTable_class, and s_TupleTable_init.
TupleTable_initialize()
void TupleTable_initialize (void) extern
Definition at line 84 of file TupleTable.c.
{
    s_TupleTable_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/internal/TupleTable"));
    s_TupleTable_init = PgObject_getJavaMethod(
                s_TupleTable_class, "<init>",
                "(Lorg/postgresql/pljava/internal/TupleDesc;[Lorg/postgresql/pljava/internal/Tuple;)V");
}
References JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_TupleTable_class, and s_TupleTable_init.
Referenced by Type_initialize().
Variable Documentation
s_TupleTable_class
jclass s_TupleTable_class static
Definition at line 26 of file TupleTable.c.
Referenced by TupleTable_create(), TupleTable_createFromSlot(), and TupleTable_initialize().
s_TupleTable_init
jmethodID s_TupleTable_init static
Definition at line 27 of file TupleTable.c.
Referenced by TupleTable_create(), TupleTable_createFromSlot(), and TupleTable_initialize().