PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/SQLInputFromChunk.c File Reference
SQLInputFromChunk.c File Reference
#include <postgres.h>
#include "pljava/SQLInputFromChunk.h"
Functions
jobject SQLInputFromChunk_create (void *data, size_t sz, bool isJavaBasedScalar)
void SQLInputFromChunk_close (jobject stream)
void SQLInputFromChunk_initialize (void)
Variables
static jclass s_SQLInputFromChunk_class
static jmethodID s_SQLInputFromChunk_init
static jmethodID s_SQLInputFromChunk_close
Function Documentation
SQLInputFromChunk_close()
void SQLInputFromChunk_close (jobject stream)
Definition at line 29 of file SQLInputFromChunk.c.
{
    JNI_callVoidMethod(stream, s_SQLInputFromChunk_close);
}
References JNI_callVoidMethod(), and s_SQLInputFromChunk_close.
Referenced by coerceScalarDatum().
SQLInputFromChunk_create()
jobject SQLInputFromChunk_create (void * data, size_t sz, bool isJavaBasedScalar)
Definition at line 20 of file SQLInputFromChunk.c.
{
    jobject dbb;
    dbb = JNI_newDirectByteBuffer(data, sz);
    return
        JNI_newObject(s_SQLInputFromChunk_class, s_SQLInputFromChunk_init, dbb,
        isJavaBasedScalar ? JNI_TRUE : JNI_FALSE);
}
References JNI_newDirectByteBuffer(), JNI_newObject(), s_SQLInputFromChunk_class, and s_SQLInputFromChunk_init.
Referenced by coerceScalarDatum().
SQLInputFromChunk_initialize()
void SQLInputFromChunk_initialize (void) extern
Definition at line 37 of file SQLInputFromChunk.c.
{
    s_SQLInputFromChunk_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/jdbc/SQLInputFromChunk"));
    s_SQLInputFromChunk_init = PgObject_getJavaMethod(s_SQLInputFromChunk_class,
        "<init>", "(Ljava/nio/ByteBuffer;Z)V");
    s_SQLInputFromChunk_close = PgObject_getJavaMethod(s_SQLInputFromChunk_class, "close", "()V");
}
References JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_SQLInputFromChunk_class, s_SQLInputFromChunk_close, and s_SQLInputFromChunk_init.
Referenced by initPLJavaClasses().
Variable Documentation
s_SQLInputFromChunk_class
jclass s_SQLInputFromChunk_class static
Definition at line 16 of file SQLInputFromChunk.c.
Referenced by SQLInputFromChunk_create(), and SQLInputFromChunk_initialize().
s_SQLInputFromChunk_close
jmethodID s_SQLInputFromChunk_close static
Definition at line 18 of file SQLInputFromChunk.c.
Referenced by SQLInputFromChunk_close(), and SQLInputFromChunk_initialize().
s_SQLInputFromChunk_init
jmethodID s_SQLInputFromChunk_init static
Definition at line 17 of file SQLInputFromChunk.c.
Referenced by SQLInputFromChunk_create(), and SQLInputFromChunk_initialize().