/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_postgresql_pljava_SPI */

#ifndef _Included_org_postgresql_pljava_SPI
#define _Included_org_postgresql_pljava_SPI
#ifdef __cplusplus
extern "C" {
#endif
#undef org_postgresql_pljava_SPI_ERROR_CONNECT
#define org_postgresql_pljava_SPI_ERROR_CONNECT -1L
#undef org_postgresql_pljava_SPI_ERROR_COPY
#define org_postgresql_pljava_SPI_ERROR_COPY -2L
#undef org_postgresql_pljava_SPI_ERROR_OPUNKNOWN
#define org_postgresql_pljava_SPI_ERROR_OPUNKNOWN -3L
#undef org_postgresql_pljava_SPI_ERROR_UNCONNECTED
#define org_postgresql_pljava_SPI_ERROR_UNCONNECTED -4L
#undef org_postgresql_pljava_SPI_ERROR_CURSOR
#define org_postgresql_pljava_SPI_ERROR_CURSOR -5L
#undef org_postgresql_pljava_SPI_ERROR_ARGUMENT
#define org_postgresql_pljava_SPI_ERROR_ARGUMENT -6L
#undef org_postgresql_pljava_SPI_ERROR_PARAM
#define org_postgresql_pljava_SPI_ERROR_PARAM -7L
#undef org_postgresql_pljava_SPI_ERROR_TRANSACTION
#define org_postgresql_pljava_SPI_ERROR_TRANSACTION -8L
#undef org_postgresql_pljava_SPI_ERROR_NOATTRIBUTE
#define org_postgresql_pljava_SPI_ERROR_NOATTRIBUTE -9L
#undef org_postgresql_pljava_SPI_ERROR_NOOUTFUNC
#define org_postgresql_pljava_SPI_ERROR_NOOUTFUNC -10L
#undef org_postgresql_pljava_SPI_ERROR_TYPUNKNOWN
#define org_postgresql_pljava_SPI_ERROR_TYPUNKNOWN -11L
#undef org_postgresql_pljava_SPI_OK_CONNECT
#define org_postgresql_pljava_SPI_OK_CONNECT 1L
#undef org_postgresql_pljava_SPI_OK_FINISH
#define org_postgresql_pljava_SPI_OK_FINISH 2L
#undef org_postgresql_pljava_SPI_OK_FETCH
#define org_postgresql_pljava_SPI_OK_FETCH 3L
#undef org_postgresql_pljava_SPI_OK_UTILITY
#define org_postgresql_pljava_SPI_OK_UTILITY 4L
#undef org_postgresql_pljava_SPI_OK_SELECT
#define org_postgresql_pljava_SPI_OK_SELECT 5L
#undef org_postgresql_pljava_SPI_OK_SELINTO
#define org_postgresql_pljava_SPI_OK_SELINTO 6L
#undef org_postgresql_pljava_SPI_OK_INSERT
#define org_postgresql_pljava_SPI_OK_INSERT 7L
#undef org_postgresql_pljava_SPI_OK_DELETE
#define org_postgresql_pljava_SPI_OK_DELETE 8L
#undef org_postgresql_pljava_SPI_OK_UPDATE
#define org_postgresql_pljava_SPI_OK_UPDATE 9L
#undef org_postgresql_pljava_SPI_OK_CURSOR
#define org_postgresql_pljava_SPI_OK_CURSOR 10L
/*
 * Class:     org_postgresql_pljava_SPI
 * Method:    exec
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_SPI_exec
  (JNIEnv *, jclass, jstring, jint);

/*
 * Class:     org_postgresql_pljava_SPI
 * Method:    getProcessed
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_SPI_getProcessed
  (JNIEnv *, jclass);

/*
 * Class:     org_postgresql_pljava_SPI
 * Method:    getResult
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_SPI_getResult
  (JNIEnv *, jclass);

/*
 * Class:     org_postgresql_pljava_SPI
 * Method:    getTupTable
 * Signature: ()Lorg/postgresql/pljava/TupleTable;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_SPI_getTupTable
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
