PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/TriggerData.c File Reference
TriggerData.c File Reference
#include <postgres.h>
#include <access/heapam.h>
#include "org_postgresql_pljava_internal_TriggerData.h"
#include "pljava/Invocation.h"
#include "pljava/DualState.h"
#include "pljava/Exception.h"
#include "pljava/type/Type_priv.h"
#include "pljava/type/String.h"
#include "pljava/type/TriggerData.h"
#include "pljava/type/Tuple.h"
#include "pljava/type/TupleDesc.h"
#include "pljava/type/Relation.h"
Functions
jobject pljava_TriggerData_create (TriggerData *triggerData)
HeapTuple pljava_TriggerData_getTriggerReturnTuple (jobject jtd, bool *wasNull)
void pljava_TriggerData_initialize (void)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getRelation (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getTriggerTuple (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getNewTuple (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jobjectArray JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getArguments (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getName (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredAfter (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredBefore (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredForEachRow (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredForStatement (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredByDelete (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredByInsert (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredByUpdate (JNIEnv *env, jclass clazz, jlong _this)
Variables
static jclass s_TriggerData_class
static jmethodID s_TriggerData_init
static jmethodID s_TriggerData_getTriggerReturnTuple
Function Documentation
Java_org_postgresql_pljava_internal_TriggerData__1getArguments()
JNIEXPORT jobjectArray JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getArguments (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 231 of file TriggerData.c.
{
    jobjectArray result = 0;
    TriggerData* self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (TriggerData*)p2l.ptrVal;
    if(self != 0)
    {
        char** cpp;
        jint idx;
        BEGIN_NATIVE
        Trigger* tg = self->tg_trigger;
        jint nargs = (jint)tg->tgnargs;
        result = JNI_newObjectArray(nargs, s_String_class, 0);
        cpp = tg->tgargs;
        for(idx = 0; idx < nargs; ++idx)
        {
            jstring js = String_createJavaStringFromNTS(cpp[idx]);
            JNI_setObjectArrayElement(result, idx, js);
            JNI_deleteLocalRef(js);
        }
        END_NATIVE
    }
    return result;
}
References jint(), JNI_deleteLocalRef(), JNI_newObjectArray(), JNI_setObjectArrayElement(), s_String_class, and String_createJavaStringFromNTS().
Referenced by pljava_TriggerData_initialize().
Java_org_postgresql_pljava_internal_TriggerData__1getName()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getName (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 265 of file TriggerData.c.
{
    jstring result = 0;
    TriggerData* self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (TriggerData*)p2l.ptrVal;
    if(self != 0)
    {
        BEGIN_NATIVE
        result = String_createJavaStringFromNTS(self->tg_trigger->tgname);
        END_NATIVE
    }
    return result;
}
References String_createJavaStringFromNTS().
Referenced by pljava_TriggerData_initialize().
Java_org_postgresql_pljava_internal_TriggerData__1getNewTuple()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getNewTuple (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 209 of file TriggerData.c.
{
    jobject result = 0;
    TriggerData* self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (TriggerData*)p2l.ptrVal;
    if(self != 0)
    {
        BEGIN_NATIVE
        result = pljava_Tuple_create(self->tg_newtuple);
        END_NATIVE
    }
    return result;
}
References pljava_Tuple_create().
Referenced by pljava_TriggerData_initialize().
Java_org_postgresql_pljava_internal_TriggerData__1getRelation()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getRelation (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 165 of file TriggerData.c.
{
    jobject result = 0;
    TriggerData* self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (TriggerData*)p2l.ptrVal;
    if(self != 0)
    {
        BEGIN_NATIVE
        result = pljava_Relation_create(self->tg_relation);
        END_NATIVE
    }
    return result;
}
References pljava_Relation_create().
Referenced by pljava_TriggerData_initialize().
Java_org_postgresql_pljava_internal_TriggerData__1getTriggerTuple()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getTriggerTuple (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 187 of file TriggerData.c.
{
    jobject result = 0;
    TriggerData* self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (TriggerData*)p2l.ptrVal;
    if(self != 0)
    {
        BEGIN_NATIVE
        result = pljava_Tuple_create(self->tg_trigtuple);
        END_NATIVE
    }
    return result;
}
References pljava_Tuple_create().
Referenced by pljava_TriggerData_initialize().
Java_org_postgresql_pljava_internal_TriggerData__1isFiredAfter()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredAfter (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 287 of file TriggerData.c.
{
    jboolean result = JNI_FALSE;
    TriggerData* self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (TriggerData*)p2l.ptrVal;
    if(self != 0)
        result = (jboolean)TRIGGER_FIRED_AFTER(self->tg_event);
    return result;
}
Referenced by pljava_TriggerData_initialize().
Java_org_postgresql_pljava_internal_TriggerData__1isFiredBefore()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredBefore (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 305 of file TriggerData.c.
{
    jboolean result = JNI_FALSE;
    TriggerData* self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (TriggerData*)p2l.ptrVal;
    if(self != 0)
        result = (jboolean)TRIGGER_FIRED_BEFORE(self->tg_event);
    return result;
}
Referenced by pljava_TriggerData_initialize().
Java_org_postgresql_pljava_internal_TriggerData__1isFiredByDelete()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredByDelete (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 359 of file TriggerData.c.
{
    jboolean result = JNI_FALSE;
    TriggerData* self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (TriggerData*)p2l.ptrVal;
    if(self != 0)
        result = (jboolean)TRIGGER_FIRED_BY_DELETE(self->tg_event);
    return result;
}
Referenced by pljava_TriggerData_initialize().
Java_org_postgresql_pljava_internal_TriggerData__1isFiredByInsert()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredByInsert (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 377 of file TriggerData.c.
{
    jboolean result = JNI_FALSE;
    TriggerData* self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (TriggerData*)p2l.ptrVal;
    if(self != 0)
        result = (jboolean)TRIGGER_FIRED_BY_INSERT(self->tg_event);
    return result;
}
Referenced by pljava_TriggerData_initialize().
Java_org_postgresql_pljava_internal_TriggerData__1isFiredByUpdate()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredByUpdate (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 395 of file TriggerData.c.
{
    jboolean result = JNI_FALSE;
    TriggerData* self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (TriggerData*)p2l.ptrVal;
    if(self != 0)
        result = (jboolean)TRIGGER_FIRED_BY_UPDATE(self->tg_event);
    return result;
}
Referenced by pljava_TriggerData_initialize().
Java_org_postgresql_pljava_internal_TriggerData__1isFiredForEachRow()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredForEachRow (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 323 of file TriggerData.c.
{
    jboolean result = JNI_FALSE;
    TriggerData* self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (TriggerData*)p2l.ptrVal;
    if(self != 0)
        result = (jboolean)TRIGGER_FIRED_FOR_ROW(self->tg_event);
    return result;
}
Referenced by pljava_TriggerData_initialize().
Java_org_postgresql_pljava_internal_TriggerData__1isFiredForStatement()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredForStatement (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 341 of file TriggerData.c.
{
    jboolean result = JNI_FALSE;
    TriggerData* self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (TriggerData*)p2l.ptrVal;
    if(self != 0)
        result = (jboolean)TRIGGER_FIRED_FOR_STATEMENT(self->tg_event);
    return result;
}
Referenced by pljava_TriggerData_initialize().
pljava_TriggerData_create()
jobject pljava_TriggerData_create (TriggerData * triggerData)
Definition at line 32 of file TriggerData.c.
{
    Ptr2Long p2ltd;
    Ptr2Long p2lro;
    if ( NULL == triggerData )
        return NULL;
    p2ltd.longVal = 0L;
    p2ltd.ptrVal = triggerData;
    p2lro.longVal = 0L;
    p2lro.ptrVal = currentInvocation;
    return JNI_newObjectLocked(
            s_TriggerData_class,
            s_TriggerData_init,
            pljava_DualState_key(),
            p2lro.longVal,
            p2ltd.longVal);
}
References currentInvocation, JNI_newObjectLocked(), pljava_DualState_key(), s_TriggerData_class, and s_TriggerData_init.
Referenced by invokeTrigger().
pljava_TriggerData_getTriggerReturnTuple()
HeapTuple pljava_TriggerData_getTriggerReturnTuple (jobject jtd, bool * wasNull)
Definition at line 54 of file TriggerData.c.
{
    Ptr2Long p2l;
    HeapTuple ret = 0;
    p2l.longVal = JNI_callLongMethod(jtd, s_TriggerData_getTriggerReturnTuple);
    if(p2l.longVal != 0)
        ret = heap_copytuple((HeapTuple)p2l.ptrVal); /* unconditional copy?? */
    else
        *wasNull = true;
    return ret;
}
References JNI_callLongMethod(), and s_TriggerData_getTriggerReturnTuple.
Referenced by invokeTrigger().
pljava_TriggerData_initialize()
void pljava_TriggerData_initialize (void)
Definition at line 68 of file TriggerData.c.
{
    TypeClass cls;
    jclass jcls;
    JNINativeMethod methods[] =
    {
        {
        "_getRelation",
        "(J)Lorg/postgresql/pljava/internal/Relation;",
        Java_org_postgresql_pljava_internal_TriggerData__1getRelation
        },
        {
        "_getTriggerTuple",
        "(J)Lorg/postgresql/pljava/internal/Tuple;",
        Java_org_postgresql_pljava_internal_TriggerData__1getTriggerTuple
        },
        {
        "_getNewTuple",
        "(J)Lorg/postgresql/pljava/internal/Tuple;",
        Java_org_postgresql_pljava_internal_TriggerData__1getNewTuple
        },
        {
        "_getArguments",
        "(J)[Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_TriggerData__1getArguments
        },
        {
        "_getName",
        "(J)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_TriggerData__1getName
        },
        {
        "_isFiredAfter",
        "(J)Z",
        Java_org_postgresql_pljava_internal_TriggerData__1isFiredAfter
        },
        {
        "_isFiredBefore",
        "(J)Z",
        Java_org_postgresql_pljava_internal_TriggerData__1isFiredBefore
        },
        {
        "_isFiredForEachRow",
        "(J)Z",
        Java_org_postgresql_pljava_internal_TriggerData__1isFiredForEachRow
        },
        {
        "_isFiredForStatement",
        "(J)Z",
        Java_org_postgresql_pljava_internal_TriggerData__1isFiredForStatement
        },
        {
        "_isFiredByDelete",
        "(J)Z",
        Java_org_postgresql_pljava_internal_TriggerData__1isFiredByDelete
        },
        {
        "_isFiredByInsert",
        "(J)Z",
        Java_org_postgresql_pljava_internal_TriggerData__1isFiredByInsert
        },
        {
        "_isFiredByUpdate",
        "(J)Z",
        Java_org_postgresql_pljava_internal_TriggerData__1isFiredByUpdate
        },
        { 0, 0, 0 }
    };
    jcls = PgObject_getJavaClass("org/postgresql/pljava/internal/TriggerData");
    PgObject_registerNatives2(jcls, methods);
    s_TriggerData_init = PgObject_getJavaMethod(jcls, "<init>",
        "(Lorg/postgresql/pljava/internal/DualState$Key;JJ)V");
    s_TriggerData_getTriggerReturnTuple = PgObject_getJavaMethod(
        jcls, "getTriggerReturnTuple", "()J");
    s_TriggerData_class = JNI_newGlobalRef(jcls);
    JNI_deleteLocalRef(jcls);
    /* Use interface name for signatures.
     */
    cls = TypeClass_alloc("type.TriggerData");
    cls->JNISignature   = "Lorg/postgresql/pljava/TriggerData;";
    cls->javaTypeName   = "org.postgresql.pljava.TriggerData";
    Type_registerType("org.postgresql.pljava.TriggerData", TypeClass_allocInstance(cls, InvalidOid));
}
References Java_org_postgresql_pljava_internal_TriggerData__1getArguments(), Java_org_postgresql_pljava_internal_TriggerData__1getName(), Java_org_postgresql_pljava_internal_TriggerData__1getNewTuple(), Java_org_postgresql_pljava_internal_TriggerData__1getRelation(), Java_org_postgresql_pljava_internal_TriggerData__1getTriggerTuple(), Java_org_postgresql_pljava_internal_TriggerData__1isFiredAfter(), Java_org_postgresql_pljava_internal_TriggerData__1isFiredBefore(), Java_org_postgresql_pljava_internal_TriggerData__1isFiredByDelete(), Java_org_postgresql_pljava_internal_TriggerData__1isFiredByInsert(), Java_org_postgresql_pljava_internal_TriggerData__1isFiredByUpdate(), Java_org_postgresql_pljava_internal_TriggerData__1isFiredForEachRow(), Java_org_postgresql_pljava_internal_TriggerData__1isFiredForStatement(), JNI_deleteLocalRef(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_registerNatives2(), s_TriggerData_class, s_TriggerData_getTriggerReturnTuple, s_TriggerData_init, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by pljava_DualState_initialize().
Variable Documentation
s_TriggerData_class
jclass s_TriggerData_class static
Definition at line 28 of file TriggerData.c.
Referenced by pljava_TriggerData_create(), and pljava_TriggerData_initialize().
s_TriggerData_getTriggerReturnTuple
jmethodID s_TriggerData_getTriggerReturnTuple static
Definition at line 30 of file TriggerData.c.
Referenced by pljava_TriggerData_getTriggerReturnTuple(), and pljava_TriggerData_initialize().
s_TriggerData_init
jmethodID s_TriggerData_init static
Definition at line 29 of file TriggerData.c.
Referenced by pljava_TriggerData_create(), and pljava_TriggerData_initialize().