PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Date.c File Reference
Date.c File Reference
#include <postgres.h>
#include <utils/date.h>
#include <utils/datetime.h>
#include "pljava/type/Type_priv.h"
#include "pljava/type/Timestamp.h"
Macros
#define EPOCH_DIFF (POSTGRES_EPOCH_JDATE - UNIX_EPOCH_JDATE)
Functions
static bool _LocalDate_canReplaceType (Type self, Type other)
static jvalue _LocalDate_coerceDatum (Type self, Datum arg)
static Datum _LocalDate_coerceObject (Type self, jobject date)
static Type _LocalDate_obtain (Oid typeId)
static jvalue _Date_coerceDatum (Type self, Datum arg)
static Datum _Date_coerceObject (Type self, jobject date)
void Date_initialize (void)
Variables
static jclass s_Date_class
static jmethodID s_Date_init
static jmethodID s_Date_getTime
static TypeClass s_LocalDateClass
static jclass s_LocalDate_class
static jmethodID s_LocalDate_ofEpochDay
static jmethodID s_LocalDate_toEpochDay
Macro Definition Documentation
EPOCH_DIFF
#define EPOCH_DIFF (POSTGRES_EPOCH_JDATE - UNIX_EPOCH_JDATE)
Definition at line 22 of file Date.c.
Function Documentation
_Date_coerceDatum()
static jvalue _Date_coerceDatum (Type self, Datum arg) static
Definition at line 95 of file Date.c.
{
    DateADT pgDate = DatumGetDateADT(arg);
    int64 ts = (int64)pgDate * INT64CONST(43200000000);
    int   tz = Timestamp_getTimeZone_id(ts); /* ts in 2 usec units */
    jlong date = (jlong)(pgDate + EPOCH_DIFF);
    jvalue result;
    date *= 86400L; // Convert to seconds
    date += tz;     // Add local timezone
    result.l = JNI_newObject(s_Date_class, s_Date_init, date * 1000);
    return result;
}
References EPOCH_DIFF, JNI_newObject(), s_Date_class, s_Date_init, and Timestamp_getTimeZone_id().
Referenced by Date_initialize().
_Date_coerceObject()
static Datum _Date_coerceObject (Type self, jobject date) static
Definition at line 110 of file Date.c.
{
    jlong milliSecs =
        JNI_callLongMethod(date, s_Date_getTime)
        - INT64CONST(86400000) * EPOCH_DIFF;
    jlong secs =
        milliSecs / 1000
        - Timestamp_getTimeZone_id(milliSecs * 500); /* those 2 usec units */
    return DateADTGetDatum((DateADT)(secs / 86400));
}
References EPOCH_DIFF, JNI_callLongMethod(), s_Date_getTime, and Timestamp_getTimeZone_id().
Referenced by Date_initialize().
_LocalDate_canReplaceType()
static bool _LocalDate_canReplaceType (Type self, Type other) static
Definition at line 51 of file Date.c.
{
    TypeClass cls = Type_getClass(other);
    return Type_getClass(self) == cls  ||  Type_getOid(other) == DATEOID;
}
References Type_getClass(), and Type_getOid().
Referenced by Date_initialize().
_LocalDate_coerceDatum()
static jvalue _LocalDate_coerceDatum (Type self, Datum arg) static
Definition at line 57 of file Date.c.
{
    DateADT pgDate = DatumGetDateADT(arg);
    jlong days = (jlong)pgDate + EPOCH_DIFF;
    jvalue result;
    result.l = JNI_callStaticObjectMethod(
        s_LocalDate_class, s_LocalDate_ofEpochDay, days);
    return result;
}
References EPOCH_DIFF, JNI_callStaticObjectMethod(), s_LocalDate_class, and s_LocalDate_ofEpochDay.
Referenced by Date_initialize().
_LocalDate_coerceObject()
static Datum _LocalDate_coerceObject (Type self, jobject date) static
Definition at line 67 of file Date.c.
{
    jlong days =
        JNI_callLongMethod(date, s_LocalDate_toEpochDay) - EPOCH_DIFF;
    return DateADTGetDatum((DateADT)(days));
}
References EPOCH_DIFF, JNI_callLongMethod(), and s_LocalDate_toEpochDay.
Referenced by Date_initialize().
_LocalDate_obtain()
static Type _LocalDate_obtain (Oid typeId) static
Definition at line 74 of file Date.c.
{
    static Type instance = NULL;
    if ( NULL == instance )
    {
        s_LocalDate_class = JNI_newGlobalRef(PgObject_getJavaClass(
            "java/time/LocalDate"));
        s_LocalDate_ofEpochDay = PgObject_getStaticJavaMethod(s_LocalDate_class,
            "ofEpochDay", "(J)Ljava/time/LocalDate;");
        s_LocalDate_toEpochDay = PgObject_getJavaMethod(s_LocalDate_class,
            "toEpochDay", "()J");
        instance = TypeClass_allocInstance(s_LocalDateClass, DATEOID);
    }
    return instance;
}
References JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_getStaticJavaMethod(), s_LocalDate_class, s_LocalDate_ofEpochDay, s_LocalDate_toEpochDay, s_LocalDateClass, Type, and TypeClass_allocInstance().
Referenced by Date_initialize().
Date_initialize()
void Date_initialize (void) extern
Definition at line 124 of file Date.c.
{
    TypeClass cls = TypeClass_alloc("type.Date");
    cls->JNISignature = "Ljava/sql/Date;";
    cls->javaTypeName = "java.sql.Date";
    cls->coerceDatum  = _Date_coerceDatum;
    cls->coerceObject = _Date_coerceObject;
    Type_registerType("java.sql.Date", TypeClass_allocInstance(cls, DATEOID));
    s_Date_class = JNI_newGlobalRef(PgObject_getJavaClass("java/sql/Date"));
    s_Date_init = PgObject_getJavaMethod(s_Date_class, "<init>", "(J)V");
    s_Date_getTime = PgObject_getJavaMethod(s_Date_class, "getTime",  "()J");
    cls = TypeClass_alloc("type.LocalDate");
    cls->JNISignature = "Ljava/time/LocalDate;";
    cls->javaTypeName = "java.time.LocalDate";
    cls->canReplaceType = _LocalDate_canReplaceType;
    cls->coerceDatum  = _LocalDate_coerceDatum;
    cls->coerceObject = _LocalDate_coerceObject;
    s_LocalDateClass  = cls;
    Type_registerType2(InvalidOid, "java.time.LocalDate", _LocalDate_obtain);
}
References _Date_coerceDatum(), _Date_coerceObject(), _LocalDate_canReplaceType(), _LocalDate_coerceDatum(), _LocalDate_coerceObject(), _LocalDate_obtain(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Date_class, s_Date_getTime, s_Date_init, s_LocalDateClass, Type_registerType(), Type_registerType2(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Variable Documentation
s_Date_class
jclass s_Date_class static
Definition at line 24 of file Date.c.
Referenced by _Date_coerceDatum(), and Date_initialize().
s_Date_getTime
jmethodID s_Date_getTime static
Definition at line 26 of file Date.c.
Referenced by _Date_coerceObject(), and Date_initialize().
s_Date_init
jmethodID s_Date_init static
Definition at line 25 of file Date.c.
Referenced by _Date_coerceDatum(), and Date_initialize().
s_LocalDate_class
jclass s_LocalDate_class static
Definition at line 33 of file Date.c.
Referenced by _LocalDate_coerceDatum(), and _LocalDate_obtain().
s_LocalDate_ofEpochDay
jmethodID s_LocalDate_ofEpochDay static
Definition at line 34 of file Date.c.
Referenced by _LocalDate_coerceDatum(), and _LocalDate_obtain().
s_LocalDate_toEpochDay
jmethodID s_LocalDate_toEpochDay static
Definition at line 35 of file Date.c.
Referenced by _LocalDate_coerceObject(), and _LocalDate_obtain().
s_LocalDateClass
TypeClass s_LocalDateClass static
Definition at line 28 of file Date.c.
Referenced by _LocalDate_obtain(), and Date_initialize().