PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Relation.c File Reference
Relation.c File Reference
#include <postgres.h>
#include <executor/spi.h>
#include "org_postgresql_pljava_internal_Relation.h"
#include "pljava/DualState.h"
#include "pljava/Exception.h"
#include "pljava/Invocation.h"
#include "pljava/SPI.h"
#include "pljava/type/Type_priv.h"
#include "pljava/type/String.h"
#include "pljava/type/TupleDesc.h"
#include "pljava/type/Tuple.h"
#include "pljava/type/Relation.h"
Functions
jobject pljava_Relation_create (Relation r)
void pljava_Relation_initialize (void)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_Relation__1getName (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_Relation__1getSchema (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Relation__1getTupleDesc (JNIEnv *env, jclass clazz, jlong _this)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Relation__1modifyTuple (JNIEnv *env, jclass clazz, jlong _this, jlong _tuple, jintArray _indexes, jobjectArray _values)
Variables
static jclass s_Relation_class
static jmethodID s_Relation_init
Function Documentation
Java_org_postgresql_pljava_internal_Relation__1getName()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_Relation__1getName (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 99 of file Relation.c.
{
    jstring result = 0;
    Relation self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (Relation)p2l.ptrVal;
    if(self != 0)
    {
        BEGIN_NATIVE
        PG_TRY();
        {
            char* relName = SPI_getrelname(self);
            result = String_createJavaStringFromNTS(relName);
            pfree(relName);
        }
        PG_CATCH();
        {
            Exception_throw_ERROR("SPI_getrelname");
        }
        PG_END_TRY();
        END_NATIVE
    }
    return result;
}
References Exception_throw_ERROR(), and String_createJavaStringFromNTS().
Referenced by pljava_Relation_initialize().
Java_org_postgresql_pljava_internal_Relation__1getSchema()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_Relation__1getSchema (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 132 of file Relation.c.
{
    jstring result = 0;
    Relation self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (Relation)p2l.ptrVal;
    if(self != 0)
    {
        BEGIN_NATIVE
        PG_TRY();
        {
            char* schema = SPI_getnspname(self);
            result = String_createJavaStringFromNTS(schema);
            pfree(schema);
        }
        PG_CATCH();
        {
            Exception_throw_ERROR("SPI_getnspname");
        }
        PG_END_TRY();
        END_NATIVE
    }
    return result;
}
References Exception_throw_ERROR(), and String_createJavaStringFromNTS().
Referenced by pljava_Relation_initialize().
Java_org_postgresql_pljava_internal_Relation__1getTupleDesc()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Relation__1getTupleDesc (JNIEnv * env, jclass clazz, jlong _this)
Definition at line 165 of file Relation.c.
{
    jobject result = 0;
    Relation self;
    Ptr2Long p2l;
    p2l.longVal = _this;
    self = (Relation)p2l.ptrVal;
    if(self != 0)
    {
        BEGIN_NATIVE
        result = pljava_TupleDesc_create(self->rd_att);
        END_NATIVE
    }
    return result;
}
References pljava_TupleDesc_create().
Referenced by pljava_Relation_initialize().
Java_org_postgresql_pljava_internal_Relation__1modifyTuple()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Relation__1modifyTuple (JNIEnv * env, jclass clazz, jlong _this, jlong _tuple, jintArray _indexes, jobjectArray _values)
Definition at line 198 of file Relation.c.
{
    jobject result = 0;
    Relation self;
    Ptr2Long p2lr;
    p2lr.longVal = _this;
    self = (Relation)p2lr.ptrVal;
    if(self != 0 && _tuple != 0)
    {
        Ptr2Long p2lt;
        p2lt.longVal = _tuple;
        BEGIN_NATIVE
        HeapTuple tuple = (HeapTuple)p2lt.ptrVal;
        PG_TRY();
        {
            jint idx;
            TupleDesc tupleDesc = self->rd_att;
            jobject typeMap = Invocation_getTypeMap();
            jint   count  = JNI_getArrayLength(_indexes);
            Datum* values = (Datum*)palloc(count * sizeof(Datum));
            char*  nulls  = 0;
            jint* javaIdxs = JNI_getIntArrayElements(_indexes, 0);
            int* indexes;
            if(sizeof(int) == sizeof(jint)) /* compiler will optimize this */
                indexes = (int*)javaIdxs;
            else
                indexes = (int*)palloc(count * sizeof(int));
            for(idx = 0; idx < count; ++idx)
            {
                int attIndex;
                Oid typeId;
                Type type;
                jobject value;
                if(sizeof(int) == sizeof(jint)) /* compiler will optimize this */
                    attIndex = indexes[idx];
                else
                {
                    attIndex = (int)javaIdxs[idx];
                    indexes[idx] = attIndex;
                }
                typeId = SPI_gettypeid(tupleDesc, attIndex);
                if(!OidIsValid(typeId))
                {
                    Exception_throw(ERRCODE_INVALID_DESCRIPTOR_INDEX,
                        "Invalid attribute index \"%d\"", attIndex);
                    return 0L;  /* Exception */
                }
                type = Type_fromOid(typeId, typeMap);
                value = JNI_getObjectArrayElement(_values, idx);
                if(value != 0)
                    values[idx] = Type_coerceObjectBridged(type, value);
                else
                {
                    if(nulls == 0)
                    {
                        nulls = (char*)palloc(count+1);
                        memset(nulls, ' ', count);  /* all values non-null initially */
                        nulls[count] = 0;
                    }
                    nulls[idx] = 'n';
                    values[idx] = 0;
                }
            }
            tuple = SPI_modifytuple(self, tuple, count, indexes, values, nulls);
            if(tuple == 0)
                Exception_throwSPI("modifytuple", SPI_result);
            JNI_releaseIntArrayElements(_indexes, javaIdxs, JNI_ABORT);
            if(sizeof(int) != sizeof(jint)) /* compiler will optimize this */
                pfree(indexes);
            pfree(values);
            if(nulls != 0)
                pfree(nulls);
        }
        PG_CATCH();
        {
            tuple = 0;
            Exception_throw_ERROR("SPI_gettypeid");
        }
        PG_END_TRY();
        if(tuple != 0)
            result = pljava_Tuple_create(tuple);
        END_NATIVE
    }
    return result;
}
References Exception_throw(), Exception_throw_ERROR(), Exception_throwSPI(), Invocation_getTypeMap(), jint(), JNI_getArrayLength(), JNI_getIntArrayElements(), JNI_getObjectArrayElement(), JNI_releaseIntArrayElements(), pljava_Tuple_create(), Type, Type_coerceObjectBridged(), and Type_fromOid().
Referenced by pljava_Relation_initialize().
pljava_Relation_create()
jobject pljava_Relation_create (Relation r)
Definition at line 35 of file Relation.c.
{
    Ptr2Long p2lr;
    Ptr2Long p2lro;
    if ( NULL == r )
        return NULL;
    p2lr.longVal = 0L;
    p2lr.ptrVal = r;
    p2lro.longVal = 0L;
    p2lro.ptrVal = currentInvocation;
    return JNI_newObjectLocked(
            s_Relation_class,
            s_Relation_init,
            pljava_DualState_key(),
            p2lro.longVal,
            p2lr.longVal);
}
References currentInvocation, JNI_newObjectLocked(), pljava_DualState_key(), s_Relation_class, and s_Relation_init.
Referenced by Java_org_postgresql_pljava_internal_TriggerData__1getRelation().
pljava_Relation_initialize()
void pljava_Relation_initialize (void)
Definition at line 57 of file Relation.c.
{
    JNINativeMethod methods[] =
    {
        {
        "_getName",
        "(J)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_Relation__1getName
        },
        {
        "_getSchema",
        "(J)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_Relation__1getSchema
        },
        {
        "_getTupleDesc",
        "(J)Lorg/postgresql/pljava/internal/TupleDesc;",
        Java_org_postgresql_pljava_internal_Relation__1getTupleDesc
        },
        {
        "_modifyTuple",
        "(JJ[I[Ljava/lang/Object;)Lorg/postgresql/pljava/internal/Tuple;",
        Java_org_postgresql_pljava_internal_Relation__1modifyTuple
        },
        { 0, 0, 0 }
    };
    s_Relation_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/internal/Relation"));
    PgObject_registerNatives2(s_Relation_class, methods);
    s_Relation_init = PgObject_getJavaMethod(s_Relation_class, "<init>",
        "(Lorg/postgresql/pljava/internal/DualState$Key;JJ)V");
}
References Java_org_postgresql_pljava_internal_Relation__1getName(), Java_org_postgresql_pljava_internal_Relation__1getSchema(), Java_org_postgresql_pljava_internal_Relation__1getTupleDesc(), Java_org_postgresql_pljava_internal_Relation__1modifyTuple(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_registerNatives2(), s_Relation_class, and s_Relation_init.
Referenced by pljava_DualState_initialize().
Variable Documentation
s_Relation_class
jclass s_Relation_class static
Definition at line 29 of file Relation.c.
Referenced by pljava_Relation_create(), and pljava_Relation_initialize().
s_Relation_init
jmethodID s_Relation_init static
Definition at line 30 of file Relation.c.
Referenced by pljava_Relation_create(), and pljava_Relation_initialize().