PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/PgSavepoint.c File Reference
PgSavepoint.c File Reference
#include <postgres.h>
#include <access/xact.h>
#include <executor/spi.h>
#include <executor/tuptable.h>
#include "org_postgresql_pljava_internal_PgSavepoint.h"
#include "pljava/PgSavepoint.h"
#include "pljava/Exception.h"
#include "pljava/Invocation.h"
#include "pljava/type/String.h"
#include "pljava/SPI.h"
Functions
void PgSavepoint_initialize (void)
static void unwind (void(*f)(void), jint xid, jint nestingLevel)
static void assertXid (SubTransactionId)
jobject pljava_PgSavepoint_forId (SubTransactionId subId)
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_PgSavepoint__1set (JNIEnv *env, jobject this, jstring jname)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_PgSavepoint__1release (JNIEnv *env, jclass clazz, jint xid, jint nestLevel)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_PgSavepoint__1rollback (JNIEnv *env, jclass clazz, jint xid, jint nestLevel)
Variables
static jclass s_PgSavepoint_class
static jmethodID s_forId
static jfieldID s_nestLevel
Function Documentation
assertXid()
static void assertXid (SubTransactionId xid) static
Definition at line 112 of file PgSavepoint.c.
{
    if(xid != GetCurrentSubTransactionId())
    {
        /* Oops. Rollback to top level transaction.
         */
        ereport(ERROR, (
            errcode(ERRCODE_INVALID_TRANSACTION_TERMINATION),
            errmsg("Subtransaction mismatch at txlevel %d",
                GetCurrentTransactionNestLevel())));
    }
}
Referenced by unwind().
Java_org_postgresql_pljava_internal_PgSavepoint__1release()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_PgSavepoint__1release (JNIEnv * env, jclass clazz, jint xid, jint nestLevel)
Definition at line 163 of file PgSavepoint.c.
{
    BEGIN_NATIVE
    PG_TRY();
    {
        unwind(ReleaseCurrentSubTransaction, xid, nestLevel);
    }
    PG_CATCH();
    {
        Exception_throw_ERROR("releaseSavepoint");
    }
    PG_END_TRY();
    END_NATIVE
}
References Exception_throw_ERROR(), and unwind().
Referenced by PgSavepoint_initialize().
Java_org_postgresql_pljava_internal_PgSavepoint__1rollback()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_PgSavepoint__1rollback (JNIEnv * env, jclass clazz, jint xid, jint nestLevel)
Definition at line 184 of file PgSavepoint.c.
{
    BEGIN_NATIVE
    PG_TRY();
    {
        unwind(RollbackAndReleaseCurrentSubTransaction, xid, nestLevel);
#if PG_VERSION_NUM < 100000
        SPI_restore_connection();
#endif
    }
    PG_CATCH();
    {
        Exception_throw_ERROR("rollbackSavepoint");
    }
    PG_END_TRY();
    END_NATIVE
}
References Exception_throw_ERROR(), and unwind().
Referenced by PgSavepoint_initialize().
Java_org_postgresql_pljava_internal_PgSavepoint__1set()
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_PgSavepoint__1set (JNIEnv * env, jobject this, jstring jname)
Definition at line 134 of file PgSavepoint.c.
{
    jint xid = 0;
    BEGIN_NATIVE
    PG_TRY();
    {
        char* name = String_createNTS(jname);
        Invocation_assertConnect();
        JNI_setIntField(this, s_nestLevel, 1+GetCurrentTransactionNestLevel());
        BeginInternalSubTransaction(name);
        xid = GetCurrentSubTransactionId();
        if ( NULL != name )
            pfree(name);
    }
    PG_CATCH();
    {
        Exception_throw_ERROR("setSavepoint");
    }
    PG_END_TRY();
    END_NATIVE
    return xid;
}
References Exception_throw_ERROR(), Invocation_assertConnect(), jint(), JNI_setIntField(), s_nestLevel, and String_createNTS().
Referenced by PgSavepoint_initialize().
PgSavepoint_initialize()
void PgSavepoint_initialize (void) extern
Definition at line 60 of file PgSavepoint.c.
{
    JNINativeMethod methods[] =
    {
        {
        "_set",
        "(Ljava/lang/String;)I",
        Java_org_postgresql_pljava_internal_PgSavepoint__1set
        },
        {
        "_release",
        "(II)V",
        Java_org_postgresql_pljava_internal_PgSavepoint__1release
        },
        {
        "_rollback",
        "(II)V",
        Java_org_postgresql_pljava_internal_PgSavepoint__1rollback
        },
        { 0, 0, 0 }
    };
    PgObject_registerNatives("org/postgresql/pljava/internal/PgSavepoint",
        methods);
    /*
     * I would rather put this at the top, but it counts as a statement, and
     * would trigger a declaration-after-statement warning.
     */
    StaticAssertStmt(sizeof(SubTransactionId) <= sizeof(jint),
        "SubTransactionId wider than jint?!");
    s_PgSavepoint_class = JNI_newGlobalRef(PgObject_getJavaClass(
        "org/postgresql/pljava/internal/PgSavepoint"));
    s_forId =
        PgObject_getStaticJavaMethod(s_PgSavepoint_class, "forId",
            "(I)Lorg/postgresql/pljava/internal/PgSavepoint;");
    s_nestLevel =
        PgObject_getJavaField(s_PgSavepoint_class, "m_nestLevel", "I");
}
References Java_org_postgresql_pljava_internal_PgSavepoint__1release(), Java_org_postgresql_pljava_internal_PgSavepoint__1rollback(), Java_org_postgresql_pljava_internal_PgSavepoint__1set(), jint(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaField(), PgObject_getStaticJavaMethod(), PgObject_registerNatives(), s_forId, s_nestLevel, and s_PgSavepoint_class.
Referenced by initPLJavaClasses().
pljava_PgSavepoint_forId()
jobject pljava_PgSavepoint_forId (SubTransactionId subId)
Definition at line 54 of file PgSavepoint.c.
{
    return JNI_callStaticObjectMethodLocked(s_PgSavepoint_class, s_forId,
            (jint)subId);
}
References jint(), JNI_callStaticObjectMethodLocked(), s_forId, and s_PgSavepoint_class.
Referenced by subXactCB().
unwind()
static void unwind (void(*)(void) f, jint xid, jint nestingLevel) static
Definition at line 100 of file PgSavepoint.c.
{
    while ( nestingLevel < GetCurrentTransactionNestLevel() )
        f();
    if ( nestingLevel == GetCurrentTransactionNestLevel() )
    {
        assertXid((SubTransactionId)xid);
        f();
    }
}
References assertXid().
Referenced by Java_org_postgresql_pljava_internal_PgSavepoint__1release(), and Java_org_postgresql_pljava_internal_PgSavepoint__1rollback().
Variable Documentation
s_forId
jmethodID s_forId static
Definition at line 47 of file PgSavepoint.c.
Referenced by PgSavepoint_initialize(), and pljava_PgSavepoint_forId().
s_nestLevel
jfieldID s_nestLevel static
Definition at line 48 of file PgSavepoint.c.
Referenced by Java_org_postgresql_pljava_internal_PgSavepoint__1set(), and PgSavepoint_initialize().
s_PgSavepoint_class
jclass s_PgSavepoint_class static
Definition at line 46 of file PgSavepoint.c.
Referenced by PgSavepoint_initialize(), and pljava_PgSavepoint_forId().