PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Composite.c File Reference
Composite.c File Reference
#include <postgres.h>
#include <funcapi.h>
#include <utils/typcache.h>
#include "pljava/type/Type_priv.h"
#include "pljava/type/Composite.h"
#include "pljava/type/TupleDesc.h"
#include "pljava/type/SingleRowReader.h"
#include "pljava/Invocation.h"
#include "org_postgresql_pljava_jdbc_SingleRowReader.h"
Data Structures
struct Composite
Functions
static jobject _createWriter (jobject tupleDesc)
static HeapTuple _getTupleAndClear (jobject jrps)
static Datum _Composite_invoke (Type self, Function fn, PG_FUNCTION_ARGS)
static jobject _Composite_getSRFCollector (Type self, PG_FUNCTION_ARGS)
static Datum _Composite_datumFromSRF (Type self, jobject row, jobject rowCollector)
static jvalue _Composite_coerceDatum (Type self, Datum arg)
static TupleDesc createGlobalTupleDescCopy (TupleDesc td)
static TupleDesc _Composite_getTupleDesc (Type self, PG_FUNCTION_ARGS)
Type Composite_obtain (Oid typeId)
void Composite_initialize (void)
Variables
static jclass s_ResultSetProvider_class
static jmethodID s_ResultSetProvider_assignRowValues
static jmethodID s_ResultSetProvider_close
static jclass s_ResultSetHandle_class
static jclass s_ResultSetPicker_class
static jmethodID s_ResultSetPicker_init
static jclass s_SingleRowWriter_class
static jmethodID s_SingleRowWriter_init
static jmethodID s_SingleRowWriter_getTupleAndClear
static TypeClass s_CompositeClass
Data Structure Documentation
Composite_
struct Composite_
Definition at line 24 of file Composite.c.
Data Fields
TupleDesc m_tupleDesc
struct Type_ Type_extension
Function Documentation
_Composite_coerceDatum()
static jvalue _Composite_coerceDatum (Type self, Datum arg) static
Definition at line 140 of file Composite.c.
{
    jvalue result;
    HeapTupleHeader hth = DatumGetHeapTupleHeader(arg);
    result.l = 0;
    if(hth == 0)
        return result;
    result.l = pljava_SingleRowReader_create(hth);
    return result;
}
References pljava_SingleRowReader_create().
Referenced by Composite_initialize().
_Composite_datumFromSRF()
static Datum _Composite_datumFromSRF (Type self, jobject row, jobject rowCollector) static
Definition at line 127 of file Composite.c.
{
    Datum result = 0;
    HeapTuple tuple = _getTupleAndClear(rowCollector);
    if(tuple != 0)
        result = HeapTupleGetDatum(tuple);
    return result;
}
References _getTupleAndClear().
Referenced by Composite_initialize().
_Composite_getSRFCollector()
static jobject _Composite_getSRFCollector (Type self, PG_FUNCTION_ARGS) static
Definition at line 113 of file Composite.c.
{
    jobject tmp1;
    jobject tmp2;
    TupleDesc tupleDesc = Type_getTupleDesc(self, fcinfo);
    if(tupleDesc == 0)
        ereport(ERROR, (errmsg("Unable to find tuple descriptor")));
    tmp1 = pljava_TupleDesc_create(tupleDesc);
    tmp2 = _createWriter(tmp1);
    JNI_deleteLocalRef(tmp1);
    return tmp2;
}
References _createWriter(), JNI_deleteLocalRef(), pljava_TupleDesc_create(), and Type_getTupleDesc().
Referenced by Composite_initialize().
_Composite_getTupleDesc()
static TupleDesc _Composite_getTupleDesc (Type self, PG_FUNCTION_ARGS) static
Definition at line 161 of file Composite.c.
{
    TupleDesc td = ((Composite)self)->m_tupleDesc;
    if(td != 0)
        return td;
    switch(get_call_result_type(fcinfo, 0, &td))
    {
        case TYPEFUNC_COMPOSITE:
        case TYPEFUNC_RECORD:
            if(td == 0)
            {
                ereport(ERROR,
                    (errcode(ERRCODE_DATATYPE_MISMATCH),
                     errmsg("function returning record is missing "
                        " result type (try AS?)")));
                break;
            }
            if(td->tdtypeid == RECORDOID)
                /*
                 * We can't hold on to this one. It's anonymous
                 * and may vary between calls.
                 */
                td = CreateTupleDescCopy(td);
            else
            {
                td = createGlobalTupleDescCopy(td);
                ((Composite)self)->m_tupleDesc = td;
            }
            break;
        default:
            ereport(ERROR,
                (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
                 errmsg("function returning record called in context "
                        "that cannot accept type record")));
    }
    return td;
}
References createGlobalTupleDescCopy().
Referenced by Composite_initialize().
_Composite_invoke()
static Datum _Composite_invoke (Type self, Function fn, PG_FUNCTION_ARGS) static
Definition at line 79 of file Composite.c.
{
    bool hasRow;
    Datum result = 0;
    TupleDesc tupleDesc = Type_getTupleDesc(self, fcinfo);
    jobject jtd = pljava_TupleDesc_create(tupleDesc);
    jvalue singleRowWriter;
    singleRowWriter.l = _createWriter(jtd);
    /*
     * Caller guarantees room for one extra reference parameter, so it will go
     * at index (length - 1).
     */
    pljava_Function_setParameter(fn, -1, singleRowWriter);
    hasRow = (pljava_Function_booleanInvoke(fn) == JNI_TRUE);
    if(hasRow)
    {
        /* Obtain tuple and return it as a Datum. Must be done using a more
         * durable context.
         */
        MemoryContext currCtx = Invocation_switchToUpperContext();
        HeapTuple tuple = _getTupleAndClear(singleRowWriter.l);
        result = HeapTupleGetDatum(tuple);
        MemoryContextSwitchTo(currCtx);
    }
    else
        fcinfo->isnull = true;
    JNI_deleteLocalRef(jtd);
    JNI_deleteLocalRef(singleRowWriter.l);
    return result;
}
References _createWriter(), _getTupleAndClear(), Invocation_switchToUpperContext(), JNI_deleteLocalRef(), pljava_Function_booleanInvoke(), pljava_Function_setParameter(), pljava_TupleDesc_create(), and Type_getTupleDesc().
Referenced by Composite_initialize().
_createWriter()
static jobject _createWriter (jobject tupleDesc) static
Definition at line 55 of file Composite.c.
{
    return JNI_newObject(s_SingleRowWriter_class, s_SingleRowWriter_init, tupleDesc);
}
References JNI_newObject(), s_SingleRowWriter_class, and s_SingleRowWriter_init.
Referenced by _Composite_getSRFCollector(), and _Composite_invoke().
_getTupleAndClear()
static HeapTuple _getTupleAndClear (jobject jrps) static
Definition at line 60 of file Composite.c.
{
    Ptr2Long p2l;
    if(jrps == 0)
        return 0;
    p2l.longVal = JNI_callLongMethod(jrps, s_SingleRowWriter_getTupleAndClear);
    return (HeapTuple)p2l.ptrVal;
}
References JNI_callLongMethod(), and s_SingleRowWriter_getTupleAndClear.
Referenced by _Composite_datumFromSRF(), and _Composite_invoke().
Composite_initialize()
void Composite_initialize (void) extern
Definition at line 217 of file Composite.c.
{
    s_SingleRowWriter_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/jdbc/SingleRowWriter"));
    s_SingleRowWriter_init = PgObject_getJavaMethod(s_SingleRowWriter_class, "<init>", "(Lorg/postgresql/pljava/internal/TupleDesc;)V");
    s_SingleRowWriter_getTupleAndClear = PgObject_getJavaMethod(s_SingleRowWriter_class, "getTupleAndClear", "()J");
    s_ResultSetProvider_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/ResultSetProvider"));
    s_ResultSetProvider_assignRowValues = PgObject_getJavaMethod(s_ResultSetProvider_class, "assignRowValues", "(Ljava/sql/ResultSet;I)Z");
    s_ResultSetProvider_close = PgObject_getJavaMethod(s_ResultSetProvider_class, "close", "()V");
    s_ResultSetHandle_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/ResultSetHandle"));
    s_ResultSetPicker_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/internal/ResultSetPicker"));
    s_ResultSetPicker_init = PgObject_getJavaMethod(s_ResultSetPicker_class, "<init>", "(Lorg/postgresql/pljava/ResultSetHandle;)V");
    s_CompositeClass = TypeClass_alloc2("type.Composite", sizeof(struct TypeClass_), sizeof(struct Composite_));
    s_CompositeClass->JNISignature    = "Ljava/sql/ResultSet;";
    s_CompositeClass->javaTypeName    = "java.sql.ResultSet";
    s_CompositeClass->getTupleDesc    = _Composite_getTupleDesc;
    s_CompositeClass->coerceDatum     = _Composite_coerceDatum;
    s_CompositeClass->invoke          = _Composite_invoke;
    s_CompositeClass->getSRFCollector = _Composite_getSRFCollector;
    s_CompositeClass->datumFromSRF    = _Composite_datumFromSRF;
    s_CompositeClass->outParameter    = true;
    Type_registerType2(InvalidOid, "java.sql.ResultSet", Composite_obtain);
}
References _Composite_coerceDatum(), _Composite_datumFromSRF(), _Composite_getSRFCollector(), _Composite_getTupleDesc(), _Composite_invoke(), Composite_obtain(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_CompositeClass, s_ResultSetHandle_class, s_ResultSetPicker_class, s_ResultSetPicker_init, s_ResultSetProvider_assignRowValues, s_ResultSetProvider_class, s_ResultSetProvider_close, s_SingleRowWriter_class, s_SingleRowWriter_getTupleAndClear, s_SingleRowWriter_init, Type_registerType2(), and TypeClass_alloc2().
Referenced by Type_initialize().
Composite_obtain()
Type Composite_obtain (Oid typeId)
Definition at line 200 of file Composite.c.
{
    Composite infant = (Composite)TypeClass_allocInstance(s_CompositeClass, typeId);
    if(typeId == RECORDOID)
        infant->m_tupleDesc = 0;
    else
    {
        TupleDesc tmp = lookup_rowtype_tupdesc(typeId, -1);
        infant->m_tupleDesc = createGlobalTupleDescCopy(tmp);
        ReleaseTupleDesc(tmp);
    }
    return (Type)infant;
}
References createGlobalTupleDescCopy(), Composite::m_tupleDesc, s_CompositeClass, Type, and TypeClass_allocInstance().
Referenced by Composite_initialize(), Function_initialize(), and Type_fromOid().
createGlobalTupleDescCopy()
static TupleDesc createGlobalTupleDescCopy (TupleDesc td) static
Definition at line 153 of file Composite.c.
{
    MemoryContext curr = MemoryContextSwitchTo(TopMemoryContext);
    td = CreateTupleDescCopyConstr(td);
    MemoryContextSwitchTo(curr);
    return td;
}
Referenced by _Composite_getTupleDesc(), and Composite_obtain().
Variable Documentation
s_CompositeClass
TypeClass s_CompositeClass static
Definition at line 53 of file Composite.c.
Referenced by Composite_initialize(), and Composite_obtain().
s_ResultSetHandle_class
jclass s_ResultSetHandle_class static
Definition at line 45 of file Composite.c.
Referenced by Composite_initialize().
s_ResultSetPicker_class
jclass s_ResultSetPicker_class static
Definition at line 46 of file Composite.c.
Referenced by Composite_initialize().
s_ResultSetPicker_init
jmethodID s_ResultSetPicker_init static
Definition at line 47 of file Composite.c.
Referenced by Composite_initialize().
s_ResultSetProvider_assignRowValues
jmethodID s_ResultSetProvider_assignRowValues static
Definition at line 42 of file Composite.c.
Referenced by Composite_initialize().
s_ResultSetProvider_class
jclass s_ResultSetProvider_class static
Definition at line 41 of file Composite.c.
Referenced by Composite_initialize().
s_ResultSetProvider_close
jmethodID s_ResultSetProvider_close static
Definition at line 43 of file Composite.c.
Referenced by Composite_initialize().
s_SingleRowWriter_class
jclass s_SingleRowWriter_class static
Definition at line 49 of file Composite.c.
Referenced by _createWriter(), and Composite_initialize().
s_SingleRowWriter_getTupleAndClear
jmethodID s_SingleRowWriter_getTupleAndClear static
Definition at line 51 of file Composite.c.
Referenced by _getTupleAndClear(), and Composite_initialize().
s_SingleRowWriter_init
jmethodID s_SingleRowWriter_init static
Definition at line 50 of file Composite.c.
Referenced by _createWriter(), and Composite_initialize().