PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Tuple.c File Reference
Tuple.c File Reference
#include <postgres.h>
#include <executor/spi.h>
#include <executor/tuptable.h>
#include "org_postgresql_pljava_internal_Tuple.h"
#include "pljava/Backend.h"
#include "pljava/DualState.h"
#include "pljava/Exception.h"
#include "pljava/type/Type_priv.h"
#include "pljava/type/Tuple.h"
#include "pljava/type/TupleDesc.h"
Functions
jobject pljava_Tuple_create (HeapTuple ht)
jobjectArray pljava_Tuple_createArray (HeapTuple *vals, jint size, bool mustCopy)
jobject pljava_Tuple_internalCreate (HeapTuple ht, bool mustCopy)
static jvalue _Tuple_coerceDatum (Type self, Datum arg)
void pljava_Tuple_initialize (void)
jobject pljava_Tuple_getObject (TupleDesc tupleDesc, HeapTuple tuple, int index, jclass rqcls)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Tuple__1getObject (JNIEnv *env, jclass cls, jlong _this, jlong _tupleDesc, jint index, jclass rqcls)
Variables
static jclass s_Tuple_class
static jmethodID s_Tuple_init
Function Documentation
_Tuple_coerceDatum()
static jvalue _Tuple_coerceDatum (Type self, Datum arg) static
Definition at line 79 of file Tuple.c.
{
    jvalue result;
    result.l = pljava_Tuple_create((HeapTuple)DatumGetPointer(arg));
    return result;
}
References pljava_Tuple_create().
Referenced by pljava_Tuple_initialize().
Java_org_postgresql_pljava_internal_Tuple__1getObject()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Tuple__1getObject (JNIEnv * env, jclass cls, jlong _this, jlong _tupleDesc, jint index, jclass rqcls)
Definition at line 146 of file Tuple.c.
{
    jobject result = 0;
    Ptr2Long p2l;
    p2l.longVal = _this;
    BEGIN_NATIVE
    HeapTuple self = (HeapTuple)p2l.ptrVal;
    p2l.longVal = _tupleDesc;
    result = pljava_Tuple_getObject((TupleDesc)p2l.ptrVal, self, (int)index, rqcls);
    END_NATIVE
    return result;
}
References pljava_Tuple_getObject().
Referenced by pljava_Tuple_initialize().
pljava_Tuple_create()
jobject pljava_Tuple_create (HeapTuple ht)
Definition at line 33 of file Tuple.c.
{
    jobject jht = 0;
    if(ht != 0)
    {
        MemoryContext curr = MemoryContextSwitchTo(JavaMemoryContext);
        jht = pljava_Tuple_internalCreate(ht, true);
        MemoryContextSwitchTo(curr);
    }
    return jht;
}
References JavaMemoryContext, and pljava_Tuple_internalCreate().
Referenced by _Tuple_coerceDatum(), Java_org_postgresql_pljava_internal_Relation__1modifyTuple(), Java_org_postgresql_pljava_internal_TriggerData__1getNewTuple(), and Java_org_postgresql_pljava_internal_TriggerData__1getTriggerTuple().
pljava_Tuple_createArray()
jobjectArray pljava_Tuple_createArray (HeapTuple * vals, jint size, bool mustCopy)
Definition at line 45 of file Tuple.c.
{
    jobjectArray tuples = JNI_newObjectArray(size, s_Tuple_class, 0);
    while(--size >= 0)
    {
        jobject heapTuple = pljava_Tuple_internalCreate(vals[size], mustCopy);
        JNI_setObjectArrayElement(tuples, size, heapTuple);
        JNI_deleteLocalRef(heapTuple);
    }
    return tuples;
}
References JNI_deleteLocalRef(), JNI_newObjectArray(), JNI_setObjectArrayElement(), pljava_Tuple_internalCreate(), and s_Tuple_class.
Referenced by TupleTable_create(), and TupleTable_createFromSlot().
pljava_Tuple_getObject()
jobject pljava_Tuple_getObject (TupleDesc tupleDesc, HeapTuple tuple, int index, jclass rqcls)
Definition at line 113 of file Tuple.c.
{
    jobject result = 0;
    PG_TRY();
    {
        Type type = pljava_TupleDesc_getColumnType(tupleDesc, index);
        if(type != 0)
        {
            bool wasNull = false;
            Datum binVal = SPI_getbinval(tuple, tupleDesc, (int)index, &wasNull);
            if(!wasNull)
                result = Type_coerceDatumAs(type, binVal, rqcls).l;
        }
    }
    PG_CATCH();
    {
        Exception_throw_ERROR("SPI_getbinval");
    }
    PG_END_TRY();
    return result;
}
References Exception_throw_ERROR(), pljava_TupleDesc_getColumnType(), Type, and Type_coerceDatumAs().
Referenced by Java_org_postgresql_pljava_internal_Tuple__1getObject().
pljava_Tuple_initialize()
void pljava_Tuple_initialize (void) extern
Definition at line 89 of file Tuple.c.
{
    TypeClass cls;
    JNINativeMethod methods[] = {
        {
        "_getObject",
        "(JJILjava/lang/Class;)Ljava/lang/Object;",
        Java_org_postgresql_pljava_internal_Tuple__1getObject
        },
        { 0, 0, 0 }};
    s_Tuple_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/internal/Tuple"));
    PgObject_registerNatives2(s_Tuple_class, methods);
    s_Tuple_init = PgObject_getJavaMethod(s_Tuple_class, "<init>",
        "(Lorg/postgresql/pljava/internal/DualState$Key;JJ)V");
    cls = TypeClass_alloc("type.Tuple");
    cls->JNISignature = "Lorg/postgresql/pljava/internal/Tuple;";
    cls->javaTypeName = "org.postgresql.pljava.internal.Tuple";
    cls->coerceDatum  = _Tuple_coerceDatum;
    Type_registerType("org.postgresql.pljava.internal.Tuple", TypeClass_allocInstance(cls, InvalidOid));
}
References _Tuple_coerceDatum(), Java_org_postgresql_pljava_internal_Tuple__1getObject(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_registerNatives2(), s_Tuple_class, s_Tuple_init, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by pljava_DualState_initialize().
pljava_Tuple_internalCreate()
jobject pljava_Tuple_internalCreate (HeapTuple ht, bool mustCopy)
Definition at line 57 of file Tuple.c.
{
    jobject jht;
    Ptr2Long htH;
    if(mustCopy)
        ht = heap_copytuple(ht);
    htH.longVal = 0L; /* ensure that the rest is zeroed out */
    htH.ptrVal = ht;
    /*
     * Passing (jlong)0 as the ResourceOwner means this will never be matched by a
     * nativeRelease call; that's appropriate (for now) as the Tuple copy is
     * being made into JavaMemoryContext, which never gets reset, so only
     * unreachability from the Java side will free it.
     * XXX? this seems like a lot of tuple copying.
     */
    jht = JNI_newObjectLocked(s_Tuple_class, s_Tuple_init,
        pljava_DualState_key(), (jlong)0, htH.longVal);
    return jht;
}
References JNI_newObjectLocked(), pljava_DualState_key(), s_Tuple_class, and s_Tuple_init.
Referenced by Java_org_postgresql_pljava_internal_TupleDesc__1formTuple(), pljava_Tuple_create(), and pljava_Tuple_createArray().
Variable Documentation
s_Tuple_class
jclass s_Tuple_class static
Definition at line 27 of file Tuple.c.
Referenced by pljava_Tuple_createArray(), pljava_Tuple_initialize(), and pljava_Tuple_internalCreate().
s_Tuple_init
jmethodID s_Tuple_init static
Definition at line 28 of file Tuple.c.
Referenced by pljava_Tuple_initialize(), and pljava_Tuple_internalCreate().