PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/byte_array.c File Reference
byte_array.c File Reference
#include "pljava/Exception.h"
#include "pljava/type/Type_priv.h"
Functions
static jvalue _byte_array_coerceDatum (Type self, Datum arg)
static Datum _byte_array_coerceObject (Type self, jobject byteArray)
void byte_array_initialize (void)
Variables
static jclass s_byteArray_class
static jclass s_BlobValue_class
static jmethodID s_BlobValue_length
static jmethodID s_BlobValue_getContents
Function Documentation
_byte_array_coerceDatum()
static jvalue _byte_array_coerceDatum (Type self, Datum arg) static
Definition at line 24 of file byte_array.c.
{
    jvalue result;
    bytea* bytes  = DatumGetByteaP(arg);
    jsize  length = VARSIZE(bytes) - VARHDRSZ;
    jbyteArray ba = JNI_newByteArray(length);
    JNI_setByteArrayRegion(ba, 0, length, (jbyte*)VARDATA(bytes));
    result.l = ba;
    return result;
}
References JNI_newByteArray(), and JNI_setByteArrayRegion().
Referenced by byte_array_initialize().
_byte_array_coerceObject()
static Datum _byte_array_coerceObject (Type self, jobject byteArray) static
Definition at line 35 of file byte_array.c.
{
    bytea* bytes = 0;
    if(byteArray == 0)
        return 0;
    if(JNI_isInstanceOf(byteArray, s_byteArray_class))
    {
        jsize  length    = JNI_getArrayLength((jarray)byteArray);
        int32  byteaSize = length + VARHDRSZ;
        bytes = (bytea*)palloc(byteaSize);
        SET_VARSIZE(bytes, byteaSize);
        JNI_getByteArrayRegion((jbyteArray)byteArray, 0, length, (jbyte*)VARDATA(bytes));
    }
    else if(JNI_isInstanceOf(byteArray, s_BlobValue_class))
    {
        jobject byteBuffer;
        int32 byteaSize;
        jlong length = JNI_callLongMethod(byteArray, s_BlobValue_length);
        byteaSize = (int32)(length + VARHDRSZ);
        bytes = (bytea*)palloc(byteaSize);
        SET_VARSIZE(bytes, byteaSize);
        byteBuffer = JNI_newDirectByteBuffer((void*)VARDATA(bytes), length);
        if(byteBuffer != 0)
            JNI_callVoidMethod(byteArray, s_BlobValue_getContents, byteBuffer);
        JNI_deleteLocalRef(byteBuffer);
    }
    else
    {
        Exception_throwIllegalArgument("Not coercable to bytea");
    }
    PG_RETURN_BYTEA_P(bytes);
}
References Exception_throwIllegalArgument(), JNI_callLongMethod(), JNI_callVoidMethod(), JNI_deleteLocalRef(), JNI_getArrayLength(), JNI_getByteArrayRegion(), JNI_isInstanceOf(), JNI_newDirectByteBuffer(), s_BlobValue_class, s_BlobValue_getContents, s_BlobValue_length, and s_byteArray_class.
Referenced by byte_array_initialize().
byte_array_initialize()
void byte_array_initialize (void) extern
Definition at line 76 of file byte_array.c.
{
    TypeClass cls = TypeClass_alloc("type.byte[]");
    cls->JNISignature = "[B";
    cls->javaTypeName = "byte[]";
    cls->coerceDatum  = _byte_array_coerceDatum;
    cls->coerceObject = _byte_array_coerceObject;
    Type_registerType("byte[]", TypeClass_allocInstance(cls, BYTEAOID));
    s_byteArray_class = JNI_newGlobalRef(PgObject_getJavaClass("[B"));
    s_BlobValue_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/jdbc/BlobValue"));
    s_BlobValue_length = PgObject_getJavaMethod(s_BlobValue_class, "length", "()J");
    s_BlobValue_getContents = PgObject_getJavaMethod(s_BlobValue_class, "getContents", "(Ljava/nio/ByteBuffer;)V");
}
References _byte_array_coerceDatum(), _byte_array_coerceObject(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_BlobValue_class, s_BlobValue_getContents, s_BlobValue_length, s_byteArray_class, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Variable Documentation
s_BlobValue_class
jclass s_BlobValue_class static
Definition at line 17 of file byte_array.c.
Referenced by _byte_array_coerceObject(), and byte_array_initialize().
s_BlobValue_getContents
jmethodID s_BlobValue_getContents static
Definition at line 19 of file byte_array.c.
Referenced by _byte_array_coerceObject(), and byte_array_initialize().
s_BlobValue_length
jmethodID s_BlobValue_length static
Definition at line 18 of file byte_array.c.
Referenced by _byte_array_coerceObject(), and byte_array_initialize().
s_byteArray_class
jclass s_byteArray_class static
Definition at line 16 of file byte_array.c.
Referenced by _byte_array_coerceObject(), and byte_array_initialize().