PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Type.c File Reference
Type.c File Reference
#include <postgres.h>
#include <fmgr.h>
#include <funcapi.h>
#include <parser/parse_coerce.h>
#include <utils/builtins.h>
#include <utils/typcache.h>
#include <utils/lsyscache.h>
#include "pljava/type/String_priv.h"
#include "pljava/type/Array.h"
#include "pljava/type/Coerce.h"
#include "pljava/type/Composite.h"
#include "pljava/type/TupleDesc.h"
#include "pljava/type/Oid.h"
#include "pljava/type/UDT.h"
#include "pljava/Function.h"
#include "pljava/Invocation.h"
#include "pljava/HashMap.h"
#include "pljava/SPI.h"
Data Structures
struct CacheEntryData
struct CallContextData
Typedefs
typedef CacheEntryData * CacheEntry
Functions
static void stashCallContext (CallContextData *ctxData)
static void _closeIteration (CallContextData *ctxData)
static void _endOfSetCB (Datum arg)
static Type _getCoerce (Type self, Type other, Oid fromOid, Oid toOid, HashMap *map, Type builder(Type, Type, Oid))
Type Type_getCoerceIn (Type self, Type other)
Type Type_getCoerceOut (Type self, Type other)
bool Type_canReplaceType (Type self, Type other)
bool Type_isDynamic (Type self)
bool Type_isOutParameter (Type self)
jvalue Type_coerceDatum (Type self, Datum value)
jvalue Type_coerceDatumAs (Type self, Datum value, jclass rqcls)
Datum Type_coerceObject (Type self, jobject object)
Datum Type_coerceObjectBridged (Type self, jobject object)
char Type_getAlign (Type self)
TypeClass Type_getClass (Type self)
int16 Type_getLength (Type self)
bool Type_isByValue (Type self)
jclass Type_getJavaClass (Type self)
const char * Type_getJavaTypeName (Type self)
const char * Type_getJNISignature (Type self)
Type Type_getArrayType (Type self, Oid arrayTypeId)
Type Type_getElementType (Type self)
Type Type_getObjectType (Type self)
Type Type_getRealType (Type self, Oid realTypeId, jobject typeMap)
Oid Type_getOid (Type self)
TupleDesc Type_getTupleDesc (Type self, PG_FUNCTION_ARGS)
Datum Type_invoke (Type self, Function fn, PG_FUNCTION_ARGS)
Datum Type_invokeSRF (Type self, Function fn, PG_FUNCTION_ARGS)
bool Type_isPrimitive (Type self)
Type Type_fromJavaType (Oid typeId, const char *javaTypeName)
void Type_cacheByOid (Oid typeId, Type type)
Type Type_fromOidCache (Oid typeId)
static Type checkTypeMappedUDT (Oid typeId, jobject typeMap, Form_pg_type typeStruct)
Type Type_fromOid (Oid typeId, jobject typeMap)
Type Type_objectTypeFromOid (Oid typeId, jobject typeMap)
bool _Type_canReplaceType (Type self, Type other)
Datum _Type_invoke (Type self, Function fn, PG_FUNCTION_ARGS)
static Type _Type_createArrayType (Type self, Oid arrayTypeId)
static jobject _Type_getSRFCollector (Type self, PG_FUNCTION_ARGS)
static Datum _Type_datumFromSRF (Type self, jobject row, jobject rowCollector)
jobject Type_getSRFCollector (Type self, PG_FUNCTION_ARGS)
Datum Type_datumFromSRF (Type self, jobject row, jobject rowCollector)
static Type _Type_getRealType (Type self, Oid realId, jobject typeMap)
static const char * _Type_getJNISignature (Type self)
TupleDesc _Type_getTupleDesc (Type self, PG_FUNCTION_ARGS)
static void addTypeBridge (jclass c, jmethodID m, char const *cName, Oid oid)
static void initializeTypeBridges ()
void Any_initialize (void)
void Coerce_initialize (void)
void Void_initialize (void)
void Boolean_initialize (void)
void Byte_initialize (void)
void Short_initialize (void)
void Integer_initialize (void)
void Long_initialize (void)
void Float_initialize (void)
void Double_initialize (void)
void BigDecimal_initialize (void)
void Date_initialize (void)
void Time_initialize (void)
void Timestamp_initialize (void)
void Oid_initialize (void)
void AclId_initialize (void)
void String_initialize (void)
void byte_array_initialize (void)
void TupleTable_initialize (void)
void Composite_initialize (void)
void pljava_SQLXMLImpl_initialize (void)
void Type_initialize (void)
static Type unimplementedTypeObtainer (Oid typeId)
static jvalue unimplementedDatumCoercer (Type, Datum)
static Datum unimplementedObjectCoercer (Type, jobject)
TypeClass TypeClass_alloc (const char *typeName)
TypeClass TypeClass_alloc2 (const char *typeName, Size classSize, Size instanceSize)
Type TypeClass_allocInstance (TypeClass cls, Oid typeId)
Type TypeClass_allocInstance2 (TypeClass cls, Oid typeId, Form_pg_type pgType)
static void _registerType (Oid typeId, const char *javaTypeName, Type type, TypeObtainer obtainer)
void Type_registerType (const char *javaTypeName, Type type)
void Type_registerType2 (Oid typeId, const char *javaTypeName, TypeObtainer obtainer)
Variables
static Oid BOOLARRAYOID
static Oid CHARARRAYOID
static Oid FLOAT8ARRAYOID
static Oid INT8ARRAYOID
static HashMap s_typeByOid
static HashMap s_obtainerByOid
static HashMap s_obtainerByJavaName
static jclass s_Map_class
static jmethodID s_Map_get
static jclass s_Iterator_class
static jmethodID s_Iterator_hasNext
static jmethodID s_Iterator_next
static jclass s_TypeBridge_Holder_class
static jmethodID s_TypeBridge_Holder_className
static jmethodID s_TypeBridge_Holder_defaultOid
static jmethodID s_TypeBridge_Holder_payload
Data Structure Documentation
CacheEntryData
struct CacheEntryData
Definition at line 47 of file Type.c.
Data Fields
TypeObtainer obtainer
Type type
Oid typeId
CallContextData
struct CallContextData
Definition at line 76 of file Type.c.
Data Fields
Type elemType
Function fn
bool hasConnected
jobject invocation
jobject rowCollector
jobject rowProducer
MemoryContext spiContext
Typedef Documentation
CacheEntry
typedef CacheEntryData* CacheEntry
Definition at line 54 of file Type.c.
Function Documentation
_closeIteration()
static void _closeIteration (CallContextData * ctxData) static
Definition at line 130 of file Type.c.
{
    jobject dummy;
    currentInvocation->hasConnected = ctxData->hasConnected;
    currentInvocation->invocation   = ctxData->invocation;
    /*
     * Why pass 1 as the call_cntr? We won't always have the actual call_cntr
     * value at _closeIteration time (the _endOfSetCB isn't passed it), and the
     * Java interfaces being used don't need it (close() isn't passed a row
     * number), but at least 1 is different from zero, in case vpcInvoke has
     * a reason to distinguish the first call (in the same invocation as the
     * overall setup) from subsequent ones.
     */
    pljava_Function_vpcInvoke(
        ctxData->fn, ctxData->rowProducer, NULL, 1, JNI_TRUE, &dummy);
    JNI_deleteGlobalRef(ctxData->rowProducer);
    if(ctxData->rowCollector != 0)
        JNI_deleteGlobalRef(ctxData->rowCollector);
    if(ctxData->hasConnected && ctxData->spiContext != 0)
    {
        /*
         * SPI was connected. We will (1) switch back to the memory context that
         * was imposed by SPI_connect, then (2) disconnect. SPI_finish will have
         * switched back to whatever memory context was current when SPI_connect
         * was called, and that context had better still be valid. It might be
         * the executor's multi_call_memory_ctx, if the SPI_connect happened
         * during initialization of the rowProducer or rowCollector, or the
         * executor's per-row context, if it happened later. Both of those are
         * still valid at this point. The final step (3) is to switch back to
         * the context we had before (1) and (2) happened.
         */
        MemoryContext currCtx = MemoryContextSwitchTo(ctxData->spiContext);
        Invocation_assertDisconnect();
        MemoryContextSwitchTo(currCtx);
    }
}
References currentInvocation, CallContextData::fn, CallContextData::hasConnected, CallContextData::invocation, Invocation_assertDisconnect(), JNI_deleteGlobalRef(), pljava_Function_vpcInvoke(), CallContextData::rowCollector, CallContextData::rowProducer, and CallContextData::spiContext.
Referenced by _endOfSetCB(), and Type_invokeSRF().
_endOfSetCB()
static void _endOfSetCB (Datum arg) static
Definition at line 174 of file Type.c.
{
    Invocation ctx;
    CallContextData* ctxData = (CallContextData*)DatumGetPointer(arg);
    /*
     * Even if there is an invocation already on the stack, there is no
     * convincing reason to think this callback belongs to it; PostgreSQL
     * will make this callback when the expression context we did belong to
     * is being torn down. This is not a hot operation; it only happens in
     * rare cases when an SRF has been called and not completely consumed.
     * So just unconditionally set up a context for this call, and clean up
     * our own mess.
     */
    PG_TRY();
    {
        Invocation_pushInvocation(&ctx);
        currentInvocation->inExprContextCB = true;
        _closeIteration(ctxData);
        Invocation_popInvocation(false);
    }
    PG_CATCH();
    {
        Invocation_popInvocation(true);
        PG_RE_THROW();
    }
    PG_END_TRY();
}
References _closeIteration(), currentInvocation, Invocation_popInvocation(), and Invocation_pushInvocation().
Referenced by Type_invokeSRF().
_getCoerce()
static Type _getCoerce (Type self, Type other, Oid fromOid, Oid toOid, HashMap * map, Type builderType, Type, Oid) static
Definition at line 221 of file Type.c.
{
    Oid  funcId;
    Type coercer;
    CoercionPathType cpt;
    if(*map != 0)
    {
        coercer = HashMap_getByOid(*map, other->typeId);
        if(coercer != 0)
            return coercer;
    }
    cpt = find_coercion_pathway(toOid, fromOid, COERCION_EXPLICIT, &funcId);
    switch ( cpt )
    {
    case COERCION_PATH_NONE:
        elog(ERROR, "no conversion function from (regtype) %d to %d",
             fromOid, toOid);
        pg_unreachable(); /*elog(ERROR is already so marked; what's with gcc?*/
    case COERCION_PATH_RELABELTYPE:
        /*
         * Binary compatible type. No need for a special coercer.
         * Unless ... it's a domain ....
         */
        if ( ! IsBinaryCoercible(fromOid, toOid) && DomainHasConstraints(toOid))
            elog(WARNING, "disregarding domain constraints of (regtype) %d",
                 toOid);
        return self;
    case COERCION_PATH_COERCEVIAIO:
        elog(ERROR, "COERCEVIAIO not implemented from (regtype) %d to %d",
             fromOid, toOid);
        pg_unreachable();
    case COERCION_PATH_ARRAYCOERCE:
        elog(ERROR, "ARRAYCOERCE not implemented from (regtype) %d to %d",
             fromOid, toOid);
        pg_unreachable();
    case COERCION_PATH_FUNC:
        break;
    }
    if(*map == 0)
        *map = HashMap_create(7, GetMemoryChunkContext(self));
    coercer = builder(self, other, funcId);
    HashMap_putByOid(*map, other->typeId, coercer);
    return coercer;
}
References HashMap_create(), HashMap_getByOid(), HashMap_putByOid(), and Type.
Referenced by Type_getCoerceIn(), and Type_getCoerceOut().
_registerType()
static void _registerType (Oid typeId, const char * javaTypeName, Type type, TypeObtainer obtainer) static
Definition at line 1135 of file Type.c.
{
    CacheEntry ce = (CacheEntry)
        MemoryContextAlloc(TopMemoryContext, sizeof(CacheEntryData));
    ce->typeId   = typeId;
    ce->type     = type;
    ce->obtainer = obtainer;
    if(javaTypeName != 0)
    {
        /*
         * The s_obtainerByJavaName cache is now keyed by Java name and an oid,
         * rather than Java name alone, to address an issue affecting arrays.
         * To avoid changing other behavior, the oid used in the hash key will
         * be InvalidOid always, unless the Java name being registered is
         * an array type and the caller has passed a valid oid.
         */
        Oid keyOid = (NULL == strchr(javaTypeName, ']'))
            ? InvalidOid
            : typeId;
        HashMap_putByStringOid(s_obtainerByJavaName, javaTypeName, keyOid, ce);
    }
    if(typeId != InvalidOid && HashMap_getByOid(s_obtainerByOid, typeId) == 0)
        HashMap_putByOid(s_obtainerByOid, typeId, ce);
}
References HashMap_getByOid(), HashMap_putByOid(), HashMap_putByStringOid(), CacheEntryData::obtainer, s_obtainerByJavaName, s_obtainerByOid, CacheEntryData::type, and CacheEntryData::typeId.
Referenced by Type_registerType(), and Type_registerType2().
_Type_canReplaceType()
bool _Type_canReplaceType (Type self, Type other)
Definition at line 808 of file Type.c.
{
    return self->typeClass == other->typeClass;
}
Referenced by BigDecimal_initialize(), TypeClass_alloc2(), and UDT_registerUDT().
_Type_createArrayType()
static Type _Type_createArrayType (Type self, Oid arrayTypeId) static
Definition at line 834 of file Type.c.
{
    return Array_fromOid(arrayTypeId, self);
}
References Array_fromOid().
Referenced by TypeClass_alloc2().
_Type_datumFromSRF()
static Datum _Type_datumFromSRF (Type self, jobject row, jobject rowCollector) static
Definition at line 844 of file Type.c.
{
    return Type_coerceObject(self, row);
}
References Type_coerceObject().
Referenced by TypeClass_alloc2().
_Type_getJNISignature()
static const char * _Type_getJNISignature (Type self) static
Definition at line 864 of file Type.c.
{
    return self->typeClass->JNISignature;
}
Referenced by TypeClass_alloc2().
_Type_getRealType()
static Type _Type_getRealType (Type self, Oid realId, jobject typeMap) static
Definition at line 859 of file Type.c.
{
    return self;
}
Referenced by TypeClass_alloc2().
_Type_getSRFCollector()
static jobject _Type_getSRFCollector (Type self, PG_FUNCTION_ARGS) static
Definition at line 839 of file Type.c.
{
    return 0;
}
Referenced by TypeClass_alloc2().
_Type_getTupleDesc()
TupleDesc _Type_getTupleDesc (Type self, PG_FUNCTION_ARGS)
Definition at line 869 of file Type.c.
{
    ereport(ERROR,
        (errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
         errmsg("Type is not associated with a record")));
    return 0;   /* Keep compiler happy */
}
Referenced by TypeClass_alloc2().
_Type_invoke()
Datum _Type_invoke (Type self, Function fn, PG_FUNCTION_ARGS)
Definition at line 813 of file Type.c.
{
    MemoryContext currCtx;
    Datum ret;
    jobject value = pljava_Function_refInvoke(fn);
    if(value == 0)
    {
        fcinfo->isnull = true;
        return 0;
    }
    /* The return value cannot be created in the current context since it
     * goes out of scope when SPI_finish is called.
     */
    currCtx = Invocation_switchToUpperContext();
    ret = self->typeClass->coerceObject(self, value);
    MemoryContextSwitchTo(currCtx);
    JNI_deleteLocalRef(value);
    return ret;
}
References Invocation_switchToUpperContext(), JNI_deleteLocalRef(), and pljava_Function_refInvoke().
Referenced by TypeClass_alloc2().
AclId_initialize()
void AclId_initialize (void) extern
Definition at line 49 of file AclId.c.
{
    JNINativeMethod methods[] = {
        {
        "_getUser",
        "()Lorg/postgresql/pljava/internal/AclId;",
        Java_org_postgresql_pljava_internal_AclId__1getUser
        },
        {
        "_getOuterUser",
        "()Lorg/postgresql/pljava/internal/AclId;",
        Java_org_postgresql_pljava_internal_AclId__1getOuterUser
        },
        {
        "_fromName",
        "(Ljava/lang/String;)Lorg/postgresql/pljava/internal/AclId;",
        Java_org_postgresql_pljava_internal_AclId__1fromName
        },
        {
        "_getName",
        "()Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_AclId__1getName
        },
        {
        "_hasSchemaCreatePermission",
        "(Lorg/postgresql/pljava/internal/Oid;)Z",
        Java_org_postgresql_pljava_internal_AclId__1hasSchemaCreatePermission
        },
        {
        "_isSuperuser",
        "()Z",
        Java_org_postgresql_pljava_internal_AclId__1isSuperuser
        },
        { 0, 0, 0 }};
    s_AclId_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/internal/AclId"));
    PgObject_registerNatives2(s_AclId_class, methods);
    s_AclId_init = PgObject_getJavaMethod(s_AclId_class, "<init>", "(I)V");
    s_AclId_m_native = PgObject_getJavaField(s_AclId_class, "m_native", "I");
}
References Java_org_postgresql_pljava_internal_AclId__1fromName(), Java_org_postgresql_pljava_internal_AclId__1getName(), Java_org_postgresql_pljava_internal_AclId__1getOuterUser(), Java_org_postgresql_pljava_internal_AclId__1getUser(), Java_org_postgresql_pljava_internal_AclId__1hasSchemaCreatePermission(), Java_org_postgresql_pljava_internal_AclId__1isSuperuser(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaField(), PgObject_getJavaMethod(), PgObject_registerNatives2(), s_AclId_class, s_AclId_init, and s_AclId_m_native.
Referenced by Type_initialize().
addTypeBridge()
static void addTypeBridge (jclass c, jmethodID m, char const * cName, Oid oid) static
Definition at line 877 of file Type.c.
{
    jstring jcn = String_createJavaStringFromNTS(cName);
    JNI_callStaticObjectMethodLocked(c, m, jcn, oid);
    JNI_deleteLocalRef(jcn);
}
References JNI_callStaticObjectMethodLocked(), JNI_deleteLocalRef(), and String_createJavaStringFromNTS().
Referenced by initializeTypeBridges().
Any_initialize()
void Any_initialize (void) extern
Definition at line 43 of file Any.c.
{
    TypeClass cls = TypeClass_alloc("type.any");
    cls->JNISignature    = "Ljava/lang/Object;";
    cls->javaTypeName    = "java.lang.Object";
    cls->dynamic         = true;
    cls->getRealType     = _Any_getRealType;
    cls->createArrayType = _Any_createArrayType;
    Type_registerType("java.lang.Object", TypeClass_allocInstance(cls, ANYELEMENTOID));
    Type_registerType(0, TypeClass_allocInstance(cls, ANYOID));
}
References _Any_createArrayType(), _Any_getRealType(), Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
BigDecimal_initialize()
void BigDecimal_initialize (void) extern
Definition at line 49 of file BigDecimal.c.
{
    s_BigDecimal_class = JNI_newGlobalRef(PgObject_getJavaClass("java/math/BigDecimal"));
    s_BigDecimal_init = PgObject_getJavaMethod(s_BigDecimal_class, "<init>", "(Ljava/lang/String;)V");
    s_BigDecimal_toString = PgObject_getJavaMethod(s_BigDecimal_class, "toString", "()Ljava/lang/String;");
    s_BigDecimalClass = TypeClass_alloc2("type.BigDecimal", sizeof(struct TypeClass_), sizeof(struct String_));
    s_BigDecimalClass->JNISignature   = "Ljava/math/BigDecimal;";
    s_BigDecimalClass->javaTypeName   = "java.math.BigDecimal";
    s_BigDecimalClass->canReplaceType = _Type_canReplaceType;
    s_BigDecimalClass->coerceDatum    = _BigDecimal_coerceDatum;
    s_BigDecimalClass->coerceObject   = _BigDecimal_coerceObject;
    Type_registerType2(NUMERICOID, "java.math.BigDecimal", BigDecimal_obtain);
}
References _BigDecimal_coerceDatum(), _BigDecimal_coerceObject(), _Type_canReplaceType(), BigDecimal_obtain(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_BigDecimal_class, s_BigDecimal_init, s_BigDecimal_toString, s_BigDecimalClass, Type_registerType2(), and TypeClass_alloc2().
Referenced by Type_initialize().
Boolean_initialize()
void Boolean_initialize (void) extern
Definition at line 115 of file Boolean.c.
{
    Type t_boolean;
    Type t_Boolean;
    TypeClass cls;
    s_Boolean_class = JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Boolean"));
    s_Boolean_init = PgObject_getJavaMethod(s_Boolean_class, "<init>", "(Z)V");
    s_Boolean_booleanValue = PgObject_getJavaMethod(s_Boolean_class, "booleanValue", "()Z");
    cls = TypeClass_alloc("type.Boolean");
    cls->canReplaceType = _Boolean_canReplace;
    cls->JNISignature = "Ljava/lang/Boolean;";
    cls->javaTypeName = "java.lang.Boolean";
    cls->coerceDatum  = _Boolean_coerceDatum;
    cls->coerceObject = _Boolean_coerceObject;
    t_Boolean = TypeClass_allocInstance(cls, BOOLOID);
    cls = TypeClass_alloc("type.boolean");
    cls->JNISignature = "Z";
    cls->javaTypeName = "boolean";
    cls->invoke       = _boolean_invoke;
    cls->coerceDatum  = _boolean_coerceDatum;
    cls->coerceObject = _Boolean_coerceObject;
    cls->createArrayType = _boolean_createArrayType;
    s_booleanClass = cls;
    t_boolean = TypeClass_allocInstance(cls, BOOLOID);
    t_boolean->objectType = t_Boolean;
    Type_registerType("boolean", t_boolean);
    Type_registerType("java.lang.Boolean", t_Boolean);
}
References _Boolean_canReplace(), _boolean_coerceDatum(), _Boolean_coerceDatum(), _Boolean_coerceObject(), _boolean_createArrayType(), _boolean_invoke(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Boolean_booleanValue, s_Boolean_class, s_Boolean_init, s_booleanClass, Type, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
byte_array_initialize()
void byte_array_initialize (void) extern
Definition at line 76 of file byte_array.c.
{
    TypeClass cls = TypeClass_alloc("type.byte[]");
    cls->JNISignature = "[B";
    cls->javaTypeName = "byte[]";
    cls->coerceDatum  = _byte_array_coerceDatum;
    cls->coerceObject = _byte_array_coerceObject;
    Type_registerType("byte[]", TypeClass_allocInstance(cls, BYTEAOID));
    s_byteArray_class = JNI_newGlobalRef(PgObject_getJavaClass("[B"));
    s_BlobValue_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/jdbc/BlobValue"));
    s_BlobValue_length = PgObject_getJavaMethod(s_BlobValue_class, "length", "()J");
    s_BlobValue_getContents = PgObject_getJavaMethod(s_BlobValue_class, "getContents", "(Ljava/nio/ByteBuffer;)V");
}
References _byte_array_coerceDatum(), _byte_array_coerceObject(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_BlobValue_class, s_BlobValue_getContents, s_BlobValue_length, s_byteArray_class, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Byte_initialize()
void Byte_initialize (void) extern
Definition at line 116 of file Byte.c.
{
    Type t_byte;
    Type t_Byte;
    TypeClass cls;
    s_Byte_class = JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Byte"));
    s_Byte_init = PgObject_getJavaMethod(s_Byte_class, "<init>", "(B)V");
    s_Byte_byteValue = PgObject_getJavaMethod(s_Byte_class, "byteValue", "()B");
    cls = TypeClass_alloc("type.Byte");
    cls->canReplaceType = _Byte_canReplace;
    cls->JNISignature = "Ljava/lang/Byte;";
    cls->javaTypeName = "java.lang.Byte";
    cls->coerceDatum  = _Byte_coerceDatum;
    cls->coerceObject = _Byte_coerceObject;
    t_Byte = TypeClass_allocInstance(cls, CHAROID);
    cls = TypeClass_alloc("type.byte");
    cls->JNISignature = "B";
    cls->javaTypeName = "byte";
    cls->invoke       = _byte_invoke;
    cls->coerceDatum  = _byte_coerceDatum;
    cls->coerceObject = _Byte_coerceObject;
    cls->createArrayType = _byte_createArrayType;
    s_byteClass = cls;
    t_byte = TypeClass_allocInstance(cls, CHAROID);
    t_byte->objectType = t_Byte;
    Type_registerType("byte", t_byte);
    Type_registerType("java.lang.Byte", t_Byte);
}
References _Byte_canReplace(), _byte_coerceDatum(), _Byte_coerceDatum(), _Byte_coerceObject(), _byte_createArrayType(), _byte_invoke(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Byte_byteValue, s_Byte_class, s_Byte_init, s_byteClass, Type, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
checkTypeMappedUDT()
static Type checkTypeMappedUDT (Oid typeId, jobject typeMap, Form_pg_type typeStruct) inline static
Definition at line 662 of file Type.c.
{
    jobject joid;
    jclass  typeClass;
    Type    type;
    jobject readMH;
    jobject writeMH;
    TupleDesc tupleDesc;
    bool    hasTupleDesc;
    if ( NULL == typeMap )
        return NULL;
    joid      = Oid_create(typeId);
    typeClass = (jclass)JNI_callObjectMethod(typeMap, s_Map_get, joid);
    JNI_deleteLocalRef(joid);
    if ( NULL == typeClass )
        return NULL;
    if ( -2 == typeStruct->typlen )
    {
        JNI_deleteLocalRef(typeClass);
        ereport(ERROR, (
            errcode(ERRCODE_FEATURE_NOT_SUPPORTED),
            errmsg(
                "type mapping in PL/Java for %s with NUL-terminated(-2) "
                "storage not supported",
                format_type_be_qualified(typeId))
        ));
    }
    readMH  = pljava_Function_udtReadHandle( typeClass, NULL, true);
    writeMH = pljava_Function_udtWriteHandle(typeClass, NULL, true);
    tupleDesc = lookup_rowtype_tupdesc_noerror(typeId, -1, true);
    hasTupleDesc = NULL != tupleDesc;
    if ( hasTupleDesc )
        ReleaseTupleDesc(tupleDesc);
    type = (Type)UDT_registerUDT(
        typeClass, typeId, typeStruct, hasTupleDesc, false,
        NULL, readMH, writeMH, NULL);
    /*
     * UDT_registerUDT calls JNI_deleteLocalRef on readMH and writeMH.
     */
    JNI_deleteLocalRef(typeClass);
    return type;
}
References JNI_callObjectMethod(), JNI_deleteLocalRef(), Oid_create(), pljava_Function_udtReadHandle(), pljava_Function_udtWriteHandle(), s_Map_get, Type, and UDT_registerUDT().
Referenced by Type_fromOid().
Coerce_initialize()
void Coerce_initialize (void) extern
Definition at line 103 of file Coerce.c.
{
    s_coerceInClass = TypeClass_alloc2("type.CoerceIn", sizeof(struct TypeClass_), sizeof(struct Coerce_));
    s_coerceInClass->getJNISignature = _Coerce_getJNISignature;
    s_coerceInClass->coerceDatum = _Coerce_coerceDatum;
    s_coerceOutClass = TypeClass_alloc2("type.CoerceOut", sizeof(struct TypeClass_), sizeof(struct Coerce_));
    s_coerceOutClass->getJNISignature = _Coerce_getJNISignature;
    s_coerceOutClass->invoke = _Coerce_invoke;
    s_coerceOutClass->coerceObject = _Coerce_coerceObject;
}
References _Coerce_coerceDatum(), _Coerce_coerceObject(), _Coerce_getJNISignature(), _Coerce_invoke(), s_coerceInClass, s_coerceOutClass, and TypeClass_alloc2().
Referenced by Type_initialize().
Composite_initialize()
void Composite_initialize (void) extern
Definition at line 217 of file Composite.c.
{
    s_SingleRowWriter_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/jdbc/SingleRowWriter"));
    s_SingleRowWriter_init = PgObject_getJavaMethod(s_SingleRowWriter_class, "<init>", "(Lorg/postgresql/pljava/internal/TupleDesc;)V");
    s_SingleRowWriter_getTupleAndClear = PgObject_getJavaMethod(s_SingleRowWriter_class, "getTupleAndClear", "()J");
    s_ResultSetProvider_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/ResultSetProvider"));
    s_ResultSetProvider_assignRowValues = PgObject_getJavaMethod(s_ResultSetProvider_class, "assignRowValues", "(Ljava/sql/ResultSet;I)Z");
    s_ResultSetProvider_close = PgObject_getJavaMethod(s_ResultSetProvider_class, "close", "()V");
    s_ResultSetHandle_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/ResultSetHandle"));
    s_ResultSetPicker_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/internal/ResultSetPicker"));
    s_ResultSetPicker_init = PgObject_getJavaMethod(s_ResultSetPicker_class, "<init>", "(Lorg/postgresql/pljava/ResultSetHandle;)V");
    s_CompositeClass = TypeClass_alloc2("type.Composite", sizeof(struct TypeClass_), sizeof(struct Composite_));
    s_CompositeClass->JNISignature    = "Ljava/sql/ResultSet;";
    s_CompositeClass->javaTypeName    = "java.sql.ResultSet";
    s_CompositeClass->getTupleDesc    = _Composite_getTupleDesc;
    s_CompositeClass->coerceDatum     = _Composite_coerceDatum;
    s_CompositeClass->invoke          = _Composite_invoke;
    s_CompositeClass->getSRFCollector = _Composite_getSRFCollector;
    s_CompositeClass->datumFromSRF    = _Composite_datumFromSRF;
    s_CompositeClass->outParameter    = true;
    Type_registerType2(InvalidOid, "java.sql.ResultSet", Composite_obtain);
}
References _Composite_coerceDatum(), _Composite_datumFromSRF(), _Composite_getSRFCollector(), _Composite_getTupleDesc(), _Composite_invoke(), Composite_obtain(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_CompositeClass, s_ResultSetHandle_class, s_ResultSetPicker_class, s_ResultSetPicker_init, s_ResultSetProvider_assignRowValues, s_ResultSetProvider_class, s_ResultSetProvider_close, s_SingleRowWriter_class, s_SingleRowWriter_getTupleAndClear, s_SingleRowWriter_init, Type_registerType2(), and TypeClass_alloc2().
Referenced by Type_initialize().
Date_initialize()
void Date_initialize (void) extern
Definition at line 124 of file Date.c.
{
    TypeClass cls = TypeClass_alloc("type.Date");
    cls->JNISignature = "Ljava/sql/Date;";
    cls->javaTypeName = "java.sql.Date";
    cls->coerceDatum  = _Date_coerceDatum;
    cls->coerceObject = _Date_coerceObject;
    Type_registerType("java.sql.Date", TypeClass_allocInstance(cls, DATEOID));
    s_Date_class = JNI_newGlobalRef(PgObject_getJavaClass("java/sql/Date"));
    s_Date_init = PgObject_getJavaMethod(s_Date_class, "<init>", "(J)V");
    s_Date_getTime = PgObject_getJavaMethod(s_Date_class, "getTime",  "()J");
    cls = TypeClass_alloc("type.LocalDate");
    cls->JNISignature = "Ljava/time/LocalDate;";
    cls->javaTypeName = "java.time.LocalDate";
    cls->canReplaceType = _LocalDate_canReplaceType;
    cls->coerceDatum  = _LocalDate_coerceDatum;
    cls->coerceObject = _LocalDate_coerceObject;
    s_LocalDateClass  = cls;
    Type_registerType2(InvalidOid, "java.time.LocalDate", _LocalDate_obtain);
}
References _Date_coerceDatum(), _Date_coerceObject(), _LocalDate_canReplaceType(), _LocalDate_coerceDatum(), _LocalDate_coerceObject(), _LocalDate_obtain(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Date_class, s_Date_getTime, s_Date_init, s_LocalDateClass, Type_registerType(), Type_registerType2(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Double_initialize()
void Double_initialize (void) extern
Definition at line 120 of file Double.c.
{
    Type t_double;
    Type t_Double;
    TypeClass cls;
    s_Double_class = JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Double"));
    s_Double_init = PgObject_getJavaMethod(s_Double_class, "<init>", "(D)V");
    s_Double_doubleValue = PgObject_getJavaMethod(s_Double_class, "doubleValue", "()D");
    cls = TypeClass_alloc("type.Double");
    cls->canReplaceType = _Double_canReplace;
    cls->JNISignature = "Ljava/lang/Double;";
    cls->javaTypeName = "java.lang.Double";
    cls->coerceDatum  = _Double_coerceDatum;
    cls->coerceObject = _Double_coerceObject;
    t_Double = TypeClass_allocInstance(cls, FLOAT8OID);
    cls = TypeClass_alloc("type.double");
    cls->JNISignature = "D";
    cls->javaTypeName = "double";
    cls->invoke       = _double_invoke;
    cls->coerceDatum  = _double_coerceDatum;
    cls->coerceObject = _Double_coerceObject;
    cls->createArrayType = _double_createArrayType;
    s_doubleClass = cls;
    t_double = TypeClass_allocInstance(cls, FLOAT8OID);
    t_double->objectType = t_Double;
    Type_registerType("double", t_double);
    Type_registerType("java.lang.Double", t_Double);
}
References _Double_canReplace(), _double_coerceDatum(), _Double_coerceDatum(), _Double_coerceObject(), _double_createArrayType(), _double_invoke(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Double_class, s_Double_doubleValue, s_Double_init, s_doubleClass, Type, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Float_initialize()
void Float_initialize (void) extern
Definition at line 122 of file Float.c.
{
    Type t_float;
    Type t_Float;
    TypeClass cls;
    s_Float_class = JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Float"));
    s_Float_init = PgObject_getJavaMethod(s_Float_class, "<init>", "(F)V");
    s_Float_floatValue = PgObject_getJavaMethod(s_Float_class, "floatValue", "()F");
    cls = TypeClass_alloc("type.Float");
    cls->canReplaceType = _Float_canReplace;
    cls->JNISignature = "Ljava/lang/Float;";
    cls->javaTypeName = "java.lang.Float";
    cls->coerceDatum  = _Float_coerceDatum;
    cls->coerceObject = _Float_coerceObject;
    t_Float = TypeClass_allocInstance(cls, FLOAT4OID);
    cls = TypeClass_alloc("type.float");
    cls->JNISignature = "F";
    cls->javaTypeName = "float";
    cls->invoke       = _float_invoke;
    cls->coerceDatum  = _float_coerceDatum;
    cls->coerceObject = _Float_coerceObject;
    cls->createArrayType = _float_createArrayType;
    s_floatClass = cls;
    t_float = TypeClass_allocInstance(cls, FLOAT4OID);
    t_float->objectType = t_Float;
    Type_registerType("float", t_float);
    Type_registerType("java.lang.Float", t_Float);
}
References _Float_canReplace(), _float_coerceDatum(), _Float_coerceDatum(), _Float_coerceObject(), _float_createArrayType(), _float_invoke(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Float_class, s_Float_floatValue, s_Float_init, s_floatClass, Type, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
initializeTypeBridges()
static void initializeTypeBridges () static
Definition at line 884 of file Type.c.
{
    jclass cls;
    jmethodID ofClass;
    jmethodID ofInterface;
    cls = PgObject_getJavaClass("org/postgresql/pljava/jdbc/TypeBridge");
    ofClass = PgObject_getStaticJavaMethod(cls, "ofClass",
        "(Ljava/lang/String;I)Lorg/postgresql/pljava/jdbc/TypeBridge;");
    ofInterface = PgObject_getStaticJavaMethod(cls, "ofInterface",
        "(Ljava/lang/String;I)Lorg/postgresql/pljava/jdbc/TypeBridge;");
    addTypeBridge(cls, ofClass, "java.time.LocalDate", DATEOID);
    addTypeBridge(cls, ofClass, "java.time.LocalDateTime", TIMESTAMPOID);
    addTypeBridge(cls, ofClass, "java.time.LocalTime", TIMEOID);
    addTypeBridge(cls, ofClass, "java.time.OffsetDateTime", TIMESTAMPTZOID);
    addTypeBridge(cls, ofClass, "java.time.OffsetTime", TIMETZOID);
    /*
     * TypeBridges that allow Java primitive array types to be passed to things
     * expecting their boxed counterparts. An oddball case is byte[], given the
     * default oid BYTEAOID here instead of CHARARRAYOID following the pattern,
     * because there is a whole 'nother (see byte_array.c) Type that also maps
     * byte[] on the Java side, but bytea for PostgreSQL (I am not at all sure
     * what I think of that), and bridging it to a different Oid here would
     * break it as a parameter to prepared statements that were working. So
     * cater to that use, while possibly complicating the new use that was not
     * formerly possible.
     *
     * There is no bridge for char[], because PL/Java has no Type that maps it
     * to anything in PostgreSQL.
     */
    addTypeBridge(cls, ofClass, "boolean[]", BOOLARRAYOID);
    addTypeBridge(cls, ofClass,    "byte[]", BYTEAOID);
    addTypeBridge(cls, ofClass,   "short[]", INT2ARRAYOID);
    addTypeBridge(cls, ofClass,     "int[]", INT4ARRAYOID);
    addTypeBridge(cls, ofClass,    "long[]", INT8ARRAYOID);
    addTypeBridge(cls, ofClass,   "float[]", FLOAT4ARRAYOID);
    addTypeBridge(cls, ofClass,  "double[]", FLOAT8ARRAYOID);
    addTypeBridge(cls, ofInterface, "java.sql.SQLXML",
#if defined(XMLOID)
        XMLOID
#else
        TEXTOID
#endif
    );
    JNI_deleteLocalRef(cls);
    cls = PgObject_getJavaClass("org/postgresql/pljava/jdbc/TypeBridge$Holder");
    s_TypeBridge_Holder_class = JNI_newGlobalRef(cls);
    s_TypeBridge_Holder_className = PgObject_getJavaMethod(cls, "className",
        "()Ljava/lang/String;");
    s_TypeBridge_Holder_defaultOid = PgObject_getJavaMethod(cls, "defaultOid",
        "()I");
    s_TypeBridge_Holder_payload = PgObject_getJavaMethod(cls, "payload",
        "()Ljava/lang/Object;");
}
References addTypeBridge(), BOOLARRAYOID, FLOAT8ARRAYOID, INT8ARRAYOID, JNI_deleteLocalRef(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_getStaticJavaMethod(), s_TypeBridge_Holder_class, s_TypeBridge_Holder_className, s_TypeBridge_Holder_defaultOid, and s_TypeBridge_Holder_payload.
Referenced by Type_initialize().
Integer_initialize()
void Integer_initialize (void) extern
Definition at line 115 of file Integer.c.
{
    Type t_int;
    Type t_Integer;
    TypeClass cls;
    s_Integer_class = JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Integer"));
    s_Integer_init = PgObject_getJavaMethod(s_Integer_class, "<init>", "(I)V");
    s_Integer_intValue = PgObject_getJavaMethod(s_Integer_class, "intValue", "()I");
    cls = TypeClass_alloc("type.Integer");
    cls->canReplaceType = _Integer_canReplace;
    cls->JNISignature = "Ljava/lang/Integer;";
    cls->javaTypeName = "java.lang.Integer";
    cls->coerceDatum  = _Integer_coerceDatum;
    cls->coerceObject = _Integer_coerceObject;
    t_Integer = TypeClass_allocInstance(cls, INT4OID);
    cls = TypeClass_alloc("type.int");
    cls->JNISignature = "I";
    cls->javaTypeName = "int";
    cls->invoke       = _int_invoke;
    cls->coerceDatum  = _int_coerceDatum;
    cls->coerceObject = _Integer_coerceObject;
    cls->createArrayType = _int_createArrayType;
    s_intClass = cls;
    t_int = TypeClass_allocInstance(cls, INT4OID);
    t_int->objectType = t_Integer;
    Type_registerType("int", t_int);
    Type_registerType("java.lang.Integer", t_Integer);
}
References _int_coerceDatum(), _int_createArrayType(), _int_invoke(), _Integer_canReplace(), _Integer_coerceDatum(), _Integer_coerceObject(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_intClass, s_Integer_class, s_Integer_init, s_Integer_intValue, Type, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Long_initialize()
void Long_initialize (void) extern
Definition at line 122 of file Long.c.
{
    Type t_long;
    Type t_Long;
    TypeClass cls;
    s_Long_class = JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Long"));
    s_Long_init = PgObject_getJavaMethod(s_Long_class, "<init>", "(J)V");
    s_Long_longValue = PgObject_getJavaMethod(s_Long_class, "longValue", "()J");
    cls = TypeClass_alloc("type.Long");
    cls->canReplaceType = _Long_canReplace;
    cls->JNISignature = "Ljava/lang/Long;";
    cls->javaTypeName = "java.lang.Long";
    cls->coerceDatum  = _Long_coerceDatum;
    cls->coerceObject = _Long_coerceObject;
    t_Long = TypeClass_allocInstance(cls, INT8OID);
    cls = TypeClass_alloc("type.long");
    cls->JNISignature = "J";
    cls->javaTypeName = "long";
    cls->invoke       = _long_invoke;
    cls->coerceDatum  = _long_coerceDatum;
    cls->coerceObject = _Long_coerceObject;
    cls->createArrayType = _long_createArrayType;
    s_longClass = cls;
    t_long = TypeClass_allocInstance(cls, INT8OID);
    t_long->objectType = t_Long;
    Type_registerType("long", t_long);
    Type_registerType("java.lang.Long", t_Long);
}
References _Long_canReplace(), _long_coerceDatum(), _Long_coerceDatum(), _Long_coerceObject(), _long_createArrayType(), _long_invoke(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Long_class, s_Long_init, s_Long_longValue, s_longClass, Type, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Oid_initialize()
void Oid_initialize (void) extern
Definition at line 174 of file Oid.c.
{
    TypeClass cls;
    JNINativeMethod methods[] = {
        {
        "_forTypeName",
        "(Ljava/lang/String;)I",
        Java_org_postgresql_pljava_internal_Oid__1forTypeName
        },
        {
        "_forSqlType",
        "(I)I",
        Java_org_postgresql_pljava_internal_Oid__1forSqlType
        },
        {
        "_getTypeId",
        "()Lorg/postgresql/pljava/internal/Oid;",
        Java_org_postgresql_pljava_internal_Oid__1getTypeId
        },
        {
        "_getJavaClassName",
        "(I)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_Oid__1getJavaClassName
        },
        {
        "_getCurrentLoader",
        "()Ljava/lang/ClassLoader;",
        Java_org_postgresql_pljava_internal_Oid__1getCurrentLoader
        },
        { 0, 0, 0 }};
    jobject tmp;
    s_Oid_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/internal/Oid"));
    PgObject_registerNatives2(s_Oid_class, methods);
    s_Oid_init = PgObject_getJavaMethod(s_Oid_class, "<init>", "(I)V");
    s_Oid_m_native = PgObject_getJavaField(s_Oid_class, "m_native", "I");
    cls = TypeClass_alloc("type.Oid");
    cls->JNISignature   = "Lorg/postgresql/pljava/internal/Oid;";
    cls->javaTypeName   = "org.postgresql.pljava.internal.Oid";
    cls->coerceDatum    = _Oid_coerceDatum;
    cls->coerceObject   = _Oid_coerceObject;
    Type_registerType("org.postgresql.pljava.internal.Oid", TypeClass_allocInstance(cls, OIDOID));
    tmp = Oid_create(OIDOID);
    s_OidOid = JNI_newGlobalRef(tmp);
    JNI_deleteLocalRef(tmp);
    s_Oid_registerType = PgObject_getStaticJavaMethod(
                s_Oid_class, "registerType",
                "(Ljava/lang/Class;Lorg/postgresql/pljava/internal/Oid;)V");
    JNI_callStaticVoidMethod(s_Oid_class, s_Oid_registerType, s_Oid_class, s_OidOid);
}
References _Oid_coerceDatum(), _Oid_coerceObject(), Java_org_postgresql_pljava_internal_Oid__1forSqlType(), Java_org_postgresql_pljava_internal_Oid__1forTypeName(), Java_org_postgresql_pljava_internal_Oid__1getCurrentLoader(), Java_org_postgresql_pljava_internal_Oid__1getJavaClassName(), Java_org_postgresql_pljava_internal_Oid__1getTypeId(), JNI_callStaticVoidMethod(), JNI_deleteLocalRef(), JNI_newGlobalRef(), Oid_create(), PgObject_getJavaClass(), PgObject_getJavaField(), PgObject_getJavaMethod(), PgObject_getStaticJavaMethod(), PgObject_registerNatives2(), s_Oid_class, s_Oid_init, s_Oid_m_native, s_Oid_registerType, s_OidOid, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
pljava_SQLXMLImpl_initialize()
void pljava_SQLXMLImpl_initialize (void) extern
Definition at line 162 of file SQLXMLImpl.c.
{
    jclass clazz;
    JNINativeMethod methods[] =
    {
        {
        "_newWritable",
        "()Ljava/sql/SQLXML;",
        Java_org_postgresql_pljava_jdbc_SQLXMLImpl__1newWritable
        },
        { 0, 0, 0 }
    };
    TypeClass cls = TypeClass_alloc("type.SQLXML");
    cls->JNISignature = "Ljava/sql/SQLXML;";
    cls->javaTypeName = "java.sql.SQLXML";
    cls->canReplaceType = _SQLXML_canReplaceType;
    cls->coerceDatum  = _SQLXML_coerceDatum;
    cls->coerceObject = _SQLXML_coerceObject;
    s_SQLXMLClass = cls;
    Type_registerType2(InvalidOid, "java.sql.SQLXML", _SQLXML_obtain);
    cls = TypeClass_alloc("type.SQLXML");
    cls->JNISignature = "Ljava/sql/SQLXML;";
    cls->javaTypeName = "java.sql.SQLXML";
    cls->canReplaceType = _SQLXML_canReplaceType;
    cls->coerceDatum  = _SQLXML_coerceDatum_synthetic;
    /* cls->coerceObject = _SQLXML_coerceObject; */
    s_SQLXMLClass_Synthetic = cls; /* what happens if I don't register it? */
    s_SQLXML_class = JNI_newGlobalRef(PgObject_getJavaClass(
        "org/postgresql/pljava/jdbc/SQLXMLImpl"));
    s_SQLXML_adopt = PgObject_getStaticJavaMethod(s_SQLXML_class, "adopt",
        "(Ljava/sql/SQLXML;I)Lorg/postgresql/pljava/internal/VarlenaWrapper;");
    s_SQLXML_Readable_PgXML_class = JNI_newGlobalRef(PgObject_getJavaClass(
        "org/postgresql/pljava/jdbc/SQLXMLImpl$Readable$PgXML"));
    s_SQLXML_Readable_PgXML_init = PgObject_getJavaMethod(
        s_SQLXML_Readable_PgXML_class,
        "<init>", "(Lorg/postgresql/pljava/internal/VarlenaWrapper$Input;I)V");
    s_SQLXML_Readable_Synthetic_class = JNI_newGlobalRef(PgObject_getJavaClass(
        "org/postgresql/pljava/jdbc/SQLXMLImpl$Readable$Synthetic"));
    s_SQLXML_Readable_Synthetic_init = PgObject_getJavaMethod(
        s_SQLXML_Readable_Synthetic_class,
        "<init>", "(Lorg/postgresql/pljava/internal/VarlenaWrapper$Input;I)V");
    s_SQLXML_Writable_class = JNI_newGlobalRef(PgObject_getJavaClass(
        "org/postgresql/pljava/jdbc/SQLXMLImpl$Writable"));
    s_SQLXML_Writable_init = PgObject_getJavaMethod(s_SQLXML_Writable_class,
        "<init>", "(Lorg/postgresql/pljava/internal/VarlenaWrapper$Output;)V");
    clazz = PgObject_getJavaClass("org/postgresql/pljava/jdbc/SQLXMLImpl");
    PgObject_registerNatives2(clazz, methods);
    JNI_deleteLocalRef(clazz);
}
References _SQLXML_canReplaceType(), _SQLXML_coerceDatum(), _SQLXML_coerceDatum_synthetic(), _SQLXML_coerceObject(), _SQLXML_obtain(), Java_org_postgresql_pljava_jdbc_SQLXMLImpl__1newWritable(), JNI_deleteLocalRef(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_getStaticJavaMethod(), PgObject_registerNatives2(), s_SQLXML_adopt, s_SQLXML_class, s_SQLXML_Readable_PgXML_class, s_SQLXML_Readable_PgXML_init, s_SQLXML_Readable_Synthetic_class, s_SQLXML_Readable_Synthetic_init, s_SQLXML_Writable_class, s_SQLXML_Writable_init, s_SQLXMLClass, s_SQLXMLClass_Synthetic, Type_registerType2(), and TypeClass_alloc().
Referenced by Type_initialize().
Short_initialize()
void Short_initialize (void) extern
Definition at line 114 of file Short.c.
{
    Type t_short;
    Type t_Short;
    TypeClass cls;
    s_Short_class = JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Short"));
    s_Short_init = PgObject_getJavaMethod(s_Short_class, "<init>", "(S)V");
    s_Short_shortValue = PgObject_getJavaMethod(s_Short_class, "shortValue", "()S");
    cls = TypeClass_alloc("type.Short");
    cls->canReplaceType = _Short_canReplace;
    cls->JNISignature = "Ljava/lang/Short;";
    cls->javaTypeName = "java.lang.Short";
    cls->coerceDatum  = _Short_coerceDatum;
    cls->coerceObject = _Short_coerceObject;
    t_Short = TypeClass_allocInstance(cls, INT2OID);
    cls = TypeClass_alloc("type.short");
    cls->JNISignature = "S";
    cls->javaTypeName = "short";
    cls->invoke       = _short_invoke;
    cls->coerceDatum  = _short_coerceDatum;
    cls->coerceObject = _Short_coerceObject;
    cls->createArrayType = _short_createArrayType;
    s_shortClass = cls;
    t_short = TypeClass_allocInstance(cls, INT2OID);
    t_short->objectType = t_Short;
    Type_registerType("short", t_short);
    Type_registerType("java.lang.Short", t_Short);
}
References _Short_canReplace(), _short_coerceDatum(), _Short_coerceDatum(), _Short_coerceObject(), _short_createArrayType(), _short_invoke(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Short_class, s_Short_init, s_Short_shortValue, s_shortClass, Type, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
stashCallContext()
static void stashCallContext (CallContextData * ctxData) static
Definition at line 107 of file Type.c.
{
    bool wasConnected = ctxData->hasConnected;
    ctxData->hasConnected  = currentInvocation->hasConnected;
    ctxData->invocation    = currentInvocation->invocation;
    if ( wasConnected )
        return;
    /*
     * If SPI has been connected for the first time, capture the memory context
     * it imposed. Curiously, this is not used again except in _closeIteration.
     */
    if(ctxData->hasConnected)
        ctxData->spiContext = CurrentMemoryContext;
}
References currentInvocation, CallContextData::hasConnected, CallContextData::invocation, and CallContextData::spiContext.
Referenced by Type_invokeSRF().
String_initialize()
void String_initialize (void) extern
Definition at line 360 of file String.c.
{
    s_Object_class = (jclass)JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Object"));
    s_Object_toString = PgObject_getJavaMethod(s_Object_class, "toString", "()Ljava/lang/String;");
    s_String_class = (jclass)JNI_newGlobalRef(PgObject_getJavaClass("java/lang/String"));
    s_StringClass = TypeClass_alloc2("type.String", sizeof(struct TypeClass_), sizeof(struct String_));
    s_StringClass->JNISignature   = "Ljava/lang/String;";
    s_StringClass->javaTypeName   = "java.lang.String";
    s_StringClass->canReplaceType = _String_canReplaceType;
    s_StringClass->coerceDatum    = _String_coerceDatum;
    s_StringClass->coerceObject   = _String_coerceObject;
    /*
     * Frame push/pop hoisted here out of String_initialize_codec to mollify
     * pre-C99 compilers that don't want that function to have declarations
     * after a statement.
     */
    JNI_pushLocalFrame(16);
    String_initialize_codec();
    JNI_popLocalFrame(NULL);
    /*
     * Registering known types will increase the performance
     * a bit. The "default" is used when all else fails.
     */
    Type_registerType2(TEXTOID,    0, String_obtain);
    Type_registerType2(CSTRINGOID, 0, String_obtain);
    Type_registerType2(BPCHAROID,  0, String_obtain);
    Type_registerType2(NAMEOID,    0, String_obtain);
    Type_registerType2(VARCHAROID, "java.lang.String", String_obtain);
}
References _String_canReplaceType(), _String_coerceDatum(), _String_coerceObject(), JNI_newGlobalRef(), JNI_popLocalFrame(), JNI_pushLocalFrame(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Object_class, s_Object_toString, s_String_class, s_StringClass, String_initialize_codec(), String_obtain(), Type_registerType2(), and TypeClass_alloc2().
Referenced by Type_initialize().
Time_initialize()
void Time_initialize (void) extern
Definition at line 351 of file Time.c.
{
    TypeClass cls;
    s_Time_class = JNI_newGlobalRef(PgObject_getJavaClass("java/sql/Time"));
    s_Time_init = PgObject_getJavaMethod(s_Time_class, "<init>", "(J)V");
    s_Time_getTime = PgObject_getJavaMethod(s_Time_class, "getTime", "()J");
    cls = TypeClass_alloc("type.Time");
    cls->JNISignature = "Ljava/sql/Time;";
    cls->javaTypeName = "java.sql.Time";
    cls->coerceDatum  = _Time_coerceDatum;
    cls->coerceObject = _Time_coerceObject;
    Type_registerType(0, TypeClass_allocInstance(cls, TIMEOID));
    cls = TypeClass_alloc("type.Timetz");
    cls->JNISignature = "Ljava/sql/Time;";
    cls->javaTypeName = "java.sql.Time";
    cls->coerceDatum  = _Timetz_coerceDatum;
    cls->coerceObject = _Timetz_coerceObject;
    Type_registerType("java.sql.Time", TypeClass_allocInstance(cls, TIMETZOID));
    cls = TypeClass_alloc("type.LocalTime");
    cls->JNISignature = "Ljava/time/LocalTime;";
    cls->javaTypeName = "java.time.LocalTime";
    cls->coerceDatum  = _LocalTime_coerceDatum;
    cls->coerceObject = _LocalTime_coerceObject;
    cls->canReplaceType = _LocalTime_canReplaceType;
    s_LocalTimeClass  = cls;
    Type_registerType2(InvalidOid, "java.time.LocalTime", _LocalTime_obtain);
    cls = TypeClass_alloc("type.OffsetTime");
    cls->JNISignature = "Ljava/time/OffsetTime;";
    cls->javaTypeName = "java.time.OffsetTime";
    cls->coerceDatum  = _OffsetTime_coerceDatum;
    cls->coerceObject = _OffsetTime_coerceObject;
    cls->canReplaceType = _OffsetTime_canReplaceType;
    s_OffsetTimeClass  = cls;
    Type_registerType2(InvalidOid, "java.time.OffsetTime", _OffsetTime_obtain);
}
References _LocalTime_canReplaceType(), _LocalTime_coerceDatum(), _LocalTime_coerceObject(), _LocalTime_obtain(), _OffsetTime_canReplaceType(), _OffsetTime_coerceDatum(), _OffsetTime_coerceObject(), _OffsetTime_obtain(), _Time_coerceDatum(), _Time_coerceObject(), _Timetz_coerceDatum(), _Timetz_coerceObject(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_LocalTimeClass, s_OffsetTimeClass, s_Time_class, s_Time_getTime, s_Time_init, Type_registerType(), Type_registerType2(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Timestamp_initialize()
void Timestamp_initialize (void) extern
Definition at line 450 of file Timestamp.c.
{
    TypeClass cls;
    s_Timestamp_class = JNI_newGlobalRef(PgObject_getJavaClass("java/sql/Timestamp"));
    s_Timestamp_init = PgObject_getJavaMethod(s_Timestamp_class, "<init>", "(J)V");
    s_Timestamp_getNanos = PgObject_getJavaMethod(s_Timestamp_class, "getNanos", "()I");
    s_Timestamp_getTime  = PgObject_getJavaMethod(s_Timestamp_class, "getTime",  "()J");
    s_Timestamp_setNanos = PgObject_getJavaMethod(s_Timestamp_class, "setNanos", "(I)V");
    cls = TypeClass_alloc("type.Timestamp");
    cls->JNISignature   = "Ljava/sql/Timestamp;";
    cls->javaTypeName   = "java.sql.Timestamp";
    cls->canReplaceType = _Timestamp_canReplaceType;
    cls->coerceDatum    = _Timestamp_coerceDatum;
    cls->coerceObject   = _Timestamp_coerceObject;
    Type_registerType(0, TypeClass_allocInstance(cls, TIMESTAMPOID));
    s_TimestampClass = cls;
    cls = TypeClass_alloc("type.Timestamptz");
    cls->JNISignature   = "Ljava/sql/Timestamp;";
    cls->javaTypeName   = "java.sql.Timestamp";
    cls->canReplaceType = _Timestamptz_canReplaceType;
    cls->coerceDatum    = _Timestamptz_coerceDatum;
    cls->coerceObject   = _Timestamptz_coerceObject;
    Type_registerType("java.sql.Timestamp", TypeClass_allocInstance(cls, TIMESTAMPTZOID));
    s_TimestamptzClass = cls;
    cls = TypeClass_alloc("type.LocalDateTime");
    cls->JNISignature = "Ljava/time/LocalDateTime;";
    cls->javaTypeName = "java.time.LocalDateTime";
    cls->coerceDatum  = _LocalDateTime_coerceDatum;
    cls->coerceObject = _LocalDateTime_coerceObject;
    cls->canReplaceType = _LocalDateTime_canReplaceType;
    s_LocalDateTimeClass  = cls;
    Type_registerType2(InvalidOid, "java.time.LocalDateTime",
        _LocalDateTime_obtain);
    cls = TypeClass_alloc("type.OffsetDateTime");
    cls->JNISignature = "Ljava/time/OffsetDateTime;";
    cls->javaTypeName = "java.time.OffsetDateTime";
    cls->coerceDatum  = _OffsetDateTime_coerceDatum;
    cls->coerceObject = _OffsetDateTime_coerceObject;
    cls->canReplaceType = _OffsetDateTime_canReplaceType;
    s_OffsetDateTimeClass  = cls;
    Type_registerType2(InvalidOid, "java.time.OffsetDateTime",
        _OffsetDateTime_obtain);
}
References _LocalDateTime_canReplaceType(), _LocalDateTime_coerceDatum(), _LocalDateTime_coerceObject(), _LocalDateTime_obtain(), _OffsetDateTime_canReplaceType(), _OffsetDateTime_coerceDatum(), _OffsetDateTime_coerceObject(), _OffsetDateTime_obtain(), _Timestamp_canReplaceType(), _Timestamp_coerceDatum(), _Timestamp_coerceObject(), _Timestamptz_canReplaceType(), _Timestamptz_coerceDatum(), _Timestamptz_coerceObject(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_LocalDateTimeClass, s_OffsetDateTimeClass, s_Timestamp_class, s_Timestamp_getNanos, s_Timestamp_getTime, s_Timestamp_init, s_Timestamp_setNanos, s_TimestampClass, s_TimestamptzClass, Type_registerType(), Type_registerType2(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
TupleTable_initialize()
void TupleTable_initialize (void) extern
Definition at line 84 of file TupleTable.c.
{
    s_TupleTable_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/internal/TupleTable"));
    s_TupleTable_init = PgObject_getJavaMethod(
                s_TupleTable_class, "<init>",
                "(Lorg/postgresql/pljava/internal/TupleDesc;[Lorg/postgresql/pljava/internal/Tuple;)V");
}
References JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_TupleTable_class, and s_TupleTable_init.
Referenced by Type_initialize().
Type_cacheByOid()
void Type_cacheByOid (Oid typeId, Type type)
Definition at line 627 of file Type.c.
{
    HashMap_putByOid(s_typeByOid, typeId, type);
}
References HashMap_putByOid(), and s_typeByOid.
Referenced by Type_fromOid().
Type_canReplaceType()
bool Type_canReplaceType (Type self, Type other)
Definition at line 271 of file Type.c.
{
    return self->typeClass->canReplaceType(self, other);
}
Referenced by _Array_canReplaceType(), Java_org_postgresql_pljava_internal_Function__1reconcileTypes(), Type_coerceDatumAs(), and Type_coerceObjectBridged().
Type_coerceDatum()
jvalue Type_coerceDatum (Type self, Datum value)
Definition at line 286 of file Type.c.
{
    return self->typeClass->coerceDatum(self, value);
}
Referenced by _Array_coerceDatum(), _Coerce_coerceDatum(), _OffsetDateTime_coerceDatum(), _OffsetTime_coerceDatum(), Function_checkTypeBaseUDT(), Function_create(), Function_invoke(), and Type_coerceDatumAs().
Type_coerceDatumAs()
jvalue Type_coerceDatumAs (Type self, Datum value, jclass rqcls)
Definition at line 291 of file Type.c.
{
    jstring rqcname;
    char *rqcname0;
    Type rqtype;
    if ( NULL == rqcls  ||  Type_getJavaClass(self) == rqcls )
        return Type_coerceDatum(self, value);
    rqcname = JNI_callObjectMethod(rqcls, Class_getCanonicalName);
    rqcname0 = String_createNTS(rqcname);
    JNI_deleteLocalRef(rqcname);
    rqtype = Type_fromJavaType(self->typeId, rqcname0);
    pfree(rqcname0);
    if ( Type_canReplaceType(rqtype, self) )
        return Type_coerceDatum(rqtype, value);
    return Type_coerceDatum(self, value);
}
References Class_getCanonicalName, JNI_callObjectMethod(), JNI_deleteLocalRef(), String_createNTS(), Type, Type_canReplaceType(), Type_coerceDatum(), Type_fromJavaType(), and Type_getJavaClass().
Referenced by Java_org_postgresql_pljava_jdbc_SingleRowReader__1getObject(), and pljava_Tuple_getObject().
Type_coerceObject()
Datum Type_coerceObject (Type self, jobject object)
Definition at line 310 of file Type.c.
{
    return self->typeClass->coerceObject(self, object);
}
Referenced by _Array_coerceObject(), _Coerce_coerceObject(), _LocalDateTime_coerceObject(), _OffsetTime_coerceObject(), _Type_datumFromSRF(), and Type_coerceObjectBridged().
Type_coerceObjectBridged()
Datum Type_coerceObjectBridged (Type self, jobject object)
Definition at line 315 of file Type.c.
{
    jstring rqcname;
    char *rqcname0;
    Type rqtype;
    if ( JNI_FALSE == JNI_isInstanceOf(object, s_TypeBridge_Holder_class) )
        return Type_coerceObject(self, object);
    rqcname = JNI_callObjectMethod(object, s_TypeBridge_Holder_className);
    rqcname0 = String_createNTS(rqcname);
    JNI_deleteLocalRef(rqcname);
    rqtype = Type_fromJavaType(self->typeId, rqcname0);
    pfree(rqcname0);
    if ( ! Type_canReplaceType(rqtype, self) )
    {
        /*
         * Ignore the TypeBridge in this one oddball case that results from the
         * existence of two Types both mapping Java's byte[].
         */
        if ( BYTEAOID == self->typeId  &&  CHARARRAYOID == rqtype->typeId )
            rqtype = self;
        else
            elog(ERROR, "type bridge failure");
    }
    object = JNI_callObjectMethod(object, s_TypeBridge_Holder_payload);
    return Type_coerceObject(rqtype, object);
}
References CHARARRAYOID, JNI_callObjectMethod(), JNI_deleteLocalRef(), JNI_isInstanceOf(), s_TypeBridge_Holder_class, s_TypeBridge_Holder_className, s_TypeBridge_Holder_payload, String_createNTS(), Type, Type_canReplaceType(), Type_coerceObject(), and Type_fromJavaType().
Referenced by coerceObjects(), Java_org_postgresql_pljava_internal_Relation__1modifyTuple(), and Java_org_postgresql_pljava_internal_TupleDesc__1formTuple().
Type_datumFromSRF()
Datum Type_datumFromSRF (Type self, jobject row, jobject rowCollector)
Definition at line 854 of file Type.c.
{
    return self->typeClass->datumFromSRF(self, row, rowCollector);
}
Referenced by Type_invokeSRF().
Type_fromJavaType()
Type Type_fromJavaType (Oid typeId, const char * javaTypeName)
Definition at line 585 of file Type.c.
{
    /*
     * Do an initial lookup with InvalidOid as the oid part of the key. Multiple
     * entries for the same Java name and distinct oids are not anticipated
     * except for arrays.
     */
    CacheEntry ce = (CacheEntry)HashMap_getByStringOid(
        s_obtainerByJavaName, javaTypeName, InvalidOid);
    /*
     * If no entry was found using InvalidOid and a valid typeId is provided
     * and the wanted Java type is an array, repeat the lookup using the typeId.
     */
    if ( NULL == ce  &&  InvalidOid != typeId
            &&  NULL != strchr(javaTypeName, ']') )
        ce = (CacheEntry)HashMap_getByStringOid(
            s_obtainerByJavaName, javaTypeName, typeId);
    if(ce == 0)
    {
        size_t jtlen = strlen(javaTypeName) - 2;
        if(jtlen > 0 && strcmp("[]", javaTypeName + jtlen) == 0)
        {
            Type type;
            char* elemName = palloc(jtlen+1);
            memcpy(elemName, javaTypeName, jtlen);
            elemName[jtlen] = 0;
            type = Type_getArrayType(Type_fromJavaType(InvalidOid, elemName), typeId);
            pfree(elemName);
            return type;
        }
        ereport(ERROR, (
            errcode(ERRCODE_CANNOT_COERCE),
            errmsg("No java type mapping installed for \"%s\"", javaTypeName)));
    }
    return ce->type == 0
        ? ce->obtainer(typeId == InvalidOid ? ce->typeId : typeId)
        : ce->type;
}
References HashMap_getByStringOid(), CacheEntryData::obtainer, s_obtainerByJavaName, Type, CacheEntryData::type, Type_fromJavaType(), Type_getArrayType(), and CacheEntryData::typeId.
Referenced by Java_org_postgresql_pljava_internal_Function__1reconcileTypes(), Java_org_postgresql_pljava_internal_Function__1storeToNonUDT(), Type_coerceDatumAs(), Type_coerceObjectBridged(), and Type_fromJavaType().
Type_fromOid()
Type Type_fromOid (Oid typeId, jobject typeMap)
Definition at line 713 of file Type.c.
{
    CacheEntry   ce;
    HeapTuple    typeTup;
    Form_pg_type typeStruct;
    Type         type = Type_fromOidCache(typeId);
    if ( NULL != type )
        return type;
    typeTup    = PgObject_getValidTuple(TYPEOID, typeId, "type");
    typeStruct = (Form_pg_type)GETSTRUCT(typeTup);
    if(typeStruct->typelem != 0 && typeStruct->typlen == -1)
    {
        type = Type_getArrayType(
            Type_fromOid(typeStruct->typelem, typeMap), typeId);
        goto finally;
    }
    /* For some reason, the anyarray is *not* an array with anyelement as the
     * element type. We'd like to see it that way though.
     * XXX would we, or does that mistake something intended in PostgreSQL?
     */
    if(typeId == ANYARRAYOID)
    {
        type = Type_getArrayType(Type_fromOid(ANYELEMENTOID, typeMap), typeId);
        goto finally;
    }
    if(typeStruct->typbasetype != 0)
    {
        /* Domain type, recurse using the base type (which in turn may
         * also be a domain)
         */
        type = Type_fromOid(typeStruct->typbasetype, typeMap);
        goto finally;
    }
    /*
     * Perhaps we have found a MappedUDT. If so, this check will register and
     * return it.
     */
    type = checkTypeMappedUDT(typeId, typeMap, typeStruct);
    if ( NULL != type )
        goto finally;
    /* Composite and record types will not have a TypeObtainer registered
     */
    if(typeStruct->typtype == 'c'
        || (typeStruct->typtype == 'p' && typeId == RECORDOID))
    {
        type = Composite_obtain(typeId);
        goto finally;
    }
    ce = (CacheEntry)HashMap_getByOid(s_obtainerByOid, typeId);
    if ( NULL == ce )
    {
        /*
         * Perhaps we have found a BaseUDT. If so, this check will register and
         * return it.
         */
        type = Function_checkTypeBaseUDT(typeId, typeStruct);
        if ( NULL != type )
            goto finally;
        /*
         * Default to String and standard textin/textout coercion.
         * Note: if the AS spec includes a Java signature, and the corresponding
         * Java type is not String, that will trigger a call to
         * Type_fromJavaType to see if a mapping is registered that way. If not,
         * *that* function reports 'No java type mapping installed for "%s"'.
         */
        type = String_obtain(typeId);
    }
    else
    {
        type = ce->type;
        if(type == 0)
            type = ce->obtainer(typeId);
    }
finally:
    ReleaseSysCache(typeTup);
    Type_cacheByOid(typeId, type);
    return type;
}
References checkTypeMappedUDT(), Composite_obtain(), Function_checkTypeBaseUDT(), HashMap_getByOid(), CacheEntryData::obtainer, PgObject_getValidTuple(), s_obtainerByOid, String_obtain(), Type, CacheEntryData::type, Type_cacheByOid(), Type_fromOid(), Type_fromOidCache(), and Type_getArrayType().
Referenced by _Any_getRealType(), _AnyArray_getRealType(), coerceObjects(), Java_org_postgresql_pljava_internal_Function__1storeToNonUDT(), Java_org_postgresql_pljava_internal_Relation__1modifyTuple(), Type_fromOid(), and Type_objectTypeFromOid().
Type_fromOidCache()
Type Type_fromOidCache (Oid typeId)
Definition at line 632 of file Type.c.
{
    return (Type)HashMap_getByOid(s_typeByOid, typeId);
}
References HashMap_getByOid(), s_typeByOid, and Type.
Referenced by Type_fromOid(), and UDT_registerUDT().
Type_getAlign()
char Type_getAlign (Type self)
Definition at line 344 of file Type.c.
{
    return self->align;
}
Referenced by _Array_coerceDatum(), and _Array_coerceObject().
Type_getArrayType()
Type Type_getArrayType (Type self, Oid arrayTypeId)
Definition at line 407 of file Type.c.
{
    Type arrayType = self->arrayType;
    if(arrayType != 0)
    {
        if(arrayType->typeId == arrayTypeId)
            return arrayType;
        if(arrayType->typeId == InvalidOid)
        {
            arrayType->typeId = arrayTypeId;
            return arrayType;
        }
    }
    arrayType = self->typeClass->createArrayType(self, arrayTypeId);
    self->arrayType = arrayType;
    return arrayType;
}
References Type.
Referenced by Type_fromJavaType(), and Type_fromOid().
Type_getClass()
TypeClass Type_getClass (Type self)
Definition at line 349 of file Type.c.
{
    return self->typeClass;
}
Referenced by _Boolean_canReplace(), _Byte_canReplace(), _Double_canReplace(), _Float_canReplace(), _Integer_canReplace(), _LocalDate_canReplaceType(), _LocalDateTime_canReplaceType(), _LocalTime_canReplaceType(), _Long_canReplace(), _OffsetDateTime_canReplaceType(), _OffsetTime_canReplaceType(), _Short_canReplace(), _SQLXML_canReplaceType(), _Timestamp_canReplaceType(), and _Timestamptz_canReplaceType().
Type_getCoerceIn()
Type Type_getCoerceIn (Type self, Type other)
Definition at line 206 of file Type.c.
{
    elog(DEBUG2, "Type_getCoerceIn(%d,%d)", self->typeId, other->typeId);
    return _getCoerce(self, other, other->typeId, self->typeId,
        &(self->inCoercions), Coerce_createIn);
}
References _getCoerce(), and Coerce_createIn().
Referenced by Java_org_postgresql_pljava_internal_Function__1reconcileTypes().
Type_getCoerceOut()
Type Type_getCoerceOut (Type self, Type other)
Definition at line 214 of file Type.c.
{
    elog(DEBUG2, "Type_getCoerceOut(%d,%d)", self->typeId, other->typeId);
    return _getCoerce(self, other, self->typeId, other->typeId,
        &(self->outCoercions), Coerce_createOut);
}
References _getCoerce(), and Coerce_createOut().
Referenced by Java_org_postgresql_pljava_internal_Function__1reconcileTypes().
Type_getElementType()
Type Type_getElementType (Type self)
Definition at line 426 of file Type.c.
{
    return self->elementType;
}
Referenced by _Any_getRealType(), _Array_canReplaceType(), _Array_coerceDatum(), _Array_coerceObject(), and passAsPrimitive().
Type_getJavaClass()
jclass Type_getJavaClass (Type self)
Definition at line 364 of file Type.c.
{
    TypeClass typeClass = self->typeClass;
    if(typeClass->javaClass == 0)
    {
        jclass cls;
        const char* cp = typeClass->JNISignature;
        if(cp == 0 || *cp == 0)
            ereport(ERROR, (
                errmsg("Type '%s' has no corresponding java class",
                    PgObjectClass_getName((PgObjectClass)typeClass))));
        if(*cp == 'L')
        {
            /* L<object name>; should be just <object name>. Strange
             * since the L and ; are retained if its an array.
             */
            size_t len = strlen(cp) - 2;
            char* bp = palloc(len + 1);
            memcpy(bp, cp + 1, len);
            bp[len] = 0;
            cls = PgObject_getJavaClass(bp);
            pfree(bp);
        }
        else
            cls = PgObject_getJavaClass(cp);
        typeClass->javaClass = JNI_newGlobalRef(cls);
        JNI_deleteLocalRef(cls);
    }
    return typeClass->javaClass;
}
References JNI_deleteLocalRef(), JNI_newGlobalRef(), PgObject_getJavaClass(), and PgObjectClass_getName().
Referenced by _Array_coerceDatum(), and Type_coerceDatumAs().
Type_getJavaTypeName()
const char * Type_getJavaTypeName (Type self)
Definition at line 397 of file Type.c.
{
    return self->typeClass->javaTypeName;
}
Referenced by Array_fromOid2(), Java_org_postgresql_pljava_internal_Function__1storeToNonUDT(), and Java_org_postgresql_pljava_internal_Oid__1getJavaClassName().
Type_getJNISignature()
const char * Type_getJNISignature (Type self)
Definition at line 402 of file Type.c.
{
    return self->typeClass->getJNISignature(self);
}
Referenced by _Coerce_getJNISignature(), and Array_fromOid2().
Type_getLength()
int16 Type_getLength (Type self)
Definition at line 354 of file Type.c.
{
    return self->length;
}
Referenced by _Array_coerceDatum(), _Array_coerceObject(), coerceScalarDatum(), coerceScalarObject(), UDT_input(), UDT_output(), UDT_receive(), and UDT_send().
Type_getObjectType()
Type Type_getObjectType (Type self)
Definition at line 431 of file Type.c.
{
    return self->objectType;
}
Referenced by _Any_getRealType(), _AnyArray_getRealType(), _Array_canReplaceType(), _Coerce_create(), and Array_fromOid2().
Type_getOid()
Oid Type_getOid (Type self)
Definition at line 441 of file Type.c.
{
    return self->typeId;
}
Referenced by _Array_coerceObject(), _Coerce_create(), _LocalDate_canReplaceType(), _LocalDateTime_canReplaceType(), _LocalTime_canReplaceType(), _OffsetDateTime_canReplaceType(), _OffsetTime_canReplaceType(), _SQLXML_canReplaceType(), _SQLXML_coerceDatum(), _SQLXML_coerceDatum_synthetic(), _SQLXML_coerceObject(), coerceScalarObject(), Java_org_postgresql_pljava_internal_Function__1reconcileTypes(), noTypmodYet(), UDT_input(), UDT_output(), UDT_receive(), and UDT_send().
Type_getRealType()
Type Type_getRealType (Type self, Oid realTypeId, jobject typeMap)
Definition at line 436 of file Type.c.
{
    return self->typeClass->getRealType(self, realTypeId, typeMap);
}
Referenced by Function_invoke().
Type_getSRFCollector()
jobject Type_getSRFCollector (Type self, PG_FUNCTION_ARGS)
Definition at line 849 of file Type.c.
{
    return self->typeClass->getSRFCollector(self, fcinfo);
}
Referenced by Type_invokeSRF().
Type_getTupleDesc()
TupleDesc Type_getTupleDesc (Type self, PG_FUNCTION_ARGS)
Definition at line 446 of file Type.c.
{
    return self->typeClass->getTupleDesc(self, fcinfo);
}
Referenced by _Composite_getSRFCollector(), _Composite_invoke(), Function_checkTypeBaseUDT(), and Function_create().
Type_initialize()
void Type_initialize (void) extern
Definition at line 976 of file Type.c.
{
    s_typeByOid          = HashMap_create(59, TopMemoryContext);
    s_obtainerByOid      = HashMap_create(59, TopMemoryContext);
    s_obtainerByJavaName = HashMap_create(59, TopMemoryContext);
    String_initialize();
    Any_initialize();
    Coerce_initialize();
    Void_initialize();
    Boolean_initialize();
    Byte_initialize();
    Short_initialize();
    Integer_initialize();
    Long_initialize();
    Float_initialize();
    Double_initialize();
    BigDecimal_initialize();
    Date_initialize();
    Time_initialize();
    Timestamp_initialize();
    Oid_initialize();
    AclId_initialize();
    byte_array_initialize();
    TupleTable_initialize();
    Composite_initialize();
    pljava_SQLXMLImpl_initialize();
    s_Map_class = JNI_newGlobalRef(PgObject_getJavaClass("java/util/Map"));
    s_Map_get = PgObject_getJavaMethod(
        s_Map_class, "get", "(Ljava/lang/Object;)Ljava/lang/Object;");
    s_Iterator_class = JNI_newGlobalRef(
        PgObject_getJavaClass("java/util/Iterator"));
    s_Iterator_hasNext = PgObject_getJavaMethod(
        s_Iterator_class, "hasNext", "()Z");
    s_Iterator_next = PgObject_getJavaMethod(
        s_Iterator_class, "next", "()Ljava/lang/Object;");
#if PG_VERSION_NUM < 110000
    BOOLARRAYOID   = get_array_type(BOOLOID);
    CHARARRAYOID   = get_array_type(CHAROID);
    FLOAT8ARRAYOID = get_array_type(FLOAT8OID);
    INT8ARRAYOID   = get_array_type(INT8OID);
#endif
    initializeTypeBridges();
}
References AclId_initialize(), Any_initialize(), BigDecimal_initialize(), BOOLARRAYOID, Boolean_initialize(), byte_array_initialize(), Byte_initialize(), CHARARRAYOID, Coerce_initialize(), Composite_initialize(), Date_initialize(), Double_initialize(), FLOAT8ARRAYOID, Float_initialize(), HashMap_create(), initializeTypeBridges(), INT8ARRAYOID, Integer_initialize(), JNI_newGlobalRef(), Long_initialize(), Oid_initialize(), PgObject_getJavaClass(), PgObject_getJavaMethod(), pljava_SQLXMLImpl_initialize(), s_Iterator_class, s_Iterator_hasNext, s_Iterator_next, s_Map_class, s_Map_get, s_obtainerByJavaName, s_obtainerByOid, s_typeByOid, Short_initialize(), String_initialize(), Time_initialize(), Timestamp_initialize(), TupleTable_initialize(), and Void_initialize().
Referenced by initPLJavaClasses().
Type_invoke()
Datum Type_invoke (Type self, Function fn, PG_FUNCTION_ARGS)
Definition at line 451 of file Type.c.
{
    return self->typeClass->invoke(self, fn, fcinfo);
}
Referenced by _Coerce_invoke(), Function_invoke(), and invokeTrigger().
Type_invokeSRF()
Datum Type_invokeSRF (Type self, Function fn, PG_FUNCTION_ARGS)
Definition at line 456 of file Type.c.
{
    jobject row;
    CallContextData* ctxData;
    FuncCallContext* context;
    MemoryContext currCtx;
    /* stuff done only on the first call of the function
     */
    if(SRF_IS_FIRSTCALL())
    {
        jobject tmp;
        /* create a function context for cross-call persistence
         */
        context = SRF_FIRSTCALL_INIT();
        /*
         * Before creating the rowProducer (and rowCollector, if applicable),
         * switch to the SRF_FIRSTCALL_INIT-created multi_call_memory_ctx that
         * is not reset between calls. The motivation seems clear enough (allow
         * the first-call initialization to allocate things in a context that
         * will last through the sequence), though it is not clear whether
         * anything in existing PL/Java code in fact does so (other than our
         * allocation of ctxData below, which could perhaps just be a direct
         * MemoryContextAllocZero).
         */
        currCtx = MemoryContextSwitchTo(context->multi_call_memory_ctx);
        /* Call the declared Java function. It returns an instance
         * that can produce the rows.
         */
        tmp = pljava_Function_refInvoke(fn);
        if(tmp == 0)
        {
            Invocation_assertDisconnect();
            MemoryContextSwitchTo(currCtx);
            fcinfo->isnull = true;
            SRF_RETURN_DONE(context);
        }
        ctxData = (CallContextData*)palloc0(sizeof(CallContextData));
        context->user_fctx = ctxData;
        ctxData->elemType = self;
        ctxData->fn = fn;
        ctxData->rowProducer = JNI_newGlobalRef(tmp);
        JNI_deleteLocalRef(tmp);
        /* Some row producers will need a writable result set in order
         * to produce the row. If one is needed, it's created here.
         */
        tmp = Type_getSRFCollector(self, fcinfo);
        if(tmp != 0)
        {
            ctxData->rowCollector = JNI_newGlobalRef(tmp);
            JNI_deleteLocalRef(tmp);
        }
        stashCallContext(ctxData);
        /* Register callback to be called when the function ends
         */
        RegisterExprContextCallback(
            ((ReturnSetInfo*)fcinfo->resultinfo)->econtext,
            _endOfSetCB, PointerGetDatum(ctxData));
        /*
         * Switch back to the context on entry, which by caller arrangement is
         * one that gets reset between calls. Thus here at the conclusion of the
         * first-call initialization, the context invariant below is satisfied.
         */
        MemoryContextSwitchTo(currCtx);
    }
    /*
     * Invariant: whether this is the first call and the SRF_IS_FIRSTCALL block
     * above just completed, or this is a subsequent call, at this point, the
     * memory context is the per-row one supplied by the executor (which gets
     * reset between calls).
     */
    context = SRF_PERCALL_SETUP();
    ctxData = (CallContextData*)context->user_fctx;
    currCtx = CurrentMemoryContext; /* save executor's per-row context */
    currentInvocation->hasConnected = ctxData->hasConnected;
    currentInvocation->invocation   = ctxData->invocation;
    if(JNI_TRUE == pljava_Function_vpcInvoke(ctxData->fn,
        ctxData->rowProducer, ctxData->rowCollector, (jlong)context->call_cntr,
        JNI_FALSE, &row))
    {
        Datum result = Type_datumFromSRF(self, row, ctxData->rowCollector);
        JNI_deleteLocalRef(row);
        stashCallContext(ctxData);
        currentInvocation->hasConnected = false;
        currentInvocation->invocation   = 0;
        MemoryContextSwitchTo(currCtx);
        SRF_RETURN_NEXT(context, result);
    }
    stashCallContext(ctxData);
    currentInvocation->hasConnected = false;
    currentInvocation->invocation   = 0;
    MemoryContextSwitchTo(currCtx);
    /* Unregister this callback and call it manually. We do this because
     * otherwise it will be called when the backend is in progress of
     * cleaning up Portals. If we close cursors (i.e. drop portals) in
     * the close, then that mechanism fails since attempts are made to
     * delete portals more then once.
     */
    UnregisterExprContextCallback(
        ((ReturnSetInfo*)fcinfo->resultinfo)->econtext,
        _endOfSetCB,
        PointerGetDatum(ctxData));
    _closeIteration(ctxData);
    /* This is the end of the set.
     */
    SRF_RETURN_DONE(context);
}
References _closeIteration(), _endOfSetCB(), currentInvocation, CallContextData::elemType, CallContextData::fn, CallContextData::hasConnected, CallContextData::invocation, Invocation_assertDisconnect(), JNI_deleteLocalRef(), JNI_newGlobalRef(), pljava_Function_refInvoke(), pljava_Function_vpcInvoke(), CallContextData::rowCollector, CallContextData::rowProducer, stashCallContext(), Type_datumFromSRF(), and Type_getSRFCollector().
Referenced by Function_invoke().
Type_isByValue()
bool Type_isByValue (Type self)
Definition at line 359 of file Type.c.
{
    return self->byValue;
}
Referenced by _Array_coerceDatum(), _Array_coerceObject(), coerceScalarDatum(), and coerceScalarObject().
Type_isDynamic()
bool Type_isDynamic (Type self)
Definition at line 276 of file Type.c.
{
    return self->typeClass->dynamic;
}
Referenced by Function_invoke().
Type_isOutParameter()
bool Type_isOutParameter (Type self)
Definition at line 281 of file Type.c.
{
    return self->typeClass->outParameter;
}
Referenced by Java_org_postgresql_pljava_internal_Function__1storeToNonUDT().
Type_isPrimitive()
bool Type_isPrimitive (Type self)
Definition at line 580 of file Type.c.
{
    return self->objectType != 0;
}
Referenced by _Any_getRealType(), _AnyArray_getRealType(), _Coerce_create(), Array_fromOid2(), Java_org_postgresql_pljava_internal_Function__1reconcileTypes(), and passAsPrimitive().
Type_objectTypeFromOid()
Type Type_objectTypeFromOid (Oid typeId, jobject typeMap)
Definition at line 801 of file Type.c.
{
    Type type = Type_fromOid(typeId, typeMap);
    Type objectType = type->objectType;
    return (objectType == 0) ? type : objectType;
}
References Type, and Type_fromOid().
Referenced by Java_org_postgresql_pljava_internal_Oid__1getJavaClassName(), Java_org_postgresql_pljava_internal_TupleDesc__1formTuple(), and pljava_TupleDesc_getColumnType().
Type_registerType()
void Type_registerType (const char * javaTypeName, Type type)
Definition at line 1163 of file Type.c.
{
    _registerType(type->typeId, javaTypeName, type, unimplementedTypeObtainer);
}
References _registerType(), and unimplementedTypeObtainer().
Referenced by Any_initialize(), Array_fromOid2(), Boolean_initialize(), byte_array_initialize(), Byte_initialize(), Date_initialize(), Double_initialize(), Float_initialize(), Integer_initialize(), Long_initialize(), Oid_initialize(), pljava_TriggerData_initialize(), pljava_Tuple_initialize(), pljava_TupleDesc_initialize(), Short_initialize(), Time_initialize(), Timestamp_initialize(), UDT_registerUDT(), and Void_initialize().
Type_registerType2()
void Type_registerType2 (Oid typeId, const char * javaTypeName, TypeObtainer obtainer)
Definition at line 1168 of file Type.c.
{
    _registerType(typeId, javaTypeName, 0, obtainer);
}
References _registerType().
Referenced by BigDecimal_initialize(), Composite_initialize(), Date_initialize(), pljava_SQLXMLImpl_initialize(), String_initialize(), Time_initialize(), and Timestamp_initialize().
TypeClass_alloc()
TypeClass TypeClass_alloc (const char * typeName)
Definition at line 1060 of file Type.c.
{
    return TypeClass_alloc2(
        typeName, sizeof(struct TypeClass_), sizeof(struct Type_));
}
References TypeClass_alloc2().
Referenced by Any_initialize(), Array_fromOid2(), Boolean_initialize(), byte_array_initialize(), Byte_initialize(), Date_initialize(), Double_initialize(), Float_initialize(), Integer_initialize(), Long_initialize(), Oid_initialize(), pljava_SQLXMLImpl_initialize(), pljava_TriggerData_initialize(), pljava_Tuple_initialize(), pljava_TupleDesc_initialize(), Short_initialize(), Time_initialize(), Timestamp_initialize(), and Void_initialize().
TypeClass_alloc2()
TypeClass TypeClass_alloc2 (const char * typeName, Size classSize, Size instanceSize)
Definition at line 1066 of file Type.c.
{
    TypeClass self = (TypeClass)MemoryContextAlloc(TopMemoryContext, classSize);
    PgObjectClass_init((PgObjectClass)self, typeName, instanceSize, 0);
    self->JNISignature    = "";
    self->javaTypeName    = "";
    self->javaClass       = 0;
    self->canReplaceType  = _Type_canReplaceType;
    self->coerceDatum     = unimplementedDatumCoercer;
    self->coerceObject    = unimplementedObjectCoercer;
    self->createArrayType = _Type_createArrayType;
    self->invoke          = _Type_invoke;
    self->getSRFCollector = _Type_getSRFCollector;
    self->datumFromSRF    = _Type_datumFromSRF;
    self->getTupleDesc    = _Type_getTupleDesc;
    self->getJNISignature = _Type_getJNISignature;
    self->dynamic         = false;
    self->outParameter    = false;
    self->getRealType     = _Type_getRealType;
    return self;
}
References _Type_canReplaceType(), _Type_createArrayType(), _Type_datumFromSRF(), _Type_getJNISignature(), _Type_getRealType(), _Type_getSRFCollector(), _Type_getTupleDesc(), _Type_invoke(), PgObjectClass_init(), unimplementedDatumCoercer(), and unimplementedObjectCoercer().
Referenced by BigDecimal_initialize(), Coerce_initialize(), Composite_initialize(), String_initialize(), TypeClass_alloc(), and UDT_registerUDT().
TypeClass_allocInstance()
Type TypeClass_allocInstance (TypeClass cls, Oid typeId)
Definition at line 1092 of file Type.c.
{
    return TypeClass_allocInstance2(cls, typeId, 0);
}
References TypeClass_allocInstance2().
Referenced by _Coerce_create(), _LocalDate_obtain(), _LocalDateTime_obtain(), _LocalTime_obtain(), _OffsetDateTime_obtain(), _OffsetTime_obtain(), _SQLXML_obtain(), Any_initialize(), Array_fromOid2(), Boolean_initialize(), byte_array_initialize(), Byte_initialize(), Composite_obtain(), Date_initialize(), Double_initialize(), Float_initialize(), Integer_initialize(), Long_initialize(), Oid_initialize(), pljava_TriggerData_initialize(), pljava_Tuple_initialize(), pljava_TupleDesc_initialize(), Short_initialize(), String_create(), Time_initialize(), Timestamp_initialize(), and Void_initialize().
TypeClass_allocInstance2()
Type TypeClass_allocInstance2 (TypeClass cls, Oid typeId, Form_pg_type pgType)
Definition at line 1100 of file Type.c.
{
    Type t = (Type)
        PgObjectClass_allocInstance((PgObjectClass)(cls), TopMemoryContext);
    t->typeId       = typeId;
    t->arrayType    = 0;
    t->elementType  = 0;
    t->objectType   = 0;
    t->inCoercions  = 0;
    t->outCoercions = 0;
    if(pgType != 0)
    {
        t->length  = pgType->typlen;
        t->byValue = pgType->typbyval;
        t->align   = pgType->typalign;
    }
    else if(typeId != InvalidOid)
    {
        get_typlenbyvalalign(typeId,
                         &t->length,
                         &t->byValue,
                         &t->align);
    }
    else
    {
        t->length = 0;
        t->byValue = true;
        t->align = 'i';
    }
    return t;
}
References PgObjectClass_allocInstance(), and Type.
Referenced by TypeClass_allocInstance(), and UDT_registerUDT().
unimplementedDatumCoercer()
static jvalue unimplementedDatumCoercer (Type t, Datum d) static
Definition at line 1043 of file Type.c.
{
    ereport(ERROR,
        (errmsg("no datum coercer registered for type oid %ud", t->typeId)));
    pg_unreachable();
}
Referenced by TypeClass_alloc2().
unimplementedObjectCoercer()
static Datum unimplementedObjectCoercer (Type t, jobject o) static
Definition at line 1050 of file Type.c.
{
    ereport(ERROR,
        (errmsg("no object coercer registered for type oid %ud", t->typeId)));
    pg_unreachable();
}
Referenced by TypeClass_alloc2().
unimplementedTypeObtainer()
static Type unimplementedTypeObtainer (Oid typeId) static
Definition at line 1036 of file Type.c.
{
    ereport(ERROR,
        (errmsg("no type obtainer registered for type oid %ud", typeId)));
    pg_unreachable();
}
Referenced by Type_registerType().
Void_initialize()
void Void_initialize (void) extern
Definition at line 44 of file Void.c.
{
    TypeClass cls = TypeClass_alloc("type.void");
    cls->JNISignature = "V";
    cls->javaTypeName = "void";
    cls->invoke       = _void_invoke;
    cls->coerceDatum  = _void_coerceDatum;
    cls->coerceObject = _void_coerceObject;
    Type_registerType("void", TypeClass_allocInstance(cls, VOIDOID));
}
References _void_coerceDatum(), _void_coerceObject(), _void_invoke(), Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Variable Documentation
BOOLARRAYOID
Oid BOOLARRAYOID static
Definition at line 34 of file Type.c.
Referenced by initializeTypeBridges(), and Type_initialize().
CHARARRAYOID
Oid CHARARRAYOID static
Definition at line 35 of file Type.c.
Referenced by Type_coerceObjectBridged(), and Type_initialize().
FLOAT8ARRAYOID
Oid FLOAT8ARRAYOID static
Definition at line 36 of file Type.c.
Referenced by initializeTypeBridges(), and Type_initialize().
INT8ARRAYOID
Oid INT8ARRAYOID static
Definition at line 37 of file Type.c.
Referenced by initializeTypeBridges(), and Type_initialize().
s_Iterator_class
jclass s_Iterator_class static
Definition at line 56 of file Type.c.
Referenced by Type_initialize().
s_Iterator_hasNext
jmethodID s_Iterator_hasNext static
Definition at line 57 of file Type.c.
Referenced by Type_initialize().
s_Iterator_next
jmethodID s_Iterator_next static
Definition at line 58 of file Type.c.
Referenced by Type_initialize().
s_Map_class
jclass s_Map_class static
Definition at line 44 of file Type.c.
Referenced by Type_initialize().
s_Map_get
jmethodID s_Map_get static
Definition at line 45 of file Type.c.
Referenced by checkTypeMappedUDT(), and Type_initialize().
s_obtainerByJavaName
HashMap s_obtainerByJavaName static
Definition at line 42 of file Type.c.
Referenced by _registerType(), Type_fromJavaType(), and Type_initialize().
s_obtainerByOid
HashMap s_obtainerByOid static
Definition at line 41 of file Type.c.
Referenced by _registerType(), Type_fromOid(), and Type_initialize().
s_TypeBridge_Holder_class
jclass s_TypeBridge_Holder_class static
Definition at line 60 of file Type.c.
Referenced by initializeTypeBridges(), and Type_coerceObjectBridged().
s_TypeBridge_Holder_className
jmethodID s_TypeBridge_Holder_className static
Definition at line 61 of file Type.c.
Referenced by initializeTypeBridges(), and Type_coerceObjectBridged().
s_TypeBridge_Holder_defaultOid
jmethodID s_TypeBridge_Holder_defaultOid static
Definition at line 62 of file Type.c.
Referenced by initializeTypeBridges().
s_TypeBridge_Holder_payload
jmethodID s_TypeBridge_Holder_payload static
Definition at line 63 of file Type.c.
Referenced by initializeTypeBridges(), and Type_coerceObjectBridged().
s_typeByOid
HashMap s_typeByOid static
Definition at line 40 of file Type.c.
Referenced by Type_cacheByOid(), Type_fromOidCache(), and Type_initialize().