PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/TupleDesc.c File Reference
TupleDesc.c File Reference
#include <postgres.h>
#include <executor/spi.h>
#include <funcapi.h>
#include "org_postgresql_pljava_internal_TupleDesc.h"
#include "pljava/Backend.h"
#include "pljava/DualState.h"
#include "pljava/Exception.h"
#include "pljava/Invocation.h"
#include "pljava/type/Type_priv.h"
#include "pljava/type/String.h"
#include "pljava/type/Tuple.h"
#include "pljava/type/TupleDesc.h"
#include "pljava/type/Oid.h"
Functions
jobject pljava_TupleDesc_create (TupleDesc td)
jobject pljava_TupleDesc_internalCreate (TupleDesc td)
Type pljava_TupleDesc_getColumnType (TupleDesc tupleDesc, int index)
static jvalue _TupleDesc_coerceDatum (Type self, Datum arg)
void pljava_TupleDesc_initialize (void)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_TupleDesc__1getColumnName (JNIEnv *env, jclass cls, jlong _this, jint index)
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_TupleDesc__1getColumnIndex (JNIEnv *env, jclass cls, jlong _this, jstring colName)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TupleDesc__1formTuple (JNIEnv *env, jclass cls, jlong _this, jobjectArray jvalues)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TupleDesc__1getOid (JNIEnv *env, jclass cls, jlong _this, jint index)
Variables
static jclass s_TupleDesc_class
static jmethodID s_TupleDesc_init
Function Documentation
_TupleDesc_coerceDatum()
static jvalue _TupleDesc_coerceDatum (Type self, Datum arg) static
Definition at line 89 of file TupleDesc.c.
{
    jvalue result;
    result.l = pljava_TupleDesc_create((TupleDesc)DatumGetPointer(arg));
    return result;
}
References pljava_TupleDesc_create().
Referenced by pljava_TupleDesc_initialize().
Java_org_postgresql_pljava_internal_TupleDesc__1formTuple()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TupleDesc__1formTuple (JNIEnv * env, jclass cls, jlong _this, jobjectArray jvalues)
Definition at line 220 of file TupleDesc.c.
{
    jobject result = 0;
    BEGIN_NATIVE
    Ptr2Long p2l;
    p2l.longVal = _this;
    PG_TRY();
    {
        jint   idx;
        HeapTuple tuple;
        MemoryContext curr;
        TupleDesc self = (TupleDesc)p2l.ptrVal;
        int    count   = self->natts;
        Datum* values  = (Datum*)palloc(count * sizeof(Datum));
        bool*  nulls   = palloc(count * sizeof(bool));
        jobject typeMap = Invocation_getTypeMap(); /* a global ref */
        memset(values, 0,  count * sizeof(Datum));
        memset(nulls, true, count * sizeof(bool));/*all values null initially*/
        for(idx = 0; idx < count; ++idx)
        {
            jobject value = JNI_getObjectArrayElement(jvalues, idx);
            if(value != 0)
            {
                /* Obtain boxed types here too, when that matters. */
                Type type = Type_objectTypeFromOid(SPI_gettypeid(self, idx + 1), typeMap);
                values[idx] = Type_coerceObjectBridged(type, value);
                nulls[idx] = false;
                JNI_deleteLocalRef(value);
            }
        }
        curr = MemoryContextSwitchTo(JavaMemoryContext);
        tuple = heap_form_tuple(self, values, nulls);
        result = pljava_Tuple_internalCreate(tuple, false);
        MemoryContextSwitchTo(curr);
        pfree(values);
        pfree(nulls);
    }
    PG_CATCH();
    {
        Exception_throw_ERROR("heap_formtuple");
    }
    PG_END_TRY();
    END_NATIVE
    return result;
}
References Exception_throw_ERROR(), Invocation_getTypeMap(), JavaMemoryContext, jint(), JNI_deleteLocalRef(), JNI_getObjectArrayElement(), pljava_Tuple_internalCreate(), Type, Type_coerceObjectBridged(), and Type_objectTypeFromOid().
Referenced by pljava_TupleDesc_initialize().
Java_org_postgresql_pljava_internal_TupleDesc__1getColumnIndex()
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_TupleDesc__1getColumnIndex (JNIEnv * env, jclass cls, jlong _this, jstring colName)
Definition at line 184 of file TupleDesc.c.
{
    jint result = 0;
    BEGIN_NATIVE
    char* name = String_createNTS(colName);
    if(name != 0)
    {
        Ptr2Long p2l;
        p2l.longVal = _this;
        PG_TRY();
        {
            result = SPI_fnumber((TupleDesc)p2l.ptrVal, name);
            if(result == SPI_ERROR_NOATTRIBUTE)
            {
                Exception_throw(ERRCODE_UNDEFINED_COLUMN,
                    "Tuple has no attribute \"%s\"", name);
            }
            pfree(name);
        }
        PG_CATCH();
        {
            Exception_throw_ERROR("SPI_fnumber");
        }
        PG_END_TRY();
    }
    END_NATIVE
    return result;
}
References Exception_throw(), Exception_throw_ERROR(), jint(), and String_createNTS().
Referenced by pljava_TupleDesc_initialize().
Java_org_postgresql_pljava_internal_TupleDesc__1getColumnName()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_TupleDesc__1getColumnName (JNIEnv * env, jclass cls, jlong _this, jint index)
Definition at line 147 of file TupleDesc.c.
{
    jstring result = 0;
    BEGIN_NATIVE
    PG_TRY();
    {
        char* name;
        Ptr2Long p2l;
        p2l.longVal = _this;
        name = SPI_fname((TupleDesc)p2l.ptrVal, (int)index);
        if(name == 0)
        {
            Exception_throw(ERRCODE_INVALID_DESCRIPTOR_INDEX,
                "Invalid attribute index \"%d\"", (int)index);
        }
        else
        {
            result = String_createJavaStringFromNTS(name);
            pfree(name);
        }
    }
    PG_CATCH();
    {
        Exception_throw_ERROR("SPI_fname");
    }
    PG_END_TRY();
    END_NATIVE
    return result;
}
References Exception_throw(), Exception_throw_ERROR(), and String_createJavaStringFromNTS().
Referenced by pljava_TupleDesc_initialize().
Java_org_postgresql_pljava_internal_TupleDesc__1getOid()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TupleDesc__1getOid (JNIEnv * env, jclass cls, jlong _this, jint index)
Definition at line 276 of file TupleDesc.c.
{
    jobject result = 0;
    BEGIN_NATIVE
    Ptr2Long p2l;
    p2l.longVal = _this;
    PG_TRY();
    {
        Oid typeId = SPI_gettypeid((TupleDesc)p2l.ptrVal, (int)index);
        if(!OidIsValid(typeId))
        {
            Exception_throw(ERRCODE_INVALID_DESCRIPTOR_INDEX,
                "Invalid attribute index \"%d\"", (int)index);
        }
        else
        {
            result = Oid_create(typeId);
        }
    }
    PG_CATCH();
    {
        Exception_throw_ERROR("SPI_gettypeid");
    }
    PG_END_TRY();
    END_NATIVE
    return result;
}
References Exception_throw(), Exception_throw_ERROR(), and Oid_create().
Referenced by pljava_TupleDesc_initialize().
pljava_TupleDesc_create()
jobject pljava_TupleDesc_create (TupleDesc td)
Definition at line 37 of file TupleDesc.c.
{
    jobject jtd = 0;
    if(td != 0)
    {
        MemoryContext curr = MemoryContextSwitchTo(JavaMemoryContext);
        jtd = pljava_TupleDesc_internalCreate(td);
        MemoryContextSwitchTo(curr);
    }
    return jtd;
}
References JavaMemoryContext, and pljava_TupleDesc_internalCreate().
Referenced by _Composite_getSRFCollector(), _Composite_invoke(), _TupleDesc_coerceDatum(), Java_org_postgresql_pljava_internal_Portal__1getTupleDesc(), Java_org_postgresql_pljava_internal_Relation__1getTupleDesc(), pljava_SingleRowReader_getTupleDesc(), and SQLOutputToTuple_create().
pljava_TupleDesc_getColumnType()
Type pljava_TupleDesc_getColumnType (TupleDesc tupleDesc, int index)
Definition at line 74 of file TupleDesc.c.
{
    Type type;
    Oid typeId = SPI_gettypeid(tupleDesc, index);
    if(!OidIsValid(typeId))
    {
        Exception_throw(ERRCODE_INVALID_DESCRIPTOR_INDEX,
            "Invalid attribute index \"%d\"", (int)index);
        type = 0;
    }
    else /* Type_objectTypeFromOid returns boxed types, when that matters */
        type = Type_objectTypeFromOid(typeId, Invocation_getTypeMap());
    return type;
}
References Exception_throw(), Invocation_getTypeMap(), Type, and Type_objectTypeFromOid().
Referenced by Java_org_postgresql_pljava_jdbc_SingleRowReader__1getObject(), and pljava_Tuple_getObject().
pljava_TupleDesc_initialize()
void pljava_TupleDesc_initialize (void) extern
Definition at line 99 of file TupleDesc.c.
{
    TypeClass cls;
    JNINativeMethod methods[] = {
        {
        "_getColumnName",
        "(JI)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_TupleDesc__1getColumnName
        },
        {
        "_getColumnIndex",
        "(JLjava/lang/String;)I",
        Java_org_postgresql_pljava_internal_TupleDesc__1getColumnIndex
        },
        {
        "_formTuple",
        "(J[Ljava/lang/Object;)Lorg/postgresql/pljava/internal/Tuple;",
        Java_org_postgresql_pljava_internal_TupleDesc__1formTuple
        },
        {
        "_getOid",
        "(JI)Lorg/postgresql/pljava/internal/Oid;",
        Java_org_postgresql_pljava_internal_TupleDesc__1getOid
        },
        { 0, 0, 0 }};
    s_TupleDesc_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/internal/TupleDesc"));
    PgObject_registerNatives2(s_TupleDesc_class, methods);
    s_TupleDesc_init = PgObject_getJavaMethod(s_TupleDesc_class, "<init>",
        "(Lorg/postgresql/pljava/internal/DualState$Key;JJI)V");
    cls = TypeClass_alloc("type.TupleDesc");
    cls->JNISignature = "Lorg/postgresql/pljava/internal/TupleDesc;";
    cls->javaTypeName = "org.postgresql.pljava.internal.TupleDesc";
    cls->coerceDatum  = _TupleDesc_coerceDatum;
    Type_registerType("org.postgresql.pljava.internal.TupleDesc", TypeClass_allocInstance(cls, InvalidOid));
}
References _TupleDesc_coerceDatum(), Java_org_postgresql_pljava_internal_TupleDesc__1formTuple(), Java_org_postgresql_pljava_internal_TupleDesc__1getColumnIndex(), Java_org_postgresql_pljava_internal_TupleDesc__1getColumnName(), Java_org_postgresql_pljava_internal_TupleDesc__1getOid(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_registerNatives2(), s_TupleDesc_class, s_TupleDesc_init, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by pljava_DualState_initialize().
pljava_TupleDesc_internalCreate()
jobject pljava_TupleDesc_internalCreate (TupleDesc td)
Definition at line 49 of file TupleDesc.c.
{
    jobject jtd;
    Ptr2Long tdH;
    td = CreateTupleDescCopyConstr(td);
    tdH.longVal = 0L; /* ensure that the rest is zeroed out */
    tdH.ptrVal = td;
    /*
     * Passing (jlong)0 as the ResourceOwner means this will never be matched by a
     * nativeRelease call; that's appropriate (for now) as the TupleDesc copy is
     * being made into JavaMemoryContext, which never gets reset, so only
     * unreachability from the Java side will free it.
     * XXX what about invalidating if DDL alters the column layout?
     */
    jtd = JNI_newObjectLocked(s_TupleDesc_class, s_TupleDesc_init,
        pljava_DualState_key(), (jlong)0, tdH.longVal, (jint)td->natts);
    return jtd;
}
References jint(), JNI_newObjectLocked(), pljava_DualState_key(), s_TupleDesc_class, and s_TupleDesc_init.
Referenced by pljava_TupleDesc_create(), TupleTable_create(), and TupleTable_createFromSlot().
Variable Documentation
s_TupleDesc_class
jclass s_TupleDesc_class static
Definition at line 28 of file TupleDesc.c.
Referenced by pljava_TupleDesc_initialize(), and pljava_TupleDesc_internalCreate().
s_TupleDesc_init
jmethodID s_TupleDesc_init static
Definition at line 29 of file TupleDesc.c.
Referenced by pljava_TupleDesc_initialize(), and pljava_TupleDesc_internalCreate().