PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/Iterator.c File Reference
Iterator.c File Reference
#include "pljava/HashMap_priv.h"
#include "pljava/Iterator.h"
Data Structures
struct Iterator_
Functions
Iterator Iterator_create (HashMap source)
static Entry Iterator_peekNext (Iterator self)
bool Iterator_hasNext (Iterator self)
Entry Iterator_next (Iterator self)
void Iterator_initialize (void)
Variables
static PgObjectClass s_IteratorClass
Data Structure Documentation
Iterator_
struct Iterator_
Definition at line 12 of file Iterator.c.
Data Fields
uint32 currentBucket
Entry nextEntry
struct PgObject_ PgObject_extension
HashMap source
uint32 sourceTableSize
Function Documentation
Iterator_create()
Iterator Iterator_create (HashMap source)
Definition at line 23 of file Iterator.c.
{
    Iterator self = (Iterator)PgObjectClass_allocInstance(s_IteratorClass, GetMemoryChunkContext(source));
    self->source = source;
    self->sourceTableSize = source->tableSize;
    self->currentBucket = 0;
    self->nextEntry = 0;
    return self;
}
References PgObjectClass_allocInstance(), and s_IteratorClass.
Referenced by Function_clearFunctionCache(), and HashMap_entries().
Iterator_hasNext()
bool Iterator_hasNext (Iterator self)
Definition at line 61 of file Iterator.c.
{
    return Iterator_peekNext(self) != 0;
}
References Iterator_peekNext().
Iterator_initialize()
void Iterator_initialize (void) extern
Definition at line 83 of file Iterator.c.
{
    s_IteratorClass = PgObjectClass_create("Iterator", sizeof(struct Iterator_), 0);
}
References PgObjectClass_create(), and s_IteratorClass.
Referenced by HashMap_initialize().
Iterator_next()
Entry Iterator_next (Iterator self)
Definition at line 66 of file Iterator.c.
{
    Entry nxt = Iterator_peekNext(self);
    if(nxt != 0)
    {
        Entry nxtNxt = nxt->next;
        if(nxtNxt == 0)
            /*
             * Leave this bucket.
             */
            self->currentBucket++;
        self->nextEntry = nxtNxt;
    }
    return nxt;
}
References Iterator_peekNext().
Referenced by Function_clearFunctionCache().
Iterator_peekNext()
static Entry Iterator_peekNext (Iterator self) static
Definition at line 33 of file Iterator.c.
{
    uint32 tableSize = self->source->tableSize;
    if(tableSize != self->sourceTableSize)
    {
        /* Rehash during Iteration. We can't continue.
         */
        self->nextEntry = 0;
    }
    else if(self->nextEntry == 0)
    {
        /* Go to next bucket
         */
        Entry* table = self->source->table;
        while(self->currentBucket < tableSize)
        {
            Entry nxt = table[self->currentBucket];
            if(nxt != 0)
            {
                self->nextEntry = nxt;
                break;
            }
            self->currentBucket++;
        }
    }
    return self->nextEntry;
}
Referenced by Iterator_hasNext(), and Iterator_next().
Variable Documentation
s_IteratorClass
PgObjectClass s_IteratorClass static
Definition at line 21 of file Iterator.c.
Referenced by Iterator_create(), and Iterator_initialize().