PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Void.c File Reference
Void.c File Reference
#include <postgres.h>
#include <utils/memutils.h>
#include <utils/numeric.h>
#include "pljava/type/Type_priv.h"
Functions
static Datum _void_invoke (Type self, Function fn, PG_FUNCTION_ARGS)
static jvalue _void_coerceDatum (Type self, Datum nothing)
static Datum _void_coerceObject (Type self, jobject nothing)
void Void_initialize (void)
Function Documentation
_void_coerceDatum()
static jvalue _void_coerceDatum (Type self, Datum nothing) static
Definition at line 29 of file Void.c.
{
    jvalue result;
    result.j = 0L;
    return result;
}
Referenced by Void_initialize().
_void_coerceObject()
static Datum _void_coerceObject (Type self, jobject nothing) static
Definition at line 36 of file Void.c.
{
    return 0;
}
Referenced by Void_initialize().
_void_invoke()
static Datum _void_invoke (Type self, Function fn, PG_FUNCTION_ARGS) static
Definition at line 22 of file Void.c.
{
    pljava_Function_voidInvoke(fn);
    fcinfo->isnull = true;
    return 0;
}
References pljava_Function_voidInvoke().
Referenced by Void_initialize().
Void_initialize()
void Void_initialize (void) extern
Definition at line 44 of file Void.c.
{
    TypeClass cls = TypeClass_alloc("type.void");
    cls->JNISignature = "V";
    cls->javaTypeName = "void";
    cls->invoke       = _void_invoke;
    cls->coerceDatum  = _void_coerceDatum;
    cls->coerceObject = _void_coerceObject;
    Type_registerType("void", TypeClass_allocInstance(cls, VOIDOID));
}
References _void_coerceDatum(), _void_coerceObject(), _void_invoke(), Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().