PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/VarlenaWrapper.c File Reference
VarlenaWrapper.c File Reference
#include <postgres.h>
#include <access/tuptoaster.h>
#include <utils/datum.h>
#include <utils/snapshot.h>
#include <utils/snapmgr.h>
#include "org_postgresql_pljava_internal_VarlenaWrapper_Input_State.h"
#include "org_postgresql_pljava_internal_VarlenaWrapper_Output_State.h"
#include "pljava/VarlenaWrapper.h"
#include "pljava/DualState.h"
#include "pljava/PgObject.h"
#include "pljava/JNICalls.h"
Data Structures
struct ExpandedVarlenaOutputStreamNode
struct ExpandedVarlenaOutputStreamHeader
Macros
#define detoast_external_attr heap_tuple_fetch_attr
#define GetOldestSnapshot() NULL
#define _VL_TYPE struct varlena *
#define VARATT_EXTERNAL_GET_EXTSIZE(toast_pointer) ((toast_pointer).va_extsize)
#define INITIALSIZE 1024
Functions
static Size VOS_get_flat_size (ExpandedObjectHeader *eohptr)
static void VOS_flatten_into (ExpandedObjectHeader *eohptr, void *result, Size allocated_size)
jobject pljava_VarlenaWrapper_Input (Datum d, MemoryContext parent, ResourceOwner ro)
jobject pljava_VarlenaWrapper_Output (MemoryContext parent, ResourceOwner ro)
Datum pljava_VarlenaWrapper_adopt (jobject vlw)
void pljava_VarlenaWrapper_initialize (void)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1unregisterSnapshot (JNIEnv *env, jobject _this, jlong snapshot, jlong ro)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1detoast (JNIEnv *env, jobject _this, jlong vl, jlong cxt, jlong snap, jlong resOwner)
JNIEXPORT jlong JNICALL Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1fetch (JNIEnv *env, jobject _this, jlong varlena, jlong memContext)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Output_00024State__1nextBuffer (JNIEnv *env, jobject _this, jlong varlenaPtr, jint currentBufPosition, jint desiredCapacity)
Variables
static jclass s_VarlenaWrapper_class
static jmethodID s_VarlenaWrapper_adopt
static jclass s_VarlenaWrapper_Input_class
static jclass s_VarlenaWrapper_Output_class
static jmethodID s_VarlenaWrapper_Input_init
static jmethodID s_VarlenaWrapper_Output_init
static jfieldID s_VarlenaWrapper_Input_State_varlena
static const ExpandedObjectMethods VOS_methods
Data Structure Documentation
ExpandedVarlenaOutputStreamNode
struct ExpandedVarlenaOutputStreamNode
Definition at line 82 of file VarlenaWrapper.c.
Data Fields
ExpandedVarlenaOutputStreamNode * next
Size size
ExpandedVarlenaOutputStreamHeader
struct ExpandedVarlenaOutputStreamHeader
Definition at line 88 of file VarlenaWrapper.c.
Data Fields
ExpandedObjectHeader hdr
ExpandedVarlenaOutputStreamNode * tail
Size total_size
Macro Definition Documentation
_VL_TYPE
#define _VL_TYPE struct varlena *
Definition at line 39 of file VarlenaWrapper.c.
detoast_external_attr
#define detoast_external_attr heap_tuple_fetch_attr
Definition at line 18 of file VarlenaWrapper.c.
GetOldestSnapshot
#define GetOldestSnapshot () NULL
Definition at line 36 of file VarlenaWrapper.c.
INITIALSIZE
#define INITIALSIZE 1024
Definition at line 45 of file VarlenaWrapper.c.
VARATT_EXTERNAL_GET_EXTSIZE
#define VARATT_EXTERNAL_GET_EXTSIZE (toast_pointer) ((toast_pointer).va_extsize)
Definition at line 42 of file VarlenaWrapper.c.
Function Documentation
Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1detoast()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1detoast (JNIEnv * env, jobject _this, jlong vl, jlong cxt, jlong snap, jlong resOwner)
Definition at line 409 of file VarlenaWrapper.c.
{
    Ptr2Long p2lvl;
    Ptr2Long p2lcxt;
    Ptr2Long p2lsnap;
    Ptr2Long p2lro;
    Ptr2Long p2ldetoasted;
    _VL_TYPE detoasted;
    MemoryContext prevcxt;
    jobject dbb = NULL;
    BEGIN_NATIVE_NO_ERRCHECK
    p2lvl.longVal = vl;
    p2lcxt.longVal = cxt;
    p2lsnap.longVal = snap;
    p2lro.longVal = resOwner;
    prevcxt = MemoryContextSwitchTo((MemoryContext)p2lcxt.ptrVal);
    detoasted = (_VL_TYPE) PG_DETOAST_DATUM_COPY(PointerGetDatum(p2lvl.ptrVal));
    p2ldetoasted.longVal = 0L;
    p2ldetoasted.ptrVal = detoasted;
    MemoryContextSwitchTo(prevcxt);
    JNI_setLongField(_this,
        s_VarlenaWrapper_Input_State_varlena, p2ldetoasted.longVal);
    pfree(p2lvl.ptrVal);
    if ( 0 != snap )
        UnregisterSnapshotFromOwner(p2lsnap.ptrVal, p2lro.ptrVal);
    dbb = JNI_newDirectByteBuffer(
        VARDATA(detoasted), VARSIZE_ANY_EXHDR(detoasted));
    END_NATIVE
    return dbb;
}
References _VL_TYPE, JNI_newDirectByteBuffer(), JNI_setLongField(), and s_VarlenaWrapper_Input_State_varlena.
Referenced by pljava_VarlenaWrapper_initialize().
Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1fetch()
JNIEXPORT jlong JNICALL Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1fetch (JNIEnv * env, jobject _this, jlong varlena, jlong memContext)
Definition at line 464 of file VarlenaWrapper.c.
{
    Ptr2Long p2lvl;
    Ptr2Long p2lcxt;
    MemoryContext prevcxt;
    _VL_TYPE fetched;
    p2lvl.longVal = varlena;
    p2lcxt.longVal = memContext;
    BEGIN_NATIVE_NO_ERRCHECK;
    prevcxt = MemoryContextSwitchTo((MemoryContext) p2lcxt.ptrVal);
    fetched = detoast_external_attr((_VL_TYPE) p2lvl.ptrVal);
    pfree(p2lvl.ptrVal);
    p2lvl.longVal = 0L;
    p2lvl.ptrVal = fetched;
    MemoryContextSwitchTo(prevcxt);
    END_NATIVE;
    return p2lvl.longVal;
}
References _VL_TYPE, and detoast_external_attr.
Referenced by pljava_VarlenaWrapper_initialize().
Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1unregisterSnapshot()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1unregisterSnapshot (JNIEnv * env, jobject _this, jlong snapshot, jlong ro)
Definition at line 391 of file VarlenaWrapper.c.
{
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2lsnap;
    Ptr2Long p2lro;
    p2lsnap.longVal = snapshot;
    p2lro.longVal = ro;
    UnregisterSnapshotFromOwner(p2lsnap.ptrVal, p2lro.ptrVal);
    END_NATIVE
}
Referenced by pljava_VarlenaWrapper_initialize().
Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Output_00024State__1nextBuffer()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Output_00024State__1nextBuffer (JNIEnv * env, jobject _this, jlong varlenaPtr, jint currentBufPosition, jint desiredCapacity)
Definition at line 493 of file VarlenaWrapper.c.
{
    ExpandedVarlenaOutputStreamHeader *evosh;
    ExpandedVarlenaOutputStreamNode *node;
    Ptr2Long p2l;
    Datum d;
    jobject dbb = NULL;
    p2l.longVal = varlenaPtr;
    d = PointerGetDatum(p2l.ptrVal);
    evosh = (ExpandedVarlenaOutputStreamHeader *)DatumGetEOHP(d);
    evosh->tail->size  = currentBufPosition;
    evosh->total_size += currentBufPosition;
    if ( 0 == desiredCapacity )
        return NULL;
    BEGIN_NATIVE
    /*
     * This adjustment of desiredCapacity is arbitrary and amenable to
     * performance experimentation. For initial signs of life, ignore the
     * desiredCapacity hint completely and use a hardwired size.
     */
    desiredCapacity = 8180;
    node = (ExpandedVarlenaOutputStreamNode *)
            MemoryContextAlloc(evosh->hdr.eoh_context, desiredCapacity);
    node->next = evosh->tail->next;
    evosh->tail->next = node;
    evosh->tail = node;
    dbb = JNI_newDirectByteBuffer(node + 1, desiredCapacity - sizeof *node);
    END_NATIVE
    return dbb;
}
References ExpandedVarlenaOutputStreamHeader::hdr, JNI_newDirectByteBuffer(), ExpandedVarlenaOutputStreamNode::next, ExpandedVarlenaOutputStreamNode::size, ExpandedVarlenaOutputStreamHeader::tail, and ExpandedVarlenaOutputStreamHeader::total_size.
Referenced by pljava_VarlenaWrapper_initialize().
pljava_VarlenaWrapper_adopt()
Datum pljava_VarlenaWrapper_adopt (jobject vlw)
Definition at line 274 of file VarlenaWrapper.c.
{
    Ptr2Long p2l;
    p2l.longVal = JNI_callLongMethodLocked(vlw, s_VarlenaWrapper_adopt,
                    pljava_DualState_key());
    return PointerGetDatum(p2l.ptrVal);
}
References JNI_callLongMethodLocked(), pljava_DualState_key(), and s_VarlenaWrapper_adopt.
Referenced by _SQLXML_coerceObject().
pljava_VarlenaWrapper_initialize()
void pljava_VarlenaWrapper_initialize (void)
Definition at line 311 of file VarlenaWrapper.c.
{
    jclass clazz;
    JNINativeMethod methodsIn[] =
    {
        {
        "_unregisterSnapshot",
        "(JJ)V",
        Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1unregisterSnapshot
        },
        {
        "_detoast",
        "(JJJJ)Ljava/nio/ByteBuffer;",
        Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1detoast
        },
        {
        "_fetch",
        "(JJ)J",
        Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1fetch
        },
        { 0, 0, 0 }
    };
    JNINativeMethod methodsOut[] =
    {
        {
        "_nextBuffer",
        "(JII)Ljava/nio/ByteBuffer;",
        Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Output_00024State__1nextBuffer
        },
        { 0, 0, 0 }
    };
    s_VarlenaWrapper_class =
        (jclass)JNI_newGlobalRef(PgObject_getJavaClass(
            "org/postgresql/pljava/internal/VarlenaWrapper"));
    s_VarlenaWrapper_Input_class =
        (jclass)JNI_newGlobalRef(PgObject_getJavaClass(
            "org/postgresql/pljava/internal/VarlenaWrapper$Input"));
    s_VarlenaWrapper_Output_class =
        (jclass)JNI_newGlobalRef(PgObject_getJavaClass(
            "org/postgresql/pljava/internal/VarlenaWrapper$Output"));
    s_VarlenaWrapper_Input_init = PgObject_getJavaMethod(
        s_VarlenaWrapper_Input_class, "<init>",
        "(Lorg/postgresql/pljava/internal/DualState$Key;"
        "JJJJJJLjava/nio/ByteBuffer;)V");
    s_VarlenaWrapper_Output_init = PgObject_getJavaMethod(
        s_VarlenaWrapper_Output_class, "<init>",
        "(Lorg/postgresql/pljava/internal/DualState$Key;"
        "JJJLjava/nio/ByteBuffer;)V");
    s_VarlenaWrapper_adopt = PgObject_getJavaMethod(
        s_VarlenaWrapper_class, "adopt",
        "(Lorg/postgresql/pljava/internal/DualState$Key;)J");
    clazz = PgObject_getJavaClass(
            "org/postgresql/pljava/internal/VarlenaWrapper$Input$State");
    PgObject_registerNatives2(clazz, methodsIn);
    s_VarlenaWrapper_Input_State_varlena = PgObject_getJavaField(
        clazz, "m_varlena", "J");
    JNI_deleteLocalRef(clazz);
    clazz = PgObject_getJavaClass(
            "org/postgresql/pljava/internal/VarlenaWrapper$Output$State");
    PgObject_registerNatives2(clazz, methodsOut);
    JNI_deleteLocalRef(clazz);
}
References Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1detoast(), Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1fetch(), Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1unregisterSnapshot(), Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Output_00024State__1nextBuffer(), JNI_deleteLocalRef(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaField(), PgObject_getJavaMethod(), PgObject_registerNatives2(), s_VarlenaWrapper_adopt, s_VarlenaWrapper_class, s_VarlenaWrapper_Input_class, s_VarlenaWrapper_Input_init, s_VarlenaWrapper_Input_State_varlena, s_VarlenaWrapper_Output_class, and s_VarlenaWrapper_Output_init.
Referenced by pljava_DualState_initialize().
pljava_VarlenaWrapper_Input()
jobject pljava_VarlenaWrapper_Input (Datum d, MemoryContext parent, ResourceOwner ro)
Definition at line 108 of file VarlenaWrapper.c.
{
    jobject vr;
    jobject dbb;
    MemoryContext mc;
    MemoryContext prevcxt;
    _VL_TYPE vl;
    Ptr2Long p2lro;
    Ptr2Long p2lcxt;
    Ptr2Long p2lpin;
    Ptr2Long p2ldatum;
    Size parked;
    Size actual;
    Snapshot pin = NULL;
    vl = (_VL_TYPE) DatumGetPointer(d);
    if ( VARATT_IS_EXTERNAL_INDIRECT(vl) ) /* at most once; can't be nested */
    {
        struct varatt_indirect redirect;
        VARATT_EXTERNAL_GET_POINTER(redirect, vl);
        vl = (_VL_TYPE)redirect.pointer;
        d = PointerGetDatum(vl);
    }
    parked = VARSIZE_ANY(vl);
    actual = toast_raw_datum_size(d) - VARHDRSZ;
    mc = AllocSetContextCreate(parent, "PL/Java VarlenaWrapper.Input",
         ALLOCSET_START_SMALL_SIZES);
    prevcxt = MemoryContextSwitchTo(mc);
    if ( actual < 4096  ||  (actual >> 1) < parked )
        goto justDetoastEagerly;
    if ( VARATT_IS_EXTERNAL_EXPANDED(vl) )
        goto justDetoastEagerly;
    if ( VARATT_IS_EXTERNAL_ONDISK(vl) )
    {
        pin = GetOldestSnapshot();
        if ( NULL == pin )
        {
            /*
             * Unable to register a snapshot and just park the tiny pointer.
             * If it points to compressed data, can still park that rather than
             * fully detoasting.
             */
            struct varatt_external toast_pointer;
            VARATT_EXTERNAL_GET_POINTER(toast_pointer, vl);
            parked = VARATT_EXTERNAL_GET_EXTSIZE(toast_pointer) + VARHDRSZ;
            if ( (actual >> 1) < parked ) /* not compressed enough to bother */
                goto justDetoastEagerly;
            vl = detoast_external_attr(vl); /* fetch without decompressing */
            d = PointerGetDatum(vl);
            dbb = NULL;
            goto constructResult;
        }
        pin = RegisterSnapshotOnOwner(pin, ro);
    }
/* parkAndDetoastLazily: */
    vl = (_VL_TYPE) DatumGetPointer(datumCopy(d, false, -1));
    dbb = NULL;
    goto constructResult;
justDetoastEagerly:
    vl = (_VL_TYPE) PG_DETOAST_DATUM_COPY(d);
    parked = actual + VARHDRSZ;
    dbb = JNI_newDirectByteBuffer(VARDATA(vl), actual);
constructResult:
    MemoryContextSwitchTo(prevcxt);
    p2lro.longVal = 0L;
    p2lcxt.longVal = 0L;
    p2lpin.longVal = 0L;
    p2ldatum.longVal = 0L;
    p2lro.ptrVal = ro;
    p2lcxt.ptrVal = mc;
    p2lpin.ptrVal = pin;
    p2ldatum.ptrVal = vl;
    vr = JNI_newObjectLocked(s_VarlenaWrapper_Input_class,
        s_VarlenaWrapper_Input_init, pljava_DualState_key(),
        p2lro.longVal, p2lcxt.longVal, p2lpin.longVal, p2ldatum.longVal,
        (jlong)parked, (jlong)actual, dbb);
    if ( NULL != dbb )
        JNI_deleteLocalRef(dbb);
    return vr;
}
References _VL_TYPE, detoast_external_attr, GetOldestSnapshot, JNI_deleteLocalRef(), JNI_newDirectByteBuffer(), JNI_newObjectLocked(), pljava_DualState_key(), s_VarlenaWrapper_Input_class, s_VarlenaWrapper_Input_init, and VARATT_EXTERNAL_GET_EXTSIZE.
Referenced by _SQLXML_coerceDatum(), and _SQLXML_coerceDatum_synthetic().
pljava_VarlenaWrapper_Output()
jobject pljava_VarlenaWrapper_Output (MemoryContext parent, ResourceOwner ro)
Definition at line 215 of file VarlenaWrapper.c.
{
    ExpandedVarlenaOutputStreamHeader *evosh;
    jobject vos;
    jobject dbb;
    MemoryContext mc;
    Ptr2Long p2lro;
    Ptr2Long p2lcxt;
    Ptr2Long p2ldatum;
    mc = AllocSetContextCreate(parent, "PL/Java VarlenaWrapper.Output",
         ALLOCSET_START_SMALL_SIZES);
    /*
     * Allocate an initial chunk sized to contain the expanded V.O.S. header,
     * plus the header and data for one node to hold INITIALSIZE data bytes.
     */
    evosh = MemoryContextAlloc(mc,
        sizeof *evosh + sizeof *(evosh->tail) + INITIALSIZE);
    /*
     * Initialize the expanded object header and its pointer to the first node.
     */
    EOH_init_header(&(evosh->hdr), &VOS_methods, mc);
    evosh->total_size = VARHDRSZ;
    evosh->tail = (ExpandedVarlenaOutputStreamNode *)(evosh + 1);
    /*
     * Initialize that first node.
     */
    evosh->tail->next = evosh->tail;
    /* evosh->tail->size will be filled in by _nextBuffer() later */
    p2lro.longVal = 0L;
    p2lcxt.longVal = 0L;
    p2ldatum.longVal = 0L;
    p2lro.ptrVal = ro;
    p2lcxt.ptrVal = mc;
    p2ldatum.ptrVal = DatumGetPointer(EOHPGetRWDatum(&(evosh->hdr)));
    /*
     * The data bytes begin right after the node header struct.
     */
    dbb = JNI_newDirectByteBuffer(evosh->tail + 1, INITIALSIZE);
    vos = JNI_newObjectLocked(s_VarlenaWrapper_Output_class,
            s_VarlenaWrapper_Output_init, pljava_DualState_key(),
            p2lro.longVal, p2lcxt.longVal, p2ldatum.longVal, dbb);
    JNI_deleteLocalRef(dbb);
    return vos;
}
References ExpandedVarlenaOutputStreamHeader::hdr, INITIALSIZE, JNI_deleteLocalRef(), JNI_newDirectByteBuffer(), JNI_newObjectLocked(), ExpandedVarlenaOutputStreamNode::next, pljava_DualState_key(), s_VarlenaWrapper_Output_class, s_VarlenaWrapper_Output_init, ExpandedVarlenaOutputStreamHeader::tail, ExpandedVarlenaOutputStreamHeader::total_size, and VOS_methods.
Referenced by Java_org_postgresql_pljava_jdbc_SQLXMLImpl__1newWritable().
VOS_flatten_into()
static void VOS_flatten_into (ExpandedObjectHeader * eohptr, void * result, Size allocated_size) static
Definition at line 291 of file VarlenaWrapper.c.
{
    ExpandedVarlenaOutputStreamHeader *evosh =
        (ExpandedVarlenaOutputStreamHeader *)eohptr;
    ExpandedVarlenaOutputStreamNode *node = evosh->tail;
    Assert(allocated_size == evosh->total_size);
    SET_VARSIZE(result, allocated_size);
    result = VARDATA(result);
    do
    {
        node = node->next;
        memcpy(result, node + 1, node->size);
        result = (char *)result + node->size;
    }
    while ( node != evosh->tail );
}
References ExpandedVarlenaOutputStreamNode::next, ExpandedVarlenaOutputStreamNode::size, ExpandedVarlenaOutputStreamHeader::tail, and ExpandedVarlenaOutputStreamHeader::total_size.
VOS_get_flat_size()
static Size VOS_get_flat_size (ExpandedObjectHeader * eohptr) static
Definition at line 284 of file VarlenaWrapper.c.
{
    ExpandedVarlenaOutputStreamHeader *evosh =
        (ExpandedVarlenaOutputStreamHeader *)eohptr;
    return evosh->total_size;
}
References ExpandedVarlenaOutputStreamHeader::total_size.
Variable Documentation
s_VarlenaWrapper_adopt
jmethodID s_VarlenaWrapper_adopt static
Definition at line 48 of file VarlenaWrapper.c.
Referenced by pljava_VarlenaWrapper_adopt(), and pljava_VarlenaWrapper_initialize().
s_VarlenaWrapper_class
jclass s_VarlenaWrapper_class static
Definition at line 47 of file VarlenaWrapper.c.
Referenced by pljava_VarlenaWrapper_initialize().
s_VarlenaWrapper_Input_class
jclass s_VarlenaWrapper_Input_class static
Definition at line 50 of file VarlenaWrapper.c.
Referenced by pljava_VarlenaWrapper_initialize(), and pljava_VarlenaWrapper_Input().
s_VarlenaWrapper_Input_init
jmethodID s_VarlenaWrapper_Input_init static
Definition at line 53 of file VarlenaWrapper.c.
Referenced by pljava_VarlenaWrapper_initialize(), and pljava_VarlenaWrapper_Input().
s_VarlenaWrapper_Input_State_varlena
jfieldID s_VarlenaWrapper_Input_State_varlena static
Definition at line 57 of file VarlenaWrapper.c.
Referenced by Java_org_postgresql_pljava_internal_VarlenaWrapper_00024Input_00024State__1detoast(), and pljava_VarlenaWrapper_initialize().
s_VarlenaWrapper_Output_class
jclass s_VarlenaWrapper_Output_class static
Definition at line 51 of file VarlenaWrapper.c.
Referenced by pljava_VarlenaWrapper_initialize(), and pljava_VarlenaWrapper_Output().
s_VarlenaWrapper_Output_init
jmethodID s_VarlenaWrapper_Output_init static
Definition at line 55 of file VarlenaWrapper.c.
Referenced by pljava_VarlenaWrapper_initialize(), and pljava_VarlenaWrapper_Output().
VOS_methods
const ExpandedObjectMethods VOS_methods static
Initial value:
=
{
    VOS_get_flat_size,
    VOS_flatten_into
}
Definition at line 74 of file VarlenaWrapper.c.
{
    VOS_get_flat_size,
    VOS_flatten_into
};
Referenced by pljava_VarlenaWrapper_Output().