var dir_1784a01aa976a8c78ef5dfc3737bcac8 =
[
    [ "type", "dir_f1a6b655ac22146a480063120e94ff11.html", "dir_f1a6b655ac22146a480063120e94ff11" ],
    [ "Backend.c", "d8/d1b/Backend_8c.html", "d8/d1b/Backend_8c" ],
    [ "DualState.c", "d9/db5/DualState_8c.html", "d9/db5/DualState_8c" ],
    [ "Exception.c", "d5/dab/Exception_8c.html", "d5/dab/Exception_8c" ],
    [ "ExecutionPlan.c", "d2/d62/ExecutionPlan_8c.html", "d2/d62/ExecutionPlan_8c" ],
    [ "Function.c", "db/d47/Function_8c.html", "db/d47/Function_8c" ],
    [ "HashMap.c", "d2/dca/HashMap_8c.html", "d2/dca/HashMap_8c" ],
    [ "InstallHelper.c", "d2/de6/InstallHelper_8c.html", "d2/de6/InstallHelper_8c" ],
    [ "Invocation.c", "d5/dc4/Invocation_8c.html", "d5/dc4/Invocation_8c" ],
    [ "Iterator.c", "d8/dd0/Iterator_8c.html", "d8/dd0/Iterator_8c" ],
    [ "JNICalls.c", "d3/d5a/JNICalls_8c.html", "d3/d5a/JNICalls_8c" ],
    [ "PgObject.c", "df/dd6/PgObject_8c.html", "df/dd6/PgObject_8c" ],
    [ "PgSavepoint.c", "d6/d68/PgSavepoint_8c.html", "d6/d68/PgSavepoint_8c" ],
    [ "Session.c", "d7/db6/Session_8c.html", "d7/db6/Session_8c" ],
    [ "SPI.c", "de/da8/SPI_8c.html", "de/da8/SPI_8c" ],
    [ "SQLChunkIOOrder.c", "df/db8/SQLChunkIOOrder_8c.html", "df/db8/SQLChunkIOOrder_8c" ],
    [ "SQLInputFromChunk.c", "da/d91/SQLInputFromChunk_8c.html", "da/d91/SQLInputFromChunk_8c" ],
    [ "SQLInputFromTuple.c", "de/d7f/SQLInputFromTuple_8c.html", "de/d7f/SQLInputFromTuple_8c" ],
    [ "SQLOutputToChunk.c", "d9/d7a/SQLOutputToChunk_8c.html", "d9/d7a/SQLOutputToChunk_8c" ],
    [ "SQLOutputToTuple.c", "df/d54/SQLOutputToTuple_8c.html", "df/d54/SQLOutputToTuple_8c" ],
    [ "SubXactListener.c", "da/d4e/SubXactListener_8c.html", "da/d4e/SubXactListener_8c" ],
    [ "TypeOid.c", "d7/d55/TypeOid_8c.html", "d7/d55/TypeOid_8c" ],
    [ "VarlenaWrapper.c", "d3/d30/VarlenaWrapper_8c.html", "d3/d30/VarlenaWrapper_8c" ],
    [ "XactListener.c", "dc/de2/XactListener_8c.html", "dc/de2/XactListener_8c" ]
];