PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Array.c File Reference
Array.c File Reference
#include "pljava/type/Type_priv.h"
#include "pljava/type/Array.h"
#include "pljava/Invocation.h"
Functions
void arraySetNull (bits8 *bitmap, int offset, bool flag)
bool arrayIsNull (const bits8 *bitmap, int offset)
ArrayType * createArrayType (jsize nElems, size_t elemSize, Oid elemType, bool withNulls)
static jvalue _Array_coerceDatum (Type self, Datum arg)
static Datum _Array_coerceObject (Type self, jobject objArray)
static bool _Array_canReplaceType (Type self, Type other)
Type Array_fromOid (Oid typeId, Type elementType)
Type Array_fromOid2 (Oid typeId, Type elementType, DatumCoercer coerceDatum, ObjectCoercer coerceObject)
Function Documentation
_Array_canReplaceType()
static bool _Array_canReplaceType (Type self, Type other) static
Definition at line 144 of file Array.c.
{
    Type oe = Type_getElementType(other);
    if ( oe == 0 )
        return false;
    return Type_canReplaceType(Type_getElementType(self), oe)
        || Type_getObjectType(self) == other;
}
References Type, Type_canReplaceType(), Type_getElementType(), and Type_getObjectType().
Referenced by Array_fromOid2().
_Array_coerceDatum()
static jvalue _Array_coerceDatum (Type self, Datum arg) static
Definition at line 62 of file Array.c.
{
    jvalue result;
    jsize idx;
    Type  elemType    = Type_getElementType(self);
    int16 elemLength  = Type_getLength(elemType);
    char  elemAlign   = Type_getAlign(elemType);
    bool  elemByValue = Type_isByValue(elemType);
    ArrayType* v = DatumGetArrayTypeP(arg);
    jsize nElems = (jsize)ArrayGetNItems(ARR_NDIM(v), ARR_DIMS(v));
    jobjectArray objArray = JNI_newObjectArray(nElems, Type_getJavaClass(elemType), 0);
    const char* values = ARR_DATA_PTR(v);
    bits8* nullBitMap = ARR_NULLBITMAP(v);
    for(idx = 0; idx < nElems; ++idx)
    {
        if(arrayIsNull(nullBitMap, idx))
            JNI_setObjectArrayElement(objArray, idx, 0);
        else
        {
            Datum value = fetch_att(values, elemByValue, elemLength);
            jvalue obj = Type_coerceDatum(elemType, value);
            JNI_setObjectArrayElement(objArray, idx, obj.l);
            JNI_deleteLocalRef(obj.l);
            values = att_addlength_datum(values, elemLength, PointerGetDatum(values));
            values = (char*)att_align_nominal(values, elemAlign);
        }
    }
    result.l = (jobject)objArray;
    return result;
}
References arrayIsNull(), JNI_deleteLocalRef(), JNI_newObjectArray(), JNI_setObjectArrayElement(), Type, Type_coerceDatum(), Type_getAlign(), Type_getElementType(), Type_getJavaClass(), Type_getLength(), and Type_isByValue().
Referenced by Array_fromOid().
_Array_coerceObject()
static Datum _Array_coerceObject (Type self, jobject objArray) static
Definition at line 95 of file Array.c.
{
    ArrayType* v;
    jsize idx;
    int    lowerBound = 1;
    Type   elemType = Type_getElementType(self);
    int    nElems   = (int)JNI_getArrayLength((jarray)objArray);
    Datum* values   = (Datum*)palloc(nElems * sizeof(Datum) + nElems * sizeof(bool));
    bool*  nulls    = (bool*)(values + nElems);
    for(idx = 0; idx < nElems; ++idx)
    {
        jobject obj = JNI_getObjectArrayElement(objArray, idx);
        if(obj == 0)
        {
            nulls[idx] = true;
            values[idx] = 0;
        }
        else
        {
            nulls[idx] = false;
            values[idx] = Type_coerceObject(elemType, obj);
            JNI_deleteLocalRef(obj);
        }
    }
    v = construct_md_array(
        values,
        nulls,
        1,
        &nElems,
        &lowerBound,
        Type_getOid(elemType),
        Type_getLength(elemType),
        Type_isByValue(elemType),
        Type_getAlign(elemType));
    pfree(values);
    PG_RETURN_ARRAYTYPE_P(v);
}
References JNI_deleteLocalRef(), JNI_getArrayLength(), JNI_getObjectArrayElement(), Type, Type_coerceObject(), Type_getAlign(), Type_getElementType(), Type_getLength(), Type_getOid(), and Type_isByValue().
Referenced by Array_fromOid().
Array_fromOid()
Type Array_fromOid (Oid typeId, Type elementType)
Definition at line 153 of file Array.c.
{
    return Array_fromOid2(typeId, elementType, _Array_coerceDatum, _Array_coerceObject);
}
References _Array_coerceDatum(), _Array_coerceObject(), and Array_fromOid2().
Referenced by _Any_createArrayType(), _Type_createArrayType(), and Array_fromOid2().
Array_fromOid2()
Type Array_fromOid2 (Oid typeId, Type elementType, DatumCoercer coerceDatum, ObjectCoercer coerceObject)
Definition at line 158 of file Array.c.
{
    Type self;
    TypeClass arrayClass;
    const char* elemClassName    = PgObjectClass_getName(PgObject_getClass((PgObject)elementType));
    const char* elemJNISignature = Type_getJNISignature(elementType);
    const char* elemJavaTypeName = Type_getJavaTypeName(elementType);
    MemoryContext currCtx = MemoryContextSwitchTo(TopMemoryContext);
    char* tmp = palloc(strlen(elemClassName) + 3);
    sprintf(tmp, "%s[]", elemClassName);
    arrayClass = TypeClass_alloc(tmp);
    tmp = palloc(strlen(elemJNISignature) + 2);
    sprintf(tmp, "[%s", elemJNISignature);
    arrayClass->JNISignature = tmp;
    tmp = palloc(strlen(elemJavaTypeName) + 3);
    sprintf(tmp, "%s[]", elemJavaTypeName);
    arrayClass->javaTypeName = tmp;
    arrayClass->coerceDatum  = coerceDatum;
    arrayClass->coerceObject = coerceObject;
    arrayClass->canReplaceType = _Array_canReplaceType;
    self = TypeClass_allocInstance(arrayClass, typeId);
    MemoryContextSwitchTo(currCtx);
    self->elementType = elementType;
    Type_registerType(arrayClass->javaTypeName, self);
    if(Type_isPrimitive(elementType))
        self->objectType = Array_fromOid(typeId, Type_getObjectType(elementType));
    return self;
}
References _Array_canReplaceType(), Array_fromOid(), PgObject_getClass(), PgObjectClass_getName(), Type, Type_getJavaTypeName(), Type_getJNISignature(), Type_getObjectType(), Type_isPrimitive(), Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by _boolean_createArrayType(), _byte_createArrayType(), _double_createArrayType(), _float_createArrayType(), _int_createArrayType(), _long_createArrayType(), _short_createArrayType(), and Array_fromOid().
arrayIsNull()
bool arrayIsNull (const bits8 * bitmap, int offset)
Definition at line 27 of file Array.c.
{
    return bitmap == 0 ? false : !(bitmap[offset / 8] & (1 << (offset % 8)));
}
Referenced by _Array_coerceDatum(), _booleanArray_coerceDatum(), _byteArray_coerceDatum(), _doubleArray_coerceDatum(), _floatArray_coerceDatum(), _intArray_coerceDatum(), _longArray_coerceDatum(), and _shortArray_coerceDatum().
arraySetNull()
void arraySetNull (bits8 * bitmap, int offset, bool flag)
Definition at line 17 of file Array.c.
{
    if(bitmap != 0)
    {
        int bitmask = 1 << (offset % 8);
        bitmap += offset / 8;
        *bitmap = (bits8)(flag? *bitmap & ~bitmask : *bitmap | bitmask);
    }
}
createArrayType()
ArrayType * createArrayType (jsize nElems, size_t elemSize, Oid elemType, bool withNulls)
Definition at line 32 of file Array.c.
{
    ArrayType* v;
    Size nBytes = elemSize * nElems;
    MemoryContext currCtx = Invocation_switchToUpperContext();
    Size dataoffset;
    if(withNulls)
    {
        dataoffset = ARR_OVERHEAD_WITHNULLS(1, nElems);
        nBytes += dataoffset;
    }
    else
    {
        dataoffset = 0;         /* marker for no null bitmap */
        nBytes += ARR_OVERHEAD_NONULLS(1);
    }
    v = (ArrayType*)palloc0(nBytes);
    AssertVariableIsOfType(v->dataoffset, int32);
    v->dataoffset = (int32)dataoffset;
    MemoryContextSwitchTo(currCtx);
    SET_VARSIZE(v, nBytes);
    ARR_NDIM(v) = 1;
    ARR_ELEMTYPE(v) = elemType;
    *((int*)ARR_DIMS(v)) = nElems;
    *((int*)ARR_LBOUND(v)) = 1;
    return v;
}
References Invocation_switchToUpperContext().
Referenced by _booleanArray_coerceObject(), _byteArray_coerceObject(), _doubleArray_coerceObject(), _floatArray_coerceObject(), _intArray_coerceObject(), _longArray_coerceObject(), and _shortArray_coerceObject().