PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Long.c File Reference
Long.c File Reference
#include "pljava/type/Type_priv.h"
#include "pljava/type/Array.h"
#include "pljava/Invocation.h"
Functions
static Datum _asDatum (jlong v)
static Datum _long_invoke (Type self, Function fn, PG_FUNCTION_ARGS)
static jvalue _long_coerceDatum (Type self, Datum arg)
static jvalue _longArray_coerceDatum (Type self, Datum arg)
static Datum _longArray_coerceObject (Type self, jobject longArray)
static bool _Long_canReplace (Type self, Type other)
static jvalue _Long_coerceDatum (Type self, Datum arg)
static Datum _Long_coerceObject (Type self, jobject longObj)
static Type _long_createArrayType (Type self, Oid arrayTypeId)
void Long_initialize (void)
Variables
static TypeClass s_longClass
static jclass s_Long_class
static jmethodID s_Long_init
static jmethodID s_Long_longValue
Function Documentation
_asDatum()
static Datum _asDatum (jlong v) static
Definition at line 26 of file Long.c.
{
    MemoryContext currCtx = Invocation_switchToUpperContext();
    Datum ret = Int64GetDatum(v);
    MemoryContextSwitchTo(currCtx);
    return ret;
}
References Invocation_switchToUpperContext().
Referenced by _Long_coerceObject(), and _long_invoke().
_Long_canReplace()
static bool _Long_canReplace (Type self, Type other) static
Definition at line 96 of file Long.c.
{
    TypeClass cls = Type_getClass(other);
    return Type_getClass(self) == cls || cls == s_longClass;
}
References s_longClass, and Type_getClass().
Referenced by Long_initialize().
_long_coerceDatum()
static jvalue _long_coerceDatum (Type self, Datum arg) static
Definition at line 39 of file Long.c.
{
    jvalue result;
    result.j = DatumGetInt64(arg);
    return result;
}
Referenced by Long_initialize().
_Long_coerceDatum()
static jvalue _Long_coerceDatum (Type self, Datum arg) static
Definition at line 102 of file Long.c.
{
    jvalue result;
    result.l = JNI_newObject(s_Long_class, s_Long_init, DatumGetInt64(arg));
    return result;
}
References JNI_newObject(), s_Long_class, and s_Long_init.
Referenced by Long_initialize().
_Long_coerceObject()
static Datum _Long_coerceObject (Type self, jobject longObj) static
Definition at line 109 of file Long.c.
{
    return _asDatum(longObj == 0 ? 0 : JNI_callLongMethod(longObj, s_Long_longValue));
}
References _asDatum(), JNI_callLongMethod(), and s_Long_longValue.
Referenced by Long_initialize().
_long_createArrayType()
static Type _long_createArrayType (Type self, Oid arrayTypeId) static
Definition at line 114 of file Long.c.
{
    return Array_fromOid2(arrayTypeId, self, _longArray_coerceDatum, _longArray_coerceObject);
}
References _longArray_coerceDatum(), _longArray_coerceObject(), and Array_fromOid2().
Referenced by Long_initialize().
_long_invoke()
static Datum _long_invoke (Type self, Function fn, PG_FUNCTION_ARGS) static
Definition at line 34 of file Long.c.
{
    return _asDatum(pljava_Function_longInvoke(fn));
}
References _asDatum(), and pljava_Function_longInvoke().
Referenced by Long_initialize().
_longArray_coerceDatum()
static jvalue _longArray_coerceDatum (Type self, Datum arg) static
Definition at line 46 of file Long.c.
{
    jvalue     result;
    ArrayType* v      = DatumGetArrayTypeP(arg);
    jsize      nElems = (jsize)ArrayGetNItems(ARR_NDIM(v), ARR_DIMS(v));
    jlongArray longArray = JNI_newLongArray(nElems);
    if(ARR_HASNULL(v))
    {
        jsize idx;
        jboolean isCopy = JNI_FALSE;
        bits8* nullBitMap = ARR_NULLBITMAP(v);
        jlong* values = (jlong*)ARR_DATA_PTR(v);
        jlong* elems  = JNI_getLongArrayElements(longArray, &isCopy);
        for(idx = 0; idx < nElems; ++idx)
        {
            if(arrayIsNull(nullBitMap, idx))
                elems[idx] = 0;
            else
                elems[idx] = *values++;
        }
        JNI_releaseLongArrayElements(longArray, elems, JNI_COMMIT);
    }
    else
        JNI_setLongArrayRegion(longArray, 0, nElems, (jlong*)ARR_DATA_PTR(v));
    result.l = (jobject)longArray;
    return result;
}
References arrayIsNull(), JNI_getLongArrayElements(), JNI_newLongArray(), JNI_releaseLongArrayElements(), and JNI_setLongArrayRegion().
Referenced by _long_createArrayType().
_longArray_coerceObject()
static Datum _longArray_coerceObject (Type self, jobject longArray) static
Definition at line 75 of file Long.c.
{
    ArrayType* v;
    jsize nElems;
    if(longArray == 0)
        return 0;
    nElems = JNI_getArrayLength((jarray)longArray);
    v = createArrayType(nElems, sizeof(jlong), INT8OID, false);
    JNI_getLongArrayRegion(
            (jlongArray)longArray, 0, nElems, (jlong*)ARR_DATA_PTR(v));
    PG_RETURN_ARRAYTYPE_P(v);
}
References createArrayType(), JNI_getArrayLength(), and JNI_getLongArrayRegion().
Referenced by _long_createArrayType().
Long_initialize()
void Long_initialize (void) extern
Definition at line 122 of file Long.c.
{
    Type t_long;
    Type t_Long;
    TypeClass cls;
    s_Long_class = JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Long"));
    s_Long_init = PgObject_getJavaMethod(s_Long_class, "<init>", "(J)V");
    s_Long_longValue = PgObject_getJavaMethod(s_Long_class, "longValue", "()J");
    cls = TypeClass_alloc("type.Long");
    cls->canReplaceType = _Long_canReplace;
    cls->JNISignature = "Ljava/lang/Long;";
    cls->javaTypeName = "java.lang.Long";
    cls->coerceDatum  = _Long_coerceDatum;
    cls->coerceObject = _Long_coerceObject;
    t_Long = TypeClass_allocInstance(cls, INT8OID);
    cls = TypeClass_alloc("type.long");
    cls->JNISignature = "J";
    cls->javaTypeName = "long";
    cls->invoke       = _long_invoke;
    cls->coerceDatum  = _long_coerceDatum;
    cls->coerceObject = _Long_coerceObject;
    cls->createArrayType = _long_createArrayType;
    s_longClass = cls;
    t_long = TypeClass_allocInstance(cls, INT8OID);
    t_long->objectType = t_Long;
    Type_registerType("long", t_long);
    Type_registerType("java.lang.Long", t_Long);
}
References _Long_canReplace(), _long_coerceDatum(), _Long_coerceDatum(), _Long_coerceObject(), _long_createArrayType(), _long_invoke(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Long_class, s_Long_init, s_Long_longValue, s_longClass, Type, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Variable Documentation
s_Long_class
jclass s_Long_class static
Definition at line 19 of file Long.c.
Referenced by _Long_coerceDatum(), and Long_initialize().
s_Long_init
jmethodID s_Long_init static
Definition at line 20 of file Long.c.
Referenced by _Long_coerceDatum(), and Long_initialize().
s_Long_longValue
jmethodID s_Long_longValue static
Definition at line 21 of file Long.c.
Referenced by _Long_coerceObject(), and Long_initialize().
s_longClass
TypeClass s_longClass static
Definition at line 18 of file Long.c.
Referenced by _Long_canReplace(), and Long_initialize().