PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/SingleRowReader.c File Reference
SingleRowReader.c File Reference
#include "pljava/type/Type_priv.h"
#include "pljava/type/SingleRowReader.h"
#include <executor/executor.h>
#include <executor/spi.h>
#include <utils/typcache.h>
#include "pljava/DualState.h"
#include "pljava/Exception.h"
#include "pljava/Invocation.h"
#include "pljava/type/TupleDesc.h"
#include "org_postgresql_pljava_jdbc_SingleRowReader.h"
Functions
jobject pljava_SingleRowReader_getTupleDesc (HeapTupleHeader ht)
jobject pljava_SingleRowReader_create (HeapTupleHeader ht)
void pljava_SingleRowReader_initialize (void)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_jdbc_SingleRowReader__1getObject (JNIEnv *env, jclass clazz, jlong hth, jlong jtd, jint attrNo, jclass rqcls)
Variables
static jclass s_SingleRowReader_class
static jmethodID s_SingleRowReader_init
Function Documentation
Java_org_postgresql_pljava_jdbc_SingleRowReader__1getObject()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_jdbc_SingleRowReader__1getObject (JNIEnv * env, jclass clazz, jlong hth, jlong jtd, jint attrNo, jclass rqcls)
Definition at line 102 of file SingleRowReader.c.
{
    jobject result = 0;
    if(hth != 0 && jtd != 0)
    {
        Ptr2Long p2lhth;
        Ptr2Long p2ltd;
        p2lhth.longVal = hth;
        p2ltd.longVal = jtd;
        BEGIN_NATIVE
        PG_TRY();
        {
            Type type = pljava_TupleDesc_getColumnType(
                (TupleDesc) p2ltd.ptrVal, (int) attrNo);
            if (type != 0)
            {
                Datum binVal;
                bool wasNull = false;
                binVal = GetAttributeByNum(
                            (HeapTupleHeader)p2lhth.ptrVal,
                            (AttrNumber)attrNo, &wasNull);
                if(!wasNull)
                    result = Type_coerceDatumAs(type, binVal, rqcls).l;
            }
        }
        PG_CATCH();
        {
            Exception_throw_ERROR("GetAttributeByNum");
        }
        PG_END_TRY();
        END_NATIVE
    }
    return result;
}
References Exception_throw_ERROR(), pljava_TupleDesc_getColumnType(), Type, and Type_coerceDatumAs().
Referenced by pljava_SingleRowReader_initialize().
pljava_SingleRowReader_create()
jobject pljava_SingleRowReader_create (HeapTupleHeader ht)
Definition at line 48 of file SingleRowReader.c.
{
    Ptr2Long p2lht;
    Ptr2Long p2lro;
    jobject result;
    jobject jtd = pljava_SingleRowReader_getTupleDesc(ht);
    p2lht.longVal = 0L;
    p2lro.longVal = 0L;
    p2lht.ptrVal = ht;
    p2lro.ptrVal = currentInvocation;
    result =
        JNI_newObjectLocked(s_SingleRowReader_class, s_SingleRowReader_init,
            pljava_DualState_key(), p2lro.longVal, p2lht.longVal, jtd);
    JNI_deleteLocalRef(jtd);
    return result;
}
References currentInvocation, JNI_deleteLocalRef(), JNI_newObjectLocked(), pljava_DualState_key(), pljava_SingleRowReader_getTupleDesc(), s_SingleRowReader_class, and s_SingleRowReader_init.
Referenced by _Composite_coerceDatum().
pljava_SingleRowReader_getTupleDesc()
jobject pljava_SingleRowReader_getTupleDesc (HeapTupleHeader ht)
Definition at line 33 of file SingleRowReader.c.
{
    jobject result;
    TupleDesc tupleDesc =
      lookup_rowtype_tupdesc(HeapTupleHeaderGetTypeId(ht),
                 HeapTupleHeaderGetTypMod(ht));
    result = pljava_TupleDesc_create(tupleDesc);
    /*
     * pljava_TupleDesc_create() creates a copy of the tuple descriptor, so
     * can release this now
     */
    ReleaseTupleDesc(tupleDesc);
    return result;
}
References pljava_TupleDesc_create().
Referenced by pljava_SingleRowReader_create(), and pljava_SQLInputFromTuple_create().
pljava_SingleRowReader_initialize()
void pljava_SingleRowReader_initialize (void)
Definition at line 71 of file SingleRowReader.c.
{
    JNINativeMethod methods[] =
    {
        {
        "_getObject",
        "(JJILjava/lang/Class;)Ljava/lang/Object;",
        Java_org_postgresql_pljava_jdbc_SingleRowReader__1getObject
        },
        { 0, 0, 0 }
    };
    jclass cls =
        PgObject_getJavaClass("org/postgresql/pljava/jdbc/SingleRowReader");
    PgObject_registerNatives2(cls, methods);
    s_SingleRowReader_init = PgObject_getJavaMethod(cls, "<init>",
        "(Lorg/postgresql/pljava/internal/DualState$Key;JJLorg/postgresql/pljava/internal/TupleDesc;)V");
    s_SingleRowReader_class = JNI_newGlobalRef(cls);
    JNI_deleteLocalRef(cls);
}
References Java_org_postgresql_pljava_jdbc_SingleRowReader__1getObject(), JNI_deleteLocalRef(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_registerNatives2(), s_SingleRowReader_class, and s_SingleRowReader_init.
Referenced by pljava_DualState_initialize().
Variable Documentation
s_SingleRowReader_class
jclass s_SingleRowReader_class static
Definition at line 30 of file SingleRowReader.c.
Referenced by pljava_SingleRowReader_create(), and pljava_SingleRowReader_initialize().
s_SingleRowReader_init
jmethodID s_SingleRowReader_init static
Definition at line 31 of file SingleRowReader.c.
Referenced by pljava_SingleRowReader_create(), and pljava_SingleRowReader_initialize().