PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Integer.c File Reference
Integer.c File Reference
#include "pljava/type/Type_priv.h"
#include "pljava/type/Array.h"
#include "pljava/Invocation.h"
Functions
static Datum _int_invoke (Type self, Function fn, PG_FUNCTION_ARGS)
static jvalue _int_coerceDatum (Type self, Datum arg)
static jvalue _intArray_coerceDatum (Type self, Datum arg)
static Datum _intArray_coerceObject (Type self, jobject intArray)
static bool _Integer_canReplace (Type self, Type other)
static jvalue _Integer_coerceDatum (Type self, Datum arg)
static Datum _Integer_coerceObject (Type self, jobject intObj)
static Type _int_createArrayType (Type self, Oid arrayTypeId)
void Integer_initialize (void)
Variables
static TypeClass s_intClass
static jclass s_Integer_class
static jmethodID s_Integer_init
static jmethodID s_Integer_intValue
Function Documentation
_int_coerceDatum()
static jvalue _int_coerceDatum (Type self, Datum arg) static
Definition at line 32 of file Integer.c.
{
    jvalue result;
    result.i = DatumGetInt32(arg);
    return result;
}
Referenced by Integer_initialize().
_int_createArrayType()
static Type _int_createArrayType (Type self, Oid arrayTypeId) static
Definition at line 107 of file Integer.c.
{
    return Array_fromOid2(arrayTypeId, self, _intArray_coerceDatum, _intArray_coerceObject);
}
References _intArray_coerceDatum(), _intArray_coerceObject(), and Array_fromOid2().
Referenced by Integer_initialize().
_int_invoke()
static Datum _int_invoke (Type self, Function fn, PG_FUNCTION_ARGS) static
Definition at line 26 of file Integer.c.
{
    jint iv = pljava_Function_intInvoke(fn);
    return Int32GetDatum(iv);
}
References jint(), and pljava_Function_intInvoke().
Referenced by Integer_initialize().
_intArray_coerceDatum()
static jvalue _intArray_coerceDatum (Type self, Datum arg) static
Definition at line 39 of file Integer.c.
{
    jvalue     result;
    ArrayType* v        = DatumGetArrayTypeP(arg);
    jsize      nElems   = (jsize)ArrayGetNItems(ARR_NDIM(v), ARR_DIMS(v));
    jintArray  intArray = JNI_newIntArray(nElems);
    if(ARR_HASNULL(v))
    {
        jsize idx;
        jboolean isCopy = JNI_FALSE;
        bits8* nullBitMap = ARR_NULLBITMAP(v);
        jint* values = (jint*)ARR_DATA_PTR(v);
        jint* elems  = JNI_getIntArrayElements(intArray, &isCopy);
        for(idx = 0; idx < nElems; ++idx)
        {
            if(arrayIsNull(nullBitMap, idx))
                elems[idx] = 0;
            else
                elems[idx] = *values++;
        }
        JNI_releaseIntArrayElements(intArray, elems, JNI_COMMIT);
    }
    else
        JNI_setIntArrayRegion(intArray, 0, nElems, (jint*)ARR_DATA_PTR(v));
    result.l = (jobject)intArray;
    return result;
}
References arrayIsNull(), jint(), JNI_getIntArrayElements(), JNI_newIntArray(), JNI_releaseIntArrayElements(), and JNI_setIntArrayRegion().
Referenced by _int_createArrayType().
_intArray_coerceObject()
static Datum _intArray_coerceObject (Type self, jobject intArray) static
Definition at line 68 of file Integer.c.
{
    ArrayType* v;
    jsize nElems;
    if(intArray == 0)
        return 0;
    nElems = JNI_getArrayLength((jarray)intArray);
    v = createArrayType(nElems, sizeof(jint), INT4OID, false);
    JNI_getIntArrayRegion(
            (jintArray)intArray, 0, nElems, (jint*)ARR_DATA_PTR(v));
    PG_RETURN_ARRAYTYPE_P(v);
}
References createArrayType(), jint(), JNI_getArrayLength(), and JNI_getIntArrayRegion().
Referenced by _int_createArrayType().
_Integer_canReplace()
static bool _Integer_canReplace (Type self, Type other) static
Definition at line 89 of file Integer.c.
{
    TypeClass cls = Type_getClass(other);
    return Type_getClass(self) == cls || cls == s_intClass;
}
References s_intClass, and Type_getClass().
Referenced by Integer_initialize().
_Integer_coerceDatum()
static jvalue _Integer_coerceDatum (Type self, Datum arg) static
Definition at line 95 of file Integer.c.
{
    jvalue result;
    result.l = JNI_newObject(s_Integer_class, s_Integer_init, DatumGetInt32(arg));
    return result;
}
References JNI_newObject(), s_Integer_class, and s_Integer_init.
Referenced by Integer_initialize().
_Integer_coerceObject()
static Datum _Integer_coerceObject (Type self, jobject intObj) static
Definition at line 102 of file Integer.c.
{
    return Int32GetDatum(intObj == 0 ? 0 : JNI_callIntMethod(intObj, s_Integer_intValue));
}
References JNI_callIntMethod(), and s_Integer_intValue.
Referenced by Integer_initialize().
Integer_initialize()
void Integer_initialize (void) extern
Definition at line 115 of file Integer.c.
{
    Type t_int;
    Type t_Integer;
    TypeClass cls;
    s_Integer_class = JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Integer"));
    s_Integer_init = PgObject_getJavaMethod(s_Integer_class, "<init>", "(I)V");
    s_Integer_intValue = PgObject_getJavaMethod(s_Integer_class, "intValue", "()I");
    cls = TypeClass_alloc("type.Integer");
    cls->canReplaceType = _Integer_canReplace;
    cls->JNISignature = "Ljava/lang/Integer;";
    cls->javaTypeName = "java.lang.Integer";
    cls->coerceDatum  = _Integer_coerceDatum;
    cls->coerceObject = _Integer_coerceObject;
    t_Integer = TypeClass_allocInstance(cls, INT4OID);
    cls = TypeClass_alloc("type.int");
    cls->JNISignature = "I";
    cls->javaTypeName = "int";
    cls->invoke       = _int_invoke;
    cls->coerceDatum  = _int_coerceDatum;
    cls->coerceObject = _Integer_coerceObject;
    cls->createArrayType = _int_createArrayType;
    s_intClass = cls;
    t_int = TypeClass_allocInstance(cls, INT4OID);
    t_int->objectType = t_Integer;
    Type_registerType("int", t_int);
    Type_registerType("java.lang.Integer", t_Integer);
}
References _int_coerceDatum(), _int_createArrayType(), _int_invoke(), _Integer_canReplace(), _Integer_coerceDatum(), _Integer_coerceObject(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_intClass, s_Integer_class, s_Integer_init, s_Integer_intValue, Type, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Variable Documentation
s_intClass
TypeClass s_intClass static
Definition at line 18 of file Integer.c.
Referenced by _Integer_canReplace(), and Integer_initialize().
s_Integer_class
jclass s_Integer_class static
Definition at line 19 of file Integer.c.
Referenced by _Integer_coerceDatum(), and Integer_initialize().
s_Integer_init
jmethodID s_Integer_init static
Definition at line 20 of file Integer.c.
Referenced by _Integer_coerceDatum(), and Integer_initialize().
s_Integer_intValue
jmethodID s_Integer_intValue static
Definition at line 21 of file Integer.c.
Referenced by _Integer_coerceObject(), and Integer_initialize().