PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Double.c File Reference
Double.c File Reference
#include "pljava/type/Type_priv.h"
#include "pljava/type/Array.h"
#include "pljava/Invocation.h"
Functions
static Datum _asDatum (jdouble v)
static Datum _double_invoke (Type self, Function fn, PG_FUNCTION_ARGS)
static jvalue _double_coerceDatum (Type self, Datum arg)
static jvalue _doubleArray_coerceDatum (Type self, Datum arg)
static Datum _doubleArray_coerceObject (Type self, jobject doubleArray)
static bool _Double_canReplace (Type self, Type other)
static jvalue _Double_coerceDatum (Type self, Datum arg)
static Datum _Double_coerceObject (Type self, jobject doubleObj)
static Type _double_createArrayType (Type self, Oid arrayTypeId)
void Double_initialize (void)
Variables
static TypeClass s_doubleClass
static jclass s_Double_class
static jmethodID s_Double_init
static jmethodID s_Double_doubleValue
Function Documentation
_asDatum()
static Datum _asDatum (jdouble v) static
Definition at line 26 of file Double.c.
{
    MemoryContext currCtx = Invocation_switchToUpperContext();
    Datum ret = Float8GetDatum(v);
    MemoryContextSwitchTo(currCtx);
    return ret;
}
References Invocation_switchToUpperContext().
Referenced by _Double_coerceObject(), and _double_invoke().
_Double_canReplace()
static bool _Double_canReplace (Type self, Type other) static
Definition at line 94 of file Double.c.
{
    TypeClass cls = Type_getClass(other);
    return Type_getClass(self) == cls || cls == s_doubleClass;
}
References s_doubleClass, and Type_getClass().
Referenced by Double_initialize().
_double_coerceDatum()
static jvalue _double_coerceDatum (Type self, Datum arg) static
Definition at line 39 of file Double.c.
{
    jvalue result;
    result.d = DatumGetFloat8(arg);
    return result;
}
Referenced by Double_initialize().
_Double_coerceDatum()
static jvalue _Double_coerceDatum (Type self, Datum arg) static
Definition at line 100 of file Double.c.
{
    jvalue result;
    result.l = JNI_newObject(s_Double_class, s_Double_init, DatumGetFloat8(arg));
    return result;
}
References JNI_newObject(), s_Double_class, and s_Double_init.
Referenced by Double_initialize().
_Double_coerceObject()
static Datum _Double_coerceObject (Type self, jobject doubleObj) static
Definition at line 107 of file Double.c.
{
    return _asDatum(doubleObj == 0 ? 0 : JNI_callDoubleMethod(doubleObj, s_Double_doubleValue));
}
References _asDatum(), JNI_callDoubleMethod(), and s_Double_doubleValue.
Referenced by Double_initialize().
_double_createArrayType()
static Type _double_createArrayType (Type self, Oid arrayTypeId) static
Definition at line 112 of file Double.c.
{
    return Array_fromOid2(arrayTypeId, self, _doubleArray_coerceDatum, _doubleArray_coerceObject);
}
References _doubleArray_coerceDatum(), _doubleArray_coerceObject(), and Array_fromOid2().
Referenced by Double_initialize().
_double_invoke()
static Datum _double_invoke (Type self, Function fn, PG_FUNCTION_ARGS) static
Definition at line 34 of file Double.c.
{
    return _asDatum(pljava_Function_doubleInvoke(fn));
}
References _asDatum(), and pljava_Function_doubleInvoke().
Referenced by Double_initialize().
_doubleArray_coerceDatum()
static jvalue _doubleArray_coerceDatum (Type self, Datum arg) static
Definition at line 46 of file Double.c.
{
    jvalue     result;
    ArrayType* v      = DatumGetArrayTypeP(arg);
    jsize      nElems = (jsize)ArrayGetNItems(ARR_NDIM(v), ARR_DIMS(v));
    jdoubleArray doubleArray = JNI_newDoubleArray(nElems);
    if(ARR_HASNULL(v))
    {
        jsize idx;
        jboolean isCopy = JNI_FALSE;
        bits8* nullBitMap = ARR_NULLBITMAP(v);
        jdouble* values = (jdouble*)ARR_DATA_PTR(v);
        jdouble* elems  = JNI_getDoubleArrayElements(doubleArray, &isCopy);
        for(idx = 0; idx < nElems; ++idx)
        {
            if(arrayIsNull(nullBitMap, idx))
                elems[idx] = 0;
            else
                elems[idx] = *values++;
        }
        JNI_releaseDoubleArrayElements(doubleArray, elems, JNI_COMMIT);
    }
    else
        JNI_setDoubleArrayRegion(doubleArray, 0, nElems, (jdouble*)ARR_DATA_PTR(v));
    result.l = (jobject)doubleArray;
    return result;
}
References arrayIsNull(), JNI_getDoubleArrayElements(), JNI_newDoubleArray(), JNI_releaseDoubleArrayElements(), and JNI_setDoubleArrayRegion().
Referenced by _double_createArrayType().
_doubleArray_coerceObject()
static Datum _doubleArray_coerceObject (Type self, jobject doubleArray) static
Definition at line 75 of file Double.c.
{
    ArrayType* v;
    jsize nElems;
    if(doubleArray == 0)
        return 0;
    nElems = JNI_getArrayLength((jarray)doubleArray);
    v = createArrayType(nElems, sizeof(jdouble), FLOAT8OID, false);
    JNI_getDoubleArrayRegion((jdoubleArray)doubleArray, 0,
                     nElems, (jdouble*)ARR_DATA_PTR(v));
    PG_RETURN_ARRAYTYPE_P(v);
}
References createArrayType(), JNI_getArrayLength(), and JNI_getDoubleArrayRegion().
Referenced by _double_createArrayType().
Double_initialize()
void Double_initialize (void) extern
Definition at line 120 of file Double.c.
{
    Type t_double;
    Type t_Double;
    TypeClass cls;
    s_Double_class = JNI_newGlobalRef(PgObject_getJavaClass("java/lang/Double"));
    s_Double_init = PgObject_getJavaMethod(s_Double_class, "<init>", "(D)V");
    s_Double_doubleValue = PgObject_getJavaMethod(s_Double_class, "doubleValue", "()D");
    cls = TypeClass_alloc("type.Double");
    cls->canReplaceType = _Double_canReplace;
    cls->JNISignature = "Ljava/lang/Double;";
    cls->javaTypeName = "java.lang.Double";
    cls->coerceDatum  = _Double_coerceDatum;
    cls->coerceObject = _Double_coerceObject;
    t_Double = TypeClass_allocInstance(cls, FLOAT8OID);
    cls = TypeClass_alloc("type.double");
    cls->JNISignature = "D";
    cls->javaTypeName = "double";
    cls->invoke       = _double_invoke;
    cls->coerceDatum  = _double_coerceDatum;
    cls->coerceObject = _Double_coerceObject;
    cls->createArrayType = _double_createArrayType;
    s_doubleClass = cls;
    t_double = TypeClass_allocInstance(cls, FLOAT8OID);
    t_double->objectType = t_Double;
    Type_registerType("double", t_double);
    Type_registerType("java.lang.Double", t_Double);
}
References _Double_canReplace(), _double_coerceDatum(), _Double_coerceDatum(), _Double_coerceObject(), _double_createArrayType(), _double_invoke(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), s_Double_class, s_Double_doubleValue, s_Double_init, s_doubleClass, Type, Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().
Variable Documentation
s_Double_class
jclass s_Double_class static
Definition at line 19 of file Double.c.
Referenced by _Double_coerceDatum(), and Double_initialize().
s_Double_doubleValue
jmethodID s_Double_doubleValue static
Definition at line 21 of file Double.c.
Referenced by _Double_coerceObject(), and Double_initialize().
s_Double_init
jmethodID s_Double_init static
Definition at line 20 of file Double.c.
Referenced by _Double_coerceDatum(), and Double_initialize().
s_doubleClass
TypeClass s_doubleClass static
Definition at line 18 of file Double.c.
Referenced by _Double_canReplace(), and Double_initialize().