PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/InstallHelper.c File Reference
InstallHelper.c File Reference
#include <postgres.h>
#include <access/htup_details.h>
#include <access/xact.h>
#include <catalog/pg_language.h>
#include <catalog/pg_proc.h>
#include <commands/dbcommands.h>
#include <commands/extension.h>
#include <commands/portalcmds.h>
#include <executor/spi.h>
#include <miscadmin.h>
#include <libpq/libpq-be.h>
#include <postmaster/autovacuum.h>
#include <tcop/pquery.h>
#include <utils/builtins.h>
#include <utils/lsyscache.h>
#include <utils/memutils.h>
#include <utils/snapmgr.h>
#include <utils/syscache.h>
#include "pljava/InstallHelper.h"
#include "pljava/Backend.h"
#include "pljava/Function.h"
#include "pljava/Invocation.h"
#include "pljava/JNICalls.h"
#include "pljava/PgObject.h"
#include "pljava/type/String.h"
Macros
#define GetNamespaceOid(k1) GetSysCacheOid1(NAMESPACENAME, k1)
#define AmAutoVacuumWorkerProcess() IsAutoVacuumWorkerProcess()
#define AmBackgroundWorkerProcess() IsBackgroundWorker
#define LOADPATH_TBL_NAME "see doc: do CREATE EXTENSION PLJAVA in new session"
Functions
static void checkLoadPath (void)
static void getExtensionLoadPath (void)
static char * origUserName ()
bool pljavaViableXact ()
char * pljavaDbName ()
char const * pljavaClusterName ()
void pljavaCheckExtension (bool *livecheck)
char * pljavaFnOidToLibPath (Oid fnOid, char **langName, bool *trusted)
bool InstallHelper_shouldDeferInit ()
bool InstallHelper_isPLJavaFunction (Oid fn, char **langName, bool *trusted)
char const * InstallHelper_defaultModulePath (char *pathbuf, char pathsep)
void InstallHelper_earlyHello ()
char * InstallHelper_hello ()
void InstallHelper_groundwork ()
void InstallHelper_initialize ()
Variables
static jclass s_InstallHelper_class
static jmethodID s_InstallHelper_hello
static jmethodID s_InstallHelper_groundwork
static jfieldID s_InstallHelper_MANAGE_CONTEXT_LOADER
static bool extensionExNihilo = false
char const * pljavaLoadPath = NULL
bool pljavaLoadingAsExtension = false
Oid pljavaTrustedOid = InvalidOid
Oid pljavaUntrustedOid = InvalidOid
Macro Definition Documentation
AmAutoVacuumWorkerProcess
#define AmAutoVacuumWorkerProcess () IsAutoVacuumWorkerProcess()
Definition at line 48 of file InstallHelper.c.
AmBackgroundWorkerProcess
#define AmBackgroundWorkerProcess () IsBackgroundWorker
Definition at line 49 of file InstallHelper.c.
GetNamespaceOid
#define GetNamespaceOid (k1) GetSysCacheOid1(NAMESPACENAME, k1)
Definition at line 36 of file InstallHelper.c.
LOADPATH_TBL_NAME
#define LOADPATH_TBL_NAME "see doc: do CREATE EXTENSION PLJAVA in new session"
Definition at line 69 of file InstallHelper.c.
Function Documentation
checkLoadPath()
static void checkLoadPath (void) static
Definition at line 168 of file InstallHelper.c.
{
    List *l;
    Node *ut;
    LoadStmt *ls;
    PlannedStmt *ps;
    if ( NULL == ActivePortal )
        return;
    l = ActivePortal->stmts;
    if ( NULL == l )
        return;
    if ( 1 < list_length( l) )
        elog(DEBUG2, "ActivePortal lists %d statements", list_length( l));
    ut = (Node *)linitial(l);
    if ( NULL == ut )
    {
        elog(DEBUG2, "got null for first statement from ActivePortal");
        return;
    }
    if ( T_PlannedStmt == nodeTag(ut) )
    {
        ps = (PlannedStmt *)ut;
        if ( CMD_UTILITY != ps->commandType )
        {
            elog(DEBUG2, "ActivePortal has PlannedStmt command type %u",
                 ps->commandType);
            return;
        }
        ut = ps->utilityStmt;
        if ( NULL == ut )
        {
            elog(DEBUG2, "got null for utilityStmt from PlannedStmt");
            return;
        }
    }
    if ( T_LoadStmt != nodeTag(ut) )
        return;
    ls = (LoadStmt *)ut;
    if ( NULL == ls->filename )
    {
        elog(DEBUG2, "got null for a LOAD statement's filename");
        return;
    }
    pljavaLoadPath =
        (char const *)MemoryContextStrdup(TopMemoryContext, ls->filename);
}
References pljavaLoadPath.
Referenced by pljavaCheckExtension().
getExtensionLoadPath()
static void getExtensionLoadPath (void) static
Definition at line 219 of file InstallHelper.c.
{
    MemoryContext curr;
    Datum dtm;
    bool isnull;
    StringInfoData buf;
    /*
     * Check whether sqlj.loadpath exists before querying it. I would more
     * happily just PG_CATCH() the error and compare to ERRCODE_UNDEFINED_TABLE
     * but what's required to make that work right is "not terribly well
     * documented, but the exception-block handling in plpgsql provides a
     * working model" and that code is a lot more fiddly than you would guess.
     */
    if ( InvalidOid == get_relname_relid(LOADPATH_TBL_NAME,
        GetNamespaceOid(CStringGetDatum("sqlj"))) )
        return;
    SPI_connect();
    curr = CurrentMemoryContext;
    initStringInfo(&buf);
    appendStringInfo(&buf, "SELECT path, exnihilo FROM sqlj.%s",
        quote_identifier(LOADPATH_TBL_NAME));
    if ( SPI_OK_SELECT == SPI_execute(buf.data, true, 1) && 1 == SPI_processed )
    {
        MemoryContextSwitchTo(TopMemoryContext);
        pljavaLoadPath = (char const *)SPI_getvalue(
            SPI_tuptable->vals[0], SPI_tuptable->tupdesc, 1);
        MemoryContextSwitchTo(curr);
        dtm = SPI_getbinval(SPI_tuptable->vals[0], SPI_tuptable->tupdesc, 2,
            &isnull);
        if ( isnull )
            elog(ERROR, "defect in CREATE EXTENSION script");
        extensionExNihilo = DatumGetBool(dtm);
    }
    SPI_finish();
}
References extensionExNihilo, GetNamespaceOid, LOADPATH_TBL_NAME, and pljavaLoadPath.
Referenced by pljavaCheckExtension().
InstallHelper_defaultModulePath()
char const * InstallHelper_defaultModulePath (char * pathbuf, char pathsep)
Definition at line 403 of file InstallHelper.c.
{
    char * const pbend = pathbuf + MAXPGPATH;
    char *pbp = pathbuf;
    size_t remaining;
    int would_have_sprinted;
    get_share_path(my_exec_path, pathbuf);
    join_path_components(pathbuf, pathbuf, "pljava");
    join_path_components(pathbuf, pathbuf, "pljava"); /* puts \0 where - goes */
    for ( ; pbp < pbend && '\0' != *pbp ; ++ pbp )
        ;
    if ( pbend == pbp )
        return NULL;
    /*
     * pbp now points to a \0 that should later be replaced with a hyphen.
     * The \0-terminated string starting at pathbuf can, for now, be reused
     * as an argument to snprintf.
     */
    remaining = (pbend - pbp) - 1;
    would_have_sprinted = snprintf(pbp + 1, remaining, "%s.jar%c%s-api-%s.jar",
        SO_VERSION_STRING, pathsep, pathbuf, SO_VERSION_STRING);
    if ( would_have_sprinted >= remaining )
        return NULL;
    *pbp = '-'; /* overwrite the \0 so now it's a single string. */
    return pathbuf;
}
Referenced by registerGUCOptions().
InstallHelper_earlyHello()
void InstallHelper_earlyHello ()
Definition at line 437 of file InstallHelper.c.
{
    elog(DEBUG2,
        "pljava-so-" SO_VERSION_STRING " built for (" PG_VERSION_STR ")");
}
Referenced by _PG_init().
InstallHelper_groundwork()
void InstallHelper_groundwork ()
Definition at line 524 of file InstallHelper.c.
{
    Invocation ctx;
    bool snapshot_set = false;
    Invocation_pushInvocation(&ctx);
    ctx.function = Function_INIT_WRITER;
    if ( ! ActiveSnapshotSet() )
    {
        PushActiveSnapshot(GetTransactionSnapshot());
        snapshot_set = true;
    }
    PG_TRY();
    {
        char const *lpt = LOADPATH_TBL_NAME;
        char const *lptq = quote_identifier(lpt);
        jstring pljlp = String_createJavaStringFromNTS(pljavaLoadPath);
        jstring jlpt = String_createJavaStringFromNTS(lpt);
        jstring jlptq = String_createJavaStringFromNTS(lptq);
        if ( lptq != lpt )
            pfree((void *)lptq);
        JNI_callStaticVoidMethod(
            s_InstallHelper_class, s_InstallHelper_groundwork,
            pljlp, jlpt, jlptq,
            pljavaLoadingAsExtension ? JNI_TRUE : JNI_FALSE,
            extensionExNihilo ? JNI_TRUE : JNI_FALSE);
        JNI_deleteLocalRef(pljlp);
        JNI_deleteLocalRef(jlpt);
        JNI_deleteLocalRef(jlptq);
        if ( snapshot_set )
        {
            PopActiveSnapshot();
        }
        Invocation_popInvocation(false);
    }
    PG_CATCH();
    {
        if ( snapshot_set )
        {
            PopActiveSnapshot();
        }
        Invocation_popInvocation(true);
        PG_RE_THROW();
    }
    PG_END_TRY();
}
References extensionExNihilo, Function_INIT_WRITER, Invocation_popInvocation(), Invocation_pushInvocation(), JNI_callStaticVoidMethod(), JNI_deleteLocalRef(), LOADPATH_TBL_NAME, pljavaLoadingAsExtension, pljavaLoadPath, s_InstallHelper_class, s_InstallHelper_groundwork, and String_createJavaStringFromNTS().
Referenced by initsequencer().
InstallHelper_hello()
char * InstallHelper_hello ()
Definition at line 443 of file InstallHelper.c.
{
    char pathbuf[MAXPGPATH];
    Invocation ctx;
    jstring nativeVer;
    jstring serverBuiltVer;
    jstring serverRunningVer;
#if PG_VERSION_NUM >= 120000
    FunctionCallInfoBaseData
#else
    FunctionCallInfoData
#endif
        fcinfo;
    text *runningVer;
    jstring user;
    jstring dbname;
    jstring clustername;
    jstring ddir;
    jstring ldir;
    jstring sdir;
    jstring edir;
    jstring greeting;
    char *greetingC;
    char const *clusternameC = pljavaClusterName();
    jboolean manageContext = JNI_getStaticBooleanField(s_InstallHelper_class,
        s_InstallHelper_MANAGE_CONTEXT_LOADER);
    pljava_JNI_threadInitialize(JNI_TRUE == manageContext);
    Invocation_pushBootContext(&ctx);
    nativeVer = String_createJavaStringFromNTS(SO_VERSION_STRING);
    serverBuiltVer = String_createJavaStringFromNTS(PG_VERSION_STR);
    InitFunctionCallInfoData(fcinfo, NULL, 0,
    InvalidOid, /* collation */
    NULL, NULL);
    runningVer = DatumGetTextP(pgsql_version(&fcinfo));
    serverRunningVer = String_createJavaString(runningVer);
    pfree(runningVer);
    user = String_createJavaStringFromNTS(origUserName());
    dbname = String_createJavaStringFromNTS(pljavaDbName());
    if ( '\0' == *clusternameC )
        clustername = NULL;
    else
        clustername = String_createJavaStringFromNTS(clusternameC);
    ddir = String_createJavaStringFromNTS(DataDir);
    get_pkglib_path(my_exec_path, pathbuf);
    ldir = String_createJavaStringFromNTS(pathbuf);
    get_share_path(my_exec_path, pathbuf);
    sdir = String_createJavaStringFromNTS(pathbuf);
    get_etc_path(my_exec_path, pathbuf);
    edir = String_createJavaStringFromNTS(pathbuf);
    greeting = JNI_callStaticObjectMethod(
        s_InstallHelper_class, s_InstallHelper_hello,
        nativeVer, serverBuiltVer, serverRunningVer,
        user, dbname, clustername,
        ddir, ldir, sdir, edir);
    JNI_deleteLocalRef(nativeVer);
    JNI_deleteLocalRef(serverBuiltVer);
    JNI_deleteLocalRef(serverRunningVer);
    JNI_deleteLocalRef(user);
    JNI_deleteLocalRef(dbname);
    if ( NULL != clustername )
        JNI_deleteLocalRef(clustername);
    JNI_deleteLocalRef(ddir);
    JNI_deleteLocalRef(ldir);
    JNI_deleteLocalRef(sdir);
    JNI_deleteLocalRef(edir);
    greetingC = String_createNTS(greeting);
    JNI_deleteLocalRef(greeting);
    Invocation_popBootContext();
    return greetingC;
}
References Invocation_popBootContext(), Invocation_pushBootContext(), JNI_callStaticObjectMethod(), JNI_deleteLocalRef(), JNI_getStaticBooleanField(), origUserName(), pljava_JNI_threadInitialize(), pljavaClusterName(), pljavaDbName(), s_InstallHelper_class, s_InstallHelper_hello, s_InstallHelper_MANAGE_CONTEXT_LOADER, String_createJavaString(), String_createJavaStringFromNTS(), and String_createNTS().
Referenced by initsequencer().
InstallHelper_initialize()
void InstallHelper_initialize ()
Definition at line 570 of file InstallHelper.c.
{
    s_InstallHelper_class = (jclass)JNI_newGlobalRef(PgObject_getJavaClass(
        "org/postgresql/pljava/internal/InstallHelper"));
    s_InstallHelper_MANAGE_CONTEXT_LOADER = PgObject_getStaticJavaField(
        s_InstallHelper_class, "MANAGE_CONTEXT_LOADER", "Z");
    s_InstallHelper_hello = PgObject_getStaticJavaMethod(s_InstallHelper_class,
        "hello",
        "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;"
        "Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;"
        "Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;"
        "Ljava/lang/String;)Ljava/lang/String;");
    s_InstallHelper_groundwork = PgObject_getStaticJavaMethod(
        s_InstallHelper_class, "groundwork",
        "(Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;ZZ)V");
}
References JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getStaticJavaField(), PgObject_getStaticJavaMethod(), s_InstallHelper_class, s_InstallHelper_groundwork, s_InstallHelper_hello, and s_InstallHelper_MANAGE_CONTEXT_LOADER.
Referenced by initPLJavaClasses().
InstallHelper_isPLJavaFunction()
bool InstallHelper_isPLJavaFunction (Oid fn, char ** langName, bool * trusted)
Definition at line 371 of file InstallHelper.c.
{
    char *itsPath;
    char *pljPath;
    bool result = false;
    itsPath = pljavaFnOidToLibPath(fn, langName, trusted);
    if ( NULL == itsPath )
        return false;
    if ( NULL == pljavaLoadPath )
    {
        pljPath = NULL;
        if ( InvalidOid != pljavaTrustedOid )
            pljPath = pljavaFnOidToLibPath(pljavaTrustedOid, NULL, NULL);
        if ( NULL == pljPath && InvalidOid != pljavaUntrustedOid )
            pljPath = pljavaFnOidToLibPath(pljavaUntrustedOid, NULL, NULL);
        if ( NULL == pljPath )
        {
            elog(WARNING, "unable to determine PL/Java's load path");
            goto finally;
        }
        pljavaLoadPath =
            (char const *)MemoryContextStrdup(TopMemoryContext, pljPath);
        pfree(pljPath);
    }
    result = 0 == strcmp(itsPath, pljavaLoadPath);
finally:
    pfree(itsPath);
    return result;
}
References pljavaFnOidToLibPath(), pljavaLoadPath, pljavaTrustedOid, and pljavaUntrustedOid.
Referenced by Function_checkTypeBaseUDT(), and Java_org_postgresql_pljava_internal_Backend__1myLibraryPath().
InstallHelper_shouldDeferInit()
bool InstallHelper_shouldDeferInit ()
Definition at line 359 of file InstallHelper.c.
{
    if ( AmAutoVacuumWorkerProcess() || AmBackgroundWorkerProcess() )
            return true;
    if ( ! IsBinaryUpgrade )
        return false;
    Backend_warnJEP411(true);
    return true;
}
References AmAutoVacuumWorkerProcess, AmBackgroundWorkerProcess, and Backend_warnJEP411().
Referenced by _PG_init().
origUserName()
static char * origUserName () static
Definition at line 115 of file InstallHelper.c.
{
    if ( AmAutoVacuumWorkerProcess() || AmBackgroundWorkerProcess() )
    {
        char *shortlived;
        static char *longlived;
        if ( NULL == longlived )
        {
            shortlived = GetUserNameFromId(GetAuthenticatedUserId(), false);
            longlived = MemoryContextStrdup(TopMemoryContext, shortlived);
            pfree(shortlived);
        }
        return longlived;
    }
    return MyProcPort->user_name;
}
References AmAutoVacuumWorkerProcess, and AmBackgroundWorkerProcess.
Referenced by InstallHelper_hello().
pljavaCheckExtension()
void pljavaCheckExtension (bool * livecheck)
Definition at line 141 of file InstallHelper.c.
{
    if ( ! creating_extension )
    {
        checkLoadPath();
        return;
    }
    if ( NULL != livecheck )
    {
        *livecheck = true;
        return;
    }
    getExtensionLoadPath();
    if ( NULL != pljavaLoadPath )
        pljavaLoadingAsExtension = true;
}
References checkLoadPath(), getExtensionLoadPath(), pljavaLoadingAsExtension, and pljavaLoadPath.
Referenced by _PG_init(), and Java_org_postgresql_pljava_internal_Backend__1isCreatingExtension().
pljavaClusterName()
char const * pljavaClusterName ()
Definition at line 132 of file InstallHelper.c.
{
    /*
     * In PostgreSQL of at least 9.5, there's always one (even if it is an empty
     * string), so PG_GETCONFIGOPTION is safe.
     */
    return PG_GETCONFIGOPTION("cluster_name");
}
Referenced by InstallHelper_hello(), and JVMOptList_addVisualVMName().
pljavaDbName()
char * pljavaDbName ()
Definition at line 95 of file InstallHelper.c.
{
    if ( AmAutoVacuumWorkerProcess() || AmBackgroundWorkerProcess() )
    {
        char *shortlived;
        static char *longlived;
        if ( NULL == longlived )
        {
            shortlived = get_database_name(MyDatabaseId);
            if ( NULL != shortlived )
            {
                longlived = MemoryContextStrdup(TopMemoryContext, shortlived);
                pfree(shortlived);
            }
        }
        return longlived;
    }
    return MyProcPort->database_name;
}
References AmAutoVacuumWorkerProcess, and AmBackgroundWorkerProcess.
Referenced by initsequencer(), InstallHelper_hello(), and JVMOptList_addVisualVMName().
pljavaFnOidToLibPath()
char * pljavaFnOidToLibPath (Oid fnOid, char ** langName, bool * trusted)
Definition at line 265 of file InstallHelper.c.
{
    bool isnull;
    HeapTuple procTup;
    Form_pg_proc procStruct;
    Oid langId;
    HeapTuple langTup;
    Form_pg_language langStruct;
    Oid handlerOid;
    Datum probinattr;
    char *probinstring;
    /*
     * It is proposed that fnOid refers to a function implemented with PL/Java.
     */
    procTup = SearchSysCache1(PROCOID, ObjectIdGetDatum(fnOid));
    if (!HeapTupleIsValid(procTup))
        elog(ERROR, "cache lookup failed for function %u", fnOid);
    procStruct = (Form_pg_proc) GETSTRUCT(procTup);
    langId = procStruct->prolang;
    ReleaseSysCache(procTup);
    /*
     * The langId just obtained (if the proposition is proved correct by
     * surviving the further steps below) is a langId for PL/Java. It could
     * be cached to simplify later checks. Not today.
     */
    if ( langId == INTERNALlanguageId || langId == ClanguageId
        || langId == SQLlanguageId )
        return NULL; /* these can be eliminated without searching syscache. */
    /*
     * So far so good ... the function thought to be done in PL/Java has at
     * least not turned out to be internal, or C, or SQL. So, next, look up its
     * language, and get the Oid for its function call handler.
     */
    langTup = SearchSysCache1(LANGOID, ObjectIdGetDatum(langId));
    if (!HeapTupleIsValid(langTup))
        elog(ERROR, "cache lookup failed for language %u", langId);
    langStruct = (Form_pg_language) GETSTRUCT(langTup);
    handlerOid = langStruct->lanplcallfoid;
    /*
     * PL/Java has certainly got a function call handler, so if this language
     * hasn't, PL/Java it's not.
     */
    if ( InvalidOid == handlerOid )
    {
        ReleaseSysCache(langTup);
        return NULL;
    }
    /*
     * Da capo al coda ... handlerOid is another function to be looked up.
     */
    procTup = SearchSysCache1(PROCOID, ObjectIdGetDatum(handlerOid));
    if (!HeapTupleIsValid(procTup))
        elog(ERROR, "cache lookup failed for function %u", handlerOid);
    procStruct = (Form_pg_proc) GETSTRUCT(procTup);
    /*
     * If the call handler's not a C function, this isn't PL/Java....
     */
    if ( ClanguageId != procStruct->prolang )
    {
        ReleaseSysCache(langTup);
        return NULL;
    }
    /*
     * Now that the handler is known to be a C function, it should have a
     * probinattr containing the name of its dynamic library.
     */
    probinattr =
        SysCacheGetAttr(PROCOID, procTup, Anum_pg_proc_probin, &isnull);
    if ( isnull )
        elog(ERROR, "null probin for C function %u", handlerOid);
    if ( NULL != langName )
        *langName = pstrdup(NameStr(langStruct->lanname));
    if ( NULL != trusted )
        *trusted = langStruct->lanpltrusted;
    ReleaseSysCache(langTup);
    probinstring = /* TextDatumGetCString(probinattr); */
        DatumGetCString(DirectFunctionCall1(textout, probinattr)); /*archaic*/
    ReleaseSysCache(procTup);
    /*
     * About this result: if the caller was initialization code passing a fnOid
     * known to refer to PL/Java (because it was the function occasioning the
     * call), then this string can be saved as the dynamic library name for
     * PL/Java. Otherwise, it is the library name for whatever language is used
     * by the fnOid passed in, and can be compared to such a saved value to
     * determine whether that is a PL/Java function or not.
     */
    return probinstring;
}
Referenced by InstallHelper_isPLJavaFunction().
pljavaViableXact()
bool pljavaViableXact ()
Definition at line 90 of file InstallHelper.c.
{
    return IsTransactionState() && 'E' != TransactionBlockStatusCode();
}
Variable Documentation
extensionExNihilo
bool extensionExNihilo = false static
Definition at line 76 of file InstallHelper.c.
Referenced by getExtensionLoadPath(), and InstallHelper_groundwork().
pljavaLoadingAsExtension
bool pljavaLoadingAsExtension = false
Definition at line 84 of file InstallHelper.c.
Referenced by initsequencer(), InstallHelper_groundwork(), and pljavaCheckExtension().
pljavaLoadPath
char const* pljavaLoadPath = NULL
Definition at line 82 of file InstallHelper.c.
Referenced by checkLoadPath(), getExtensionLoadPath(), initsequencer(), InstallHelper_groundwork(), InstallHelper_isPLJavaFunction(), Java_org_postgresql_pljava_internal_Backend__1myLibraryPath(), and pljavaCheckExtension().
pljavaTrustedOid
Oid pljavaTrustedOid = InvalidOid
Definition at line 86 of file InstallHelper.c.
Referenced by InstallHelper_isPLJavaFunction(), internalCallHandler(), internalValidator(), and Java_org_postgresql_pljava_internal_Backend__1myLibraryPath().
pljavaUntrustedOid
Oid pljavaUntrustedOid = InvalidOid
Definition at line 88 of file InstallHelper.c.
Referenced by InstallHelper_isPLJavaFunction(), internalCallHandler(), internalValidator(), and Java_org_postgresql_pljava_internal_Backend__1myLibraryPath().
s_InstallHelper_class
jclass s_InstallHelper_class static
Definition at line 71 of file InstallHelper.c.
Referenced by InstallHelper_groundwork(), InstallHelper_hello(), and InstallHelper_initialize().
s_InstallHelper_groundwork
jmethodID s_InstallHelper_groundwork static
Definition at line 73 of file InstallHelper.c.
Referenced by InstallHelper_groundwork(), and InstallHelper_initialize().
s_InstallHelper_hello
jmethodID s_InstallHelper_hello static
Definition at line 72 of file InstallHelper.c.
Referenced by InstallHelper_hello(), and InstallHelper_initialize().
s_InstallHelper_MANAGE_CONTEXT_LOADER
jfieldID s_InstallHelper_MANAGE_CONTEXT_LOADER static
Definition at line 74 of file InstallHelper.c.
Referenced by InstallHelper_hello(), and InstallHelper_initialize().