/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_postgresql_pljava_Portal */

#ifndef _Included_org_postgresql_pljava_Portal
#define _Included_org_postgresql_pljava_Portal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_postgresql_pljava_Portal
 * Method:    close
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_postgresql_pljava_Portal_close
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_Portal
 * Method:    getPortalPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_Portal_getPortalPos
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_Portal
 * Method:    fetch
 * Signature: (ZI)I
 */
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_Portal_fetch
  (JNIEnv *, jobject, jboolean, jint);

/*
 * Class:     org_postgresql_pljava_Portal
 * Method:    isAtEnd
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_Portal_isAtEnd
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_Portal
 * Method:    isAtStart
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_Portal_isAtStart
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_Portal
 * Method:    isPosOverflow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_Portal_isPosOverflow
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_Portal
 * Method:    move
 * Signature: (ZI)I
 */
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_Portal_move
  (JNIEnv *, jobject, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
