/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_postgresql_pljava_internal_Portal */

#ifndef _Included_org_postgresql_pljava_internal_Portal
#define _Included_org_postgresql_pljava_internal_Portal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    _getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_Portal__1getName
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    _getPortalPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_Portal__1getPortalPos
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    _getTupleDesc
 * Signature: ()Lorg/postgresql/pljava/internal/TupleDesc;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Portal__1getTupleDesc
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    _fetch
 * Signature: (ZI)I
 */
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_Portal__1fetch
  (JNIEnv *, jobject, jboolean, jint);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    _invalidate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_Portal__1invalidate
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    _isAtEnd
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_Portal__1isAtEnd
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    _isAtStart
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_Portal__1isAtStart
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    _isPosOverflow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_Portal__1isPosOverflow
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    _move
 * Signature: (ZI)I
 */
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_Portal__1move
  (JNIEnv *, jobject, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
