/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_postgresql_pljava_internal_Portal */

#ifndef _Included_org_postgresql_pljava_internal_Portal
#define _Included_org_postgresql_pljava_internal_Portal
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_Portal_getName
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    getPortalPos
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_Portal_getPortalPos
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    getTupleDesc
 * Signature: ()Lorg/postgresql/pljava/internal/TupleDesc;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Portal_getTupleDesc
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    fetch
 * Signature: (ZI)I
 */
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_Portal_fetch
  (JNIEnv *, jobject, jboolean, jint);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    invalidate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_Portal_invalidate
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    isAtEnd
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_Portal_isAtEnd
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    isAtStart
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_Portal_isAtStart
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    isPosOverflow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_Portal_isPosOverflow
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_Portal
 * Method:    move
 * Signature: (ZI)I
 */
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_Portal_move
  (JNIEnv *, jobject, jboolean, jint);

#ifdef __cplusplus
}
#endif
#endif
