/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_postgresql_pljava_Relation */

#ifndef _Included_org_postgresql_pljava_Relation
#define _Included_org_postgresql_pljava_Relation
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_postgresql_pljava_Relation
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_Relation_getName
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_Relation
 * Method:    getTupleDesc
 * Signature: ()Lorg/postgresql/pljava/TupleDesc;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_Relation_getTupleDesc
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_Relation
 * Method:    modifyTuple
 * Signature: (Lorg/postgresql/pljava/Tuple;[I[Ljava/lang/Object;)Lorg/postgresql/pljava/Tuple;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_Relation_modifyTuple
  (JNIEnv *, jobject, jobject, jintArray, jobjectArray);

#ifdef __cplusplus
}
#endif
#endif
