/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_postgresql_pljava_internal_TriggerData */

#ifndef _Included_org_postgresql_pljava_internal_TriggerData
#define _Included_org_postgresql_pljava_internal_TriggerData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_postgresql_pljava_internal_TriggerData
 * Method:    _getRelation
 * Signature: ()Lorg/postgresql/pljava/internal/Relation;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getRelation
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_TriggerData
 * Method:    _getTriggerTuple
 * Signature: ()Lorg/postgresql/pljava/internal/Tuple;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getTriggerTuple
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_TriggerData
 * Method:    _getNewTuple
 * Signature: ()Lorg/postgresql/pljava/internal/Tuple;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getNewTuple
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_TriggerData
 * Method:    _getArguments
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getArguments
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_TriggerData
 * Method:    _getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_TriggerData__1getName
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_TriggerData
 * Method:    _isFiredAfter
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredAfter
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_TriggerData
 * Method:    _isFiredBefore
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredBefore
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_TriggerData
 * Method:    _isFiredForEachRow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredForEachRow
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_TriggerData
 * Method:    _isFiredForStatement
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredForStatement
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_TriggerData
 * Method:    _isFiredByDelete
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredByDelete
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_TriggerData
 * Method:    _isFiredByInsert
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredByInsert
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_TriggerData
 * Method:    _isFiredByUpdate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_TriggerData__1isFiredByUpdate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
