/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_postgresql_pljava_TriggerData */

#ifndef _Included_org_postgresql_pljava_TriggerData
#define _Included_org_postgresql_pljava_TriggerData
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_postgresql_pljava_TriggerData
 * Method:    getRelation
 * Signature: ()Lorg/postgresql/pljava/Relation;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_TriggerData_getRelation
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_TriggerData
 * Method:    getTriggerTuple
 * Signature: ()Lorg/postgresql/pljava/Tuple;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_TriggerData_getTriggerTuple
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_TriggerData
 * Method:    getNewTuple
 * Signature: ()Lorg/postgresql/pljava/Tuple;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_TriggerData_getNewTuple
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_TriggerData
 * Method:    getArguments
 * Signature: ()[Ljava/lang/String;
 */
JNIEXPORT jobjectArray JNICALL Java_org_postgresql_pljava_TriggerData_getArguments
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_TriggerData
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_TriggerData_getName
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_TriggerData
 * Method:    isFiredAfter
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_TriggerData_isFiredAfter
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_TriggerData
 * Method:    isFiredBefore
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_TriggerData_isFiredBefore
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_TriggerData
 * Method:    isFiredForEachRow
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_TriggerData_isFiredForEachRow
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_TriggerData
 * Method:    isFiredForStatement
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_TriggerData_isFiredForStatement
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_TriggerData
 * Method:    isFiredByDelete
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_TriggerData_isFiredByDelete
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_TriggerData
 * Method:    isFiredByInsert
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_TriggerData_isFiredByInsert
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_TriggerData
 * Method:    isFiredByUpdate
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_TriggerData_isFiredByUpdate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
