/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_postgresql_pljava_internal_TupleTableSlot */

#ifndef _Included_org_postgresql_pljava_internal_TupleTableSlot
#define _Included_org_postgresql_pljava_internal_TupleTableSlot
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_postgresql_pljava_internal_TupleTableSlot
 * Method:    getTuple
 * Signature: ()Lorg/postgresql/pljava/internal/Tuple;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TupleTableSlot_getTuple
  (JNIEnv *, jobject);

/*
 * Class:     org_postgresql_pljava_internal_TupleTableSlot
 * Method:    getTupleDesc
 * Signature: ()Lorg/postgresql/pljava/internal/TupleDesc;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TupleTableSlot_getTupleDesc
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
