/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_postgresql_pljava_internal_Tuple */

#ifndef _Included_org_postgresql_pljava_internal_Tuple
#define _Included_org_postgresql_pljava_internal_Tuple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_postgresql_pljava_internal_Tuple
 * Method:    _getObject
 * Signature: (Lorg/postgresql/pljava/internal/TupleDesc;I)Ljava/lang/Object;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_Tuple__1getObject
  (JNIEnv *, jobject, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
