/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_postgresql_pljava_internal_TupleDesc */

#ifndef _Included_org_postgresql_pljava_internal_TupleDesc
#define _Included_org_postgresql_pljava_internal_TupleDesc
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_postgresql_pljava_internal_TupleDesc
 * Method:    _getColumnName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_TupleDesc__1getColumnName
  (JNIEnv *, jobject, jint);

/*
 * Class:     org_postgresql_pljava_internal_TupleDesc
 * Method:    _getColumnIndex
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_TupleDesc__1getColumnIndex
  (JNIEnv *, jobject, jstring);

/*
 * Class:     org_postgresql_pljava_internal_TupleDesc
 * Method:    _formTuple
 * Signature: ([Ljava/lang/Object;)Lorg/postgresql/pljava/internal/Tuple;
 */
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_TupleDesc__1formTuple
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     org_postgresql_pljava_internal_TupleDesc
 * Method:    _size
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_TupleDesc__1size
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
