PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/HashMap.c File Reference
HashMap.c File Reference
#include "pljava/HashMap_priv.h"
Functions
HashKey HashKey_clone (HashKey self, MemoryContext ctx)
bool HashKey_equals (HashKey self, HashKey other)
uint32 HashKey_hashCode (HashKey self)
HashKey _HashKey_clone (HashKey self, MemoryContext ctx)
HashKeyClass HashKeyClass_alloc (const char *className, Size instanceSize, Finalizer finalizer)
static uint32 _OidKey_hashCode (HashKey self)
static bool _OidKey_equals (HashKey self, HashKey other)
static void OidKey_init (OidKey self, Oid keyVal)
static HashKey _StringKey_clone (HashKey self, MemoryContext ctx)
static bool _StringKey_equals (HashKey self, HashKey other)
static void _StringKey_finalize (PgObject self)
static uint32 _StringKey_hashCode (HashKey self)
static void StringKey_init (StringKey self, const char *keyVal)
static uint32 _OpaqueKey_hashCode (HashKey self)
static bool _OpaqueKey_equals (HashKey self, HashKey other)
static void OpaqueKey_init (OpaqueKey self, void *keyVal)
static HashKey _StringOidKey_clone (HashKey self, MemoryContext ctx)
static bool _StringOidKey_equals (HashKey self, HashKey other)
static uint32 _StringOidKey_hashCode (HashKey self)
static void StringOidKey_init (StringOidKey self, const char *string, Oid oid)
HashKey Entry_getKey (Entry self)
void * Entry_getValue (Entry self)
void * Entry_setValue (Entry self, void *value)
static void _Entry_finalize (PgObject self)
static void HashMap_rehash (HashMap self, uint32 newCapacity)
void HashMap_clear (HashMap self)
static void _HashMap_finalize (PgObject self)
HashMap HashMap_create (uint32 initialCapacity, MemoryContext ctx)
Iterator HashMap_entries (HashMap self)
void * HashMap_get (HashMap self, HashKey key)
void * HashMap_put (HashMap self, HashKey key, void *value)
void * HashMap_remove (HashMap self, HashKey key)
void * HashMap_getByOid (HashMap self, Oid oid)
void * HashMap_getByOpaque (HashMap self, void *opaque)
void * HashMap_getByString (HashMap self, const char *key)
void * HashMap_getByStringOid (HashMap self, const char *string, Oid oid)
void * HashMap_putByOid (HashMap self, Oid oid, void *value)
void * HashMap_putByOpaque (HashMap self, void *opaque, void *value)
void * HashMap_putByString (HashMap self, const char *key, void *value)
void * HashMap_putByStringOid (HashMap self, const char *string, Oid oid, void *value)
void * HashMap_removeByOid (HashMap self, Oid oid)
void * HashMap_removeByOpaque (HashMap self, void *opaque)
void * HashMap_removeByString (HashMap self, const char *key)
void * HashMap_removeByStringOid (HashMap self, const char *string, Oid oid)
uint32 HashMap_size (HashMap self)
void Iterator_initialize (void)
void HashMap_initialize (void)
Variables
static HashKeyClass s_OidKeyClass
static HashKeyClass s_StringKeyClass
static HashKeyClass s_OpaqueKeyClass
static HashKeyClass s_StringOidKeyClass
static PgObjectClass s_EntryClass
static PgObjectClass s_HashMapClass
Function Documentation
_Entry_finalize()
static void _Entry_finalize (PgObject self) static
Definition at line 216 of file HashMap.c.
{
    PgObject_free((PgObject)((Entry)self)->key);
}
References PgObject_free().
Referenced by HashMap_initialize().
_HashKey_clone()
HashKey _HashKey_clone (HashKey self, MemoryContext ctx)
Definition at line 30 of file HashMap.c.
{
    Size sz = ((PgObjectClass)self->m_class)->instanceSize;
    HashKey clone = (HashKey)MemoryContextAlloc(ctx, sz);
    memcpy(clone, self, sz);
    return clone;
}
Referenced by _StringKey_clone(), and HashKeyClass_alloc().
_HashMap_finalize()
static void _HashMap_finalize (PgObject self) static
Definition at line 275 of file HashMap.c.
{
    /* Delete all Entries before deleting the table and
     * self.
     */
    HashMap_clear((HashMap)self);
    pfree(((HashMap)self)->table);
}
References HashMap_clear().
Referenced by HashMap_initialize().
_OidKey_equals()
static bool _OidKey_equals (HashKey self, HashKey other) static
Definition at line 65 of file HashMap.c.
{
    return other->m_class == self->m_class /* Same class */
        && ((OidKey)self)->key == ((OidKey)other)->key;
}
Referenced by HashMap_initialize().
_OidKey_hashCode()
static uint32 _OidKey_hashCode (HashKey self) static
Definition at line 57 of file HashMap.c.
{
    return (uint32)((OidKey)self)->key;
}
Referenced by HashMap_initialize().
_OpaqueKey_equals()
static bool _OpaqueKey_equals (HashKey self, HashKey other) static
Definition at line 146 of file HashMap.c.
{
    return other->m_class == self->m_class /* Same class */
        && ((OpaqueKey)self)->key == ((OpaqueKey)other)->key;
}
Referenced by HashMap_initialize().
_OpaqueKey_hashCode()
static uint32 _OpaqueKey_hashCode (HashKey self) static
Definition at line 135 of file HashMap.c.
{
    Ptr2Long p2l;
    p2l.longVal = 0L; /* ensure that the rest is zeroed out */
    p2l.ptrVal = ((OpaqueKey)self)->key;
    return (uint32)(p2l.longVal >> 3);
}
Referenced by HashMap_initialize().
_StringKey_clone()
static HashKey _StringKey_clone (HashKey self, MemoryContext ctx) static
Definition at line 80 of file HashMap.c.
{
    HashKey clone = _HashKey_clone(self, ctx);
    ((StringKey)clone)->key = MemoryContextStrdup(ctx, ((StringKey)self)->key);
    return clone;
}
References _HashKey_clone().
Referenced by _StringOidKey_clone(), and HashMap_initialize().
_StringKey_equals()
static bool _StringKey_equals (HashKey self, HashKey other) static
Definition at line 90 of file HashMap.c.
{
    return other->m_class == self->m_class /* Same class */
        && strcmp(((StringKey)self)->key, ((StringKey)other)->key) == 0;
}
Referenced by HashMap_initialize().
_StringKey_finalize()
static void _StringKey_finalize (PgObject self) static
Definition at line 96 of file HashMap.c.
{
    pfree((char*)((StringKey)self)->key);
}
Referenced by HashMap_initialize().
_StringKey_hashCode()
static uint32 _StringKey_hashCode (HashKey self) static
Definition at line 111 of file HashMap.c.
{
    const char* val = ((StringKey)self)->key;
    uint32 h = ((StringKey)self)->hash;
    if(h == 0)
    {
        uint32 c;
        while((c = *val++) != 0)
            h = 31 * h + c;
        ((StringKey)self)->hash = h;
    }
    return h;
}
Referenced by _StringOidKey_hashCode(), and HashMap_initialize().
_StringOidKey_clone()
static HashKey _StringOidKey_clone (HashKey self, MemoryContext ctx) static
Definition at line 161 of file HashMap.c.
{
    HashKey clone = _StringKey_clone(self, ctx);
    ((StringOidKey)clone)->oid = ((StringOidKey)self)->oid;
    return clone;
}
References _StringKey_clone().
Referenced by HashMap_initialize().
_StringOidKey_equals()
static bool _StringOidKey_equals (HashKey self, HashKey other) static
Definition at line 171 of file HashMap.c.
{
    return other->m_class == self->m_class /* Same class */
        && strcmp(((StringKey)self)->key, ((StringKey)other)->key) == 0
        && ((StringOidKey)self)->oid == ((StringOidKey)other)->oid;
}
Referenced by HashMap_initialize().
_StringOidKey_hashCode()
static uint32 _StringOidKey_hashCode (HashKey self) static
Definition at line 181 of file HashMap.c.
{
    return ((uint32)((StringOidKey)self)->oid) ^ _StringKey_hashCode(self);
}
References _StringKey_hashCode().
Referenced by HashMap_initialize().
Entry_getKey()
HashKey Entry_getKey (Entry self)
Definition at line 199 of file HashMap.c.
{
    return self->key;
}
Referenced by Function_clearFunctionCache().
Entry_getValue()
void * Entry_getValue (Entry self)
Definition at line 204 of file HashMap.c.
{
    return self->value;
}
Referenced by Function_clearFunctionCache().
Entry_setValue()
void * Entry_setValue (Entry self, void * value)
Definition at line 209 of file HashMap.c.
{
    void* old = self->value;
    self->value = value;
    return old;
}
Referenced by Function_clearFunctionCache().
HashKey_clone()
HashKey HashKey_clone (HashKey self, MemoryContext ctx)
Definition at line 15 of file HashMap.c.
{
    return self->m_class->clone(self, ctx);
}
Referenced by HashMap_put().
HashKey_equals()
bool HashKey_equals (HashKey self, HashKey other)
Definition at line 20 of file HashMap.c.
{
    return self->m_class->equals(self, other);
}
Referenced by HashMap_get(), HashMap_put(), and HashMap_remove().
HashKey_hashCode()
uint32 HashKey_hashCode (HashKey self)
Definition at line 25 of file HashMap.c.
{
    return self->m_class->hashCode(self);
}
HashKeyClass_alloc()
HashKeyClass HashKeyClass_alloc (const char * className, Size instanceSize, Finalizer finalizer)
Definition at line 38 of file HashMap.c.
{
    HashKeyClass self = (HashKeyClass)MemoryContextAlloc(TopMemoryContext, sizeof(struct HashKeyClass_));
    PgObjectClass_init((PgObjectClass)self, className, instanceSize, finalizer);
    self->clone = _HashKey_clone;
    return self;
}
References _HashKey_clone(), and PgObjectClass_init().
Referenced by HashMap_initialize().
HashMap_clear()
void HashMap_clear (HashMap self)
Definition at line 250 of file HashMap.c.
{
    /* Delete all Entries before deleting the table and
     * self.
     */
    if(self->size > 0)
    {
        Entry* table = self->table;
        uint32 top = self->tableSize;
        uint32 idx;
        for(idx = 0; idx < top; ++idx)
        {
            Entry e = table[idx];
            table[idx] = 0;
            while(e != 0)
            {
                Entry eNext = e->next;
                PgObject_free((PgObject)e);
                e = eNext;
            }
        }
        self->size = 0;
    }
}
References PgObject_free().
Referenced by _HashMap_finalize().
HashMap_create()
HashMap HashMap_create (uint32 initialCapacity, MemoryContext ctx)
Definition at line 284 of file HashMap.c.
{
    HashMap self;
    if(ctx == 0)
        ctx = CurrentMemoryContext;
    self = (HashMap)PgObjectClass_allocInstance(s_HashMapClass, ctx);
    if(initialCapacity < 13)
        initialCapacity = 13;
    self->table = (Entry*)MemoryContextAlloc(ctx, initialCapacity * sizeof(Entry));
    memset(self->table, 0, initialCapacity * sizeof(Entry));
    self->tableSize = initialCapacity;
    self->size = 0;
    return self;
}
References PgObjectClass_allocInstance(), and s_HashMapClass.
Referenced by _getCoerce(), Function_clearFunctionCache(), Function_initialize(), getModulePath(), and Type_initialize().
HashMap_entries()
Iterator HashMap_entries (HashMap self)
Definition at line 302 of file HashMap.c.
{
    return Iterator_create(self);
}
References Iterator_create().
HashMap_get()
void * HashMap_get (HashMap self, HashKey key)
Definition at line 307 of file HashMap.c.
{
    Entry slot;
    slot = self->table[HASHSLOT(self, key)];
    while(slot != 0)
        {
        if(HashKey_equals(slot->key, key))
            break;
        slot = slot->next;
        }
    return (slot == 0) ? 0 : slot->value;
}
References HashKey_equals().
Referenced by HashMap_getByOid(), HashMap_getByOpaque(), HashMap_getByString(), and HashMap_getByStringOid().
HashMap_getByOid()
void * HashMap_getByOid (HashMap self, Oid oid)
Definition at line 391 of file HashMap.c.
{
    struct OidKey_ oidKey;
    OidKey_init(&oidKey, oid);
    return HashMap_get(self, (HashKey)&oidKey);
}
References HashMap_get(), and OidKey_init().
Referenced by _getCoerce(), _registerType(), getFunction(), Type_fromOid(), and Type_fromOidCache().
HashMap_getByOpaque()
void * HashMap_getByOpaque (HashMap self, void * opaque)
Definition at line 398 of file HashMap.c.
{
    struct OpaqueKey_ opaqueKey;
    OpaqueKey_init(&opaqueKey, opaque);
    return HashMap_get(self, (HashKey)&opaqueKey);
}
References HashMap_get(), and OpaqueKey_init().
HashMap_getByString()
void * HashMap_getByString (HashMap self, const char * key)
Definition at line 405 of file HashMap.c.
{
    struct StringKey_ stringKey;
    StringKey_init(&stringKey, key);
    return HashMap_get(self, (HashKey)&stringKey);
}
References HashMap_get(), and StringKey_init().
Referenced by appendPathParts().
HashMap_getByStringOid()
void * HashMap_getByStringOid (HashMap self, const char * string, Oid oid)
Definition at line 412 of file HashMap.c.
{
    struct StringOidKey_ stringOidKey;
    StringOidKey_init(&stringOidKey, string, oid);
    return HashMap_get(self, (HashKey)&stringOidKey);
}
References HashMap_get(), and StringOidKey_init().
Referenced by Type_fromJavaType().
HashMap_initialize()
void HashMap_initialize (void) extern
Definition at line 483 of file HashMap.c.
{
    Iterator_initialize();
    s_EntryClass    = PgObjectClass_create("Entry", sizeof(struct Entry_), _Entry_finalize);
    s_HashMapClass  = PgObjectClass_create("HashMap", sizeof(struct HashMap_), _HashMap_finalize);
    s_OidKeyClass = HashKeyClass_alloc("OidKey", sizeof(struct OidKey_), 0);
    s_OidKeyClass->hashCode = _OidKey_hashCode;
    s_OidKeyClass->equals   = _OidKey_equals;
    s_OpaqueKeyClass = HashKeyClass_alloc("OpaqueKey", sizeof(struct OpaqueKey_), 0);
    s_OpaqueKeyClass->hashCode = _OpaqueKey_hashCode;
    s_OpaqueKeyClass->equals   = _OpaqueKey_equals;
    s_StringKeyClass = HashKeyClass_alloc("StringKey", sizeof(struct StringKey_), _StringKey_finalize);
    s_StringKeyClass->hashCode = _StringKey_hashCode;
    s_StringKeyClass->equals   = _StringKey_equals;
    s_StringKeyClass->clone    = _StringKey_clone;
    s_StringOidKeyClass = HashKeyClass_alloc("StringOidKey",
        sizeof(struct StringOidKey_), _StringKey_finalize); /* same finalize */
    s_StringOidKeyClass->hashCode = _StringOidKey_hashCode;
    s_StringOidKeyClass->equals   = _StringOidKey_equals;
    s_StringOidKeyClass->clone    = _StringOidKey_clone;
}
References _Entry_finalize(), _HashMap_finalize(), _OidKey_equals(), _OidKey_hashCode(), _OpaqueKey_equals(), _OpaqueKey_hashCode(), _StringKey_clone(), _StringKey_equals(), _StringKey_finalize(), _StringKey_hashCode(), _StringOidKey_clone(), _StringOidKey_equals(), _StringOidKey_hashCode(), HashKeyClass_alloc(), Iterator_initialize(), PgObjectClass_create(), s_EntryClass, s_HashMapClass, s_OidKeyClass, s_OpaqueKeyClass, s_StringKeyClass, and s_StringOidKeyClass.
Referenced by initsequencer().
HashMap_put()
void * HashMap_put (HashMap self, HashKey key, void * value)
Definition at line 320 of file HashMap.c.
{
    void* old = 0;
    uint32 slotNo = HASHSLOT(self, key);
    Entry  slot = self->table[slotNo];
    while(slot != 0)
    {
        if(HashKey_equals(slot->key, key))
            break;
        slot = slot->next;
    }
    if(slot == 0)
    {
        uint32 currSz = self->size;
        MemoryContext ctx = GetMemoryChunkContext(self);
        if((currSz + currSz / 2) > self->tableSize)
            {
            /* Always double the size. It gives predictable repositioning
             * of entries (a necessity if an Iteator is created some
             * time in the future.
             */
            HashMap_rehash(self, self->tableSize * 2);
            slotNo = HASHSLOT(self, key);
            }
        slot = Entry_create(ctx);
        slot->key   = HashKey_clone(key, ctx);  /* Create a private copy of the key */
        slot->value = value;
        slot->next  = self->table[slotNo];
        self->table[slotNo] = slot;
        self->size++;
    }
    else
    {
        old = slot->value;
        slot->value = value;
    }
    return old;
}
References HashKey_clone(), HashKey_equals(), and HashMap_rehash().
Referenced by Function_clearFunctionCache(), HashMap_putByOid(), HashMap_putByOpaque(), HashMap_putByString(), and HashMap_putByStringOid().
HashMap_putByOid()
void * HashMap_putByOid (HashMap self, Oid oid, void * value)
Definition at line 419 of file HashMap.c.
{
    struct OidKey_ oidKey;
    OidKey_init(&oidKey, oid);
    return HashMap_put(self, (HashKey)&oidKey, value);
}
References HashMap_put(), and OidKey_init().
Referenced by _getCoerce(), _registerType(), getFunction(), and Type_cacheByOid().
HashMap_putByOpaque()
void * HashMap_putByOpaque (HashMap self, void * opaque, void * value)
Definition at line 426 of file HashMap.c.
{
    struct OpaqueKey_ opaqueKey;
    OpaqueKey_init(&opaqueKey, opaque);
    return HashMap_put(self, (HashKey)&opaqueKey, value);
}
References HashMap_put(), and OpaqueKey_init().
HashMap_putByString()
void * HashMap_putByString (HashMap self, const char * key, void * value)
Definition at line 433 of file HashMap.c.
{
    struct StringKey_ stringKey;
    StringKey_init(&stringKey, key);
    return HashMap_put(self, (HashKey)&stringKey, value);
}
References HashMap_put(), and StringKey_init().
Referenced by appendPathParts().
HashMap_putByStringOid()
void * HashMap_putByStringOid (HashMap self, const char * string, Oid oid, void * value)
Definition at line 440 of file HashMap.c.
{
    struct StringOidKey_ stringOidKey;
    StringOidKey_init(&stringOidKey, string, oid);
    return HashMap_put(self, (HashKey)&stringOidKey, value);
}
References HashMap_put(), and StringOidKey_init().
Referenced by _registerType().
HashMap_rehash()
static void HashMap_rehash (HashMap self, uint32 newCapacity) static
Definition at line 221 of file HashMap.c.
{
    Entry* oldTable = self->table;
    uint32 top = self->tableSize;
    uint32 idx;
    Entry* newTable = (Entry*)MemoryContextAlloc(GetMemoryChunkContext(self), newCapacity * sizeof(Entry));
    memset(newTable, 0, newCapacity * sizeof(Entry));
    self->table = newTable;
    self->tableSize = newCapacity;
    /* Move all old slots to the new table
     */
    for(idx = 0; idx < top; ++idx)
    {
        Entry e = oldTable[idx];
        while(e != 0)
        {
            Entry eNext = e->next;
            HashKey eKey = e->key;
            uint32 slotNo = HASHSLOT(self, eKey);
            e->next = newTable[slotNo];
            newTable[slotNo] = e;
            e = eNext;
        }
    }
    pfree(oldTable);
}
Referenced by HashMap_put().
HashMap_remove()
void * HashMap_remove (HashMap self, HashKey key)
Definition at line 359 of file HashMap.c.
{
    PgObject old = 0;
    uint32 slotNo = HASHSLOT(self, key);
    Entry slot = self->table[slotNo];
    while(slot != 0)
    {
        if(HashKey_equals(slot->key, key))
            break;
        slot = slot->next;
    }
    if(slot != 0)
    {
        /* Find the preceding slot and create a bypass for the
         * found slot, i.e. disconnect it.
         */
        Entry prev = self->table[slotNo];
        if(slot == prev)
            self->table[slotNo] = slot->next;
        else
        {
            while(prev->next != slot)
                prev = prev->next;
            prev->next = slot->next;
        }
        old = slot->value;
        self->size--;
        PgObject_free((PgObject)slot);
    }
    return old;
}
References HashKey_equals(), and PgObject_free().
Referenced by HashMap_removeByOid(), HashMap_removeByOpaque(), HashMap_removeByString(), and HashMap_removeByStringOid().
HashMap_removeByOid()
void * HashMap_removeByOid (HashMap self, Oid oid)
Definition at line 448 of file HashMap.c.
{
    struct OidKey_ oidKey;
    OidKey_init(&oidKey, oid);
    return HashMap_remove(self, (HashKey)&oidKey);
}
References HashMap_remove(), and OidKey_init().
HashMap_removeByOpaque()
void * HashMap_removeByOpaque (HashMap self, void * opaque)
Definition at line 455 of file HashMap.c.
{
    struct OpaqueKey_ opaqueKey;
    OpaqueKey_init(&opaqueKey, opaque);
    return HashMap_remove(self, (HashKey)&opaqueKey);
}
References HashMap_remove(), and OpaqueKey_init().
HashMap_removeByString()
void * HashMap_removeByString (HashMap self, const char * key)
Definition at line 462 of file HashMap.c.
{
    struct StringKey_ stringKey;
    StringKey_init(&stringKey, key);
    return HashMap_remove(self, (HashKey)&stringKey);
}
References HashMap_remove(), and StringKey_init().
HashMap_removeByStringOid()
void * HashMap_removeByStringOid (HashMap self, const char * string, Oid oid)
Definition at line 469 of file HashMap.c.
{
    struct StringOidKey_ stringOidKey;
    StringOidKey_init(&stringOidKey, string, oid);
    return HashMap_remove(self, (HashKey)&stringOidKey);
}
References HashMap_remove(), and StringOidKey_init().
HashMap_size()
uint32 HashMap_size (HashMap self)
Definition at line 476 of file HashMap.c.
{
    return self->size;
}
Referenced by appendPathParts().
Iterator_initialize()
void Iterator_initialize (void) extern
Definition at line 83 of file Iterator.c.
{
    s_IteratorClass = PgObjectClass_create("Iterator", sizeof(struct Iterator_), 0);
}
References PgObjectClass_create(), and s_IteratorClass.
Referenced by HashMap_initialize().
OidKey_init()
static void OidKey_init (OidKey self, Oid keyVal) static
Definition at line 71 of file HashMap.c.
{
    ((HashKey)self)->m_class = s_OidKeyClass;
    self->key = keyVal;
}
References s_OidKeyClass.
Referenced by HashMap_getByOid(), HashMap_putByOid(), and HashMap_removeByOid().
OpaqueKey_init()
static void OpaqueKey_init (OpaqueKey self, void * keyVal) static
Definition at line 152 of file HashMap.c.
{
    ((HashKey)self)->m_class = s_OpaqueKeyClass;
    self->key = keyVal;
}
References s_OpaqueKeyClass.
Referenced by HashMap_getByOpaque(), HashMap_putByOpaque(), and HashMap_removeByOpaque().
StringKey_init()
static void StringKey_init (StringKey self, const char * keyVal) static
Definition at line 125 of file HashMap.c.
{
    ((HashKey)self)->m_class = s_StringKeyClass;
    self->key = keyVal; /* a private copy is made when the key is made permanent */
    self->hash = 0;
}
References s_StringKeyClass.
Referenced by HashMap_getByString(), HashMap_putByString(), HashMap_removeByString(), and StringOidKey_init().
StringOidKey_init()
static void StringOidKey_init (StringOidKey self, const char * string, Oid oid) static
Definition at line 186 of file HashMap.c.
{
    StringKey_init((StringKey)self, string);
    ((HashKey)self)->m_class = s_StringOidKeyClass;
    self->oid = oid;
}
References s_StringOidKeyClass, and StringKey_init().
Referenced by HashMap_getByStringOid(), HashMap_putByStringOid(), and HashMap_removeByStringOid().
Variable Documentation
s_EntryClass
static PgObjectClass s_EntryClass static
Definition at line 51 of file HashMap.c.
Referenced by HashMap_initialize().
s_HashMapClass
PgObjectClass s_HashMapClass static
Definition at line 52 of file HashMap.c.
Referenced by HashMap_create(), and HashMap_initialize().
s_OidKeyClass
HashKeyClass s_OidKeyClass static
Definition at line 46 of file HashMap.c.
Referenced by HashMap_initialize(), and OidKey_init().
s_OpaqueKeyClass
HashKeyClass s_OpaqueKeyClass static
Definition at line 48 of file HashMap.c.
Referenced by HashMap_initialize(), and OpaqueKey_init().
s_StringKeyClass
HashKeyClass s_StringKeyClass static
Definition at line 47 of file HashMap.c.
Referenced by HashMap_initialize(), and StringKey_init().
s_StringOidKeyClass
HashKeyClass s_StringOidKeyClass static
Definition at line 49 of file HashMap.c.
Referenced by HashMap_initialize(), and StringOidKey_init().