PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Coerce.c File Reference
Coerce.c File Reference
#include "pljava/type/Type_priv.h"
#include "pljava/type/Coerce.h"
#include "pljava/HashMap.h"
#include "pljava/Invocation.h"
Data Structures
struct Coerce
Functions
static Datum _Coerce_invoke (Type type, Function fn, PG_FUNCTION_ARGS)
static jvalue _Coerce_coerceDatum (Type type, Datum arg)
static Datum _Coerce_coerceObject (Type type, jobject jval)
static const char * _Coerce_getJNISignature (Type self)
static Type _Coerce_create (TypeClass coerceClass, Type innerType, Type outerType, Oid coerceFunctionID)
Type Coerce_createIn (Type innerType, Type outerType, Oid coerceFunctionID)
Type Coerce_createOut (Type innerType, Type outerType, Oid coerceFunctionID)
void Coerce_initialize (void)
Variables
static TypeClass s_coerceInClass
static TypeClass s_coerceOutClass
Data Structure Documentation
Coerce_
struct Coerce_
Definition at line 21 of file Coerce.c.
Data Fields
FmgrInfo coerceFunction
Type innerType
Type outerType
struct Type_ Type_extension
Function Documentation
_Coerce_coerceDatum()
static jvalue _Coerce_coerceDatum (Type type, Datum arg) static
Definition at line 52 of file Coerce.c.
{
    jvalue result;
    Coerce self = (Coerce)type;
    if(arg == 0)
        result.j = 0;
    else
        result = Type_coerceDatum(self->innerType, FunctionCall1(&self->coerceFunction, arg));
    return result;
}
References Type_coerceDatum().
Referenced by Coerce_initialize().
_Coerce_coerceObject()
static Datum _Coerce_coerceObject (Type type, jobject jval) static
Definition at line 63 of file Coerce.c.
{
    Coerce self = (Coerce)type;
    Datum arg = Type_coerceObject(self->innerType, jval);
    if(arg != 0)
    {
        MemoryContext currCtx = Invocation_switchToUpperContext();
        arg = FunctionCall1(&self->coerceFunction, arg);
        MemoryContextSwitchTo(currCtx);
    }
    return arg;
}
References Invocation_switchToUpperContext(), and Type_coerceObject().
Referenced by Coerce_initialize().
_Coerce_create()
static Type _Coerce_create (TypeClass coerceClass, Type innerType, Type outerType, Oid coerceFunctionID) static
Definition at line 81 of file Coerce.c.
{
    Coerce self = (Coerce)TypeClass_allocInstance(coerceClass, Type_getOid(outerType));
    fmgr_info_cxt(coerceFunctionID, &self->coerceFunction, GetMemoryChunkContext(self));
    self->innerType = innerType;
    self->outerType = outerType;
    if(Type_isPrimitive(self->innerType))
        ((Type)self)->objectType = _Coerce_create(coerceClass, Type_getObjectType(self->innerType), outerType, coerceFunctionID);
    return (Type)self;
}
References _Coerce_create(), Coerce::innerType, Coerce::outerType, Type, Type_getObjectType(), Type_getOid(), Type_isPrimitive(), and TypeClass_allocInstance().
Referenced by _Coerce_create(), Coerce_createIn(), and Coerce_createOut().
_Coerce_getJNISignature()
static const char * _Coerce_getJNISignature (Type self) static
Definition at line 76 of file Coerce.c.
{
    return Type_getJNISignature(((Coerce)self)->innerType);
}
References Coerce::innerType, and Type_getJNISignature().
Referenced by Coerce_initialize().
_Coerce_invoke()
static Datum _Coerce_invoke (Type type, Function fn, PG_FUNCTION_ARGS) static
Definition at line 39 of file Coerce.c.
{
    Coerce self = (Coerce)type;
    Datum arg = Type_invoke(self->innerType, fn, fcinfo);
    if(arg != 0)
    {
        MemoryContext currCtx = Invocation_switchToUpperContext();
        arg = FunctionCall1(&self->coerceFunction, arg);
        MemoryContextSwitchTo(currCtx);
    }
    return arg;
}
References Invocation_switchToUpperContext(), and Type_invoke().
Referenced by Coerce_initialize().
Coerce_createIn()
Type Coerce_createIn (Type innerType, Type outerType, Oid coerceFunctionID)
Definition at line 92 of file Coerce.c.
{
    return _Coerce_create(s_coerceInClass, innerType, outerType, coerceFunctionID);
}
References _Coerce_create(), Coerce::innerType, Coerce::outerType, and s_coerceInClass.
Referenced by Type_getCoerceIn().
Coerce_createOut()
Type Coerce_createOut (Type innerType, Type outerType, Oid coerceFunctionID)
Definition at line 97 of file Coerce.c.
{
    return _Coerce_create(s_coerceOutClass, innerType, outerType, coerceFunctionID);
}
References _Coerce_create(), Coerce::innerType, Coerce::outerType, and s_coerceOutClass.
Referenced by Type_getCoerceOut().
Coerce_initialize()
void Coerce_initialize (void) extern
Definition at line 103 of file Coerce.c.
{
    s_coerceInClass = TypeClass_alloc2("type.CoerceIn", sizeof(struct TypeClass_), sizeof(struct Coerce_));
    s_coerceInClass->getJNISignature = _Coerce_getJNISignature;
    s_coerceInClass->coerceDatum = _Coerce_coerceDatum;
    s_coerceOutClass = TypeClass_alloc2("type.CoerceOut", sizeof(struct TypeClass_), sizeof(struct Coerce_));
    s_coerceOutClass->getJNISignature = _Coerce_getJNISignature;
    s_coerceOutClass->invoke = _Coerce_invoke;
    s_coerceOutClass->coerceObject = _Coerce_coerceObject;
}
References _Coerce_coerceDatum(), _Coerce_coerceObject(), _Coerce_getJNISignature(), _Coerce_invoke(), s_coerceInClass, s_coerceOutClass, and TypeClass_alloc2().
Referenced by Type_initialize().
Variable Documentation
s_coerceInClass
TypeClass s_coerceInClass static
Definition at line 18 of file Coerce.c.
Referenced by Coerce_createIn(), and Coerce_initialize().
s_coerceOutClass
TypeClass s_coerceOutClass static
Definition at line 19 of file Coerce.c.
Referenced by Coerce_createOut(), and Coerce_initialize().