PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/ErrorData.c File Reference
ErrorData.c File Reference
#include "org_postgresql_pljava_internal_ErrorData.h"
#include "pljava/DualState.h"
#include "pljava/Exception.h"
#include "pljava/type/Type_priv.h"
#include "pljava/type/ErrorData.h"
#include "pljava/type/String.h"
Functions
jobject pljava_ErrorData_getCurrentError (void)
ErrorData * pljava_ErrorData_getErrorData (jobject jed)
void pljava_ErrorData_initialize (void)
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getErrorLevel (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getMessage (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getSqlState (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_ErrorData__1isOutputToServer (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_ErrorData__1isOutputToClient (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_ErrorData__1isShowFuncname (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getFilename (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getLineno (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getFuncname (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getDetail (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getHint (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getContextMessage (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getCursorPos (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getInternalPos (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getInternalQuery (JNIEnv *env, jclass cls, jlong _this)
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getSavedErrno (JNIEnv *env, jclass cls, jlong _this)
Variables
static jclass s_ErrorData_class
static jmethodID s_ErrorData_init
static jmethodID s_ErrorData_getNativePointer
Function Documentation
Java_org_postgresql_pljava_internal_ErrorData__1getContextMessage()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getContextMessage (JNIEnv * env, jclass cls, jlong _this)
Definition at line 334 of file ErrorData.c.
{
    jstring result = 0;
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2l;
    p2l.longVal = _this;
    result = String_createJavaStringFromNTS(((ErrorData*)p2l.ptrVal)->context);
    END_NATIVE
    return result;
}
References String_createJavaStringFromNTS().
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1getCursorPos()
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getCursorPos (JNIEnv * env, jclass cls, jlong _this)
Definition at line 350 of file ErrorData.c.
{
    Ptr2Long p2l;
    p2l.longVal = _this;
    return (jint)((ErrorData*)p2l.ptrVal)->cursorpos;
}
References jint().
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1getDetail()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getDetail (JNIEnv * env, jclass cls, jlong _this)
Definition at line 302 of file ErrorData.c.
{
    jstring result = 0;
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2l;
    p2l.longVal = _this;
    result = String_createJavaStringFromNTS(((ErrorData*)p2l.ptrVal)->detail);
    END_NATIVE
    return result;
}
References String_createJavaStringFromNTS().
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1getErrorLevel()
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getErrorLevel (JNIEnv * env, jclass cls, jlong _this)
Definition at line 160 of file ErrorData.c.
{
    Ptr2Long p2l;
    p2l.longVal = _this;
    return ((ErrorData*)p2l.ptrVal)->elevel;
}
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1getFilename()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getFilename (JNIEnv * env, jclass cls, jlong _this)
Definition at line 258 of file ErrorData.c.
{
    jstring result = 0;
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2l;
    p2l.longVal = _this;
    result = String_createJavaStringFromNTS(((ErrorData*)p2l.ptrVal)->filename);
    END_NATIVE
    return result;
}
References String_createJavaStringFromNTS().
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1getFuncname()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getFuncname (JNIEnv * env, jclass cls, jlong _this)
Definition at line 286 of file ErrorData.c.
{
    jstring result = 0;
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2l;
    p2l.longVal = _this;
    result = String_createJavaStringFromNTS(((ErrorData*)p2l.ptrVal)->funcname);
    END_NATIVE
    return result;
}
References String_createJavaStringFromNTS().
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1getHint()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getHint (JNIEnv * env, jclass cls, jlong _this)
Definition at line 318 of file ErrorData.c.
{
    jstring result = 0;
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2l;
    p2l.longVal = _this;
    result = String_createJavaStringFromNTS(((ErrorData*)p2l.ptrVal)->hint);
    END_NATIVE
    return result;
}
References String_createJavaStringFromNTS().
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1getInternalPos()
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getInternalPos (JNIEnv * env, jclass cls, jlong _this)
Definition at line 362 of file ErrorData.c.
{
    Ptr2Long p2l;
    p2l.longVal = _this;
    return (jint)((ErrorData*)p2l.ptrVal)->internalpos;
}
References jint().
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1getInternalQuery()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getInternalQuery (JNIEnv * env, jclass cls, jlong _this)
Definition at line 374 of file ErrorData.c.
{
    jstring result = 0;
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2l;
    p2l.longVal = _this;
    result = String_createJavaStringFromNTS(((ErrorData*)p2l.ptrVal)->internalquery);
    END_NATIVE
    return result;
}
References String_createJavaStringFromNTS().
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1getLineno()
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getLineno (JNIEnv * env, jclass cls, jlong _this)
Definition at line 274 of file ErrorData.c.
{
    Ptr2Long p2l;
    p2l.longVal = _this;
    return (jint)((ErrorData*)p2l.ptrVal)->lineno;
}
References jint().
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1getMessage()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getMessage (JNIEnv * env, jclass cls, jlong _this)
Definition at line 172 of file ErrorData.c.
{
    jstring result = 0;
    BEGIN_NATIVE_NO_ERRCHECK
    Ptr2Long p2l;
    p2l.longVal = _this;
    result = String_createJavaStringFromNTS(((ErrorData*)p2l.ptrVal)->message);
    END_NATIVE
    return result;
}
References String_createJavaStringFromNTS().
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1getSavedErrno()
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getSavedErrno (JNIEnv * env, jclass cls, jlong _this)
Definition at line 392 of file ErrorData.c.
{
    Ptr2Long p2l;
    p2l.longVal = _this;
    return (jint)((ErrorData*)p2l.ptrVal)->saved_errno;
}
References jint().
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1getSqlState()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_ErrorData__1getSqlState (JNIEnv * env, jclass cls, jlong _this)
Definition at line 188 of file ErrorData.c.
{
    jstring result = 0;
    BEGIN_NATIVE_NO_ERRCHECK
    char buf[6];
    int errCode;
    int idx;
    Ptr2Long p2l;
    p2l.longVal = _this;
    /* unpack MAKE_SQLSTATE code
     */
    errCode = ((ErrorData*)p2l.ptrVal)->sqlerrcode;
    for (idx = 0; idx < 5; ++idx)
    {
        buf[idx] = (char)PGUNSIXBIT(errCode); /*why not cast in macro?*/
        errCode >>= 6;
    }
    buf[idx] = 0;
    result = String_createJavaStringFromNTS(buf);
    END_NATIVE
    return result;
}
References String_createJavaStringFromNTS().
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1isOutputToClient()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_ErrorData__1isOutputToClient (JNIEnv * env, jclass cls, jlong _this)
Definition at line 230 of file ErrorData.c.
{
    Ptr2Long p2l;
    p2l.longVal = _this;
    return (jboolean)((ErrorData*)p2l.ptrVal)->output_to_client;
}
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1isOutputToServer()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_ErrorData__1isOutputToServer (JNIEnv * env, jclass cls, jlong _this)
Definition at line 218 of file ErrorData.c.
{
    Ptr2Long p2l;
    p2l.longVal = _this;
    return (jboolean)((ErrorData*)p2l.ptrVal)->output_to_server;
}
Referenced by pljava_ErrorData_initialize().
Java_org_postgresql_pljava_internal_ErrorData__1isShowFuncname()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_ErrorData__1isShowFuncname (JNIEnv * env, jclass cls, jlong _this)
Definition at line 242 of file ErrorData.c.
{
#if PG_VERSION_NUM < 140000
    Ptr2Long p2l;
    p2l.longVal = _this;
    return (jboolean)((ErrorData*)p2l.ptrVal)->show_funcname;
#else
    return JNI_FALSE;
#endif
}
Referenced by pljava_ErrorData_initialize().
pljava_ErrorData_getCurrentError()
jobject pljava_ErrorData_getCurrentError (void)
Definition at line 26 of file ErrorData.c.
{
    Ptr2Long p2l;
    jobject jed;
    MemoryContext curr = MemoryContextSwitchTo(JavaMemoryContext);
    ErrorData* errorData = CopyErrorData();
    MemoryContextSwitchTo(curr);
    p2l.longVal = 0L; /* ensure that the rest is zeroed out */
    p2l.ptrVal = errorData;
    /*
     * Passing (jlong)0 as the ResourceOwner means this will never be matched by
     * a nativeRelease call; that's appropriate (for now) as the ErrorData copy
     * is being made into JavaMemoryContext, which never gets reset, so only
     * unreachability from the Java side will free it.
     */
    jed = JNI_newObjectLocked(s_ErrorData_class, s_ErrorData_init,
        pljava_DualState_key(), (jlong)0, p2l.longVal);
    return jed;
}
References JavaMemoryContext, JNI_newObjectLocked(), pljava_DualState_key(), s_ErrorData_class, and s_ErrorData_init.
Referenced by Exception_throw_ERROR().
pljava_ErrorData_getErrorData()
ErrorData * pljava_ErrorData_getErrorData (jobject jed)
Definition at line 48 of file ErrorData.c.
{
    Ptr2Long p2l;
    p2l.longVal = JNI_callLongMethod(jed, s_ErrorData_getNativePointer);
    return (ErrorData*)p2l.ptrVal;
}
References JNI_callLongMethod(), and s_ErrorData_getNativePointer.
Referenced by endCall(), and endCallMonitorHeld().
pljava_ErrorData_initialize()
void pljava_ErrorData_initialize (void)
Definition at line 57 of file ErrorData.c.
{
    JNINativeMethod methods[] = {
        {
        "_getErrorLevel",
        "(J)I",
        Java_org_postgresql_pljava_internal_ErrorData__1getErrorLevel
        },
        {
        "_isOutputToServer",
        "(J)Z",
        Java_org_postgresql_pljava_internal_ErrorData__1isOutputToServer
        },
        {
        "_isOutputToClient",
        "(J)Z",
        Java_org_postgresql_pljava_internal_ErrorData__1isOutputToClient
        },
        {
        "_isShowFuncname",
        "(J)Z",
        Java_org_postgresql_pljava_internal_ErrorData__1isShowFuncname
        },
        {
        "_getFilename",
        "(J)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_ErrorData__1getFilename
        },
        {
        "_getLineno",
        "(J)I",
        Java_org_postgresql_pljava_internal_ErrorData__1getLineno
        },
        {
        "_getFuncname",
        "(J)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_ErrorData__1getFuncname
        },
        {
        "_getSqlState",
        "(J)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_ErrorData__1getSqlState
        },
        {
        "_getMessage",
        "(J)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_ErrorData__1getMessage
        },
        {
        "_getDetail",
        "(J)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_ErrorData__1getDetail
        },
        {
        "_getHint",
        "(J)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_ErrorData__1getHint
        },
        {
        "_getContextMessage",
        "(J)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_ErrorData__1getContextMessage
        },
        {
        "_getCursorPos",
        "(J)I",
        Java_org_postgresql_pljava_internal_ErrorData__1getCursorPos
        },
        {
        "_getInternalPos",
        "(J)I",
        Java_org_postgresql_pljava_internal_ErrorData__1getInternalPos
        },
        {
        "_getInternalQuery",
        "(J)Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_ErrorData__1getInternalQuery
        },
        {
        "_getSavedErrno",
        "(J)I",
        Java_org_postgresql_pljava_internal_ErrorData__1getSavedErrno
        },
        { 0, 0, 0 }
    };
    s_ErrorData_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/internal/ErrorData"));
    PgObject_registerNatives2(s_ErrorData_class, methods);
    s_ErrorData_init = PgObject_getJavaMethod(s_ErrorData_class, "<init>",
        "(Lorg/postgresql/pljava/internal/DualState$Key;JJ)V");
    s_ErrorData_getNativePointer = PgObject_getJavaMethod(s_ErrorData_class, "getNativePointer", "()J");
}
References Java_org_postgresql_pljava_internal_ErrorData__1getContextMessage(), Java_org_postgresql_pljava_internal_ErrorData__1getCursorPos(), Java_org_postgresql_pljava_internal_ErrorData__1getDetail(), Java_org_postgresql_pljava_internal_ErrorData__1getErrorLevel(), Java_org_postgresql_pljava_internal_ErrorData__1getFilename(), Java_org_postgresql_pljava_internal_ErrorData__1getFuncname(), Java_org_postgresql_pljava_internal_ErrorData__1getHint(), Java_org_postgresql_pljava_internal_ErrorData__1getInternalPos(), Java_org_postgresql_pljava_internal_ErrorData__1getInternalQuery(), Java_org_postgresql_pljava_internal_ErrorData__1getLineno(), Java_org_postgresql_pljava_internal_ErrorData__1getMessage(), Java_org_postgresql_pljava_internal_ErrorData__1getSavedErrno(), Java_org_postgresql_pljava_internal_ErrorData__1getSqlState(), Java_org_postgresql_pljava_internal_ErrorData__1isOutputToClient(), Java_org_postgresql_pljava_internal_ErrorData__1isOutputToServer(), Java_org_postgresql_pljava_internal_ErrorData__1isShowFuncname(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaMethod(), PgObject_registerNatives2(), s_ErrorData_class, s_ErrorData_getNativePointer, and s_ErrorData_init.
Referenced by pljava_DualState_initialize().
Variable Documentation
s_ErrorData_class
jclass s_ErrorData_class static
Definition at line 22 of file ErrorData.c.
Referenced by pljava_ErrorData_getCurrentError(), and pljava_ErrorData_initialize().
s_ErrorData_getNativePointer
jmethodID s_ErrorData_getNativePointer static
Definition at line 24 of file ErrorData.c.
Referenced by pljava_ErrorData_getErrorData(), and pljava_ErrorData_initialize().
s_ErrorData_init
jmethodID s_ErrorData_init static
Definition at line 23 of file ErrorData.c.
Referenced by pljava_ErrorData_getCurrentError(), and pljava_ErrorData_initialize().