PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/XactListener.c File Reference
XactListener.c File Reference
#include "pljava/Backend.h"
#include "pljava/Exception.h"
#include "org_postgresql_pljava_internal_XactListener.h"
#include "access/xact.h"
Macros
#define CASE(c)
Functions
static void xactCB (XactEvent event, void *arg)
void XactListener_initialize (void)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_XactListener__1register (JNIEnv *env, jclass cls)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_XactListener__1unregister (JNIEnv *env, jclass cls)
Variables
static jclass s_XactListener_class
static jmethodID s_XactListener_invokeListeners
Macro Definition Documentation
CASE
#define CASE (c)
Value:
case XACT_EVENT_##c: \
    mapped = org_postgresql_pljava_internal_XactListener_##c; \
    break
Function Documentation
Java_org_postgresql_pljava_internal_XactListener__1register()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_XactListener__1register (JNIEnv * env, jclass cls)
Definition at line 84 of file XactListener.c.
{
    BEGIN_NATIVE
    PG_TRY();
    {
        RegisterXactCallback(xactCB, NULL);
    }
    PG_CATCH();
    {
        Exception_throw_ERROR("RegisterXactCallback");
    }
    PG_END_TRY();
    END_NATIVE
}
References Exception_throw_ERROR(), and xactCB().
Referenced by XactListener_initialize().
Java_org_postgresql_pljava_internal_XactListener__1unregister()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_XactListener__1unregister (JNIEnv * env, jclass cls)
Definition at line 105 of file XactListener.c.
{
    BEGIN_NATIVE
    PG_TRY();
    {
        UnregisterXactCallback(xactCB, NULL);
    }
    PG_CATCH();
    {
        Exception_throw_ERROR("UnregisterXactCallback");
    }
    PG_END_TRY();
    END_NATIVE
}
References Exception_throw_ERROR(), and xactCB().
Referenced by XactListener_initialize().
xactCB()
static void xactCB (XactEvent event, void * arg) static
Definition at line 22 of file XactListener.c.
{
    /*
     * Upstream has, regrettably, not merely added events over the years, but
     * changed their order, so a mapping is needed. Use a switch with the known
     * cases enumerated, to improve the chance that a clever compiler will warn
     * if yet more have been added, and initialize 'mapped' to a value that the
     * Java code won't mistake for a real one.
     */
#define CASE(c) \
case XACT_EVENT_##c: \
    mapped = org_postgresql_pljava_internal_XactListener_##c; \
    break
    jint mapped = -1;
    switch(event)
    {
        CASE( COMMIT );
        CASE( ABORT );
        CASE( PREPARE );
        CASE( PRE_COMMIT );
        CASE( PRE_PREPARE );
        CASE( PARALLEL_COMMIT );
        CASE( PARALLEL_ABORT );
        CASE( PARALLEL_PRE_COMMIT );
    }
    JNI_callStaticVoidMethod(s_XactListener_class,
        s_XactListener_invokeListeners, mapped);
}
References CASE, jint(), JNI_callStaticVoidMethod(), s_XactListener_class, and s_XactListener_invokeListeners.
Referenced by Java_org_postgresql_pljava_internal_XactListener__1register(), and Java_org_postgresql_pljava_internal_XactListener__1unregister().
XactListener_initialize()
void XactListener_initialize (void) extern
Definition at line 54 of file XactListener.c.
{
    JNINativeMethod methods[] = {
        {
        "_register",
        "()V",
        Java_org_postgresql_pljava_internal_XactListener__1register
        },
        {
        "_unregister",
        "()V",
        Java_org_postgresql_pljava_internal_XactListener__1unregister
        },
        { 0, 0, 0 }
    };
    PgObject_registerNatives("org/postgresql/pljava/internal/XactListener", methods);
    s_XactListener_class = JNI_newGlobalRef(PgObject_getJavaClass(
        "org/postgresql/pljava/internal/XactListener"));
    s_XactListener_invokeListeners = PgObject_getStaticJavaMethod(
        s_XactListener_class, "invokeListeners", "(I)V");
}
References Java_org_postgresql_pljava_internal_XactListener__1register(), Java_org_postgresql_pljava_internal_XactListener__1unregister(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getStaticJavaMethod(), PgObject_registerNatives(), s_XactListener_class, and s_XactListener_invokeListeners.
Referenced by initPLJavaClasses().
Variable Documentation
s_XactListener_class
jclass s_XactListener_class static
Definition at line 19 of file XactListener.c.
Referenced by xactCB(), and XactListener_initialize().
s_XactListener_invokeListeners
jmethodID s_XactListener_invokeListeners static
Definition at line 20 of file XactListener.c.
Referenced by xactCB(), and XactListener_initialize().