PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/SPI.c File Reference
SPI.c File Reference
#include "org_postgresql_pljava_internal_SPI.h"
#include "pljava/SPI.h"
#include "pljava/Invocation.h"
#include "pljava/Exception.h"
#include "pljava/type/String.h"
#include "pljava/type/TupleTable.h"
#include <funcapi.h>
#include <access/xact.h>
Macros
#define CONFIRMCONST(c)
Functions
void SPI_initialize (void)
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_SPI__1exec (JNIEnv *env, jclass cls, jstring cmd, jint count)
JNIEXPORT jlong JNICALL Java_org_postgresql_pljava_internal_SPI__1getProcessed (JNIEnv *env, jclass cls)
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_SPI__1getResult (JNIEnv *env, jclass cls)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_SPI__1getTupTable (JNIEnv *env, jclass cls, jobject td)
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_SPI__1freeTupTable (JNIEnv *env, jclass cls)
Macro Definition Documentation
CONFIRMCONST
#define CONFIRMCONST (c)
Value:
StaticAssertStmt((c) == (org_postgresql_pljava_internal_##c), \
    "Java/C value mismatch for " #c)
Definition at line 28 of file SPI.c.
Function Documentation
Java_org_postgresql_pljava_internal_SPI__1exec()
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_SPI__1exec (JNIEnv * env, jclass cls, jstring cmd, jint count)
Definition at line 123 of file SPI.c.
{
    jint result = 0;
    BEGIN_NATIVE
    char* command = String_createNTS(cmd);
    if(command != 0)
    {
        STACK_BASE_VARS
        STACK_BASE_PUSH(env)
        PG_TRY();
        {
            Invocation_assertConnect();
            result = (jint)SPI_exec(command, (int)count);
            if(result < 0)
                Exception_throwSPI("exec", result);
        }
        PG_CATCH();
        {
            Exception_throw_ERROR("SPI_exec");
        }
        PG_END_TRY();
        pfree(command);
        STACK_BASE_POP()
    }
    END_NATIVE
    return result;
}
References Exception_throw_ERROR(), Exception_throwSPI(), Invocation_assertConnect(), jint(), and String_createNTS().
Referenced by SPI_initialize().
Java_org_postgresql_pljava_internal_SPI__1freeTupTable()
JNIEXPORT void JNICALL Java_org_postgresql_pljava_internal_SPI__1freeTupTable (JNIEnv * env, jclass cls)
Definition at line 199 of file SPI.c.
{
    if(SPI_tuptable != 0)
    {
        BEGIN_NATIVE
        SPI_freetuptable(SPI_tuptable);
        SPI_tuptable = 0;
        END_NATIVE
    }
}
Referenced by SPI_initialize().
Java_org_postgresql_pljava_internal_SPI__1getProcessed()
JNIEXPORT jlong JNICALL Java_org_postgresql_pljava_internal_SPI__1getProcessed (JNIEnv * env, jclass cls)
Definition at line 159 of file SPI.c.
{
    return (jlong)SPI_processed;
}
Referenced by SPI_initialize().
Java_org_postgresql_pljava_internal_SPI__1getResult()
JNIEXPORT jint JNICALL Java_org_postgresql_pljava_internal_SPI__1getResult (JNIEnv * env, jclass cls)
Definition at line 170 of file SPI.c.
{
    return (jint)SPI_result;
}
References jint().
Referenced by SPI_initialize().
Java_org_postgresql_pljava_internal_SPI__1getTupTable()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_SPI__1getTupTable (JNIEnv * env, jclass cls, jobject td)
Definition at line 181 of file SPI.c.
{
    jobject tupleTable = 0;
    if(SPI_tuptable != 0)
    {
        BEGIN_NATIVE
        tupleTable = TupleTable_create(SPI_tuptable, td);
        END_NATIVE
    }
    return tupleTable;
}
References TupleTable_create().
Referenced by SPI_initialize().
SPI_initialize()
void SPI_initialize (void) extern
Definition at line 33 of file SPI.c.
{
    JNINativeMethod methods[] = {
        {
        "_exec",
        "(Ljava/lang/String;I)I",
        Java_org_postgresql_pljava_internal_SPI__1exec
        },
        {
        "_getProcessed",
        "()J",
        Java_org_postgresql_pljava_internal_SPI__1getProcessed
        },
        {
        "_getResult",
        "()I",
        Java_org_postgresql_pljava_internal_SPI__1getResult
        },
        {
        "_getTupTable",
        "(Lorg/postgresql/pljava/internal/TupleDesc;)Lorg/postgresql/pljava/internal/TupleTable;",
        Java_org_postgresql_pljava_internal_SPI__1getTupTable
        },
        {
        "_freeTupTable",
        "()V",
        Java_org_postgresql_pljava_internal_SPI__1freeTupTable
        },
        { 0, 0, 0 }};
    PgObject_registerNatives("org/postgresql/pljava/internal/SPI", methods);
    /*
     * Statically assert that the Java code has the right values for these.
     * I would rather have this at the top, but these count as statements and
     * would trigger a declaration-after-statment warning.
     */
    CONFIRMCONST(SPI_ERROR_CONNECT);
    CONFIRMCONST(SPI_ERROR_COPY);
    CONFIRMCONST(SPI_ERROR_OPUNKNOWN);
    CONFIRMCONST(SPI_ERROR_UNCONNECTED);
    CONFIRMCONST(SPI_ERROR_CURSOR);
    CONFIRMCONST(SPI_ERROR_ARGUMENT);
    CONFIRMCONST(SPI_ERROR_PARAM);
    CONFIRMCONST(SPI_ERROR_TRANSACTION);
    CONFIRMCONST(SPI_ERROR_NOATTRIBUTE);
    CONFIRMCONST(SPI_ERROR_NOOUTFUNC);
    CONFIRMCONST(SPI_ERROR_TYPUNKNOWN);
#if PG_VERSION_NUM >= 100000
    CONFIRMCONST(SPI_ERROR_REL_DUPLICATE);
    CONFIRMCONST(SPI_ERROR_REL_NOT_FOUND);
#endif
    CONFIRMCONST(SPI_OK_CONNECT);
    CONFIRMCONST(SPI_OK_FINISH);
    CONFIRMCONST(SPI_OK_FETCH);
    CONFIRMCONST(SPI_OK_UTILITY);
    CONFIRMCONST(SPI_OK_SELECT);
    CONFIRMCONST(SPI_OK_SELINTO);
    CONFIRMCONST(SPI_OK_INSERT);
    CONFIRMCONST(SPI_OK_DELETE);
    CONFIRMCONST(SPI_OK_UPDATE);
    CONFIRMCONST(SPI_OK_CURSOR);
    CONFIRMCONST(SPI_OK_INSERT_RETURNING);
    CONFIRMCONST(SPI_OK_DELETE_RETURNING);
    CONFIRMCONST(SPI_OK_UPDATE_RETURNING);
    CONFIRMCONST(SPI_OK_REWRITTEN);
#if PG_VERSION_NUM >= 100000
    CONFIRMCONST(SPI_OK_REL_REGISTER);
    CONFIRMCONST(SPI_OK_REL_UNREGISTER);
    CONFIRMCONST(SPI_OK_TD_REGISTER);
#endif
#if PG_VERSION_NUM >= 150000
    CONFIRMCONST(SPI_OK_MERGE);
#endif
#if PG_VERSION_NUM >= 110000
    CONFIRMCONST(SPI_OPT_NONATOMIC);
#endif
}
References CONFIRMCONST, Java_org_postgresql_pljava_internal_SPI__1exec(), Java_org_postgresql_pljava_internal_SPI__1freeTupTable(), Java_org_postgresql_pljava_internal_SPI__1getProcessed(), Java_org_postgresql_pljava_internal_SPI__1getResult(), Java_org_postgresql_pljava_internal_SPI__1getTupTable(), and PgObject_registerNatives().
Referenced by initPLJavaClasses().