PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/AclId.c File Reference
AclId.c File Reference
#include <postgres.h>
#include <miscadmin.h>
#include <utils/acl.h>
#include <catalog/pg_authid.h>
#include "pljava/type/AclId.h"
#include "pljava/type/Oid.h"
#include "pljava/type/String.h"
#include "pljava/type/Type_priv.h"
#include "org_postgresql_pljava_internal_AclId.h"
#include "pljava/Exception.h"
Functions
jobject AclId_create (AclId aclId)
AclId AclId_getAclId (jobject aclId)
void AclId_initialize (void)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_AclId__1getUser (JNIEnv *env, jclass clazz)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_AclId__1getOuterUser (JNIEnv *env, jclass clazz)
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_AclId__1fromName (JNIEnv *env, jclass clazz, jstring jname)
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_AclId__1getName (JNIEnv *env, jobject aclId)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_AclId__1hasSchemaCreatePermission (JNIEnv *env, jobject aclId, jobject oid)
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_AclId__1isSuperuser (JNIEnv *env, jobject aclId)
Variables
static jclass s_AclId_class
static jmethodID s_AclId_init
static jfieldID s_AclId_m_native
Function Documentation
AclId_create()
jobject AclId_create (AclId aclId)
Definition at line 38 of file AclId.c.
{
    return JNI_newObject(s_AclId_class, s_AclId_init, (jint)aclId);
}
References jint(), JNI_newObject(), s_AclId_class, and s_AclId_init.
Referenced by Java_org_postgresql_pljava_internal_AclId__1fromName(), Java_org_postgresql_pljava_internal_AclId__1getOuterUser(), and Java_org_postgresql_pljava_internal_AclId__1getUser().
AclId_getAclId()
AclId AclId_getAclId (jobject aclId)
Definition at line 43 of file AclId.c.
{
    return (AclId)JNI_getIntField(aclId, s_AclId_m_native);
}
References JNI_getIntField(), and s_AclId_m_native.
Referenced by Java_org_postgresql_pljava_internal_AclId__1getName(), Java_org_postgresql_pljava_internal_AclId__1hasSchemaCreatePermission(), Java_org_postgresql_pljava_internal_AclId__1isSuperuser(), and Java_org_postgresql_pljava_internal_Session__1setUser().
AclId_initialize()
void AclId_initialize (void) extern
Definition at line 49 of file AclId.c.
{
    JNINativeMethod methods[] = {
        {
        "_getUser",
        "()Lorg/postgresql/pljava/internal/AclId;",
        Java_org_postgresql_pljava_internal_AclId__1getUser
        },
        {
        "_getOuterUser",
        "()Lorg/postgresql/pljava/internal/AclId;",
        Java_org_postgresql_pljava_internal_AclId__1getOuterUser
        },
        {
        "_fromName",
        "(Ljava/lang/String;)Lorg/postgresql/pljava/internal/AclId;",
        Java_org_postgresql_pljava_internal_AclId__1fromName
        },
        {
        "_getName",
        "()Ljava/lang/String;",
        Java_org_postgresql_pljava_internal_AclId__1getName
        },
        {
        "_hasSchemaCreatePermission",
        "(Lorg/postgresql/pljava/internal/Oid;)Z",
        Java_org_postgresql_pljava_internal_AclId__1hasSchemaCreatePermission
        },
        {
        "_isSuperuser",
        "()Z",
        Java_org_postgresql_pljava_internal_AclId__1isSuperuser
        },
        { 0, 0, 0 }};
    s_AclId_class = JNI_newGlobalRef(PgObject_getJavaClass("org/postgresql/pljava/internal/AclId"));
    PgObject_registerNatives2(s_AclId_class, methods);
    s_AclId_init = PgObject_getJavaMethod(s_AclId_class, "<init>", "(I)V");
    s_AclId_m_native = PgObject_getJavaField(s_AclId_class, "m_native", "I");
}
References Java_org_postgresql_pljava_internal_AclId__1fromName(), Java_org_postgresql_pljava_internal_AclId__1getName(), Java_org_postgresql_pljava_internal_AclId__1getOuterUser(), Java_org_postgresql_pljava_internal_AclId__1getUser(), Java_org_postgresql_pljava_internal_AclId__1hasSchemaCreatePermission(), Java_org_postgresql_pljava_internal_AclId__1isSuperuser(), JNI_newGlobalRef(), PgObject_getJavaClass(), PgObject_getJavaField(), PgObject_getJavaMethod(), PgObject_registerNatives2(), s_AclId_class, s_AclId_init, and s_AclId_m_native.
Referenced by Type_initialize().
Java_org_postgresql_pljava_internal_AclId__1fromName()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_AclId__1fromName (JNIEnv * env, jclass clazz, jstring jname)
Definition at line 145 of file AclId.c.
{
    jobject result = 0;
    if(jname != 0)
    {
        BEGIN_NATIVE
        PG_TRY();
        {
            char* roleName = String_createNTS(jname);
            HeapTuple roleTup = SearchSysCache(AUTHNAME, PointerGetDatum(roleName), 0, 0, 0);
            if(!HeapTupleIsValid(roleTup))
                ereport(ERROR,
                        (errcode(ERRCODE_UNDEFINED_OBJECT),
                         errmsg("role \"%s\" does not exist", roleName)));
            result = AclId_create(
#if PG_VERSION_NUM >= 120000
                ((Form_pg_authid) GETSTRUCT(roleTup))->oid
#else
                HeapTupleGetOid(roleTup)
#endif
            );
            ReleaseSysCache(roleTup);
        }
        PG_CATCH();
        {
            Exception_throw_ERROR("SearchSysCache");
        }
        PG_END_TRY();
        END_NATIVE
    }
    return result;
}
References AclId_create(), Exception_throw_ERROR(), and String_createNTS().
Referenced by AclId_initialize().
Java_org_postgresql_pljava_internal_AclId__1getName()
JNIEXPORT jstring JNICALL Java_org_postgresql_pljava_internal_AclId__1getName (JNIEnv * env, jobject aclId)
Definition at line 185 of file AclId.c.
{
    jstring result = 0;
    BEGIN_NATIVE
    PG_TRY();
    {
        result = String_createJavaStringFromNTS(
            GetUserNameFromId(
                AclId_getAclId(aclId), /* noerr= */ false
            )
        );
    }
    PG_CATCH();
    {
        Exception_throw_ERROR("GetUserNameFromId");
    }
    PG_END_TRY();
    END_NATIVE
    return result;
}
References AclId_getAclId(), Exception_throw_ERROR(), and String_createJavaStringFromNTS().
Referenced by AclId_initialize().
Java_org_postgresql_pljava_internal_AclId__1getOuterUser()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_AclId__1getOuterUser (JNIEnv * env, jclass clazz)
Definition at line 122 of file AclId.c.
{
    jobject result = 0;
    BEGIN_NATIVE
    PG_TRY();
    {
        result = AclId_create(GetOuterUserId());
    }
    PG_CATCH();
    {
        Exception_throw_ERROR("GetOuterUserId");
    }
    PG_END_TRY();
    END_NATIVE
    return result;
}
References AclId_create(), and Exception_throw_ERROR().
Referenced by AclId_initialize().
Java_org_postgresql_pljava_internal_AclId__1getUser()
JNIEXPORT jobject JNICALL Java_org_postgresql_pljava_internal_AclId__1getUser (JNIEnv * env, jclass clazz)
Definition at line 99 of file AclId.c.
{
    jobject result = 0;
    BEGIN_NATIVE
    PG_TRY();
    {
        result = AclId_create(GetUserId());
    }
    PG_CATCH();
    {
        Exception_throw_ERROR("GetUserId");
    }
    PG_END_TRY();
    END_NATIVE
    return result;
}
References AclId_create(), and Exception_throw_ERROR().
Referenced by AclId_initialize().
Java_org_postgresql_pljava_internal_AclId__1hasSchemaCreatePermission()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_AclId__1hasSchemaCreatePermission (JNIEnv * env, jobject aclId, jobject oid)
Definition at line 212 of file AclId.c.
{
    jboolean result = JNI_FALSE;
    BEGIN_NATIVE
    result = (jboolean)(pg_namespace_aclcheck(Oid_getOid(oid), AclId_getAclId(aclId), ACL_CREATE) == ACLCHECK_OK);
    END_NATIVE
    return result;
}
References AclId_getAclId(), and Oid_getOid().
Referenced by AclId_initialize().
Java_org_postgresql_pljava_internal_AclId__1isSuperuser()
JNIEXPORT jboolean JNICALL Java_org_postgresql_pljava_internal_AclId__1isSuperuser (JNIEnv * env, jobject aclId)
Definition at line 227 of file AclId.c.
{
    jboolean result = JNI_FALSE;
    BEGIN_NATIVE
    result = superuser_arg(AclId_getAclId(aclId)) ? JNI_TRUE : JNI_FALSE;
    END_NATIVE
    return result;
}
References AclId_getAclId().
Referenced by AclId_initialize().
Variable Documentation
s_AclId_class
jclass s_AclId_class static
Definition at line 31 of file AclId.c.
Referenced by AclId_create(), and AclId_initialize().
s_AclId_init
jmethodID s_AclId_init static
Definition at line 32 of file AclId.c.
Referenced by AclId_create(), and AclId_initialize().
s_AclId_m_native
jfieldID s_AclId_m_native static
Definition at line 33 of file AclId.c.
Referenced by AclId_getAclId(), and AclId_initialize().