PL-JAVA (shared library): /home/bgiles/src/tada/pljava/pljava-so/src/main/c/type/Any.c File Reference
Any.c File Reference
#include <postgres.h>
#include <utils/memutils.h>
#include <utils/numeric.h>
#include "pljava/type/Type_priv.h"
#include "pljava/type/Array.h"
Functions
static Type _Any_getRealType (Type self, Oid realId, jobject typeMap)
static Type _AnyArray_getRealType (Type self, Oid realId, jobject typeMap)
static Type _Any_createArrayType (Type self, Oid arrayTypeId)
void Any_initialize (void)
Function Documentation
_Any_createArrayType()
static Type _Any_createArrayType (Type self, Oid arrayTypeId) static
Definition at line 32 of file Any.c.
{
    Type t = Array_fromOid(arrayTypeId, self);
    t->typeClass->getRealType = _AnyArray_getRealType;
    t->typeClass->dynamic = true;
    return t;
}
References _AnyArray_getRealType(), Array_fromOid(), and Type.
Referenced by Any_initialize().
_Any_getRealType()
static Type _Any_getRealType (Type self, Oid realId, jobject typeMap) static
Definition at line 16 of file Any.c.
{
    Type real = Type_fromOid(realId, typeMap);
    if(Type_isPrimitive(real) && Type_getElementType(real) == 0)
        real = Type_getObjectType(real);
    return real;
}
References Type, Type_fromOid(), Type_getElementType(), Type_getObjectType(), and Type_isPrimitive().
Referenced by Any_initialize().
_AnyArray_getRealType()
static Type _AnyArray_getRealType (Type self, Oid realId, jobject typeMap) static
Definition at line 24 of file Any.c.
{
    Type real = Type_fromOid(realId, typeMap);
    if(Type_isPrimitive(real))
        real = Type_getObjectType(real);
    return real;
}
References Type, Type_fromOid(), Type_getObjectType(), and Type_isPrimitive().
Referenced by _Any_createArrayType().
Any_initialize()
void Any_initialize (void) extern
Definition at line 43 of file Any.c.
{
    TypeClass cls = TypeClass_alloc("type.any");
    cls->JNISignature    = "Ljava/lang/Object;";
    cls->javaTypeName    = "java.lang.Object";
    cls->dynamic         = true;
    cls->getRealType     = _Any_getRealType;
    cls->createArrayType = _Any_createArrayType;
    Type_registerType("java.lang.Object", TypeClass_allocInstance(cls, ANYELEMENTOID));
    Type_registerType(0, TypeClass_allocInstance(cls, ANYOID));
}
References _Any_createArrayType(), _Any_getRealType(), Type_registerType(), TypeClass_alloc(), and TypeClass_allocInstance().
Referenced by Type_initialize().